import type { Section } from "./types";

export const drivers: Section = {
  slug: "drivers",
  title: {
    en: "Drivers & Commuters",
    pcm: "Drivers & Commuters",
    yo: "Awọn Awakọ & Awọn Aririn Ajo",
    ha: "Direbobi & Masu Tafiya",
    ig: "Ndị Ọkwọ Ụgbọ & Ndị Na-aga",
  },
  description: {
    en: "Your rights at FRSC checkpoints, VIO stops, and police roadblocks — what officers can check, what levies are legal, and how to handle extortion.",
    pcm: "Your rights for FRSC checkpoint, VIO stop, and police roadblock — wetin dem fit check, wetin levy dey legal, and how to handle dem if dem try extort you.",
    yo: "Awọn ẹtọ rẹ ni awọn ibudo FRSC, VIO, ati ọlọpaa — ohun ti wọn le ṣayẹwo, awọn adeta ti o tọ, ati bi a ṣe le farada ikọlu.",
    ha: "Haƙƙoƙinka a binciken FRSC, VIO, da garkuwan 'yan sanda — abin da za su iya bincika, wane haraji ne bisa doka, da yadda za a magance cin hanci.",
    ig: "Ikike gị na ọdụ FRSC, VIO, na nkwụsị uwe ojii — ihe ha nwere ike nyochaa, ụtụ ndị kwesịrị iwu, na otu e si ejikwa ha maka nnwere.",
  },
  icon: "Car",
  color: "bg-blue-50 text-blue-700",
  topics: [
    {
      slug: "frsc-rights",
      title: {
        en: "Your Rights at FRSC Checkpoints",
        pcm: "Your Rights for FRSC Checkpoint",
        yo: "Awọn Ẹtọ Rẹ ni Ibudo FRSC",
        ha: "Haƙƙoƙinka a Binciken FRSC",
        ig: "Ikike Gị na Ọdụ FRSC",
      },
      summary: {
        en: "The Federal Road Safety Corps (FRSC) is responsible for road safety enforcement. They can check your vehicle documents but cannot extort, harass, or illegally detain you.",
        pcm: "FRSC dey handle road safety. Dem fit check your vehicle papers but dem no fit collect bribe, harass you, or illegally hold you.",
        yo: "Ẹgbẹ Aabo Ọna Ilu Apapo (FRSC) ni o jẹ ojutu fun imuse aabo ọna. Wọn le ṣayẹwo awọn iwe ọkọ rẹ ṣugbọn ko le kọlu, ṣe ikọlu, tabi fi ọ pamọ́ ni aitọ.",
        ha: "Rundunar Tsaron Hanyoyi ta Tarayya (FRSC) tana da alhakin tilasta bin tsaron hanyoyi. Za su iya bincika takardunka amma ba za su iya cin hanci, cin zarafi, ko tsare ka ba daidai ba.",
        ig: "Federal Road Safety Corps (FRSC) na-ahụ maka mmegharị nchedo ụzọ. Ha nwere ike nyochaa akwụkwọ ụgbọ gị mana ha enweghị ike ịjaghasị, ịhụ gị n'anya ọjọọ, ma ọ bụ ijide gị n'ụzọ na-ezighị ezi.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Request your driver's licence, vehicle licence, insurance certificate, and road worthiness certificate",
          "Check that your vehicle is roadworthy",
          "Issue fines for traffic violations",
          "Impound a vehicle that poses a public danger",
          "Check that your vehicle number plate is valid",
        ],
        pcm: ["Ask for your driver's licence, vehicle licence, insurance, and road worthiness", "Check if your vehicle dey roadworthy", "Give you fine for traffic offence", "Impound vehicle wey dey dangerous to public", "Check if your number plate correct"],
        yo: ["Beere fun iwe awakọ rẹ, iwe ọkọ, iwe iṣeduro, ati iwe ọna", "Ṣayẹwo bi ọkọ rẹ ṣe dara fun ọna", "Fun ọ ni itanran fun ìka ọna", "Gba ọkọ ti o jẹ eewu fun ọpọlọpọ", "Ṣayẹwo boya nọmba awo rẹ wulo"],
        ha: ["Nemi lasinka, lasisin mota, takardar inshora, da takardar dacewa da hanya", "Bincika ko motar ka ta dace da hanya", "Ba ka tarar keta doka kan hanya", "Kwace mota da ke hatsarin jama'a", "Bincika ko faranti lambar motar ka daidai"],
        ig: ["Rịọ laịsensị ịkwọ ụgbọ, laịsensị ụgbọ, asambodo insurance, na asambodo ụzọ", "Nyochaa ma ụgbọ gị dị mma maka ụzọ", "Nye gị mkpọsa maka mmebi iwu ụzọ", "Nweta ụgbọ na-egbu egbu maka ọha", "Nyochaa ma nọmba ụgbọ gị dị mma"],
      },
      cannotDo: {
        en: [
          "Collect unofficial cash payments — all fines must be receipted",
          "Seize your vehicle without issuing an official impoundment notice",
          "Demand food, airtime, or gifts",
          "Use abusive or threatening language",
          "Detain you without a valid legal reason",
          "Request documents not listed under the Highway Code",
        ],
        pcm: ["Collect unofficial cash — all fine must get receipt", "Seize your vehicle without official paper", "Ask for food, recharge card, or gift", "Abuse or threaten you", "Hold you without valid legal reason", "Ask for documents wey Highway Code no require"],
        yo: ["Gba owo ni aṣiri — gbogbo itanran gbọdọ ni 英 riri", "Gba ọkọ laisi iwe ijagba alaye", "Beere fun ounje, akoko afẹfẹ, tabi ẹbun", "Lo ede ikọlu tabi ìdọjútì", "Fi ọ pamọ́ laisi idi ofin to dara", "Beere awọn iwe ti kii ṣe ohun ti Highway Code nilo"],
        ha: ["Karɓar kuɗi a ɓoye — duk tarar dole ta sami kirtani", "Kwace motar ba tare da takarda hukuma ba", "Nemi abinci, lokacin waya, ko kyauta", "Yi amfani da harshe mai cutarwa ko barazana", "Tsare ka ba tare da dalilin doka mai inganci ba", "Nemi takardun da Highway Code bai bukata ba"],
        ig: ["Nweta ego na-ezighị ezi — mkpọsa niile kwesịrị recept", "Nweta ụgbọ gị na-enweghị akwụkwọ nkwụpụ ọrụ", "Rịọ nri, oge ekwenti, ma ọ bụ onyinye", "Ojiji asụsụ ọjọọ ma ọ bụ iyi egwu", "Jide gị na-enweghị ezi ihe kpatara iwu", "Rịọ akwụkwọ ndị na-adịghị n'Highway Code"],
      },
      whatToDo: {
        en: [
          "Pull over calmly and safely when signalled",
          "Greet the officer respectfully",
          "Provide your documents calmly",
          "If fined, demand a printed official receipt — never pay cash without a receipt",
          "Note the officer's name, badge number, and station",
          "Report extortion to FRSC via 122 or their website",
        ],
        pcm: ["Pull over calmly when dem signal you", "Greet the officer with respect", "Give your documents without trouble", "If dem fine you, demand official printed receipt — never pay cash without receipt", "Note officer name, badge number, and station", "Report extortion to FRSC: call 122 or report online"],
        yo: ["Duro ni ijẹ nigba ti wọn ba fun ami", "Ki ọfẹ pẹlu ọwọ", "Fun awọn iwe rẹ ni idakẹjẹ", "Ti a ba fun ọ ni itanran, beere fun riri alaye ti a tẹ — má san owo laisi riri", "Ṣe akiyesi orukọ ọfẹ, nọmba ati ibudo", "Ròyìn ikọlu si FRSC nipasẹ 122"],
        ha: ["Tsaya a hankali kuma lafiya idan aka yi maka alamar", "Yi wa jandarm gaisuwa da ladabi", "Ba da takardunka cikin nutsuwa", "Idan aka ba ka tara, nemi kirtani hukuma — kada ka biya kuɗi ba tare da kirtani ba", "Lura da sunan jandarm, badge, da tashar", "Kai ƙara cin hanci ga FRSC ta hanyar 122"],
        ig: ["Kwụsị ụgbọ n'udo mgbe ha nyere gị akara", "Nnọọ onye ọrụ ahụ n'ụzọ ọcha", "Nye akwụkwọ gị n'ịdị jụụ", "Ọ bụrụ na e nye gị mkpọsa, rịọ recept ọrụ—akwụkwala ego na-enweghị recept", "Cheta aha onye ọrụ, badge, na ụlọ ọrụ ya", "Kọọ nnwere na FRSC site na 122"],
      },
      whatNotToDo: {
        en: [
          "Do not drive away from a checkpoint — it is a serious offence",
          "Do not pay bribes — carry out your right to demand a receipt",
          "Do not argue aggressively",
          "Do not leave your car running unattended at a checkpoint",
          "Do not allow officers into your vehicle without clear justification",
        ],
        pcm: ["No drive away from checkpoint — na serious offence", "No give bribe — demand receipt", "No argue aggressively", "No leave your engine running without you for checkpoint", "No allow officer enter your vehicle without clear reason"],
        yo: ["Má wakọ lọ kuro ni ibudo — o jẹ ẹṣẹ pataki", "Má fun ẹbọ — lo ẹtọ rẹ lati beere fun riri", "Má ṣe ariyanjiyan ni agbara", "Má fi ọkọ rẹ silẹ n'iyara ni ibudo", "Má jẹ ki awọn ọfẹ wọ ọkọ rẹ laisi idi to dara"],
        ha: ["Kada ka tuka zuwa daga bincike — babban laifi ne", "Kada ka ba da cin hanci — nemi kirtani", "Kada ka yi jayayya cikin zafin rai", "Kada ka bar injinan motar tana tafiya ba tare da ka ba a bincike", "Kada ka bar jandarm ya shiga motar ka ba tare da dalili mai bayyanawa ba"],
        ig: ["Agakwala ụgbọ na-agbapụ na ọdụ — ọ bụ nnukwu mmehie", "Atụkwasịla ego n'aka ha — rịọ recept", "Emekwala esemokwu n'ike", "Hapụkwala injin gị na-agba n'ọdụ na-enweghị gị", "Ikwekwala ndị ọrụ ọ bụla banye n'ime ụgbọ gị na-enweghị ihe kpatara doro anya"],
      },
      laws: [
        {
          name: "Federal Road Safety Commission Act",
          section: "Section 10",
          plainEnglish: {
            en: "FRSC officers are authorised to stop vehicles, check documents, and issue fines for road traffic offences. All payments must be made through official channels with receipts.",
            pcm: "FRSC officers get authority to stop vehicles, check documents, and issue fines. All payments must be through official channels with receipt.",
            yo: "Awọn ọfẹ FRSC ni aṣẹ lati da awọn ọkọ duro, ṣayẹwo awọn iwe, ati fun awọn itanran. Gbogbo awọn sisanwo gbọdọ wa nipasẹ awọn ikanni alaye.",
            ha: "Jandaman FRSC na da izini don tsai da motoci, bincika takardun, da ba da tarar. Duk biyan kuɗi dole ta kasance ta hanyar hanyoyin hukuma tare da kirtani.",
            ig: "Ndị ọrụ FRSC nwere ikike ịkwụsị ụgbọ, inyocha akwụkwọ, na inye mkpọsa maka mmebi iwu ụzọ. Ụgwọ niile kwesịrị ikwụ site na ụzọ ọrụ na recept.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "An FRSC officer stops you and your documents are all valid. He refuses to let you go unless you 'settle' him.",
            pcm: "FRSC officer stop you, all your papers correct. He say you must 'settle' am before he let you go.",
            yo: "Ọfẹ FRSC da ọ duro ati pe gbogbo awọn iwe rẹ wulo. O kọ lati jẹ ki o lọ ayafi ti o ba 'yanju' rẹ.",
            ha: "Jandamin FRSC ya tsai da kai kuma duk takardunka sun yi daidai. Yana ƙi bar ka tafi sai ka 'biya' shi.",
            ig: "Onye ọrụ FRSC kwụsịa gị na akwụkwọ gị niile dị mma. Ọ jụ ịhapụ gị gaa ma ọ bụrụ na ịkwụghị ya ụgwọ.",
          },
          steps: {
            en: [
              "Stay calm. Do not pay any money.",
              "State clearly: 'All my documents are valid. I am not required to pay anything other than official fines.'",
              "Ask for the officer's name and service number.",
              "Politely ask: 'Are you issuing me an official fine? Please provide a receipt.'",
              "If he persists, note all details and report to FRSC: call 122 or report on their official portal.",
              "You may also report to the Independent Corrupt Practices Commission (ICPC).",
            ],
            pcm: ["No panic, no pay.", "Tell am: 'All my papers correct. I no go pay any unofficial money.'", "Ask for officer name and service number.", "Ask: 'You dey give me official fine? Give me receipt.'", "If he continue, note everything and report to FRSC: call 122.", "You fit also report to ICPC."],
            yo: ["Jẹ ki o balẹ. Má san owo eyikeyi.", "Sọ gbangba: 'Gbogbo awọn iwe mi wulo. Mi o nilo lati san ohunkohun yatọ si itanran alaye.'", "Beere fun orukọ ọfẹ ati nọmba iṣẹ.", "Beere pẹlu ọwọ: 'Ṣe o n fun mi ni itanran alaye? Jọwọ pese riri.'", "Ti o ba tẹsiwaju, gba alaye gbogbo ati ròyìn si FRSC: pe 122.", "O tun le ròyìn si ICPC."],
            ha: ["Kasance a nutsuwa. Kada ka biya komai.", "Fada a sarari: 'Duk takarduna sun yi daidai. Ba ni da wajibcin biya komai banda tarar hukuma.'", "Nemi sunan jandamin da lambar aiki.", "Yi tambaya da ladabi: 'Kana ba ni tarar hukuma? Don Allah ba ni kirtani.'", "Idan ya ci gaba, rubuta komai kuma kai ƙara ga FRSC: kira 122.", "Kuma zaka iya kai ƙara ga ICPC."],
            ig: ["Nọrọ n'udo. Akwụkwala ego ọ bụla.", "Kwuo nke ọma: 'Akwụkwọ m niile dị mma. Achọghị m ịkwụ ihe ọ bụla karịa mkpọsa ọrụ.'", "Rịọ aha onye ọrụ na nọmba ọrụ ya.", "Jụọ ya n'ụzọ ọcha: 'I na-enye m mkpọsa ọrụ? Biko nye m recept.'", "Ọ bụrụ na ọ gaa n'ihu, dee ihe niile ma kọọ na FRSC: kpọọ 122.", "Ị nwekwara ike kọọ na ICPC."],
          },
        },
      ],
    },
    {
      slug: "vio-rights",
      title: {
        en: "Your Rights with VIO Officers",
        pcm: "Your Rights with VIO",
        yo: "Awọn Ẹtọ Rẹ pẹlu VIO",
        ha: "Haƙƙoƙinka tare da VIO",
        ig: "Ikike Gị na VIO",
      },
      summary: {
        en: "The Vehicle Inspection Officers (VIO) are state-level officials who inspect commercial and private vehicles for roadworthiness. Their jurisdiction and powers are limited — they cannot act like police.",
        pcm: "VIO na state officials wey inspect vehicle for roadworthiness. Their power get limit — dem no fit act like police.",
        yo: "Awọn Oṣiṣẹ Ayẹwo Ọkọ (VIO) jẹ awọn oṣiṣẹ ipinle ti o ṣayẹwo awọn ọkọ aladani ati ti iṣowo fun ọna. Agbara wọn ni opin.",
        ha: "Jandaman Binciken Mota (VIO) su ne jami'an jiha da ke bincika motoci na kasuwanci da masu zaman kansu. Ikon su yana da iyaka.",
        ig: "Vehicle Inspection Officers (VIO) bụ ndị ọrụ steeti na-enyocha ụgbọ ndị ahịa na nke onwe onye maka ụzọ. Ọchịchọ ha dị oke — ha enweghị ike ime ka ndị uwe ojii.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Inspect your vehicle for roadworthiness",
          "Check your vehicle licence and road worthiness certificate",
          "Issue fines for vehicle standard violations",
          "Impound vehicles that fail inspection",
        ],
        pcm: ["Inspect your vehicle for roadworthiness", "Check your vehicle licence and road worthiness", "Give fine for vehicle standard violation", "Impound vehicle wey fail inspection"],
        yo: ["Ṣayẹwo ọkọ rẹ fun ọna", "Ṣayẹwo iwe ọkọ rẹ ati iwe ọna", "Fun itanran fun awọn ìka ipele ọkọ", "Gba awọn ọkọ ti o kuna idanwo"],
        ha: ["Bincika motar ka don dacewa da hanya", "Bincika lasisin motar ka da takardar dacewa", "Ba da tara don keta dokokin mota", "Kwace motocin da suka kasa bincike"],
        ig: ["Nyochaa ụgbọ gị maka ụzọ", "Nyochaa laịsensị ụgbọ gị na asambodo ụzọ", "Inye mkpọsa maka mmebi ọkwa ụgbọ", "Nweta ụgbọ ndị na-emeghị ule"],
      },
      cannotDo: {
        en: [
          "Act as law enforcement officers — they are not police",
          "Carry or use firearms",
          "Arrest drivers for criminal offences",
          "Demand money that is not an officially receipted fine",
          "Operate at night or in plainclothes without clear identification",
        ],
        pcm: ["Act like police — dem no be police", "Carry gun", "Arrest driver for criminal offence", "Collect money wey no be official receipted fine", "Work at night or in mufti without proper ID"],
        yo: ["Ṣiṣẹ bi awọn ọlọpaa — wọn kii ṣe ọlọpaa", "Gbe tabi lo ohun ija", "Mu awakọ fun awọn ẹṣẹ ọdaràn", "Beere owo ti kii ṣe itanran alaye pẹlu riri", "Ṣiṣẹ ni alẹ tabi ni aṣọ alagbada laisi idanimọ to dara"],
        ha: ["Zama kamar 'yan sanda — ba 'yan sanda bane", "Ɗauke ko amfani da makami", "Kama direba don laifukan aikata laifi", "Nemi kuɗi wanda ba tarar da kirtani ba", "Aiki da dare ko a cikin tufafin farar hula ba tare da bayyananniyar shaida ba"],
        ig: ["Ime ka ndị uwe ojii — ha abụghị ndị uwe ojii", "Iburu ma ọ bụ ojiji egbe", "Jide ọkwọ ụgbọ maka mmehie mpụ", "Rịọ ego na-abụghị mkpọsa ọrụ na recept", "Ọrụ n'abalị ma ọ bụ n'uwe onwe na-enweghị njirimara doro anya"],
      },
      whatToDo: {
        en: [
          "Confirm the officer's identity — ask for their VIO ID card",
          "Cooperate with a legitimate inspection",
          "Demand a receipt for any fine",
          "Report abuse to the State Ministry of Transport",
        ],
        pcm: ["Confirm the officer ID — ask for their VIO ID card", "Cooperate with proper inspection", "Demand receipt for any fine", "Report abuse to State Ministry of Transport"],
        yo: ["Jẹrisi idanimọ ọfẹ — beere fun kaadi VIO wọn", "Ṣiṣẹ pẹlu ayẹwo ti o tọ", "Beere fun riri fun itanran eyikeyi", "Ròyìn ilokulo si Ile-iṣẹ Ijọba Ipinle ti Irinna"],
        ha: ["Tabbatar da shaida jandamin — nemi kaotinan VIO nasu", "Yi haɗin gwiwa da bincike na gaskiya", "Nemi kirtani ga duk wata tara", "Kai ƙara cin zarafi ga Ma'aikatar Sufuri ta Jiha"],
        ig: ["Nwaa njirimara onye ọrụ ahụ — rịọ kaadị VIO ha", "Mekọọ n'ule kwesịrị", "Rịọ recept maka mkpọsa ọ bụla", "Kọọ mmegbu na Minịstri Steeti nke Ụgbọ"],
      },
      whatNotToDo: {
        en: [
          "Do not pay cash without a receipt",
          "Do not allow a VIO officer to drive your vehicle away without documentation",
          "Do not mistake VIO for FRSC — their powers are different",
        ],
        pcm: ["No pay cash without receipt", "No allow VIO officer drive your vehicle away without paper", "No confuse VIO with FRSC — their powers dey different"],
        yo: ["Má san owo laisi riri", "Má jẹ ki ọfẹ VIO wakọ ọkọ rẹ lọ laisi iwe", "Má dapo VIO pẹlu FRSC — awọn agbara wọn yatọ"],
        ha: ["Kada ka biya kuɗi ba tare da kirtani ba", "Kada ka bar jandamin VIO ya tuka motar ka da tafiya ba tare da takardu ba", "Kada ka ruɗe VIO da FRSC — ikonsu ya bambanta"],
        ig: ["Akwụkwala ego na-enweghị recept", "Ikwekwala onye ọrụ VIO ịkwọ ụgbọ gị agapụ na-enweghị akwụkwọ", "Ejikotaghị VIO na FRSC — ọchịchọ ha dị iche iche"],
      },
      laws: [
        {
          name: "Motor Vehicle (Prohibition) Act & State Transport Laws",
          section: "Various Sections",
          plainEnglish: {
            en: "VIO officers derive their powers from state transport legislation. They are not empowered to make criminal arrests. Their primary mandate is vehicle inspection.",
            pcm: "VIO get their power from state transport law. Dem no get power to do criminal arrest. Their main job na vehicle inspection.",
            yo: "Awọn ọfẹ VIO gba agbara wọn lati ofin irinna ipinle. Wọn ko ni aṣẹ lati mu ẹnikẹni fun ẹṣẹ ọdaràn.",
            ha: "Jandaman VIO suna samun ikonsu daga dokokin sufuri na jiha. Ba a basu izinin yin kama na laifukan aikata laifi ba.",
            ig: "Ndị ọrụ VIO na-enweta ọchịchọ ha site n'iwu ụgbọ steeti. E nyeghị ha ikike ime njide mpụ. Ọrụ ha bụ nyochaa ụgbọ.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "police-roadblock",
      title: {
        en: "Police Roadblocks & Stops",
        pcm: "Police Roadblock & Stop",
        yo: "Idena Ọna ati Idaduro Ọlọpaa",
        ha: "Garkuwan Hanya da Tsayawa na 'Yan Sanda",
        ig: "Nkwụsị Uwe Ojii n'Ụzọ",
      },
      summary: {
        en: "Police have limited powers at roadblocks. They can check identity and documents but cannot shake you down for money or harass you without lawful reason.",
        pcm: "Police power for roadblock get limit. Dem fit check identity and documents but dem no fit collect money from you or harass you without reason.",
        yo: "Ọlọpaa ni agbara to ni opin ni awọn idena ọna. Wọn le ṣayẹwo idanimọ ati awọn iwe ṣugbọn ko le ji owo tabi ṣe ikọlu laisi idi ofin.",
        ha: "Yan sanda suna da ikon iyakantacce a garkuwan hanya. Za su iya bincika shaida da takardun amma ba za su iya neman kuɗi ko cin zarafi ba tare da dalili na doka ba.",
        ig: "Ndị uwe ojii nwere ike obere na nkwụsị ụzọ. Ha nwere ike nyochaa njirimara na akwụkwọ mana ha enweghị ike ịjaghasị gị maka ego ma ọ bụ ịhụ gị n'anya ọjọọ na-enweghị ezi ihe kpatara.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Ask for your ID or driver's licence",
          "Conduct a search if they have reasonable grounds (not just suspicion based on appearance)",
          "Arrest you if you have committed or are committing a crime",
          "Impound your vehicle for serious traffic violations",
        ],
        pcm: ["Ask for your ID or driver's licence", "Search you if dem get genuine reason — not just because of how you look", "Arrest you if you commit crime", "Impound your vehicle for serious traffic offence"],
        yo: ["Beere fun idanimọ rẹ tabi iwe awakọ", "Ṣe ayẹwo ti wọn ba ni idi to dara — kii ṣe nitori irisi rẹ", "Mu ọ ti o ba ṣe ẹṣẹ", "Gba ọkọ rẹ fun ìka ọna to buruju"],
        ha: ["Nemi ID naka ko lasisin tukin motar", "Yi bincike idan suna da dalili mai kyau — ba kawai zargi bisa bayyanar ka ba", "Kama ka idan ka aikata laifi", "Kwace motar ka don keta muhimmun dokokin hanya"],
        ig: ["Rịọ ID gị ma ọ bụ laịsensị ịkwọ ụgbọ", "Nyochaa gị ọ bụrụ na ha nwere ezi ihe kpatara — ọ bụghị n'ihi ọdịdị gị", "Jide gị ọ bụrụ na ị mere mmehie", "Nweta ụgbọ gị maka nnukwu mmebi iwu ụzọ"],
      },
      cannotDo: {
        en: [
          "Demand money at a roadblock",
          "Search your phone or belongings without a court order",
          "Arrest you based solely on your appearance",
          "Hold you at a roadblock beyond a reasonable time without cause",
          "Fire at your vehicle for failing to stop at a roadblock (without extreme circumstances)",
        ],
        pcm: ["Demand money for roadblock", "Search your phone or things without court order", "Arrest you just because of how you look", "Hold you for roadblock too long without reason", "Shoot your vehicle for not stopping (except extreme situation)"],
        yo: ["Beere owo ni idena ọna", "Ṣayẹwo foonu tabi ohun ini rẹ laisi aṣẹ ile-ẹjọ", "Mu ọ nikan nitori irisi rẹ", "Fi ọ duro ni idena ọna fun akoko pipẹ laisi idi", "Yinbọn si ọkọ rẹ fun aiwo duro ni idena ọna"],
        ha: ["Nemi kuɗi a garkuwar hanya", "Bincika wayar ka ko dukiyarka ba tare da umurnin kotu ba", "Kama ka kawai saboda bayyanarka", "Tsare ka a garkuwa na dogon lokaci ba tare da dalili ba", "Harbi motar ka don rashin tsayawa a garkuwa"],
        ig: ["Rịọ ego n'ọdụ ụzọ", "Nyochaa ekwenti gị ma ọ bụ ihe nile gị na-enweghị iwu ụlọ ikpe", "Jide gị naanị n'ihi ọdịdị gị", "Nọdee gị n'ọdụ ụzọ ogologo oge na-enweghị ihe kpatara", "Kpaa ụgbọ gị maka ọ bụghị ịkwụsị n'ọdụ ụzọ"],
      },
      whatToDo: {
        en: [
          "Stop safely and greet the officer",
          "Provide your ID or driver's licence if asked",
          "If asked for money, say: 'I do not pay at roadblocks. If I have committed an offence, please issue an official fine with a receipt.'",
          "Note officer details and report to the nearest police complaint desk or the Police Service Commission",
        ],
        pcm: ["Stop safely and greet the officer", "Give your ID or licence if dem ask", "If dem ask for money, say: 'I no pay for roadblock. If I do offence, give me official fine with receipt.'", "Note officer details and report to complaint desk or Police Service Commission"],
        yo: ["Duro ni aabo ati ki ọfẹ", "Fun ID rẹ tabi iwe awakọ ti wọn ba beere", "Ti wọn ba beere owo, sọ: 'Mi o san owo ni idena ọna. Ti mo ba ṣe ẹṣẹ, jọwọ fun mi itanran alaye.'", "Ṣe akiyesi alaye ọfẹ ati ròyìn si Igbimọ Iṣẹ Ọlọpaa"],
        ha: ["Tsaya lafiya kuma yi wa jandamin gaisuwa", "Ba da ID naka ko lasisin idan aka nema", "Idan aka nemi kuɗi, ce: 'Ba ni biya a garkuwa. Idan na keta doka, don Allah ba ni tarar hukuma.'", "Lura da bayanan jandamin kuma kai ƙara ga Hukumar Sabis na 'Yan Sanda"],
        ig: ["Kwụsị ụgbọ nke ọma ma nnọọ onye ọrụ ahụ", "Nye ID gị ma ọ bụ laịsensị ọ bụrụ na ha jụọ", "Ọ bụrụ na ha rịọ ego, kwuo: 'Akwụghị m ego n'ọdụ ụzọ. Ọ bụrụ na emeela m mmehie, biko nye m mkpọsa ọrụ na recept.'", "Cheta ihe banyere onye ọrụ ma kọọ na teebụl mkpesa ma ọ bụ Police Service Commission"],
      },
      whatNotToDo: {
        en: [
          "Do not drive through a roadblock — it is dangerous and illegal",
          "Do not pay any money without an official receipt",
          "Do not hand over your phone without a court order",
          "Do not leave your engine running and walk away",
        ],
        pcm: ["No drive through roadblock — dangerous and illegal", "No pay money without official receipt", "No hand over your phone without court order", "No leave engine running and walk away"],
        yo: ["Má wakọ kọja idena ọna — o lewu ati aitọ", "Má san owo eyikeyi laisi riri alaye", "Má fi foonu rẹ fun wọn laisi aṣẹ ile-ẹjọ", "Má fi inaro ọkọ rẹ n'iyara ki o tẹle"],
        ha: ["Kada ka tuka ta garkuwar hanya — haɗari ne kuma ba doka ba", "Kada ka biya kuɗi ba tare da kirtani hukuma ba", "Kada ka mika wayar ka ba tare da umurnin kotu ba", "Kada ka bar injinan motar tana tafiya ka tafi"],
        ig: ["Agakwala n'ụgbọ n'ọdụ ụzọ — ọ dị ize ndụ ma ọ bụghị iwu", "Akwụkwala ego ọ bụla na-enweghị recept ọrụ", "Ekenyekwala ekwenti gị na-enweghị iwu ụlọ ikpe", "Hapụkwala injin gị na-agba wee gaa"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 37",
          plainEnglish: {
            en: "Every citizen of Nigeria is entitled to respect for the privacy of their home and correspondence, and telephone conversations. Police cannot access your phone without a court order.",
            pcm: "Every Nigerian citizen get right to privacy of their home, letters, and phone calls. Police no fit access your phone without court order.",
            yo: "Gbogbo ọmọ ilu Nigeria ni ẹtọ si ọwọ fun ikọkọ ti ile wọn ati lẹta, ati awọn ipe foonu. Ọlọpaa ko le wọle si foonu rẹ laisi aṣẹ ile-ẹjọ.",
            ha: "Kowane ɗan ƙasar Najeriya yana da hakkin mutunci na gidan sa da wasiƙunsa, da tattaunawar wayar tarho. Yan sanda ba za su iya shiga wayar ka ba tare da umurnin kotu ba.",
            ig: "Onye ọ bụla nke Naịjirịa nwere ikike maka nzuzo nke ụlọ ya na akwụkwọ ozi ya, na mkparịta ụka ekwenti. Ndị uwe ojii enweghị ike ọbanye n'ekwenti gị na-enweghị iwu ụlọ ikpe.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "vehicle-impoundment",
      title: {
        en: "Vehicle Impoundment: What Is Legal",
        pcm: "Vehicle Impoundment: Wetin Dey Legal",
        yo: "Gbigba Ọkọ: Ohun Ti O Jẹ Ofin",
        ha: "Kwace Mota: Abin Da Ke Bisa Doka",
        ig: "Nweta Ụgbọ: Ihe Dị n'Iwu",
      },
      summary: {
        en: "FRSC, VIO, and police can only impound your vehicle for specific serious offences. They cannot impound it simply because you refused to pay a bribe or because the violation is minor. You are entitled to a receipt listing all contents, and you have the right to retrieve your vehicle promptly after paying any lawful fine.",
        pcm: "FRSC, VIO, and police fit only impound your vehicle for specific serious offences. Dem no fit impound am just because you refuse to pay bribe or because the offence small. Dem must give you receipt wey list everything inside the vehicle, and you get right to collect your vehicle fast after you pay any lawful fine.",
        yo: "FRSC, VIO, ati ọlọpaa le gba ọkọ rẹ nikan fun awọn ẹṣẹ pataki kan pato. Wọn ko le gba ọkọ rẹ nitori o kọ lati fun ẹbọ tabi nitori ẹṣẹ kekere. O yẹ ki wọn fun ọ ni riri ti o ṣe atokọ gbogbo awọn ohun inu ọkọ, ati pe o ni ẹtọ lati gba ọkọ rẹ pada ni kiakia lẹhin ti o san eyikeyi itanran ofin.",
        ha: "FRSC, VIO, da 'yan sanda za su iya kwace motar ka ne kawai don wasu manyan laifuffuka na musamman. Ba za su iya kwace ta ba kawai saboda ka ƙi ba da cin hanci ko saboda laifin ƙarami ne. Dole ne su ba ka kirtani da ke lissafa abubuwan da ke cikin mota, kuma kana da hakkin dawo da motarka da sauri bayan biyan duk wata tarar da ta dace da doka.",
        ig: "FRSC, VIO, na ndị uwe ojii nwere ike nweta ụgbọ gị naanị maka nnukwu mmehie ndị a kapịtara. Ha enweghị ike nweta ya n'ihi na ị jụrụ ịtụ ego n'aka ha ma ọ bụ n'ihi na mmehie ahụ dị obere. Ha kwesịrị inye gị recept na-edepụta ihe niile dị n'ime ụgbọ, ị nwekwara ikike ịnweta ụgbọ gị ngwa ngwa mgbe ịkwụchara ụgwọ iwu ọ bụla.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Impound a vehicle that poses a clear public danger (e.g., severely defective brakes, overloading)",
          "Impound for serious traffic offences prescribed under the FRSC Act or Highway Code",
          "Issue an official impoundment notice listing the reason and the vehicle's contents",
          "Charge officially approved storage fees where applicable",
        ],
        pcm: [
          "Impound vehicle wey dey clear danger to public (e.g., bad brakes, overload)",
          "Impound for serious traffic offence wey FRSC Act or Highway Code talk about",
          "Issue official impoundment notice wey list the reason and vehicle contents",
          "Charge officially approved storage fee where e apply",
        ],
        yo: [
          "Gba ọkọ ti o jẹ eewu gbangba (fun apẹẹrẹ, bireki ti o buru, apọju ẹru)",
          "Gba ọkọ fun awọn ẹṣẹ ọna pataki bi o ti wọ FRSC Act tabi Highway Code",
          "Fun akọsilẹ ijagba alaye ti o ṣe atokọ idi ati awọn ohun inu ọkọ",
          "Gba owo ipamọ ti a fọwọsi bi o ti yẹ",
        ],
        ha: [
          "Kwace mota da ke barazanar jama'a a fili (misali, birki mara kyau, ɗaukar kaya fiye da kima)",
          "Kwace don manyan laifuffukan hanya da FRSC Act ko Highway Code suka tanada",
          "Ba da takardar kwace hukuma mai lissafin dalilin da abubuwan da ke cikin mota",
          "Karɓar kuɗin ajiya da aka amince da su hukuma inda ya dace",
        ],
        ig: [
          "Nweta ụgbọ na-egbu egbu maka ọha (dịka, breeki ojoo, ibu karịrị)",
          "Nweta maka nnukwu mmehie ụzọ ndị e depụtara n'FRSC Act ma ọ bụ Highway Code",
          "Nye akwụkwọ nkwụpụ ọrụ na-akọwapụta ihe kpatara ya na ihe niile dị n'ime ụgbọ",
          "Bawere ụgwọ nchekwa a kwadoro n'ụzọ ọrụ ebe o dị mkpa",
        ],
      },
      cannotDo: {
        en: [
          "Impound your vehicle because you refused to pay a bribe",
          "Impound for a minor or technical violation where the law does not authorise impoundment",
          "Seize a vehicle without issuing a written receipt that lists all items inside",
          "Charge storage fees that are not officially gazetted or approved",
          "Refuse to release your vehicle after you have paid the lawful fine and met the release conditions",
        ],
        pcm: [
          "Impound your vehicle because you refuse to pay bribe",
          "Impound for small or technical offence wey law no allow impoundment for",
          "Take vehicle without giving written receipt wey list everything inside",
          "Charge storage fee wey government no officially approve",
          "Refuse to release your vehicle after you pay lawful fine and meet release conditions",
        ],
        yo: [
          "Gba ọkọ rẹ nitori o kọ lati san ẹbọ",
          "Gba ọkọ fun ẹṣẹ kekere tabi ti iṣẹ ọna ti ofin ko gba ẹ laaye",
          "Gba ọkọ laisi fifun riri ti o ṣe atokọ gbogbo ohun inu",
          "Gba owo ipamọ ti ko ni atilẹyin alaye tabi ifọwọsi",
          "Kọ lati tu ọkọ rẹ silẹ lẹhin ti o san itanran ofin ati pade awọn ipo itusilẹ",
        ],
        ha: [
          "Kwace motar ka saboda ka ƙi ba da cin hanci",
          "Kwace don ƙaramin laifi ko laifin fasaha wanda doka ba ta bada izini a kansa ba",
          "Kwace mota ba tare da ba da kirtanin rubutu mai lissafin duk abubuwan da ke ciki ba",
          "Karɓar kuɗin ajiya wanda ba a buga shi a jarida ta hukuma ba ko amince da shi",
          "Ƙi sakin motar ka bayan ka biya tarar da ta dace da doka da cika sharuɗɗan saki",
        ],
        ig: [
          "Nweta ụgbọ gị n'ihi na ị jụrụ ịtụ ego n'aka ha",
          "Nweta maka obere mmehie ma ọ bụ mmehie ọrụ ebe iwu anaghị akwado nweta",
          "Nweta ụgbọ na-enweghị inye gị recept ederede na-edepụta ihe niile dị n'ime",
          "Bawere ụgwọ nchekwa ndị na-enweghị nkwado ọrụ ma ọ bụ nkwado",
          "Jụ ịhapụ ụgbọ gị mgbe ịkwụchara ụgwọ iwu ma mezue ọnọdụ ntọhapụ",
        ],
      },
      whatToDo: {
        en: [
          "Ask the officer to state the specific legal reason for impoundment",
          "Demand a written receipt that lists the vehicle's contents and the impoundment reason",
          "Note the officer's name, badge number, and the impound location",
          "Pay only officially receipted fines; keep all receipts as evidence",
          "Contact a lawyer or call FRSC (122) if the impoundment appears unlawful",
        ],
        pcm: [
          "Ask the officer to state the specific legal reason why dem dey impound your vehicle",
          "Demand written receipt wey list vehicle contents and impoundment reason",
          "Note officer name, badge number, and where dem carry the vehicle go",
          "Pay only official receipted fine; keep all receipts as evidence",
          "Contact lawyer or call FRSC (122) if the impoundment look unlawful",
        ],
        yo: [
          "Beere lọwọ ọfẹ fun idi ofin kan pato fun ijagba ọkọ",
          "Beere fun riri ti a kọ ti o ṣe atokọ awọn ohun inu ọkọ ati idi ijagba",
          "Ṣe akiyesi orukọ ọfẹ, nọmba aami, ati ibi ijagba",
          "San nikan awọn itanran ti o ni riri alaye; pa gbogbo awọn riri mọ bi ẹri",
          "Pe agbẹjọro tabi pe FRSC (122) ti ijagba naa ba dabi aitọ",
        ],
        ha: [
          "Nemi jandamin ya faɗi takamaiman dalili na doka don kwacewa",
          "Nemi kirtanin rubutu mai lissafin abubuwan da ke cikin mota da dalili na kwacewa",
          "Lura da sunan jandamin, lambar badge, da wurin da aka kai mota",
          "Biya tarar da aka ba kirtani kawai; ajiye duk kirtanin a matsayin shaida",
          "Tuntuɓi lauya ko kira FRSC (122) idan kwacewa ta yi kama ba bisa doka ba",
        ],
        ig: [
          "Rịọ onye ọrụ ahụ ka ọ kwuo ihe kpatara iwu a kapịtara maka nweta ụgbọ",
          "Rịọ recept ederede na-edepụta ihe niile dị n'ime ụgbọ na ihe kpatara nweta",
          "Cheta aha onye ọrụ, badge, na ebe ọ dọtara ụgbọ ahụ",
          "Kwụọ naanị ụgwọ ndị enwetara recept; chekwaa recept niile dị ka ihe akaebe",
          "Kpọtụrụ ọkà mmụta iwu ma ọ bụ kpọọ FRSC (122) ọ bụrụ na nweta ahụ dị ka iwu ezigheghị",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not pay a bribe to avoid impoundment — it is illegal and funds corruption",
          "Do not drive away after an impoundment order — it can lead to arrest",
          "Do not leave valuables in the vehicle without documenting them on the receipt",
          "Do not sign any blank or incomplete documents at the scene",
        ],
        pcm: [
          "No pay bribe to avoid impoundment — e dey illegal and e dey fund corruption",
          "No drive away after dem give impoundment order — e fit lead to arrest",
          "No leave valuables inside the vehicle without making dem write am on the receipt",
          "No sign any blank or incomplete document for the scene",
        ],
        yo: [
          "Má san ẹbọ lati yago fun ijagba — aitọ ni ati pe o ṣe atilẹyin ibajẹ",
          "Má wakọ lọ lẹhin aṣẹ ijagba — o le yori si imuni",
          "Má fi ohun iyebiye silẹ ninu ọkọ laisi ṣiṣe akọsilẹ wọn lori riri",
          "Má fowo si eyikeyi iwe alaini tabi ti ko pari ni aaye iṣẹlẹ",
        ],
        ha: [
          "Kada ka ba da cin hanci don gujewa kwacewa — ba doka ce kuma tana goyon bayan cin hanci",
          "Kada ka tuka zuwa bayan umurnin kwacewa — yana iya kai ga kama",
          "Kada ka bar kayan daraja a cikin mota ba tare da lissafa su a kan kirtani ba",
          "Kada ka sanya hannu a kan wani takardar da ta fantsama ko ba cikakkiya a wurin",
        ],
        ig: [
          "Atụkwasịla ego n'aka ha iji zere nweta ụgbọ — ọ bụ iwu na-eme ka ọdachi dị mma",
          "Agakwala ụgbọ n'oge e nyere iwu nweta — nweta nwere ike ebute njide",
          "Ahapụkwala ihe ndị bara uru n'ime ụgbọ na-edepụtaghị ha n'ime recept",
          "Abanyelakwala aka gị n'akwụkwọ ọ bụla na-adịghị n'ọdịnaya ma ọ bụ na-ezughị oke n'ebe ahụ",
        ],
      },
      laws: [
        {
          name: "Federal Road Safety Commission Act",
          section: "Section 10 & 11",
          plainEnglish: {
            en: "FRSC officers may impound vehicles for prescribed offences. Any impoundment must be documented with an official notice, and the owner is entitled to a receipt for all items in the vehicle.",
            pcm: "FRSC officers fit impound vehicle for specific offences. Any impoundment must get official notice and the owner must receive receipt for everything inside the vehicle.",
            yo: "Awọn ọfẹ FRSC le gba awọn ọkọ fun awọn ẹṣẹ ti a pato. Ijagba eyikeyi gbọdọ ni akọsilẹ pẹlu akọsilẹ alaye, ati pe oniwun ni ẹtọ si riri fun gbogbo awọn ohun inu ọkọ.",
            ha: "Jandaman FRSC na iya kwace motoci don laifuffukan da aka tanada. Duk wata kwacewa dole ta sami takardar hukuma, kuma mai motar yana da hakkin kirtani na duk abubuwan da ke cikin mota.",
            ig: "Ndị ọrụ FRSC nwere ike nweta ụgbọ maka mmehie ndị e kapịtara. Nweta ọ bụla kwesịrị ịbụ ihe e depụtara n'akwụkwọ ọrụ, onye nwe ụgbọ nwekwara ikike inweta recept maka ihe niile dị n'ime ụgbọ.",
          },
        },
        {
          name: "Highway Code (Nigeria)",
          section: "General Provisions",
          plainEnglish: {
            en: "The Highway Code specifies which violations warrant vehicle impoundment. Minor or technical infractions that do not appear in this list cannot justify impoundment.",
            pcm: "The Highway Code list the violations wey justify impoundment. Small or technical offences wey no dey on the list no fit justify impoundment.",
            yo: "Koodu Ọna ṣe atokọ awọn ìka ti o jẹ ki ijagba ọkọ yẹ. Awọn ẹṣẹ kekere tabi ti iṣẹ ọna ti ko si ninu atokọ yii ko le jẹ ki ijagba jẹ ẹtọ.",
            ha: "Lambar Hanya ta lissafa waɗanne keta doka suke ba da dalilin kwace mota. Ƙananan laifuka ko na fasaha da ba sa wannan jerin ba za su tabbatar da kwacewa ba.",
            ig: "Highway Code na-edepụta mmehie ndị na-akwado nweta ụgbọ. Obere mmehie ma ọ bụ mmehie ọrụ ndị na-adịghị n'ndepụta a enweghị ike ijustify nweta.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A VIO officer stops you, says your tyre tread is slightly worn, and threatens to impound your vehicle unless you pay him ₦5,000 on the spot.",
            pcm: "VIO officer stop you, say your tyre small worn, and threaten to impound your vehicle unless you pay am ₦5,000 cash.",
            yo: "Ọfẹ VIO da ọ duro, sọ pe okun taya rẹ ti fọ die, o si halẹ lati gba ọkọ rẹ ayafi ti o ba san ₦5,000 lẹsẹkẹsẹ.",
            ha: "Jandamin VIO ya tsai da kai, ya ce raban tayar motar ka ya ɗan lalace, ya kuma barazanar kwace motar ka sai ka biya ₦5,000 nan take.",
            ig: "Onye ọrụ VIO kwụsịa gị, kwuo na taịa gị dị obere, na-egosi na ọ ga-anweta ụgbọ gị ma ọ bụrụ na ịkwụghị ya ₦5,000 n'oge ahụ.",
          },
          steps: {
            en: [
              "Remain calm. Do not pay cash on the spot.",
              "Ask the officer to show you his official VIO identification.",
              "Ask him to state the specific law or regulation that authorises impoundment for tyre tread depth.",
              "If he cannot cite a law, say: 'I understand this may be a violation. Please issue me an official fine with a receipt.'",
              "Note his name, badge number, and the time and location of the stop.",
              "Report the attempted extortion to the State Ministry of Transport and, if appropriate, the ICPC.",
            ],
            pcm: [
              "Calm down. No pay cash.",
              "Ask officer to show you official VIO ID.",
              "Ask am to tell you the specific law wey allow impoundment for tyre tread.",
              "If he no fit mention law, say: 'If na violation, give me official fine with receipt.'",
              "Note him name, badge number, time, and location.",
              "Report the extortion attempt to State Ministry of Transport and ICPC.",
            ],
            yo: [
              "Duro ni idakẹjẹ. Má san owo lẹsẹkẹsẹ.",
              "Beere lọwọ ọfẹ lati fihan ọ idanimọ VIO alaye rẹ.",
              "Beere lọwọ rẹ lati darukọ ofin kan pato ti o fun laaye ijagba fun jijin okun taya.",
              "Ti o ba ko le darukọ ofin, sọ: 'Mo ni oye pe eyi le jẹ ẹṣẹ. Jọwọ fun mi itanran alaye pẹlu riri.'",
              "Kọ orukọ rẹ, nọmba aami, akoko ati ibi idaduro.",
              "Ròyìn igbiyanju ikọlu si Ile-iṣẹ Ijọba Ipinle ti Irinna ati ICPC.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka biya kuɗi.",
              "Nemi jandamin ya nuna maka ID na hukuma na VIO.",
              "Nemi shi ya ambaci takamaiman dokar da ta bada izinin kwacewa don zurfin igiyar taya.",
              "Idan ba zai iya ambaci doka ba, ce: 'Na fahimci wannan na iya zama keta doka. Don Allah ba ni tarar hukuma tare da kirtani.'",
              "Rubuta sunansa, lambar badge, lokaci, da wurin tsayawa.",
              "Kai ƙarar yunƙurin cin hanci ga Ma'aikatar Sufuri ta Jiha da ICPC.",
            ],
            ig: [
              "Nọrọ n'udo. Akwụkwala ego n'oge ahụ.",
              "Rịọ onye ọrụ ahụ ka ọ gosi gị njirimara VIO ọrụ ya.",
              "Rịọ ya ka ọ kọọ iwu ma ọ bụ iwuiwu ndị a kapịtara na-akwado nweta maka omimi ihe taịa.",
              "Ọ bụrụ na ọ nweghị ike ịkọ iwu, kwuo: 'Ọ bụrụ na ọ bụ mmehie, biko nye m mkpọsa ọrụ na recept.'",
              "Cheta aha ya, badge, oge, na ebe nkwụsị.",
              "Kọọ nnwere ahụ na Minịstri Steeti nke Ụgbọ na ICPC.",
            ],
          },
        },
      ],
    },
    {
      slug: "driver-documents",
      title: {
        en: "Driver Documents: What to Carry & Your Rights",
        pcm: "Driver Documents: Wetin to Carry & Your Rights",
        yo: "Awọn Iwe Awakọ: Ohun Ti O Yẹ Ki O Gbe & Awọn Ẹtọ Rẹ",
        ha: "Takardun Direba: Abin Da Za Ka Ɗauka & Haƙƙoƙinka",
        ig: "Akwụkwọ Ọkwọ Ụgbọ: Ihe I Kwesịrị Iburu & Ikike Gị",
      },
      summary: {
        en: "You must carry a valid driver's licence, vehicle licence, insurance certificate, and proof of ownership. However, officers can only inspect these documents — they cannot seize your originals. Using document confiscation as an unofficial fine-collection method is illegal.",
        pcm: "You must carry valid driver's licence, vehicle licence, insurance certificate, and proof of ownership. But officers fit only check these documents — dem no fit seize your original copies. Using document seizure as unofficial fine collection na illegal.",
        yo: "O yẹ ki o gbe iwe awakọ to wulo, iwe ọkọ, iwe iṣeduro, ati ẹri ohun-ini. Ṣugbọn awọn ọfẹ le nikan ṣayẹwo awọn iwe wọnyi — wọn ko le gba awọn atilẹba rẹ. Lilo igba iwe bi ọna gbigba itanran ni aitọ.",
        ha: "Dole ka ɗauki ingantaccen lasin tuka, lasin mota, takardar inshora, da hujjar mallaka. Amma jandaman na iya duba waɗannan takardun kawai — ba za su iya kwace asalin takardunka ba. Amfani da kwace takardun a matsayin hanyar tara kuɗin tara ba bisa doka ba ne.",
        ig: "I kwesịrị iburu laịsensị ịkwọ ụgbọ dị n'ike, laịsensị ụgbọ, asambodo insurance, na ihe akaebe nwe. Mana ndị ọrụ nwere ike naanị nyochaa akwụkwọ ndị a — ha enweghị ike nweta ndị izizi gị. Ojiji nweta akwụkwọ dị ka ụzọ nkwụta ego na-ezighị ezi bụ iwu.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Request to see your driver's licence, vehicle licence, insurance certificate, and proof of ownership",
          "Inspect the documents to verify their validity",
          "Issue a fine if a required document is missing or expired",
          "Detain you briefly to verify documents through official channels if authenticity is in question",
        ],
        pcm: [
          "Ask to see your driver's licence, vehicle licence, insurance certificate, and proof of ownership",
          "Inspect the documents to check if dem valid",
          "Give you fine if required document dey missing or don expire",
          "Hold you small to verify documents through official channels if authenticity dey question",
        ],
        yo: [
          "Beere lati ri iwe awakọ rẹ, iwe ọkọ, iwe iṣeduro, ati ẹri ohun-ini",
          "Ṣayẹwo awọn iwe lati jẹrisi pe wọn wulo",
          "Fun itanran ti iwe kan ba nsọnu tabi ti pari",
          "Da ọ duro ni ṣoki lati jẹrisi awọn iwe nipasẹ awọn ikanni alaye ti ìmọ̀ pe wọn jẹ ti ara ba wa ni ibeere",
        ],
        ha: [
          "Nemi ganin lasin tuka, lasin mota, takardar inshora, da hujjar mallaka",
          "Bincika takardun don tabbatar da ingancinsu",
          "Ba da tara idan takarda da ake bukata ta ɓace ko ta ƙare",
          "Riƙe ka ɗan lokaci don tabbatar da takardun ta hanyoyin hukuma idan an yi tambaya game da ingancin su",
        ],
        ig: [
          "Rịọ ịhụ laịsensị ịkwọ ụgbọ gị, laịsensị ụgbọ, asambodo insurance, na ihe akaebe nwe",
          "Nyochaa akwụkwọ ndị ahụ iji gosi na ha dị n'ike",
          "Nye mkpọsa ọ bụrụ na akwụkwọ a chọrọ adịghị ma ọ bụ agwụchala",
          "Jide gị obere oge iji nwaa akwụkwọ site n'ụzọ ọrụ ọ bụrụ na ha ajụ izi ya eziokwu",
        ],
      },
      cannotDo: {
        en: [
          "Seize or retain your original documents — they can only inspect them",
          "Confiscate documents as an informal penalty or to compel payment of a bribe",
          "Demand documents not legally required under the FRSC Act or Highway Code",
          "Refuse to return documents without issuing an official seizure receipt",
          "Use document seizure to delay you indefinitely as a form of pressure",
        ],
        pcm: [
          "Seize or keep your original documents — dem fit only look at them",
          "Confiscate documents as unofficial penalty or to force bribe payment",
          "Ask for documents wey FRSC Act or Highway Code no require",
          "Refuse to return documents without official seizure receipt",
          "Use document seizure to delay you indefinitely as pressure",
        ],
        yo: [
          "Gba tabi mu awọn iwe atilẹba rẹ — wọn le nikan ṣayẹwo wọn",
          "Jẹ awọn iwe ninu bi ijiya alaiṣẹ tabi lati fi ẹ pa agbara san ẹbọ",
          "Beere awọn iwe ti ko nilo ofin labẹ FRSC Act tabi Highway Code",
          "Kọ lati da awọn iwe pada laisi fifun riri ijagba alaye",
          "Lo ijagba iwe lati da ọ duro laisi aala bi ọna titẹ",
        ],
        ha: [
          "Kwace ko riƙe asalin takardunka — na iya duba su kawai",
          "Kwace takardun a matsayin hukunci marasa hukuma ko don tilasta biyan cin hanci",
          "Nemi takardun da FRSC Act ko Highway Code ba ta bukata ba",
          "Ƙi mayar da takardun ba tare da ba da kirtanin kwacewa ba na hukuma",
          "Yi amfani da kwace takardun don jinkirta ka ba iyaka a matsayin nau'in matsin lamba",
        ],
        ig: [
          "Nweta ma ọ bụ jide ndị izizi akwụkwọ gị — ha nwere ike naanị nyochaa ha",
          "Chịkọta akwụkwọ dị ka ntaramahụhụ na-ezighị ezi ma ọ bụ iji manye gị ikwụ ego ụjọ",
          "Rịọ akwụkwọ ndị na-achọghị n'iwu n'okpuru FRSC Act ma ọ bụ Highway Code",
          "Jụ iweghachi akwụkwọ na-enweghị inye recept nweta ọrụ",
          "Ojiji nweta akwụkwọ iji rebe gị oge na-enweghị njedebe dị ka ụdị nrụgide",
        ],
      },
      whatToDo: {
        en: [
          "Carry all required documents: driver's licence, vehicle licence, insurance certificate (third-party minimum), and proof of ownership",
          "Hand documents over for inspection but state clearly: 'You may inspect these — I will not be surrendering them'",
          "If documents are seized, demand an official written receipt listing each document taken",
          "Keep digital copies (photos) of all your documents on your phone as backup",
          "Report unlawful seizure to FRSC (122), VIO's supervising ministry, or the police complaints desk",
        ],
        pcm: [
          "Carry all required documents: driver's licence, vehicle licence, insurance, and proof of ownership",
          "Hand them over for inspection but tell officer: 'You fit check these — I no go surrender them'",
          "If dem seize your documents, demand official written receipt listing each one",
          "Keep digital copies (photos) of all your documents on your phone as backup",
          "Report unlawful seizure to FRSC (122), VIO supervising ministry, or police complaints desk",
        ],
        yo: [
          "Gbe gbogbo awọn iwe ti a beere: iwe awakọ, iwe ọkọ, iwe iṣeduro (ẹkẹta o kere ju), ati ẹri ohun-ini",
          "Fi awọn iwe fun ayẹwo ṣugbọn sọ gbangba: 'O le ṣayẹwo wọnyi — Emi kii yoo jọwọ wọn'",
          "Ti wọn ba gba awọn iwe rẹ, beere fun riri alaye ti a kọ ti o ṣe atokọ iwe kọọkan",
          "Pa awọn daakọ fọnranṣẹ (awọn fọto) ti gbogbo awọn iwe rẹ lori foonu rẹ gẹgẹbi afẹyinti",
          "Ròyìn ijagba aiti si FRSC (122), ile-iṣẹ abojuto VIO, tabi igbimọ ẹdun ọlọpaa",
        ],
        ha: [
          "Ɗauki duk takardun da ake bukata: lasin tuka, lasin mota, takardar inshora (na uku aƙalla), da hujjar mallaka",
          "Mika takardun don bincike amma fada a sarari: 'Zaka iya bincika waɗannan — ba zan mika su ba'",
          "Idan aka kwace takardunka, nemi kirtanin rubutu na hukuma mai lissafin kowane takarda da aka ɗauka",
          "Ajiye kwafi na dijital (hotuna) na duk takardunka a wayarka a matsayin ajiyar baya",
          "Kai ƙara kwacewa marasa doka ga FRSC (122), ma'aikatar da ke kula da VIO, ko teburin korafe-korafe na 'yan sanda",
        ],
        ig: [
          "Buru akwụkwọ niile a chọrọ: laịsensị ịkwọ ụgbọ, laịsensị ụgbọ, asambodo insurance (nke nke atọ n'ala), na ihe akaebe nwe",
          "Nyefee akwụkwọ maka nyocha mana kwuo nke ọma: 'Ị nwere ike nyochaa ndị a — agaghị m nyefee ha'",
          "Ọ bụrụ na e nwetara akwụkwọ gị, rịọ recept ederede ọrụ na-edepụta akwụkwọ ọ bụla e wepụtara",
          "Chekwaa onyonyo dijitalụ (foto) nke akwụkwọ gị niile n'ekwenti gị dị ka nchekwa",
          "Kọọ nweta na-ezighị ezi na FRSC (122), minịstri na-ahụ maka VIO, ma ọ bụ teebụl mkpesa uwe ojii",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not hand over your original documents and walk away — always stay present during inspection",
          "Do not pay a bribe in exchange for the return of your documents",
          "Do not sign any blank receipt or document presented by an officer",
          "Do not drive without at least the minimum required documents — keep them in the vehicle at all times",
        ],
        pcm: [
          "No hand over your original documents and walk away — always stay while dem dey inspect",
          "No pay bribe in exchange for your documents to be returned",
          "No sign any blank receipt or document wey officer present to you",
          "No drive without at least the minimum required documents — always keep them inside the vehicle",
        ],
        yo: [
          "Má fi awọn iwe atilẹba rẹ fun wọn ki o lọ — duro ni gbogbo igba ni akoko ayẹwo",
          "Má san ẹbọ ni paaro fun ipadabọ awọn iwe rẹ",
          "Má fowo si eyikeyi riri alaini tabi iwe ti ọfẹ ba gbekalẹ",
          "Má wakọ laisi awọn iwe ti o nilo — pa wọn mọ ninu ọkọ ni gbogbo igba",
        ],
        ha: [
          "Kada ka mika asalin takardunka ka tafi — koyaushe ka kasance a wurin lokacin bincike",
          "Kada ka ba da cin hanci don dawo da takardunka",
          "Kada ka sanya hannu a kan wani kirtani ko takardar da ta fantsama da jandamin ya gabatar",
          "Kada ka tuka ba tare da aƙalla takardun da ake bukata ba — koyaushe ka ajiye su a cikin mota",
        ],
        ig: [
          "Anyọkwala ndị izizi akwụkwọ gị wee gaa — nọrọ n'oge nyocha niile",
          "Akwụkwala ego ụjọ n'ozụchange maka iweghachi akwụkwọ gị",
          "Abanyelakwala aka gị n'akwụkwọ recept ọ bụla na-adịghị n'ọdịnaya ma ọ bụ akwụkwọ onye ọrụ ahụ wetara",
          "Akwọkwala ụgbọ na-enweghị ọ dị ka ọchụchọ n'ala nke akwụkwọ a chọrọ — chekwaanụ ha n'ime ụgbọ n'oge niile",
        ],
      },
      laws: [
        {
          name: "Federal Road Safety Commission Act",
          section: "Section 10",
          plainEnglish: {
            en: "FRSC officers are authorised to inspect vehicle documents. There is no provision empowering them to seize original documents as an enforcement or penalty mechanism.",
            pcm: "FRSC officers get authority to inspect vehicle documents. There is no law wey allow them to seize original documents as enforcement or penalty.",
            yo: "Awọn ọfẹ FRSC ni aṣẹ lati ṣayẹwo awọn iwe ọkọ. Ko si ipese kan ti o fun wọn ni agbara lati gba awọn iwe atilẹba gẹgẹbi ọna imuse tabi ijiya.",
            ha: "Jandaman FRSC na da izini don bincika takardun mota. Babu wata tanadi da ke ba su izinin kwace asalin takardun a matsayin hanyar tilastawa ko hukunci.",
            ig: "Ndị ọrụ FRSC nwere ikike ịnyocha akwụkwọ ụgbọ. Ọ dịghị ihe e depụtara na-enye ha ike ịnweta ndị izizi akwụkwọ dị ka usoro mmejuputa iwu ma ọ bụ ntaramahụhụ.",
          },
        },
        {
          name: "Motor Vehicles (Third Party Insurance) Act",
          section: "Section 3 & 4",
          plainEnglish: {
            en: "Every vehicle used on a public road must have at least a valid third-party insurance certificate. Officers may inspect this certificate but cannot permanently confiscate it.",
            pcm: "Every vehicle wey dey use public road must get at least valid third-party insurance certificate. Officers fit inspect this certificate but dem no fit permanently confiscate am.",
            yo: "Gbogbo ọkọ ti a lo lori ọna gbangba gbọdọ ni o kere ju iwe iṣeduro ẹkẹta to wulo. Awọn ọfẹ le ṣayẹwo iwe yii ṣugbọn ko le gba ni titilai.",
            ha: "Duk mota da ake amfani da ita a kan hanyar jama'a dole ta sami aƙalla ingantacciyar takardar inshora ta ɓangare na uku. Jandaman na iya bincika wannan takardar amma ba za su iya kwace ta dindindin ba.",
            ig: "Ụgbọ ọ bụla a na-eji n'ụzọ ọha kwesịrị inwe ọ dị ka asambodo insurance nke nke atọ dị n'ike. Ndị ọrụ nwere ike nyochaa asambodo a mana ha enweghị ike nweta ya n'oge niile.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A police officer at a roadblock takes your driver's licence and tells you he will only return it after you pay him ₦3,000.",
            pcm: "Police officer for roadblock collect your driver's licence and tell you he go only return am after you pay him ₦3,000.",
            yo: "Ọlọpaa kan ni idena ọna gba iwe awakọ rẹ o si sọ pe oun yoo da pada nikan lẹhin ti o san ₦3,000 fun un.",
            ha: "Jandamin 'yan sanda a garkuwar hanya ya ɗauki lasin tukanka ya ce zai mayar da shi ne kawai bayan ka biya shi ₦3,000.",
            ig: "Onye uwe ojii n'ọdụ ụzọ weere laịsensị ịkwọ ụgbọ gị ma kwuo ya ga-aweghachi ya naanị mgbe ịkwụchara ya ₦3,000.",
          },
          steps: {
            en: [
              "Stay calm. Do not pay.",
              "State clearly: 'Seizing my original documents without an official receipt is unlawful. Please return my licence.'",
              "Demand a written seizure receipt if he refuses to return it immediately.",
              "Note the officer's name, badge number, station, and the time.",
              "Report to the nearest police station DPO, the Police Service Commission, or the ICPC.",
              "You may also report to FRSC if it is an FRSC officer: call 122.",
            ],
            pcm: [
              "Calm down. No pay.",
              "Tell am: 'Seizing my original documents without official receipt na illegal. Return my licence.'",
              "Demand written seizure receipt if he no return am immediately.",
              "Note officer name, badge number, station, and time.",
              "Report to nearest police station DPO, Police Service Commission, or ICPC.",
              "If na FRSC officer, you fit also call 122.",
            ],
            yo: [
              "Duro ni idakẹjẹ. Má san owo.",
              "Sọ gbangba: 'Gbigba awọn iwe atilẹba mi laisi riri alaye jẹ aitọ. Jọwọ da iwe awakọ mi pada.'",
              "Beere fun riri ijagba ti a kọ ti o ba kọ lati da pada lẹsẹkẹsẹ.",
              "Kọ orukọ ọfẹ, nọmba aami, ibudo, ati akoko.",
              "Ròyìn si DPO ibudo ọlọpaa to sunmọ, Igbimọ Iṣẹ Ọlọpaa, tabi ICPC.",
              "Ti o ba jẹ ọfẹ FRSC, o tun le pe 122.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka biya.",
              "Fada a sarari: 'Kwace asalin takarduna ba tare da kirtanin hukuma ba ba bisa doka ba. Don Allah mayar da lasin tukana.'",
              "Nemi kirtanin kwacewa na rubutu idan ya ƙi mayarwa nan take.",
              "Rubuta sunan jandamin, lambar badge, tashar, da lokaci.",
              "Kai ƙara ga DPO na tashar 'yan sanda mafi kusa, Hukumar Sabis na 'Yan Sanda, ko ICPC.",
              "Idan jandamin FRSC ne, zaka iya kira 122.",
            ],
            ig: [
              "Nọrọ n'udo. Akwụkwala ego.",
              "Kwuo nke ọma: 'Ịnweta ndị izizi akwụkwọ m na-enweghị recept ọrụ bụ iwu na-ezighị ezi. Biko weghachi laịsensị m.'",
              "Rịọ recept nweta ederede ọ bụrụ na ọ jụ ịweghachi ya ozugbo.",
              "Cheta aha onye ọrụ, badge, ụlọ ọrụ, na oge.",
              "Kọọ na DPO nke ụlọ ndị uwe ojii kacha nso, Police Service Commission, ma ọ bụ ICPC.",
              "Ọ bụrụ na ọ bụ onye ọrụ FRSC, ị nwekwara ike ịkpọọ 122.",
            ],
          },
        },
      ],
    },
    {
      slug: "accident-rights",
      title: {
        en: "Your Rights at a Road Traffic Accident Scene",
        pcm: "Your Rights for Road Accident Scene",
        yo: "Awọn Ẹtọ Rẹ ni Aaye Ijamba Ọna",
        ha: "Haƙƙoƙinka a Wurin Haɗarin Hanya",
        ig: "Ikike Gị na Ebe Mberede Ụzọ",
      },
      summary: {
        en: "After a road traffic accident you have the right to seek immediate medical treatment, take photos of the scene, call a lawyer before making any statement, and leave once lawfully free to do so. No officer can unlawfully detain you or compel you to sign a statement at the scene.",
        pcm: "After road accident you get right to seek immediate medical treatment, take photos of the scene, call lawyer before you make any statement, and leave once them free you lawfully. No officer fit unlawfully detain you or force you to sign statement for the scene.",
        yo: "Lẹhin ijamba ọna o ni ẹtọ lati wa itọju ilera lẹsẹkẹsẹ, ya awọn fọto ti aaye naa, pe agbẹjọro ṣaaju sisọ eyikeyi alaye, ati lati lọ ni kete ti o ba ti ni ominira ni ofin lati ṣe bẹ. Ko si ọfẹ ti o le fi ọ pamọ́ ni aitọ tabi fi ọ pa agbara lati fowo si alaye ni aaye.",
        ha: "Bayan haɗarin hanya kana da hakkin neman kulawar likita nan take, ɗaukar hotuna na wurin haɗari, kiran lauya kafin ka ba da wata sanarwa, da barin wurin da zarar ka sami 'yanci bisa doka. Babu jandami da zai iya tsare ka ba bisa doka ba ko tilasta ka sanya hannu a kan sanarwa a wurin.",
        ig: "Mgbe ọ dị mberede n'ụzọ ị nwere ikike ịchọ ọgwụgwọ ozugbo, ịse foto nke ebe ahụ, ịkpọọ ọkà mmụta iwu tupu ị kwuo okwu ọ bụla, na ịpụ mgbe iwu hapụrụ gị. Onye ọrụ ọ bụla enweghị ike ijide gị n'ụzọ na-ezighị ezi ma ọ bụ ịmanye gị itinye aka n'ọnụ n'ebe mmehie.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Secure the accident scene to prevent further harm",
          "Take statements from parties involved and witnesses — voluntarily and at an appropriate time",
          "Arrest a driver if there is reasonable suspicion of a criminal offence (e.g., drunk driving, manslaughter)",
          "Request that vehicles be moved only when necessary for traffic or safety reasons",
        ],
        pcm: [
          "Secure the accident scene to prevent further harm",
          "Take voluntary statements from parties and witnesses at appropriate time",
          "Arrest driver if there is reasonable suspicion of criminal offence (e.g., drunk driving, manslaughter)",
          "Ask for vehicles to be moved only when necessary for traffic or safety",
        ],
        yo: [
          "Ni aaye ijamba lati dena ipalara siwaju",
          "Gba alaye lati awọn ẹgbẹ ati awọn ẹlẹri — ni ifẹ ati ni akoko to yẹ",
          "Mu awakọ ti ẹtọ ti o peye ba wa fun ẹṣẹ ọdaràn (fun apẹẹrẹ, mimu oti wakọ, ipaniyan)",
          "Beere fun awọn ọkọ lati gbe nikan nigba ti o jẹ dandan fun ọna tabi aabo",
        ],
        ha: [
          "Tsare wurin haɗari don hana ƙarin cutarwa",
          "Ɗauki sanarwa daga ɓangarorin da abin ya shafa da shaidu — son rai da a lokaci mai dacewa",
          "Kama direba idan akwai zargi mai ma'ana game da laifin aikata laifi (misali, tuka maye, kisan kai)",
          "Nemi a tura motocin ne kawai idan ya zama dole don dalilai na zirga-zirga ko aminci",
        ],
        ig: [
          "Chebe ebe mmehie ahụ iji gbochie mmetụta ọzọ",
          "Were nkwupụta site n'aka ndị metụtara na ndị ọ hụrụ — n'ike onwe ha na n'oge kwesịrị",
          "Jide ọkwọ ụgbọ ọ bụrụ na e nwere echiche kwesịrị maka mmehie mpụ (dịka ịkwọ ụgbọ na mmanya, igbu mmadụ)",
          "Rịọ ka e bugharịa ụgbọ naanị mgbe ọ dị mkpa maka ụzọ ma ọ bụ nchedo",
        ],
      },
      cannotDo: {
        en: [
          "Delay or prevent you from receiving emergency medical treatment",
          "Compel you to sign a statement at the accident scene",
          "Detain you at the scene without formally arresting you and informing you of the reason",
          "Seize your phone or camera to delete photos of the scene",
          "Prevent you from calling a lawyer before making any statement",
        ],
        pcm: [
          "Delay or stop you from getting emergency medical treatment",
          "Force you to sign statement at the accident scene",
          "Detain you at the scene without formally arresting you and telling you the reason",
          "Seize your phone or camera to delete photos of the scene",
          "Stop you from calling lawyer before you make any statement",
        ],
        yo: [
          "Da duro tabi dena ọ lati gba itọju ilera pajawiri",
          "Fi ọ pa agbara lati fowo si alaye ni aaye ijamba",
          "Fi ọ pamọ́ ni aaye naa laisi imuni rẹ ni alaye ati sísọ idi fun ọ",
          "Gba foonu tabi kamẹra rẹ lati pa awọn fọto ti aaye naa",
          "Dena ọ lati pe agbẹjọro ṣaaju sisọ eyikeyi alaye",
        ],
        ha: [
          "Jinkirta ko hana ka samu magani na gaggawa",
          "Tilasta ka sanya hannu a kan sanarwa a wurin haɗarin",
          "Tsare ka a wurin ba tare da kama ka a hukumance ba da sanar da kai dalili",
          "Kwace wayarka ko kyamararka don share hotuna na wurin",
          "Hana ka kiran lauya kafin ka ba da wata sanarwa",
        ],
        ig: [
          "Rebe ma ọ bụ gbochie gị ịnata ọgwụgwọ mberede",
          "Manye gị itinye aka n'ọnụ n'ebe mmehie",
          "Jide gị n'ebe ahụ na-ejide gị n'ụzọ ọrụ enweghị ikwupụta ihe kpatara",
          "Nweta ekwenti ma ọ bụ igwefoto gị iji hichapụ foto nke ebe ahụ",
          "Gbochie gị ịkpọọ ọkà mmụta iwu tupu ị kwuo okwu ọ bụla",
        ],
      },
      whatToDo: {
        en: [
          "Seek medical attention immediately if you or anyone is injured — your health comes first",
          "Take photos of the accident scene, vehicle positions, damages, and any injuries before anything is moved",
          "Collect the names, phone numbers, and vehicle details of all parties and witnesses",
          "If police arrive, cooperate calmly but state: 'I would like to speak with a lawyer before making any written statement'",
          "Report the accident to your insurer and, where required, to FRSC within 24 hours",
        ],
        pcm: [
          "Seek medical attention immediately if you or anyone dey injured — your health come first",
          "Take photos of accident scene, vehicle positions, damages, and injuries before anything move",
          "Collect names, phone numbers, and vehicle details of all parties and witnesses",
          "If police come, cooperate calmly but say: 'I want to talk to lawyer before I make any written statement'",
          "Report the accident to your insurer and to FRSC within 24 hours where required",
        ],
        yo: [
          "Wa itọju ilera lẹsẹkẹsẹ ti ẹ tabi ẹnikẹni ba ti gbọgbẹ — ilera rẹ wa ni akọkọ",
          "Ya awọn fọto ti aaye ijamba, awọn ipo ọkọ, ibajẹ, ati eyikeyi ipalara ṣaaju ki a ba ohunkohun",
          "Gba awọn orukọ, awọn nọmba foonu, ati alaye ọkọ ti gbogbo awọn ẹgbẹ ati awọn ẹlẹri",
          "Ti ọlọpaa ba de, ṣiṣẹ pẹlu wọn ni idakẹjẹ ṣugbọn sọ: 'Mo fẹ sọrọ pẹlu agbẹjọro ṣaaju ṣiṣe alaye kikọ eyikeyi'",
          "Ròyìn ijamba si aṣeduro rẹ ati si FRSC laarin wakati 24 ni ibi ti o nilo",
        ],
        ha: [
          "Nemi kulawa na likita nan take idan ka ko wani ya ji rauni — lafiyarka ta fi komai muhimmanci",
          "Ɗauki hotuna na wurin haɗarin, matsayin motoci, lalacewar, da duk raunuka kafin a rusa komai",
          "Tattara sunaye, lambobin wayar, da bayanin mota na duk ɓangarori da shaidu",
          "Idan 'yan sanda suka zo, haɗa kai da su cikin nutsuwa amma fada: 'Ina son magana da lauya kafin in ba da wata sanarwa ta rubutu'",
          "Kai rahoto na haɗarin ga kamfanin inshora ka da ga FRSC a cikin awanni 24 inda aka bukata",
        ],
        ig: [
          "Chọọ ọgwụgwọ ozugbo ọ bụrụ na gị ma ọ bụ onye ọ bụla merụrụ ahụ — ahụike gị bụ nke mbụ",
          "See foto nke ebe mmehie, ọnọdụ ụgbọ, mmebi, na imerụ ahụ ọ bụla tupu e kpagharịa ihe ọ bụla",
          "Nweta aha, nọmba ekwenti, na ihe banyere ụgbọ nke ndị niile metụtara na ndị ọ hụrụ",
          "Ọ bụrụ na ndị uwe ojii abịa, mekọọ ha n'ịdị jụụ mana kwuo: 'Achọrọ m ị kparịta ụka na ọkà mmụta iwu tupu m kwuo okwu ederede ọ bụla'",
          "Kọọ mmehie ahụ na onye ọrụ insurance gị na, ebe a chọrọ ya, na FRSC n'ime awa 24",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not flee the scene of an accident — it is a criminal offence",
          "Do not sign any statement or document at the scene without legal advice",
          "Do not move vehicles before photographing their positions (unless there is an immediate safety risk)",
          "Do not make admissions of fault or apologise in a way that can be used against you legally",
        ],
        pcm: [
          "No run away from accident scene — na criminal offence",
          "No sign any statement or document at the scene without legal advice",
          "No move vehicles before you take photos of their positions (unless immediate safety risk)",
          "No admit fault or apologise in a way wey dem fit use against you legally",
        ],
        yo: [
          "Má salọ kuro ni aaye ijamba — o jẹ ẹṣẹ ọdaràn",
          "Má fowo si eyikeyi alaye tabi iwe ni aaye naa laisi imọran ofin",
          "Má gbe awọn ọkọ ṣaaju ki o ya fọto ti awọn ipo wọn (ayafi ti eewu aabo ba wa lẹsẹkẹsẹ)",
          "Má jẹwọ ẹbi tabi tọrọ aforijin ni ọna ti a le lo lodi si ọ ni ofin",
        ],
        ha: [
          "Kada ka gudu daga wurin haɗarin — laifin aikata laifi ne",
          "Kada ka sanya hannu a kan wata sanarwa ko takardar a wurin ba tare da shawara ta doka ba",
          "Kada ka tura motocin kafin ka ɗauki hotuna na matsayinsu (sai dai idan akwai haɗarin aminci na gaggawa)",
          "Kada ka yarda da laifi ko nemi gafara ta hanyar da za a iya amfani da shi a kanka bisa doka",
        ],
        ig: [
          "Ọ gwụghị na-agbapụ n'ebe mmehie — ọ bụ mmehie mpụ",
          "Atinyelakwala aka gị n'okwu ọ bụla ma ọ bụ akwụkwọ n'ebe ahụ na-enweghị ndụmọdụ iwu",
          "Ebughariala ụgbọ tupu ị see foto nke ọnọdụ ha (ma ọ bụrụhaa na e nwere ihe ize ndụ nchedo ozugbo)",
          "Anaghị anabata mmehie ma ọ bụ arịọ mgbaghara n'ụzọ enwere ike iji megide gị n'iwu",
        ],
      },
      laws: [
        {
          name: "Federal Road Safety Commission Act",
          section: "Section 10",
          plainEnglish: {
            en: "FRSC officers are required to respond to road traffic accidents. However, their powers do not include compelling persons to make statements or preventing them from seeking medical care.",
            pcm: "FRSC officers must respond to road accidents. But their power no include forcing people to make statements or stopping them from getting medical care.",
            yo: "Awọn ọfẹ FRSC nilo lati dahun si awọn ijamba ọna. Ṣugbọn awọn agbara wọn ko pẹlu fifi eniyan pa agbara lati ṣe alaye tabi dena wọn lati wa itọju ilera.",
            ha: "Ana buƙatar jandaman FRSC su amsa haɗarin hanya. Amma ikonsu baya haɗa da tilasta mutane su ba da sanarwa ko hana su neman kulawar likita.",
            ig: "A chọrọ ndị ọrụ FRSC ịza ụzọ na mberede ụzọ. Mana ọchịchọ ha anaghị agụnye ịmanye ndị mmadụ inye nkwupụta ma ọ bụ gbochie ha ịchọ ọgwụgwọ.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 6 & 7",
          plainEnglish: {
            en: "A suspect has the right to remain silent and to consult a lawyer before making any statement to the police. No confession or statement made under duress is admissible in court.",
            pcm: "A suspect get right to remain silent and talk to lawyer before making any statement to police. Any confession or statement wey dem force you to make no dey admissible for court.",
            yo: "Olufura ni ẹtọ lati duro ni idakẹjẹ ati lati kan si agbẹjọro ṣaaju ṣiṣe alaye eyikeyi si ọlọpaa. Ko si ijewo tabi alaye ti a ṣe labẹ ìpèníjà ti o le gba si ile-ẹjọ.",
            ha: "Wanda ake zargi yana da hakkin yin shiru da kuma tuntuɓar lauya kafin ya ba da wata sanarwa ga 'yan sanda. Babu wata furcewa ko sanarwa da aka yi ƙarƙashin tilastawa da za a iya yarda da ita a gaban kotu.",
            ig: "Onye a na-eche n'ọchịchọ nwere ikike ịnọ n'udo na ịkparịta ụka na ọkà mmụta iwu tupu ọ kwuo okwu ọ bụla na ndị uwe ojii. Nkwupụta ma ọ bụ ihe e kwuputara n'ike anaghị anabata n'ụlọ ikpe.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "You are involved in a minor road accident. A police officer arrives and says you cannot leave or call anyone until you sign a statement admitting fault.",
            pcm: "You get involved in minor road accident. Police officer come and say you cannot leave or call anyone until you sign statement wey say na your fault.",
            yo: "O ni ipa ninu ijamba ọna kekere. Ọlọpaa kan de o si sọ pe o ko le lọ tabi pe ẹnikẹni titi di igba ti o ba fowo si alaye ti o jẹwọ ẹbi.",
            ha: "Ka shiga cikin ƙaramin haɗarin hanya. Jandamin 'yan sanda ya zo ya ce ba za ka iya tafi ko kiran kowa ba har sai ka sanya hannu a kan sanarwa da ke yarda da laifi.",
            ig: "Ị metụtara na obere mberede ụzọ. Onye uwe ojii abịa ma kwuo na ị nweghị ike ịpụ ma ọ bụ ịkpọọ onye ọ bụla ruo mgbe ị tinye aka n'okwu na-anabata ihe kpatara.",
          },
          steps: {
            en: [
              "Stay calm. Do not sign anything.",
              "State clearly: 'I have the right to remain silent and to consult a lawyer before making any statement. I will not sign any document without legal advice.'",
              "Ask the officer: 'Am I under arrest? If so, please inform me of the specific offence.'",
              "If you are not under formal arrest, you are entitled to leave — state that you are exercising that right.",
              "Call a lawyer, a trusted person, or the Legal Aid Council (08039289236) as soon as possible.",
              "Document everything: officer's name, badge, time, and what was said.",
            ],
            pcm: [
              "Calm down. No sign anything.",
              "Tell officer: 'I get right to remain silent and talk to lawyer before I make any statement. I no go sign any document without legal advice.'",
              "Ask officer: 'You dey arrest me? If yes, tell me the specific offence.'",
              "If dem no formally arrest you, you get right to leave — tell am you dey exercise that right.",
              "Call lawyer, trusted person, or Legal Aid Council (08039289236) as soon as possible.",
              "Document everything: officer name, badge, time, and wetin dem say.",
            ],
            yo: [
              "Duro ni idakẹjẹ. Má fowo si ohunkohun.",
              "Sọ gbangba: 'Mo ni ẹtọ lati duro ni idakẹjẹ ati lati kan si agbẹjọro ṣaaju ṣiṣe alaye eyikeyi. Emi kii yoo fowo si iwe eyikeyi laisi imọran ofin.'",
              "Beere lọwọ ọfẹ: 'Ṣe o n mu mi? Ti bẹẹ ba ri, jọwọ sọ ẹṣẹ kan pato fun mi.'",
              "Ti a ko ba mu ọ ni alaye, o ni ẹtọ lati lọ — sọ pe o n lo ẹtọ yẹn.",
              "Pe agbẹjọro, eniyan ti o gbẹkẹle, tabi Igbimọ Iranlọwọ Ofin (08039289236) ni kete bi o ti ṣee ṣe.",
              "Ṣe akọsilẹ ohun gbogbo: orukọ ọfẹ, aami, akoko, ati ohun ti a sọ.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka sanya hannu a kan komai.",
              "Fada a sarari: 'Ina da hakkin yin shiru da kuma tuntuɓar lauya kafin na ba da wata sanarwa. Ba zan sanya hannu a kan wani takardan ba tare da shawara ta doka ba.'",
              "Tambayi jandamin: 'Kana kama ni ne? Idan haka ne, don Allah sanar da ni takamaiman laifin.'",
              "Idan ba a kama ka a hukumance ba, kana da hakkin tafiya — fada cewa kana amfani da wannan hakkin.",
              "Kira lauya, mutumin da ka amince da shi, ko Majalisar Taimako ta Shari'a (08039289236) da wuri gwargwadon yiwuwa.",
              "Rubuta komai: sunan jandamin, badge, lokaci, da abin da aka faɗa.",
            ],
            ig: [
              "Nọrọ n'udo. Atinyelakwala aka gị n'ihe ọ bụla.",
              "Kwuo nke ọma: 'Nwere m ikike ịnọ n'udo na ịkparịta ụka na ọkà mmụta iwu tupu m kwuo okwu ọ bụla. Agaghị m tinye aka m n'akwụkwọ ọ bụla na-enweghị ndụmọdụ iwu.'",
              "Jụọ onye ọrụ ahụ: 'I jidere m? Ọ bụrụ n'ezie, biko kọọ m mmehie a kapịtara.'",
              "Ọ bụrụ na e jideghị gị n'ụzọ ọrụ, ị nwere ikike ịpụ — kwuo na ị na-eme n'ikike ahụ.",
              "Kpọọ ọkà mmụta iwu, onye a tụkwasịrị obi, ma ọ bụ Legal Aid Council (08039289236) ozugbo o kwere omume.",
              "Depụta ihe niile: aha onye ọrụ, badge, oge, na ihe e kwuru.",
            ],
          },
        },
      ],
    },
  ],
};
