import type { Section } from "./types";

export const drivers: Section = {
  slug: "drivers",
  title: {
    en: "Drivers & Commuters",
    pcm: "Drivers & Commuters",
    yo: "Awọn Awakọ & Awọn Aririn Ajo",
    ha: "Direbobi & Masu Tafiya",
    ig: "Ndị Ọkwọ Ụgbọ & Ndị Na-aga",
  },
  description: {
    en: "Your rights at FRSC checkpoints, VIO stops, and police roadblocks — what officers can check, what levies are legal, and how to handle extortion.",
    pcm: "Your rights for FRSC checkpoint, VIO stop, and police roadblock — wetin dem fit check, wetin levy dey legal, and how to handle dem if dem try extort you.",
    yo: "Awọn ẹtọ rẹ ni awọn ibudo FRSC, VIO, ati ọlọpaa — ohun ti wọn le ṣayẹwo, awọn adeta ti o tọ, ati bi a ṣe le farada ikọlu.",
    ha: "Haƙƙoƙinka a binciken FRSC, VIO, da garkuwan 'yan sanda — abin da za su iya bincika, wane haraji ne bisa doka, da yadda za a magance cin hanci.",
    ig: "Ikike gị na ọdụ FRSC, VIO, na nkwụsị uwe ojii — ihe ha nwere ike nyochaa, ụtụ ndị kwesịrị iwu, na otu e si ejikwa ha maka nnwere.",
  },
  icon: "Car",
  color: "bg-blue-50 text-blue-700",
  topics: [
    {
      slug: "frsc-rights",
      title: {
        en: "Your Rights at FRSC Checkpoints",
        pcm: "Your Rights for FRSC Checkpoint",
        yo: "Awọn Ẹtọ Rẹ ni Ibudo FRSC",
        ha: "Haƙƙoƙinka a Binciken FRSC",
        ig: "Ikike Gị na Ọdụ FRSC",
      },
      summary: {
        en: "The Federal Road Safety Corps (FRSC) is responsible for road safety enforcement. They can check your vehicle documents but cannot extort, harass, or illegally detain you.",
        pcm: "FRSC dey handle road safety. Dem fit check your vehicle papers but dem no fit collect bribe, harass you, or illegally hold you.",
        yo: "Ẹgbẹ Aabo Ọna Ilu Apapo (FRSC) ni o jẹ ojutu fun imuse aabo ọna. Wọn le ṣayẹwo awọn iwe ọkọ rẹ ṣugbọn ko le kọlu, ṣe ikọlu, tabi fi ọ pamọ́ ni aitọ.",
        ha: "Rundunar Tsaron Hanyoyi ta Tarayya (FRSC) tana da alhakin tilasta bin tsaron hanyoyi. Za su iya bincika takardunka amma ba za su iya cin hanci, cin zarafi, ko tsare ka ba daidai ba.",
        ig: "Federal Road Safety Corps (FRSC) na-ahụ maka mmegharị nchedo ụzọ. Ha nwere ike nyochaa akwụkwọ ụgbọ gị mana ha enweghị ike ịjaghasị, ịhụ gị n'anya ọjọọ, ma ọ bụ ijide gị n'ụzọ na-ezighị ezi.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Request your driver's licence, vehicle licence, insurance certificate, and road worthiness certificate",
          "Check that your vehicle is roadworthy",
          "Issue fines for traffic violations",
          "Impound a vehicle that poses a public danger",
          "Check that your vehicle number plate is valid",
        ],
        pcm: ["Ask for your driver's licence, vehicle licence, insurance, and road worthiness", "Check if your vehicle dey roadworthy", "Give you fine for traffic offence", "Impound vehicle wey dey dangerous to public", "Check if your number plate correct"],
        yo: ["Beere fun iwe awakọ rẹ, iwe ọkọ, iwe iṣeduro, ati iwe ọna", "Ṣayẹwo bi ọkọ rẹ ṣe dara fun ọna", "Fun ọ ni itanran fun ìka ọna", "Gba ọkọ ti o jẹ eewu fun ọpọlọpọ", "Ṣayẹwo boya nọmba awo rẹ wulo"],
        ha: ["Nemi lasinka, lasisin mota, takardar inshora, da takardar dacewa da hanya", "Bincika ko motar ka ta dace da hanya", "Ba ka tarar keta doka kan hanya", "Kwace mota da ke hatsarin jama'a", "Bincika ko faranti lambar motar ka daidai"],
        ig: ["Rịọ laịsensị ịkwọ ụgbọ, laịsensị ụgbọ, asambodo insurance, na asambodo ụzọ", "Nyochaa ma ụgbọ gị dị mma maka ụzọ", "Nye gị mkpọsa maka mmebi iwu ụzọ", "Nweta ụgbọ na-egbu egbu maka ọha", "Nyochaa ma nọmba ụgbọ gị dị mma"],
      },
      cannotDo: {
        en: [
          "Collect unofficial cash payments — all fines must be receipted",
          "Seize your vehicle without issuing an official impoundment notice",
          "Demand food, airtime, or gifts",
          "Use abusive or threatening language",
          "Detain you without a valid legal reason",
          "Request documents not listed under the Highway Code",
        ],
        pcm: ["Collect unofficial cash — all fine must get receipt", "Seize your vehicle without official paper", "Ask for food, recharge card, or gift", "Abuse or threaten you", "Hold you without valid legal reason", "Ask for documents wey Highway Code no require"],
        yo: ["Gba owo ni aṣiri — gbogbo itanran gbọdọ ni 英 riri", "Gba ọkọ laisi iwe ijagba alaye", "Beere fun ounje, akoko afẹfẹ, tabi ẹbun", "Lo ede ikọlu tabi ìdọjútì", "Fi ọ pamọ́ laisi idi ofin to dara", "Beere awọn iwe ti kii ṣe ohun ti Highway Code nilo"],
        ha: ["Karɓar kuɗi a ɓoye — duk tarar dole ta sami kirtani", "Kwace motar ba tare da takarda hukuma ba", "Nemi abinci, lokacin waya, ko kyauta", "Yi amfani da harshe mai cutarwa ko barazana", "Tsare ka ba tare da dalilin doka mai inganci ba", "Nemi takardun da Highway Code bai bukata ba"],
        ig: ["Nweta ego na-ezighị ezi — mkpọsa niile kwesịrị recept", "Nweta ụgbọ gị na-enweghị akwụkwọ nkwụpụ ọrụ", "Rịọ nri, oge ekwenti, ma ọ bụ onyinye", "Ojiji asụsụ ọjọọ ma ọ bụ iyi egwu", "Jide gị na-enweghị ezi ihe kpatara iwu", "Rịọ akwụkwọ ndị na-adịghị n'Highway Code"],
      },
      whatToDo: {
        en: [
          "Pull over calmly and safely when signalled",
          "Greet the officer respectfully",
          "Provide your documents calmly",
          "If fined, demand a printed official receipt — never pay cash without a receipt",
          "Note the officer's name, badge number, and station",
          "Report extortion to FRSC via 122 or their website",
        ],
        pcm: ["Pull over calmly when dem signal you", "Greet the officer with respect", "Give your documents without trouble", "If dem fine you, demand official printed receipt — never pay cash without receipt", "Note officer name, badge number, and station", "Report extortion to FRSC: call 122 or report online"],
        yo: ["Duro ni ijẹ nigba ti wọn ba fun ami", "Ki ọfẹ pẹlu ọwọ", "Fun awọn iwe rẹ ni idakẹjẹ", "Ti a ba fun ọ ni itanran, beere fun riri alaye ti a tẹ — má san owo laisi riri", "Ṣe akiyesi orukọ ọfẹ, nọmba ati ibudo", "Ròyìn ikọlu si FRSC nipasẹ 122"],
        ha: ["Tsaya a hankali kuma lafiya idan aka yi maka alamar", "Yi wa jandarm gaisuwa da ladabi", "Ba da takardunka cikin nutsuwa", "Idan aka ba ka tara, nemi kirtani hukuma — kada ka biya kuɗi ba tare da kirtani ba", "Lura da sunan jandarm, badge, da tashar", "Kai ƙara cin hanci ga FRSC ta hanyar 122"],
        ig: ["Kwụsị ụgbọ n'udo mgbe ha nyere gị akara", "Nnọọ onye ọrụ ahụ n'ụzọ ọcha", "Nye akwụkwọ gị n'ịdị jụụ", "Ọ bụrụ na e nye gị mkpọsa, rịọ recept ọrụ—akwụkwala ego na-enweghị recept", "Cheta aha onye ọrụ, badge, na ụlọ ọrụ ya", "Kọọ nnwere na FRSC site na 122"],
      },
      whatNotToDo: {
        en: [
          "Do not drive away from a checkpoint — it is a serious offence",
          "Do not pay bribes — carry out your right to demand a receipt",
          "Do not argue aggressively",
          "Do not leave your car running unattended at a checkpoint",
          "Do not allow officers into your vehicle without clear justification",
        ],
        pcm: ["No drive away from checkpoint — na serious offence", "No give bribe — demand receipt", "No argue aggressively", "No leave your engine running without you for checkpoint", "No allow officer enter your vehicle without clear reason"],
        yo: ["Má wakọ lọ kuro ni ibudo — o jẹ ẹṣẹ pataki", "Má fun ẹbọ — lo ẹtọ rẹ lati beere fun riri", "Má ṣe ariyanjiyan ni agbara", "Má fi ọkọ rẹ silẹ n'iyara ni ibudo", "Má jẹ ki awọn ọfẹ wọ ọkọ rẹ laisi idi to dara"],
        ha: ["Kada ka tuka zuwa daga bincike — babban laifi ne", "Kada ka ba da cin hanci — nemi kirtani", "Kada ka yi jayayya cikin zafin rai", "Kada ka bar injinan motar tana tafiya ba tare da ka ba a bincike", "Kada ka bar jandarm ya shiga motar ka ba tare da dalili mai bayyanawa ba"],
        ig: ["Agakwala ụgbọ na-agbapụ na ọdụ — ọ bụ nnukwu mmehie", "Atụkwasịla ego n'aka ha — rịọ recept", "Emekwala esemokwu n'ike", "Hapụkwala injin gị na-agba n'ọdụ na-enweghị gị", "Ikwekwala ndị ọrụ ọ bụla banye n'ime ụgbọ gị na-enweghị ihe kpatara doro anya"],
      },
      laws: [
        {
          name: "Federal Road Safety Commission Act",
          section: "Section 10",
          plainEnglish: {
            en: "FRSC officers are authorised to stop vehicles, check documents, and issue fines for road traffic offences. All payments must be made through official channels with receipts.",
            pcm: "FRSC officers get authority to stop vehicles, check documents, and issue fines. All payments must be through official channels with receipt.",
            yo: "Awọn ọfẹ FRSC ni aṣẹ lati da awọn ọkọ duro, ṣayẹwo awọn iwe, ati fun awọn itanran. Gbogbo awọn sisanwo gbọdọ wa nipasẹ awọn ikanni alaye.",
            ha: "Jandaman FRSC na da izini don tsai da motoci, bincika takardun, da ba da tarar. Duk biyan kuɗi dole ta kasance ta hanyar hanyoyin hukuma tare da kirtani.",
            ig: "Ndị ọrụ FRSC nwere ikike ịkwụsị ụgbọ, inyocha akwụkwọ, na inye mkpọsa maka mmebi iwu ụzọ. Ụgwọ niile kwesịrị ikwụ site na ụzọ ọrụ na recept.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "An FRSC officer stops you and your documents are all valid. He refuses to let you go unless you 'settle' him.",
            pcm: "FRSC officer stop you, all your papers correct. He say you must 'settle' am before he let you go.",
            yo: "Ọfẹ FRSC da ọ duro ati pe gbogbo awọn iwe rẹ wulo. O kọ lati jẹ ki o lọ ayafi ti o ba 'yanju' rẹ.",
            ha: "Jandamin FRSC ya tsai da kai kuma duk takardunka sun yi daidai. Yana ƙi bar ka tafi sai ka 'biya' shi.",
            ig: "Onye ọrụ FRSC kwụsịa gị na akwụkwọ gị niile dị mma. Ọ jụ ịhapụ gị gaa ma ọ bụrụ na ịkwụghị ya ụgwọ.",
          },
          steps: {
            en: [
              "Stay calm. Do not pay any money.",
              "State clearly: 'All my documents are valid. I am not required to pay anything other than official fines.'",
              "Ask for the officer's name and service number.",
              "Politely ask: 'Are you issuing me an official fine? Please provide a receipt.'",
              "If he persists, note all details and report to FRSC: call 122 or report on their official portal.",
              "You may also report to the Independent Corrupt Practices Commission (ICPC).",
            ],
            pcm: ["No panic, no pay.", "Tell am: 'All my papers correct. I no go pay any unofficial money.'", "Ask for officer name and service number.", "Ask: 'You dey give me official fine? Give me receipt.'", "If he continue, note everything and report to FRSC: call 122.", "You fit also report to ICPC."],
            yo: ["Jẹ ki o balẹ. Má san owo eyikeyi.", "Sọ gbangba: 'Gbogbo awọn iwe mi wulo. Mi o nilo lati san ohunkohun yatọ si itanran alaye.'", "Beere fun orukọ ọfẹ ati nọmba iṣẹ.", "Beere pẹlu ọwọ: 'Ṣe o n fun mi ni itanran alaye? Jọwọ pese riri.'", "Ti o ba tẹsiwaju, gba alaye gbogbo ati ròyìn si FRSC: pe 122.", "O tun le ròyìn si ICPC."],
            ha: ["Kasance a nutsuwa. Kada ka biya komai.", "Fada a sarari: 'Duk takarduna sun yi daidai. Ba ni da wajibcin biya komai banda tarar hukuma.'", "Nemi sunan jandamin da lambar aiki.", "Yi tambaya da ladabi: 'Kana ba ni tarar hukuma? Don Allah ba ni kirtani.'", "Idan ya ci gaba, rubuta komai kuma kai ƙara ga FRSC: kira 122.", "Kuma zaka iya kai ƙara ga ICPC."],
            ig: ["Nọrọ n'udo. Akwụkwala ego ọ bụla.", "Kwuo nke ọma: 'Akwụkwọ m niile dị mma. Achọghị m ịkwụ ihe ọ bụla karịa mkpọsa ọrụ.'", "Rịọ aha onye ọrụ na nọmba ọrụ ya.", "Jụọ ya n'ụzọ ọcha: 'I na-enye m mkpọsa ọrụ? Biko nye m recept.'", "Ọ bụrụ na ọ gaa n'ihu, dee ihe niile ma kọọ na FRSC: kpọọ 122.", "Ị nwekwara ike kọọ na ICPC."],
          },
        },
      ],
    },
    {
      slug: "vio-rights",
      title: {
        en: "Your Rights with VIO Officers",
        pcm: "Your Rights with VIO",
        yo: "Awọn Ẹtọ Rẹ pẹlu VIO",
        ha: "Haƙƙoƙinka tare da VIO",
        ig: "Ikike Gị na VIO",
      },
      summary: {
        en: "The Vehicle Inspection Officers (VIO) are state-level officials who inspect commercial and private vehicles for roadworthiness. Their jurisdiction and powers are limited — they cannot act like police.",
        pcm: "VIO na state officials wey inspect vehicle for roadworthiness. Their power get limit — dem no fit act like police.",
        yo: "Awọn Oṣiṣẹ Ayẹwo Ọkọ (VIO) jẹ awọn oṣiṣẹ ipinle ti o ṣayẹwo awọn ọkọ aladani ati ti iṣowo fun ọna. Agbara wọn ni opin.",
        ha: "Jandaman Binciken Mota (VIO) su ne jami'an jiha da ke bincika motoci na kasuwanci da masu zaman kansu. Ikon su yana da iyaka.",
        ig: "Vehicle Inspection Officers (VIO) bụ ndị ọrụ steeti na-enyocha ụgbọ ndị ahịa na nke onwe onye maka ụzọ. Ọchịchọ ha dị oke — ha enweghị ike ime ka ndị uwe ojii.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Inspect your vehicle for roadworthiness",
          "Check your vehicle licence and road worthiness certificate",
          "Issue fines for vehicle standard violations",
          "Impound vehicles that fail inspection",
        ],
        pcm: ["Inspect your vehicle for roadworthiness", "Check your vehicle licence and road worthiness", "Give fine for vehicle standard violation", "Impound vehicle wey fail inspection"],
        yo: ["Ṣayẹwo ọkọ rẹ fun ọna", "Ṣayẹwo iwe ọkọ rẹ ati iwe ọna", "Fun itanran fun awọn ìka ipele ọkọ", "Gba awọn ọkọ ti o kuna idanwo"],
        ha: ["Bincika motar ka don dacewa da hanya", "Bincika lasisin motar ka da takardar dacewa", "Ba da tara don keta dokokin mota", "Kwace motocin da suka kasa bincike"],
        ig: ["Nyochaa ụgbọ gị maka ụzọ", "Nyochaa laịsensị ụgbọ gị na asambodo ụzọ", "Inye mkpọsa maka mmebi ọkwa ụgbọ", "Nweta ụgbọ ndị na-emeghị ule"],
      },
      cannotDo: {
        en: [
          "Act as law enforcement officers — they are not police",
          "Carry or use firearms",
          "Arrest drivers for criminal offences",
          "Demand money that is not an officially receipted fine",
          "Operate at night or in plainclothes without clear identification",
        ],
        pcm: ["Act like police — dem no be police", "Carry gun", "Arrest driver for criminal offence", "Collect money wey no be official receipted fine", "Work at night or in mufti without proper ID"],
        yo: ["Ṣiṣẹ bi awọn ọlọpaa — wọn kii ṣe ọlọpaa", "Gbe tabi lo ohun ija", "Mu awakọ fun awọn ẹṣẹ ọdaràn", "Beere owo ti kii ṣe itanran alaye pẹlu riri", "Ṣiṣẹ ni alẹ tabi ni aṣọ alagbada laisi idanimọ to dara"],
        ha: ["Zama kamar 'yan sanda — ba 'yan sanda bane", "Ɗauke ko amfani da makami", "Kama direba don laifukan aikata laifi", "Nemi kuɗi wanda ba tarar da kirtani ba", "Aiki da dare ko a cikin tufafin farar hula ba tare da bayyananniyar shaida ba"],
        ig: ["Ime ka ndị uwe ojii — ha abụghị ndị uwe ojii", "Iburu ma ọ bụ ojiji egbe", "Jide ọkwọ ụgbọ maka mmehie mpụ", "Rịọ ego na-abụghị mkpọsa ọrụ na recept", "Ọrụ n'abalị ma ọ bụ n'uwe onwe na-enweghị njirimara doro anya"],
      },
      whatToDo: {
        en: [
          "Confirm the officer's identity — ask for their VIO ID card",
          "Cooperate with a legitimate inspection",
          "Demand a receipt for any fine",
          "Report abuse to the State Ministry of Transport",
        ],
        pcm: ["Confirm the officer ID — ask for their VIO ID card", "Cooperate with proper inspection", "Demand receipt for any fine", "Report abuse to State Ministry of Transport"],
        yo: ["Jẹrisi idanimọ ọfẹ — beere fun kaadi VIO wọn", "Ṣiṣẹ pẹlu ayẹwo ti o tọ", "Beere fun riri fun itanran eyikeyi", "Ròyìn ilokulo si Ile-iṣẹ Ijọba Ipinle ti Irinna"],
        ha: ["Tabbatar da shaida jandamin — nemi kaotinan VIO nasu", "Yi haɗin gwiwa da bincike na gaskiya", "Nemi kirtani ga duk wata tara", "Kai ƙara cin zarafi ga Ma'aikatar Sufuri ta Jiha"],
        ig: ["Nwaa njirimara onye ọrụ ahụ — rịọ kaadị VIO ha", "Mekọọ n'ule kwesịrị", "Rịọ recept maka mkpọsa ọ bụla", "Kọọ mmegbu na Minịstri Steeti nke Ụgbọ"],
      },
      whatNotToDo: {
        en: [
          "Do not pay cash without a receipt",
          "Do not allow a VIO officer to drive your vehicle away without documentation",
          "Do not mistake VIO for FRSC — their powers are different",
        ],
        pcm: ["No pay cash without receipt", "No allow VIO officer drive your vehicle away without paper", "No confuse VIO with FRSC — their powers dey different"],
        yo: ["Má san owo laisi riri", "Má jẹ ki ọfẹ VIO wakọ ọkọ rẹ lọ laisi iwe", "Má dapo VIO pẹlu FRSC — awọn agbara wọn yatọ"],
        ha: ["Kada ka biya kuɗi ba tare da kirtani ba", "Kada ka bar jandamin VIO ya tuka motar ka da tafiya ba tare da takardu ba", "Kada ka ruɗe VIO da FRSC — ikonsu ya bambanta"],
        ig: ["Akwụkwala ego na-enweghị recept", "Ikwekwala onye ọrụ VIO ịkwọ ụgbọ gị agapụ na-enweghị akwụkwọ", "Ejikotaghị VIO na FRSC — ọchịchọ ha dị iche iche"],
      },
      laws: [
        {
          name: "Motor Vehicle (Prohibition) Act & State Transport Laws",
          section: "Various Sections",
          plainEnglish: {
            en: "VIO officers derive their powers from state transport legislation. They are not empowered to make criminal arrests. Their primary mandate is vehicle inspection.",
            pcm: "VIO get their power from state transport law. Dem no get power to do criminal arrest. Their main job na vehicle inspection.",
            yo: "Awọn ọfẹ VIO gba agbara wọn lati ofin irinna ipinle. Wọn ko ni aṣẹ lati mu ẹnikẹni fun ẹṣẹ ọdaràn.",
            ha: "Jandaman VIO suna samun ikonsu daga dokokin sufuri na jiha. Ba a basu izinin yin kama na laifukan aikata laifi ba.",
            ig: "Ndị ọrụ VIO na-enweta ọchịchọ ha site n'iwu ụgbọ steeti. E nyeghị ha ikike ime njide mpụ. Ọrụ ha bụ nyochaa ụgbọ.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "police-roadblock",
      title: {
        en: "Police Roadblocks & Stops",
        pcm: "Police Roadblock & Stop",
        yo: "Idena Ọna ati Idaduro Ọlọpaa",
        ha: "Garkuwan Hanya da Tsayawa na 'Yan Sanda",
        ig: "Nkwụsị Uwe Ojii n'Ụzọ",
      },
      summary: {
        en: "Police have limited powers at roadblocks. They can check identity and documents but cannot shake you down for money or harass you without lawful reason.",
        pcm: "Police power for roadblock get limit. Dem fit check identity and documents but dem no fit collect money from you or harass you without reason.",
        yo: "Ọlọpaa ni agbara to ni opin ni awọn idena ọna. Wọn le ṣayẹwo idanimọ ati awọn iwe ṣugbọn ko le ji owo tabi ṣe ikọlu laisi idi ofin.",
        ha: "Yan sanda suna da ikon iyakantacce a garkuwan hanya. Za su iya bincika shaida da takardun amma ba za su iya neman kuɗi ko cin zarafi ba tare da dalili na doka ba.",
        ig: "Ndị uwe ojii nwere ike obere na nkwụsị ụzọ. Ha nwere ike nyochaa njirimara na akwụkwọ mana ha enweghị ike ịjaghasị gị maka ego ma ọ bụ ịhụ gị n'anya ọjọọ na-enweghị ezi ihe kpatara.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Ask for your ID or driver's licence",
          "Conduct a search if they have reasonable grounds (not just suspicion based on appearance)",
          "Arrest you if you have committed or are committing a crime",
          "Impound your vehicle for serious traffic violations",
        ],
        pcm: ["Ask for your ID or driver's licence", "Search you if dem get genuine reason — not just because of how you look", "Arrest you if you commit crime", "Impound your vehicle for serious traffic offence"],
        yo: ["Beere fun idanimọ rẹ tabi iwe awakọ", "Ṣe ayẹwo ti wọn ba ni idi to dara — kii ṣe nitori irisi rẹ", "Mu ọ ti o ba ṣe ẹṣẹ", "Gba ọkọ rẹ fun ìka ọna to buruju"],
        ha: ["Nemi ID naka ko lasisin tukin motar", "Yi bincike idan suna da dalili mai kyau — ba kawai zargi bisa bayyanar ka ba", "Kama ka idan ka aikata laifi", "Kwace motar ka don keta muhimmun dokokin hanya"],
        ig: ["Rịọ ID gị ma ọ bụ laịsensị ịkwọ ụgbọ", "Nyochaa gị ọ bụrụ na ha nwere ezi ihe kpatara — ọ bụghị n'ihi ọdịdị gị", "Jide gị ọ bụrụ na ị mere mmehie", "Nweta ụgbọ gị maka nnukwu mmebi iwu ụzọ"],
      },
      cannotDo: {
        en: [
          "Demand money at a roadblock",
          "Search your phone or belongings without a court order",
          "Arrest you based solely on your appearance",
          "Hold you at a roadblock beyond a reasonable time without cause",
          "Fire at your vehicle for failing to stop at a roadblock (without extreme circumstances)",
        ],
        pcm: ["Demand money for roadblock", "Search your phone or things without court order", "Arrest you just because of how you look", "Hold you for roadblock too long without reason", "Shoot your vehicle for not stopping (except extreme situation)"],
        yo: ["Beere owo ni idena ọna", "Ṣayẹwo foonu tabi ohun ini rẹ laisi aṣẹ ile-ẹjọ", "Mu ọ nikan nitori irisi rẹ", "Fi ọ duro ni idena ọna fun akoko pipẹ laisi idi", "Yinbọn si ọkọ rẹ fun aiwo duro ni idena ọna"],
        ha: ["Nemi kuɗi a garkuwar hanya", "Bincika wayar ka ko dukiyarka ba tare da umurnin kotu ba", "Kama ka kawai saboda bayyanarka", "Tsare ka a garkuwa na dogon lokaci ba tare da dalili ba", "Harbi motar ka don rashin tsayawa a garkuwa"],
        ig: ["Rịọ ego n'ọdụ ụzọ", "Nyochaa ekwenti gị ma ọ bụ ihe nile gị na-enweghị iwu ụlọ ikpe", "Jide gị naanị n'ihi ọdịdị gị", "Nọdee gị n'ọdụ ụzọ ogologo oge na-enweghị ihe kpatara", "Kpaa ụgbọ gị maka ọ bụghị ịkwụsị n'ọdụ ụzọ"],
      },
      whatToDo: {
        en: [
          "Stop safely and greet the officer",
          "Provide your ID or driver's licence if asked",
          "If asked for money, say: 'I do not pay at roadblocks. If I have committed an offence, please issue an official fine with a receipt.'",
          "Note officer details and report to the nearest police complaint desk or the Police Service Commission",
        ],
        pcm: ["Stop safely and greet the officer", "Give your ID or licence if dem ask", "If dem ask for money, say: 'I no pay for roadblock. If I do offence, give me official fine with receipt.'", "Note officer details and report to complaint desk or Police Service Commission"],
        yo: ["Duro ni aabo ati ki ọfẹ", "Fun ID rẹ tabi iwe awakọ ti wọn ba beere", "Ti wọn ba beere owo, sọ: 'Mi o san owo ni idena ọna. Ti mo ba ṣe ẹṣẹ, jọwọ fun mi itanran alaye.'", "Ṣe akiyesi alaye ọfẹ ati ròyìn si Igbimọ Iṣẹ Ọlọpaa"],
        ha: ["Tsaya lafiya kuma yi wa jandamin gaisuwa", "Ba da ID naka ko lasisin idan aka nema", "Idan aka nemi kuɗi, ce: 'Ba ni biya a garkuwa. Idan na keta doka, don Allah ba ni tarar hukuma.'", "Lura da bayanan jandamin kuma kai ƙara ga Hukumar Sabis na 'Yan Sanda"],
        ig: ["Kwụsị ụgbọ nke ọma ma nnọọ onye ọrụ ahụ", "Nye ID gị ma ọ bụ laịsensị ọ bụrụ na ha jụọ", "Ọ bụrụ na ha rịọ ego, kwuo: 'Akwụghị m ego n'ọdụ ụzọ. Ọ bụrụ na emeela m mmehie, biko nye m mkpọsa ọrụ na recept.'", "Cheta ihe banyere onye ọrụ ma kọọ na teebụl mkpesa ma ọ bụ Police Service Commission"],
      },
      whatNotToDo: {
        en: [
          "Do not drive through a roadblock — it is dangerous and illegal",
          "Do not pay any money without an official receipt",
          "Do not hand over your phone without a court order",
          "Do not leave your engine running and walk away",
        ],
        pcm: ["No drive through roadblock — dangerous and illegal", "No pay money without official receipt", "No hand over your phone without court order", "No leave engine running and walk away"],
        yo: ["Má wakọ kọja idena ọna — o lewu ati aitọ", "Má san owo eyikeyi laisi riri alaye", "Má fi foonu rẹ fun wọn laisi aṣẹ ile-ẹjọ", "Má fi inaro ọkọ rẹ n'iyara ki o tẹle"],
        ha: ["Kada ka tuka ta garkuwar hanya — haɗari ne kuma ba doka ba", "Kada ka biya kuɗi ba tare da kirtani hukuma ba", "Kada ka mika wayar ka ba tare da umurnin kotu ba", "Kada ka bar injinan motar tana tafiya ka tafi"],
        ig: ["Agakwala n'ụgbọ n'ọdụ ụzọ — ọ dị ize ndụ ma ọ bụghị iwu", "Akwụkwala ego ọ bụla na-enweghị recept ọrụ", "Ekenyekwala ekwenti gị na-enweghị iwu ụlọ ikpe", "Hapụkwala injin gị na-agba wee gaa"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 37",
          plainEnglish: {
            en: "Every citizen of Nigeria is entitled to respect for the privacy of their home and correspondence, and telephone conversations. Police cannot access your phone without a court order.",
            pcm: "Every Nigerian citizen get right to privacy of their home, letters, and phone calls. Police no fit access your phone without court order.",
            yo: "Gbogbo ọmọ ilu Nigeria ni ẹtọ si ọwọ fun ikọkọ ti ile wọn ati lẹta, ati awọn ipe foonu. Ọlọpaa ko le wọle si foonu rẹ laisi aṣẹ ile-ẹjọ.",
            ha: "Kowane ɗan ƙasar Najeriya yana da hakkin mutunci na gidan sa da wasiƙunsa, da tattaunawar wayar tarho. Yan sanda ba za su iya shiga wayar ka ba tare da umurnin kotu ba.",
            ig: "Onye ọ bụla nke Naịjirịa nwere ikike maka nzuzo nke ụlọ ya na akwụkwọ ozi ya, na mkparịta ụka ekwenti. Ndị uwe ojii enweghị ike ọbanye n'ekwenti gị na-enweghị iwu ụlọ ikpe.",
          },
        },
      ],
      scenarios: [],
    },
  ],
};
