import type { Section } from "./types";

export const generalPublic: Section = {
  slug: "general-public",
  title: {
    en: "General Public",
    pcm: "Every Nigerian",
    yo: "Gbogbo Eniyan",
    ha: "Jama'a Gabaɗaya",
    ig: "Ọha na Eze",
  },
  description: {
    en: "Your fundamental rights during police encounters, arrests, detention, and searches — backed by the Nigerian Constitution.",
    pcm: "Your basic rights when police stop you, arrest you, or search your things — according to Nigerian Constitution.",
    yo: "Awọn ẹtọ rẹ nigba ti ọlọpaa ba da ọ duro, mu ọ, tabi ṣàyẹwò ohun ini rẹ.",
    ha: "Haƙƙoƙinka na asali a lokacin da 'yan sanda suka tsai da kai, kama ka, ko bincika kayanki.",
    ig: "Ikike gị bụ nke ndị ọha ya mgbe ndị uwe ojii kwụsịa gị, jidee gị, ma ọ bụ nyochaa ihe nke gị.",
  },
  icon: "Shield",
  color: "bg-primary-50 text-primary-700",
  topics: [
    {
      slug: "right-to-silence",
      title: {
        en: "Right to Remain Silent",
        pcm: "Right to Keep Quiet",
        yo: "Ẹtọ Lati Dakẹ",
        ha: "Haƙƙin Yin Shiru",
        ig: "Ikike Ị Nọ Nè",
      },
      summary: {
        en: "You are not legally required to answer questions that may incriminate you. This right is guaranteed by Section 35 of the 1999 Constitution.",
        pcm: "You no need to answer any question wey fit land you for trouble. Section 35 of Nigeria Constitution cover you.",
        yo: "Ofin ko fi ọ lọwọ lati dahun awọn ibeere ti o le jẹ ki wọn fi ẹsun kan ọ.",
        ha: "Dokar ba ta tilasta ka amsa tambayoyi da zai iya sa ka zama mai laifi.",
        ig: "Iwu anaghị amanye gị ịza ajụjụ ndị nwere ike ibupụta ihe ojọ megide gị.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Ask you questions voluntarily",
          "Inform you that you are being questioned",
          "Record your statement if you choose to give one voluntarily",
        ],
        pcm: [
          "Dem fit ask you question if you agree",
          "Dem fit tell you say dem dey question you",
          "Dem fit write your statement if you want give am",
        ],
        yo: ["Beere lọwọ rẹ awọn ibeere lairotẹlẹ", "Sọ fun ọ pe wọn n beere lọwọ rẹ", "Gbasilẹ alaye rẹ ti o ba fẹ fun un"],
        ha: ["Su maka tambayoyi bisa son rai", "Sanar da kai cewa ana tambaya maka", "Rubuta magana naka idan ka zabi bayarwa"],
        ig: ["Jụọ gị ajụjụ ọ bụrụ na ị kwere", "Gwa gị na ha na-ajụ gị ajụjụ", "Dekọọ nkwupụta gị ọ bụrụ na ị họrọ inye ya"],
      },
      cannotDo: {
        en: [
          "Force you to make a statement",
          "Beat or torture you to extract a confession",
          "Use your silence as proof of guilt",
          "Refuse to let you contact a lawyer before questioning",
        ],
        pcm: [
          "Dem no fit force you give statement",
          "Dem no fit beat you to make you talk",
          "Dem no fit use your silence to say you guilty",
          "Dem no fit stop you from calling lawyer before dem question you",
        ],
        yo: ["Fi agbara mu ọ sọ ohun", "Na ọ tabi fọ ọ lara lati fa ijẹwọ", "Lo idakẹjẹ rẹ gẹgẹbi ẹri ẹbi", "Kọ lati jẹ ki o pe agbẹjọro"],
        ha: ["Tilastar ka bayar da sanarwa", "Duka ko azabtar da kai don ciro ikirari", "Amfani da shiru naka a matsayin hujja", "Hana ka tuntubi lauya"],
        ig: ["Manye gị ịwụpụta nkwupụta", "Tie gị ma ọ bụ ịta gị ahụhụ iji nweta nkwupụta ngụzọ", "Ojiji nnọọ gị dị ka ihe akaebe nke mmehie", "Igbochi gị ịkpọtụrụ ọka iwu"],
      },
      whatToDo: {
        en: [
          "Calmly state: 'I am exercising my right to remain silent.'",
          "Ask clearly: 'Am I free to go? Am I under arrest?'",
          "Request a lawyer before answering any questions",
          "Note the officer's badge number and name if possible",
        ],
        pcm: [
          "Tell dem calmly: 'I dey use my right to keep quiet.'",
          "Ask am: 'I free to go? You don arrest me?'",
          "Ask for lawyer before you answer any question",
          "Try remember the officer badge number and name",
        ],
        yo: ["Sọ ni idakẹjẹ: 'Mo n lo ẹtọ mi lati dakẹ.'", "Beere: 'Ṣe mo le lọ? Ṣe o mu mi?'", "Beere lati ri agbẹjọro", "Ṣe akiyesi nọmba aami ọfẹ rẹ"],
        ha: ["Fada cikin nutsuwa: 'Ina amfani da haƙƙina na yin shiru.'", "Yi tambaya: 'Ina iya tafiya? An kama ni?'", "Nemi lauya kafin amsa tambayoyi", "Lura da lambar ƙaramin badge"],
        ig: ["Kwuo n'ịdị jụụ: 'Ana m iji ikike m ịnọ nè.'", "Jụọ: 'Enwere m ike ịga? A jidere m?'", "Rịọ ọka iwu tupu ị za ajụjụ ọ bụla", "Cheta nọmba badge nke onye ọrụ ahụ"],
      },
      whatNotToDo: {
        en: [
          "Do not argue aggressively or raise your voice",
          "Do not volunteer information beyond what is necessary",
          "Do not sign any statement without reading it and consulting a lawyer",
          "Do not physically resist — comply, then challenge it legally later",
        ],
        pcm: [
          "No fight dem or shout — e go make things worse",
          "No give dem extra information wey dem no ask for",
          "No sign any paper without reading am and talking to lawyer",
          "No try fight dem physically — obey first, fight am for court later",
        ],
        yo: ["Má ja pẹlu wọn ni agbara", "Má fi ẹsun ara rẹ silẹ larọwọto", "Má fowo si iwe eyikeyi laisi kika ati agbẹjọro", "Má dojuko wọn ni ara — tẹle, lẹhinna ja ni ile-ẹjọ"],
        ha: ["Kada ka yi jayayya ko ɗagawa muryarka", "Kada ka ba da bayani fiye da yadda ya kamata", "Kada ka sanya hannu kan duk wata sanarwa ba tare da karantawa ba", "Kada ka tsayas da su jiki — yi biyayya, sannan ka kalubalance daga baya"],
        ig: ["Emekwala esemokwu ma ọ bụ ọtụtụ olu", "Ekwuwanla ihe ndị ọzọ karịa ihe dị mkpa", "Akwadobiahala nkwupụta ọ bụla na-agụghị ya na ọka iwu", "Emegidekwala ha n'ahụ — soro ha, wee luso ha ọgụ n'ụlọ ikpe"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 35(2)",
          plainEnglish: {
            en: "Any person who is arrested or detained shall be informed of the reasons for the arrest or detention within 24 hours.",
            pcm: "Any person wey dem arrest or detain must hear why dem do am within 24 hours.",
            yo: "Ẹnikẹni ti a mu tabi ti a fi pa duro gbọdọ gba alaye fun idi naa laarin wakati 24.",
            ha: "Duk wanda aka kama ko tsare dole a sanar da shi dalilin kama ko tsare a cikin awanni 24.",
            ig: "Onye ọ bụla a jidere ma ọ bụ nọdere n'ogige ga-anọwa ozi maka ihe kpatara ya n'ime awa 24.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 6",
          plainEnglish: {
            en: "A suspect has the right to remain silent and cannot be compelled to give any statement.",
            pcm: "Any suspect get right to keep quiet and nobody fit force am to talk.",
            yo: "Afurasi ni ẹtọ lati dakẹ, ẹnikẹni ko le fi agbara mu u sọ ohun.",
            ha: "Mai zargi yana da haƙƙin yin shiru kuma ba za a iya tilastar da shi ya bayyana ba.",
            ig: "Onye a na-achọ ikpe nwere ikike ịnọ nè, a nweghị onye nwere ike ịmanye ya ikwu ihe.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A police officer stops you on the street and begins asking where you are coming from and what you do for a living.",
            pcm: "One police stop you for road and e dey ask you where you dey come from and wetin you do for work.",
            yo: "Ọlọpaa kan da ọ duro lori ita ati bẹrẹ lati beere ibiti o ti nbo ati ohun ti o ṣe fun igbesi aye.",
            ha: "Jandarm ya tsai da kai a kan hanya ya fara tambayar inda kake zuwa da abin da kake yi.",
            ig: "Onye uwe ojii kwụsịa gị n'ụzọ ma jikwa ịjụ gị ebe i si bia na ihe ị na-arụ ọrụ.",
          },
          steps: {
            en: [
              "Stay calm. Do not panic or run.",
              "Politely ask: 'Good day officer, am I being detained or am I free to go?'",
              "If they say you are free — leave politely.",
              "If detained, say: 'I understand. I would like to exercise my right to remain silent and speak with a lawyer.'",
              "Do not answer questions about your personal life, phone content, or finances.",
              "Note the officer's name, badge number, and location.",
            ],
            pcm: [
              "No panic, no run.",
              "Ask am politely: 'Good day officer, you don detain me or I free to go?'",
              "If dem say you free — leave with respect.",
              "If dem detain you, say: 'I hear. I want to use my right to keep quiet and talk to lawyer.'",
              "No answer question about your personal life, phone, or money.",
              "Try remember officer name, badge number, and where e happen.",
            ],
            yo: [
              "Jẹ ki o balẹ. Má ṣe ẹru tabi sá.",
              "Beere pẹlu ọwọ: 'Ẹkáàárọ̀ ọgagun, ṣe o n fi mi pamọ́ tabi mo le lọ?'",
              "Ti wọn ba sọ pe o le lọ — lọ pẹlu ọwọ.",
              "Ti o ba fi ọ pamọ́, sọ: 'Mo gbọ. Mo fẹ lo ẹtọ mi lati dakẹ ati ba agbẹjọro sọrọ.'",
              "Má dahun awọn ibeere nipa igbesi aye ara ẹni rẹ, foonu, tabi owo.",
              "Ṣe akiyesi orukọ ọfẹ, nọmba aami, ati ipo naa.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka firgita ko gudu.",
              "Yi tambaya da ladabi: 'Rana mai kyau jandarm, ana tsare ni ne ko ina da 'yanci in tafi?'",
              "Idan sun ce ka da 'yanci — ka tafi da ladabi.",
              "Idan an tsare ka, ce: 'Na fahimta. Ina son yin amfani da haƙƙina na yin shiru da magana da lauya.'",
              "Kada ka amsa tambayoyi game da rayuwarka, waya, ko kudi.",
              "Lura da sunan jandarm, lambar badge, da wurin da hakan ya faru.",
            ],
            ig: [
              "Nọrọ n'udo. Atụla egwu ma ọ bụ gbaa ọsọ.",
              "Jụọ ya n'ụzọ ọcha: 'Ehihie ọma oga, a na-enye m mkpọrọ ka o kwesịrị ma ọ bụ enwere m ike ịgaghachi?'",
              "Ọ bụrụ na ha kwuo na ị nwere ike ịga — hapụ ya nke ọma.",
              "Ọ bụrụ na e nọdere gị n'ogige, kwuo: 'Anọwa m. Achọrọ m iji ikike m ịnọ nè wee kwuo n'ọka iwu.'",
              "Azaghị ajụjụ banyere ndụ onwe gị, ekwenti, ma ọ bụ ego.",
              "Cheta aha onye ọrụ ahụ, nọmba badge, na ebe ọ mere.",
            ],
          },
        },
      ],
    },
    {
      slug: "unlawful-arrest",
      title: {
        en: "Right Against Unlawful Arrest",
        pcm: "Right Against Illegal Arrest",
        yo: "Ẹtọ Lodi si Imudani Aifowosi",
        ha: "Haƙƙi Kan Kama Kai Ba Bisa Doka Ba",
        ig: "Ikike Megide Njide Na-ezughị Oke",
      },
      summary: {
        en: "Police cannot arrest you without a warrant or reasonable cause. Section 35 of the Constitution protects you from arbitrary detention.",
        pcm: "Police no fit arrest you without warrant or good reason. Section 35 of Constitution protect you from illegal detention.",
        yo: "Ọlọpaa ko le mu ọ laisi iwe aṣẹ tabi idi ti o tọ. Abala 35 daabo bo ọ.",
        ha: "Yan sanda ba za su iya kama ka ba tare da doka ko dalili mai kyau ba.",
        ig: "Ndị uwe ojii enweghị ike ijide gị na-enweghị iwu ma ọ bụ ezi ihe kpatara.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Arrest you if they witness you committing a crime",
          "Arrest you with a valid warrant signed by a judge",
          "Detain you for questioning for up to 24 hours before charging or releasing you",
          "Use reasonable force if you resist a lawful arrest",
        ],
        pcm: [
          "Dem fit arrest you if dem see you do crime",
          "Dem fit arrest you with valid court warrant",
          "Dem fit hold you for 24 hours before charge or release",
          "Dem fit use force if you resist legal arrest",
        ],
        yo: ["Mu ọ ti wọn ba ri ọ ṣe ẹṣẹ", "Mu ọ pẹlu iwe aṣẹ ti idajọ ti fowo si", "Fi ọ pamọ́ fun wakati 24 ṣaaju idiyele", "Lo agbara ti o ba dojuko imudani ti o tọ"],
        ha: ["Kama ka idan sun gan ka yin laifi", "Kama ka tare da takardar kama daga alkali", "Tsare ka har zuwa awanni 24 kafin tuhumar ko sakin ka", "Yi amfani da ƙarfi mai ma'ana idan ka tsayas da kama bisa doka"],
        ig: ["Jide gị ọ bụrụ na ha hụ gị na-eme ihe ọjọọ", "Jide gị na iwu edeere n'aka ikpe", "Nọdee gị n'ogige ruo awa 24 tupu ha ebulizie gị ma ọ bụ hapụ gị", "Ojiji ike kwesịrị ọ bụrụ na ị melite njide iwu"],
      },
      cannotDo: {
        en: [
          "Arrest you based on your appearance, tattoos, dreadlocks, or style of dress",
          "Arrest you without telling you why",
          "Hold you for more than 24 hours without charging you or taking you to court",
          "Arrest you as a way to extort money",
          "Detain you at night in an unofficial location",
        ],
        pcm: [
          "Dem no fit arrest you because of how you look, tattoo, dreadlocks, or clothes",
          "Dem no fit arrest you without telling you why",
          "Dem no fit hold you more than 24 hours without charging you or taking you court",
          "Dem no fit arrest you just to collect money from you",
          "Dem no fit keep you for night for unofficial place",
        ],
        yo: ["Mu ọ nitori irisi rẹ, tatuu, dreads, tabi aṣọ", "Mu ọ laisi sọ idi fun ọ", "Fi ọ pamọ́ fun ju wakati 24 lọ laisi ẹsun", "Mu ọ lati gba owo rẹ", "Fi ọ pamọ́ ni alẹ ni ibi aiṣẹ"],
        ha: ["Kama ka saboda bayyanarka, zane jiki, dreads, ko tufafi", "Kama ka ba tare da sanar da kai dalilin ba", "Tsare ka fiye da awanni 24 ba tare da tuhuma ba", "Kama ka don neman cin hanci", "Tsare ka daren dare a wuri marasa izini"],
        ig: ["Jide gị n'ihi ọdịdị gị, tatuu, dreads, ma ọ bụ uwe", "Jide gị na-agwa gị ihe kpatara", "Nọdee gị n'ogige ihe karịa awa 24 na-ebulizie gị", "Jide gị iji nnwere ego gị", "Nọdee gị n'abalị n'ebe na-adịghị n'ọrụ"],
      },
      whatToDo: {
        en: [
          "Ask clearly: 'What am I being arrested for?'",
          "Ask to see the arrest warrant if they claim to have one",
          "Do not physically resist — it can be used against you",
          "Contact a lawyer or relative as soon as possible",
          "If held beyond 24 hours without charge, your lawyer can file for habeas corpus",
        ],
        pcm: [
          "Ask am: 'Why una dey arrest me?'",
          "Ask to see the warrant if dem say dem get am",
          "No fight dem — e fit be used against you later",
          "Call lawyer or family member as soon as you can",
          "If dem hold you pass 24 hours without charge, your lawyer fit file habeas corpus",
        ],
        yo: ["Beere gbangba: 'Kí ni mo ṣe tí ẹ fi n mu mí?'", "Beere lati ri iwe aṣẹ", "Má dojuko wọn ni ara", "Kan si agbẹjọro tabi ẹbi lẹsẹkẹsẹ", "Ti o ba fi ọ pamọ́ ju wakati 24 lọ, agbẹjọro le fi ẹjọ habeas corpus"],
        ha: ["Yi tambaya a sarari: 'Me zan kamawa?'", "Nemi ganin takardar kama", "Kada ka tsayas da su jiki", "Tuntubi lauya ko ɗan uwa da wuri", "Idan aka tsare ka fiye da awanni 24, lauyanka zai iya shigar da kara habeas corpus"],
        ig: ["Jụọ nke ọma: 'Gịnị ka e ji ejide m?'", "Rịọ ka i hụ iwu njide", "Emegidekwala ha n'ahụ", "Kpọtụrụ ọka iwu ma ọ bụ onye ikwu n'oge ọ soonest", "Ọ bụrụ na e nọdee gị n'ogige ihe karịa awa 24, ọka iwu gị nwere ike ibuo habeas corpus"],
      },
      whatNotToDo: {
        en: [
          "Do not run — it can be used as evidence of guilt",
          "Do not bribe officers — it is a crime and weakens your case",
          "Do not sign any document you have not read",
          "Do not insult or threaten officers",
        ],
        pcm: [
          "No run — dem fit use am against you say you guilty",
          "No give officer bribe — na crime and e go weaken your case",
          "No sign any paper you no read",
          "No curse or threaten officer",
        ],
        yo: ["Má sá — wọn le lo o gẹgẹbi ẹri ẹbi", "Má gbọn ọfẹ — ọ jẹ ẹṣẹ ati ó mú ẹjọ rẹ lagbara lagbara", "Má fowo si iwe eyikeyi ti o ko ti ka", "Má bú tabi pa ọfẹ lẹru"],
        ha: ["Kada ka gudu — ana iya amfani da shi a matsayin hujja", "Kada ka yi cin hanci — laifi ne kuma yana raunana karar ka", "Kada ka sanya hannu kan takarda da ba ka karanta ba", "Kada ka zagi ko yi wa jandarm barazana"],
        ig: ["Agbakwala ọsọ — a nwere ike iji ya dị ka ihe akaebe nke mmehie", "Atụkwasịla ego n'aka ndị ọrụ — ọ bụ mmehie ma ọ dị ka ntụgharị nke ikpe gị", "Akwadobiahala akwụkwọ ọ bụla ọ bụrụ na ọ naghị agụ ya", "Atụkwasịla iyi ma ọ bụ iyi egwu ndị ọrụ"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 35(1)",
          plainEnglish: {
            en: "Every person shall be entitled to his personal liberty and no person shall be deprived of such liberty except in cases prescribed by law.",
            pcm: "Every person get right to their freedom and nobody fit take that freedom except the law say so.",
            yo: "Gbogbo eniyan ni ẹtọ si ominira ti ara ẹni ati pe ẹnikẹni ko gbọdọ gba ominira na kuro ayafi ti ofin ba gba laaye.",
            ha: "Kowane mutum yana da haƙƙin yana da 'yancin kai kuma babu wanda za a hana 'yancin sa sai dai yadda doka ta tanada.",
            ig: "Onye ọ bụla nwere ikike na onwe ya, onye ọ bụla enweghị ike ibochie ya n'ike ahụ ma ọ dịghị n'ụzọ iwu kwetara.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 9",
          plainEnglish: {
            en: "A police officer may arrest a person without a warrant if the person commits a felony in his presence, or if he reasonably suspects the person of having committed a felony.",
            pcm: "Police fit arrest person without warrant if dem see the person do serious crime, or if dem get good reason to believe the person do am.",
            yo: "Ọlọpaa le mu eniyan laisi iwe aṣẹ ti eniyan na ba ẹṣẹ nla ṣe ni iwaju rẹ, tabi ti o ba ni idi to dara lati fura si.",
            ha: "Jandarm na iya kama mutum ba tare da takardar kama ba idan mutumin ya aikata babban laifi a gabansa, ko idan yana da dalili mai kyau na zargi.",
            ig: "Onye uwe ojii nwere ike ijide onye na-enweghị iwu ọ bụrụ na onye ahụ na-emegbu iwu n'ihu ya, ma ọ bụ ọ nwere ezi ihe kpatara ijidere ya.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Police stop you near your house and say you 'look suspicious.' They want to take you to the station.",
            pcm: "Police stop you near your house say you 'look suspicious.' Dem wan carry you go station.",
            yo: "Ọlọpaa da ọ duro nitosi ile rẹ wí pé o 'dabi ẹni ifura.' Wọn fẹ mu ọ lọ si ibudo.",
            ha: "Yan sanda sun tsai da kai kusa da gidanka cewa kana 'kamar mai zargi.' Suna son kai ka tashar.",
            ig: "Ndị uwe ojii kwụsịa gị n'akụkụ ụlọ gị wee kwuo na ị 'dị ka onye a na-eche anya ya.' Ha chọọ ịkpọ gị ụlọ ọrụ.",
          },
          steps: {
            en: [
              "Stay calm. Do not run or raise your voice.",
              "Ask politely: 'Officer, what crime am I suspected of committing?'",
              "'Looking suspicious' is not a crime. You cannot be arrested for it.",
              "If they insist, say: 'I am being arrested for looking suspicious? Please give me the warrant or inform me of the specific crime.'",
              "If taken to the station, immediately ask to call a lawyer or family member.",
              "Document everything: time, location, officer's name and badge number.",
            ],
            pcm: [
              "No panic, no run, no shout.",
              "Ask am: 'Officer, which crime you say I commit?'",
              "'Looking suspicious' na nothing — e no be crime.",
              "If dem insist, tell dem: 'You dey arrest me because I look suspicious? Show me warrant or tell me the crime.'",
              "If dem carry you go station, ask immediately to call lawyer or family.",
              "Write everything down: time, place, officer name and badge number.",
            ],
            yo: ["Jẹ ki o balẹ. Má sá tabi ṣe ariwo.", "Beere pẹlu ọwọ: 'Ọgagun, ẹṣẹ wo ni mo ṣe?'", "'Dabi ẹni ifura' kii ṣe ẹṣẹ. Won ko le mu ọ fun idi yii.", "Ti wọn ba tẹnumọ, sọ: 'Mo n mu mi duro nitori mo dabi ẹni ifura? Jọwọ fihan mi iwe aṣẹ.'", "Ti wọn ba mu ọ lọ, beere lẹsẹkẹsẹ lati pe agbẹjọro tabi ẹbi.", "Ṣe akiyesi ohun gbogbo: akoko, ipo, orukọ ọfẹ ati nọmba."],
            ha: ["Kasance a nutsuwa. Kada ka gudu ko ɗaga muryarka.", "Yi tambaya da ladabi: 'Jandarm, wane laifi ake zargin nan?'", "'Kamar mai zargi' ba laifi bane. Ba za a iya kama ka saboda haka ba.", "Idan sun dage, ce: 'Ana kamana saboda ina kamar mai zargi? Don Allah nuna min takardar kama ko fada min laifin.'", "Idan aka kai ka tashar, nan da nan nemi kiran lauya ko ɗan uwa.", "Rubuta komai: lokaci, wuri, sunan jandarm da lambar badge."],
            ig: ["Nọrọ n'udo. Agbakwala ọsọ ma ọ bụ ọtụtụ olu.", "Jụọ ya n'ụzọ ọcha: 'Oga, ihe ọjọọ gịnị ka a na-eche na m mere?'", "'Dị ka onye a na-eche anya ya' abụghị ihe ọjọọ. A nweghị ike ijide gị n'ihi ya.", "Ọ bụrụ na ha arọba, kwuo: 'A na-ejide m n'ihi na m dị ka onye a na-eche anya ya? Biko nye m iwu ma ọ bụ gwa m ihe ọjọọ ọ bụ.'", "Ọ bụrụ na ha kpọ gị ụlọ ọrụ, ozugbo rịọ ka i kpọọ ọka iwu ma ọ bụ onye ikwu.", "Deechie ihe niile: oge, ebe, aha onye ọrụ na nọmba badge."],
          },
        },
      ],
    },
    {
      slug: "right-to-bail",
      title: {
        en: "Right to Bail",
        pcm: "Right to Get Bail",
        yo: "Ẹtọ si Ìdásílẹ̀",
        ha: "Haƙƙin Beli",
        ig: "Ikike Nweta Bọọlụ",
      },
      summary: {
        en: "For most offences, you have a right to bail. Police cannot hold you indefinitely without charge. Bail is not for sale — paying for bail is illegal.",
        pcm: "For most offences, you get right to bail. Police no fit hold you forever without charge. Bail no be for sale — paying for bail na crime.",
        yo: "Fun ọpọlọpọ awọn ẹṣẹ, o ni ẹtọ si ìdásílẹ̀. Ọlọpaa ko le fi ọ pamọ́ lailai laisi ẹsun. Ìdásílẹ̀ kii ta — sisanwo fun ìdásílẹ̀ jẹ ẹṣẹ.",
        ha: "Don yawancin laifuka, kana da haƙƙin beli. Yan sanda ba za su iya tsare ka har abada ba tare da tuhuma ba. Beli ba ya sayarwa.",
        ig: "Maka ọtụtụ mmehie, ị nwere ikike nweta bọọlụ. Ndị uwe ojii enweghị ike ijidegide gị na-ebulizie gị. Bọọlụ abụghị ihe ere — ịkwụ ụgwọ maka bọọlụ bụ mmehie.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Refuse bail for capital offences (murder, treason, armed robbery)",
          "Set bail conditions and amounts",
          "Require a surety (guarantor) for bail",
          "Revoke bail if conditions are violated",
        ],
        pcm: ["Refuse bail for serious offence like murder or armed robbery", "Set bail amount and conditions", "Ask for surety (guarantor) before giving bail", "Cancel bail if you violate the conditions"],
        yo: ["Kọ ìdásílẹ̀ fun awọn ẹṣẹ pataki (ipaniyan, ọlọ́ọ̀tà)", "Ṣeto awọn ipo ati iye ìdásílẹ̀", "Beere fun ẹni iṣeduro", "Fagile ìdásílẹ̀ ti awọn ipo ba fọ"],
        ha: ["Ƙi beli ga laifuka masu nauyi (kisa, cin amanar kasa, fashi da makami)", "Tsara yanayin da adadin beli", "Buƙatar mai ba da tabbaci", "Soke beli idan an karya yanayin"],
        ig: ["Jụ bọọlụ maka nnukwu mmehie (igbu mmadụ, armed robbery)", "Tọọ ọnụahịa na ọnọdụ bọọlụ", "Chọọ onye nkwado", "Kagbuo bọọlụ ọ bụrụ na ọnọdụ ahụ e mebiiri"],
      },
      cannotDo: {
        en: [
          "Demand money in exchange for bail at a police station",
          "Hold you beyond 24 hours without charging you or granting bail",
          "Refuse bail for bailable offences",
          "Demand personal gifts or bribes as conditions for release",
        ],
        pcm: ["Collect money from you to give you bail for station", "Hold you pass 24 hours without charge or bail", "Refuse bail for offences wey deserve bail", "Ask for gifts or bribe before dem release you"],
        yo: ["Beere owo fun ìdásílẹ̀ ni ibudo ọlọpaa", "Fi ọ pamọ́ ju wakati 24 lọ laisi ẹsun tabi ìdásílẹ̀", "Kọ ìdásílẹ̀ fun awọn ẹṣẹ ti o yẹ fun ìdásílẹ̀", "Beere awọn ẹbun tabi ẹbọ bi ipo ìdásílẹ̀"],
        ha: ["Nemi kuɗi don beli a tashar 'yan sanda", "Tsare ka fiye da awanni 24 ba tare da tuhuma ko beli ba", "Ƙi beli ga laifuka masu cancanta", "Nemi kyaututtuka ko cin hanci don sake ka"],
        ig: ["Rịọ ego maka bọọlụ n'ụlọ ọrụ uwe ojii", "Nọdee gị n'ogige ihe karịa awa 24 na-ebulizie gị ma ọ bụ enye gị bọọlụ", "Jụ bọọlụ maka mmehie ndị kwesịrị bọọlụ", "Rịọ onyinye ma ọ bụ ego iji tọhapụ gị"],
      },
      whatToDo: {
        en: [
          "Clearly request bail: 'I am requesting bail as is my legal right.'",
          "Ask for the bail amount in writing",
          "Have a family member or lawyer come to the station",
          "If bail is denied improperly, your lawyer can apply to court for bail",
          "If asked to pay for bail informally, refuse and report it",
        ],
        pcm: ["Ask for bail clearly: 'I dey request bail, na my legal right.'", "Ask make dem write the bail amount for paper", "Make family or lawyer come to station", "If dem deny bail without good reason, your lawyer fit go court for bail", "If dem ask you to pay for bail under the table, refuse and report am"],
        yo: ["Beere ìdásílẹ̀ gbangba: 'Mo n beere ìdásílẹ̀ gẹgẹbi ẹtọ mi ti ofin.'", "Beere lati gba iye ìdásílẹ̀ ni kikọ", "Jẹ ki ẹbi tabi agbẹjọro wa si ibudo", "Ti a ba kọ ìdásílẹ̀ laisi idi to dara, agbẹjọro le lo si ile-ẹjọ", "Ti wọn ba beere owo ni aṣiri, kọ ati ròyìn rẹ"],
        ha: ["Nemi beli a sarari: 'Ina neman beli kamar yadda haƙƙina na doka yake.'", "Nemi adadin beli a rubuce", "Sa ɗan uwa ko lauya ya zo tashar", "Idan aka ki beli ba bisa ƙa'ida ba, lauyanka zai iya neman beli a kotu", "Idan aka nemi ka biya beli a boyaye, ƙi kuma kai ƙara"],
        ig: ["Rịọ bọọlụ nke ọma: 'Ana m arịọ bọọlụ dị ka ikike m n'iwu.'", "Rịọ ka e dee ọnụahịa bọọlụ n'akwụkwọ", "Mee ka onye ikwu ma ọ bụ ọka iwu bia ụlọ ọrụ", "Ọ bụrụ na e jụ bọọlụ n'ụzọ na-ezighị ezi, ọka iwu gị nwere ike ịga n'ụlọ ikpe maka bọọlụ", "Ọ bụrụ na ha rịọ ka ị kwụọ ụgwọ maka bọọlụ n'ụzọ nzuzo, jụ ma ọ bụ kọọ ya"],
      },
      whatNotToDo: {
        en: [
          "Do not pay unofficial bail fees — it is bribery and a crime",
          "Do not leave without written documentation of your release",
          "Do not fail to report for court dates after bail",
          "Do not skip bail — a warrant will be issued for your arrest",
        ],
        pcm: ["No pay unofficial bail money — na bribery and crime", "No leave station without paper wey show your release", "No miss your court date after bail", "No skip bail — dem go issue warrant for your arrest"],
        yo: ["Má san owo ìdásílẹ̀ ti kii ṣe alaye — o jẹ ẹṣẹ", "Má lọ laisi iwe ikede ti ìdásílẹ̀ rẹ", "Má padanu ọjọ ile-ẹjọ lẹhin ìdásílẹ̀", "Má salọ ìdásílẹ̀ — wọn yoo gba iwe aṣẹ imudani fun ọ"],
        ha: ["Kada ka biya kuɗin beli marasa izini — cin hanci ne kuma laifi ne", "Kada ka tafi ba tare da takardar sakin ka ba", "Kada ka rasa kwanan kotu bayan beli", "Kada ka gudu daga beli — za a ba da takardar kama ka"],
        ig: ["Akwụkwala ụgwọ bọọlụ n'ụzọ ziri ezi — ọ bụ ọtụtụ achịcha na mmehie", "Agakwala na-enweghị akwụkwọ nke ntọhapụ gị", "Egosighị ụbọchị ụlọ ikpe ka bọọlụ gasie", "Agbakwala ọsọ bọọlụ — a ga-ede iwu maka njide gị"],
      },
      laws: [
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 17",
          plainEnglish: {
            en: "A suspect shall be entitled to bail if held for more than 24 hours without being charged to court.",
            pcm: "Any suspect wey dem hold for more than 24 hours without charge get right to bail.",
            yo: "Afurasi ni ẹtọ si ìdásílẹ̀ ti o ba fi pamọ́ ju wakati 24 lọ laisi ẹsun si ile-ẹjọ.",
            ha: "Mai zargi na da haƙƙin beli idan aka tsare shi fiye da awanni 24 ba tare da kai shi kotu ba.",
            ig: "Onye a na-achọ ikpe nwere ikike nweta bọọlụ ọ bụrụ na e nọdee ya n'ogige ihe karịa awa 24 na-akpọghị ya n'ụlọ ikpe.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "search-and-seizure",
      title: {
        en: "Right Against Unlawful Search",
        pcm: "Right Against Illegal Search",
        yo: "Ẹtọ Lodi si Ìwádìí Aifowosi",
        ha: "Haƙƙi Kan Bincike Ba Bisa Doka Ba",
        ig: "Ikike Megide Nyocha Na-ezughị Oke",
      },
      summary: {
        en: "Section 37 of the 1999 Constitution guarantees your right to privacy. Police need a search warrant from a magistrate or court to search your home. They may only conduct a personal search if they have reasonable grounds, and they cannot search your phone without a court order.",
        pcm: "Section 37 of the Constitution protect your privacy. Police need search warrant from court before dem search your house. Dem fit only do body search if dem get good reason, and dem no fit search your phone without court order.",
        yo: "Abala 37 ti Ofin 1999 ṣe idaniloju ẹtọ rẹ si asiri. Ọlọpaa nilo iwe aṣẹ ìwádìí lati ile-ẹjọ lati ṣàyẹwò ile rẹ. Wọn le ṣe ìwádìí ti ara nikan ti wọn ba ni idi to dara, ko si le ṣàyẹwò foonu rẹ laisi aṣẹ ile-ẹjọ.",
        ha: "Sashe na 37 na Kundin Tsarin Mulki na 1999 yana ba da tabbacin haƙƙinka na sirri. Yan sanda suna buƙatar takardar bincike daga alkalin shari'a don bincika gidanka. Za su iya bincika jikinka ne kawai idan suna da dalili mai kyau, kuma ba za su iya bincika wayarka ba tare da odar kotu ba.",
        ig: "Ngalaba 37 nke Ihe Ọmụma nke 1999 na-echekwa ikike gị nke nzuzo. Ndị uwe ojii chọọ iwu nyocha sitere n'ụlọ ikpe iji nyochaa ụlọ gị. Ha nwere ike ime nyocha ahụ naanị ma ọ bụrụ na ha nwere ezi ihe kpatara, ha enweghịkwa ike inyochaa ekwenti gị na-enweghị iwu nke ụlọ ikpe.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Search your home with a valid search warrant signed by a magistrate or judge",
          "Conduct a personal (pat-down) search if they have reasonable grounds to suspect you are armed or carrying contraband",
          "Seize items specifically named in the search warrant",
          "Search you at a checkpoint if there is reasonable suspicion of a crime",
        ],
        pcm: [
          "Search your house if dem get valid search warrant from court",
          "Do body search if dem get good reason to think say you carry weapon or contraband",
          "Collect things wey the search warrant mention",
          "Search you for checkpoint if dem get reason to think say crime dey involved",
        ],
        yo: [
          "Ṣàyẹwò ile rẹ pẹlu iwe aṣẹ ìwádìí ti o wulo lati ọdọ adajọ",
          "Ṣe ìwádìí ti ara ti wọn ba ni idi to dara lati fura si pe o ni ohun ija tabi contraband",
          "Gbe awọn ohun ti a mẹnuba ninu iwe aṣẹ ìwádìí",
          "Ṣàyẹwò ọ ni ibi ayẹwo ti o ba ni ifura to dara si ẹṣẹ",
        ],
        ha: [
          "Bincika gidanka tare da takardar bincike mai inganci daga alkalin shari'a",
          "Yin binciken jiki idan suna da dalili mai kyau na zargin dauke da makami ko kaya haramun",
          "Kwace abubuwa da aka ambata a cikin takardar bincike",
          "Bincika ka a bawul idan akwai zargin da ya dace game da laifi",
        ],
        ig: [
          "Nyochaa ụlọ gị na iwu nyocha ziri ezi edeere n'aka onye ọka ikpe",
          "Mee nyocha ahụ ọ bụrụ na ha nwere ezi ihe kpatara ịdị mma na ị na-ebu ngwa agha ma ọ bụ ihe a machibidoro",
          "Were ihe ndị a kọwara n'iwu nyocha ahụ",
          "Nyochaa gị n'ọnọdụ nyocha ọ bụrụ na enwere ihe echere banyere mmehie",
        ],
      },
      cannotDo: {
        en: [
          "Search your home without a valid search warrant",
          "Conduct a search warrant obtained from another district not covering your location",
          "Search your phone, laptop, or digital devices without a specific court order",
          "Conduct a body search of a woman — only a female officer may do so",
          "Damage or remove property beyond what is specified in the warrant",
          "Use the search as a pretext to extort money from you",
        ],
        pcm: [
          "Search your house without valid search warrant",
          "Use warrant from different area wey no cover your location",
          "Search your phone, laptop or any digital device without court order",
          "Do body search on woman — only female officer fit do am",
          "Damage or remove property wey the warrant no mention",
          "Use the search as excuse to collect money from you",
        ],
        yo: [
          "Ṣàyẹwò ile rẹ laisi iwe aṣẹ ìwádìí ti o wulo",
          "Lo iwe aṣẹ lati agbegbe miiran ti ko bo ipo rẹ",
          "Ṣàyẹwò foonu, kọmputa, tabi awọn ẹrọ oni-nọmba laisi aṣẹ ile-ẹjọ",
          "Ṣe ìwádìí ti ara obinrin — ọlọpaa obinrin nikan le ṣe bẹẹ",
          "Ba tabi gbe ohun ini ti a ko mẹnuba ninu iwe aṣẹ",
          "Lo ìwádìí gẹgẹbi ọ̀nà lati gba owo rẹ",
        ],
        ha: [
          "Bincika gidanka ba tare da takardar bincike mai inganci ba",
          "Amfani da takardar bincike daga wani yanki da bai rufe wurinka ba",
          "Bincika wayarka, kwamfutarka ko kowane na'urar dijital ba tare da odar kotu ba",
          "Yin binciken jiki a kan mace — jandama mace ce kawai za ta iya yin haka",
          "Lalata ko kwace dukiya da ba a ambata a cikin takardar ba",
          "Amfani da binciken a matsayin hujja don ɗebo kuɗi daga gare ka",
        ],
        ig: [
          "Nyochaa ụlọ gị na-enweghị iwu nyocha ziri ezi",
          "Ojiji iwu nyocha sitere n'mpaghara ọzọ na-ekpuchighi ebe gị dị",
          "Nyochaa ekwenti gị, kọmpụta gị, ma ọ bụ ngwaọrụ dijitalụ na-enweghị iwu ụlọ ikpe",
          "Imee nyocha ahụ n'ahụ ụmụ nwanyị — naanị onye uwe ojii nwanyị ka nwere ike ime ya",
          "Mebiri ma ọ bụ wepụ ihe ndị a kọwaghị n'iwu ahụ",
          "Ojiji nyocha ahụ dị ka ihe mgbochi iji nweta ego gị",
        ],
      },
      whatToDo: {
        en: [
          "Ask to see the search warrant before allowing entry — check the address and date",
          "Remain calm and do not physically obstruct the search, but state your objection clearly",
          "Note the names and badge numbers of officers conducting the search",
          "Make a list of all items taken and ask for a receipt",
          "Contact a lawyer immediately after the search",
        ],
        pcm: [
          "Ask to see search warrant before you allow dem enter — check the address and date on am",
          "Stay calm, no block dem physically, but talk your objection clear",
          "Write down names and badge numbers of all officers wey do the search",
          "List all items dem take and ask for receipt",
          "Call lawyer immediately after the search",
        ],
        yo: [
          "Beere lati ri iwe aṣẹ ìwádìí ṣaaju ki o to jẹ wọn wọle — ṣàyẹwò adirẹsi ati ọjọ",
          "Jẹ ki o balẹ ki o má dena ìwádìí ni ara, ṣugbọn sọ asọtẹlẹ rẹ gbangba",
          "Ṣe akiyesi awọn orukọ ati nọmba aami awọn ọfẹ",
          "Ṣe atokọ gbogbo awọn ohun ti wọn gbe ki o beere fun gbowo",
          "Pe agbẹjọro lẹsẹkẹsẹ lẹhin ìwádìí",
        ],
        ha: [
          "Nemi ganin takardar bincike kafin ka bar su shiga — duba adireshin da kwanan wata",
          "Kasance a nutsuwa kuma kada ka toshe binciken jiki, amma bayyana kin naka a sarari",
          "Rubuta sunaye da lambobin badge na dukan jandaman da suka yi binciken",
          "Jera dukan abubuwan da aka ɗauka kuma nemi rasit",
          "Tuntubi lauya nan da nan bayan binciken",
        ],
        ig: [
          "Rịọ ka i hụ iwu nyocha tupu ị hapụ ha ịbanye — lelee adreesị na ụbọchị ya",
          "Nọrọ n'udo ma emegidekwala nyocha ahụ n'ahụ, mana kwuo nnupụisi gị nke ọma",
          "Deechie aha na nọmba badge nke ndị ọrụ ndị na-eme nyocha ahụ",
          "Mee ndepụta ihe niile ha weere ma rịọ ihe akaebe nke nnata",
          "Kpọtụrụ ọka iwu ozugbo ka nyocha ahụ gasie",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not physically block or attack officers — comply and challenge it legally later",
          "Do not consent to a search if no warrant is presented — you are not obliged to",
          "Do not unlock your phone under pressure without a court order",
          "Do not allow officers to remove property not listed on the warrant without objecting",
        ],
        pcm: [
          "No block or attack officers — obey first, fight am for court later",
          "No agree to search if dem no show you warrant — you no dey obliged",
          "No open your phone under pressure without court order",
          "No allow dem carry property wey no dey on warrant without you talking",
        ],
        yo: [
          "Má dena tabi kọlu awọn ọfẹ ni ara — tẹle, lẹhinna ja ni ile-ẹjọ",
          "Má gba aṣẹ fun ìwádìí ti wọn ko ba fi iwe aṣẹ hàn — o ko si dandan",
          "Má ṣii foonu rẹ labẹ titẹ laisi aṣẹ ile-ẹjọ",
          "Má jẹ ki wọn gbe ohun ini ti ko si ninu iwe aṣẹ laisi asọtẹlẹ",
        ],
        ha: [
          "Kada ka toshe ko kai hari kan jandaman jiki — yi biyayya, sannan ka kalubalance daga baya",
          "Kada ka yarda da bincike idan ba a nuna takardar ba — ba tilas bane",
          "Kada ka buɗe wayarka a ƙarƙashin matsi ba tare da odar kotu ba",
          "Kada ka bar su ɗauke da dukiya da ba ta cikin takardar ba tare da nuna kin ba",
        ],
        ig: [
          "Emegidekwala ma ọ bụ wakpoo ndị ọrụ n'ahụ — soro ha, wee luso ha ọgụ n'ụlọ ikpe",
          "Ekwekọkwala na nyocha ọ bụrụ na ha egosighị gị iwu — ọ abụghị mkpa gị",
          "Emeghe ekwenti gị n'okpuru nrụgide na-enweghị iwu ụlọ ikpe",
          "Ekwekọkwala ka ha wepụ ihe ndị a dịghị n'iwu ahụ na-ekwupụtaghị",
        ],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 37",
          plainEnglish: {
            en: "The privacy of citizens, their homes, correspondence, telephone conversations and telegraphic communications is hereby guaranteed and protected.",
            pcm: "The privacy of every Nigerian citizen, their house, letters, phone calls and messages na protected by law.",
            yo: "Asiri awọn ọmọ ilu, ile wọn, lẹta, awọn ipe foonu ati awọn ifiranṣẹ ni a ṣe idaniloju ati daabo bo nipasẹ ofin yii.",
            ha: "Sirrin 'yan ƙasa, gidajensu, wasiƙu, tattaunawar waya da saƙonni na dijital an ba da tabbaci kuma ana kiyaye su.",
            ig: "A na-echekwa ma nọchite anya nzuzo nke ndị ọchịchị, ụlọ ha, ozi ha, mkparịta ụka ekwenti na ozi eletrọnịks ha n'iwu a.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 143",
          plainEnglish: {
            en: "A search warrant must specify the premises to be searched and the items sought. It must be executed by the officer named in the warrant.",
            pcm: "Search warrant must clearly state the house to be searched and the things dem dey look for. The officer named for the warrant must be the one to execute am.",
            yo: "Iwe aṣẹ ìwádìí gbọdọ ṣalaye ile ti a fẹ ṣàyẹwò ati awọn ohun ti a n wa. Ọ gbọdọ jẹ ki ọfẹ ti a mẹnuba ninu iwe aṣẹ ṣe ìwádìí naa.",
            ha: "Takardar bincike dole ta bayyana ginin da za a bincika da kayayyakin da ake nema. Dole ne jandamin da aka ambata a cikin takardar ya aiwatar da shi.",
            ig: "Iwu nyocha ga-akọwapụta ụlọ a ga-anyochaa na ihe ndị a na-achọ. Onye ọrụ a kọwara n'iwu ahụ ka ga-enye ya n'ọrụ.",
          },
        },
        {
          name: "Nigerian Police Act 2020",
          section: "Section 84",
          plainEnglish: {
            en: "A police officer shall not search a female person except through a female officer.",
            pcm: "Police officer no fit search woman except through female police officer.",
            yo: "Ọlọpaa ko le ṣàyẹwò obinrin ayafi nipasẹ ọlọpaa obinrin.",
            ha: "Jandamin ba zai iya bincika mace ba sai ta hanyar jandama mace.",
            ig: "Onye uwe ojii enweghị ike inyochaa ụmụ nwanyị ma ọ dịghị site n'aka onye uwe ojii nwanyị.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Officers arrive at your home at night and say they want to search it. They do not have a search warrant.",
            pcm: "Police come your house for night say dem wan search am. Dem no get search warrant.",
            yo: "Awọn ọfẹ de ile rẹ ni alẹ wí pé wọn fẹ ṣàyẹwò rẹ. Wọn ko ni iwe aṣẹ ìwádìí.",
            ha: "Jandaman sun zo gidanka da dare suna cewa suna son bincika shi. Ba su da takardar bincike.",
            ig: "Ndị ọrụ bịara n'ụlọ gị n'abalị wee kwuo na ha chọọ inyochaa ya. Ha enweghị iwu nyocha.",
          },
          steps: {
            en: [
              "Do not open the door immediately. Ask through the door: 'Do you have a search warrant?'",
              "If they say no, you are entitled to refuse entry. Say: 'I cannot allow entry without a valid search warrant.'",
              "If they force entry anyway, do not physically resist — but state clearly: 'I do not consent to this search.'",
              "Note the names and badge numbers of all officers present.",
              "Contact a lawyer immediately and document all items removed.",
            ],
            pcm: [
              "No open door immediately. Ask through the door: 'You get search warrant?'",
              "If dem say no, you fit refuse dem entry. Tell dem: 'I no fit allow una enter without search warrant.'",
              "If dem force enter anyway, no fight dem — but talk clear: 'I no consent to this search.'",
              "Write down names and badge numbers of all officers wey dey there.",
              "Call lawyer immediately and document every item dem remove.",
            ],
            yo: [
              "Má ṣii ilẹkun lẹsẹkẹsẹ. Beere nipasẹ ilẹkun: 'Ṣe ẹ ni iwe aṣẹ ìwádìí?'",
              "Ti wọn ba sọ rara, o ni ẹtọ lati kọ wọle. Sọ: 'Emi ko le jẹ ki ẹ wọle laisi iwe aṣẹ ìwádìí ti o wulo.'",
              "Ti wọn ba fi agbara wọle, má dojuko wọn ni ara — ṣugbọn sọ gbangba: 'Emi ko fun ni aṣẹ fun ìwádìí yii.'",
              "Ṣe akiyesi awọn orukọ ati nọmba aami gbogbo awọn ọfẹ ti o wa.",
              "Pe agbẹjọro lẹsẹkẹsẹ ki o si ṣe akọsilẹ gbogbo awọn ohun ti a gbe.",
            ],
            ha: [
              "Kada ka buɗe ƙofa nan da nan. Yi tambaya ta ƙofar: 'Kuna da takardar bincike?'",
              "Idan sun ce a'a, kana da haƙƙin ƙin ba su shiga. Ce: 'Ba zan iya ba da izinin shiga ba tare da takardar bincike mai inganci ba.'",
              "Idan sun tilasta shiga duk da haka, kada ka tsayas da su jiki — amma ce a sarari: 'Ba na yarda da wannan binciken.'",
              "Rubuta sunaye da lambobin badge na dukan jandaman da suke can.",
              "Tuntubi lauya nan da nan kuma rubuta dukan abubuwan da aka ɗauka.",
            ],
            ig: [
              "Emegheghị ọnụ ụzọ ozugbo. Jụọ site n'ọnụ ụzọ: 'Enwere ha iwu nyocha?'",
              "Ọ bụrụ na ha kwuo mba, ị nwere ikike ịjụ ha ịbanye. Kwuo: 'Enweghị m ike ikwe ha ịbanye na-enweghị iwu nyocha ziri ezi.'",
              "Ọ bụrụ na ha banye n'ike n'agbanyeghị, emegidekwala ha n'ahụ — mana kwuo nke ọma: 'Enweghị m ikwe maka nyocha a.'",
              "Deechie aha na nọmba badge nke ndị ọrụ niile ndị dị ebe ahụ.",
              "Kpọtụrụ ọka iwu ozugbo ma deechie ihe niile ha weere.",
            ],
          },
        },
      ],
    },
    {
      slug: "right-to-legal-representation",
      title: {
        en: "Right to Legal Representation",
        pcm: "Right to Get Lawyer",
        yo: "Ẹtọ si Agbẹjọro",
        ha: "Haƙƙin Samun Lauya",
        ig: "Ikike Nweta Ọka Iwu",
      },
      summary: {
        en: "Section 36(6)(c) of the Constitution guarantees your right to a lawyer of your choice. If you cannot afford one, the state must provide one for serious offences. Police must inform you of this right, and no statement taken without doing so is admissible in court.",
        pcm: "Section 36(6)(c) of the Constitution give you right to get lawyer of your choice. If you no get money, the government must provide one for serious offences. Police must tell you this right, and any statement dem take without telling you no fit be used for court.",
        yo: "Abala 36(6)(c) ti Ofin ṣe idaniloju ẹtọ rẹ si agbẹjọro ti yiyan rẹ. Ti o ko ba le san, ijọba gbọdọ pese ọkan fun awọn ẹṣẹ pataki. Ọlọpaa gbọdọ fi ẹtọ yii hàn ọ, ati pe alaye eyikeyi ti a gba laisi ṣiṣe bẹẹ ko le gba gbà ni ile-ẹjọ.",
        ha: "Sashe na 36(6)(c) na Kundin Tsarin Mulki yana ba da tabbacin haƙƙinka na samun lauya na zaɓinka. Idan ba ka iya biyan kuɗi ba, gwamnati dole ta samar da ɗaya don laifuka masu nauyi. Yan sanda dole su sanar da kai wannan haƙƙin, kuma babu wata sanarwa da aka ɗauka ba tare da yin haka ba da za a yarda da ita a kotu.",
        ig: "Ngalaba 36(6)(c) nke Ihe Ọmụma na-enyocha ikike gị nweta ọka iwu nke họrọ. Ọ bụrụ na ị enweghị ego, ọchịchị ga-enye gị otu maka nnukwu mmehie. Ndị uwe ojii ga-agwa gị banyere ikike a, na nkwupụta ọ bụla e wetara na-agwachị gị banyere ya adịghị mma n'ụlọ ikpe.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Question you in the presence of your lawyer",
          "Proceed with prosecution if you waive your right to a lawyer voluntarily and knowingly",
          "Appoint a state-funded lawyer if you cannot afford one and the offence is serious",
          "Record a statement you voluntarily choose to give after being informed of your rights",
        ],
        pcm: [
          "Question you when your lawyer dey there",
          "Continue prosecution if you willingly give up your right to lawyer",
          "Assign government lawyer to you if you no get money and the offence serious",
          "Write your statement if you choose to give am after dem tell you your rights",
        ],
        yo: [
          "Beere lọwọ rẹ awọn ibeere ni iwaju agbẹjọro rẹ",
          "Tẹsiwaju pẹlu ẹjọ ti o ba fi ẹtọ rẹ si agbẹjọro silẹ lairotẹlẹ",
          "Yan agbẹjọro ti ijọba gba owo fun ti o ko ba le san ati ẹṣẹ naa ba jẹ pataki",
          "Gbasilẹ alaye ti o ba fẹ fun ni lairotẹlẹ lẹhin ti a ti sọ ẹtọ rẹ",
        ],
        ha: [
          "Tambaya maka a gaban lauyanka",
          "Ci gaba da tuhumar idan ka yi watsi da haƙƙinka na lauya da son rai da sanin yakamata",
          "Nada lauyan gwamnati idan ba ka iya biyan kuɗi ba kuma laifin yana da nauyi",
          "Rubuta sanarwa da ka zaɓi ba da son rai bayan an sanar da kai haƙƙoƙinka",
        ],
        ig: [
          "Jụọ gị ajụjụ n'ihu ọka iwu gị",
          "Gaa n'ihu na ikpe ọ bụrụ na ị hapụ ikike gị nke ọka iwu n'onwe gị",
          "họọ ọka iwu nke ọchịchị kwụọ ụgwọ ya ọ bụrụ na ị enweghị ego na mmehie a dị njọ",
          "Deechie nkwupụta ọ bụrụ na ị họrọ inye n'onwe gị ka a gwaara gị banyere ikike gị",
        ],
      },
      cannotDo: {
        en: [
          "Question you about a criminal matter without informing you of your right to a lawyer",
          "Take a statement from you after you have asked for a lawyer but before one arrives",
          "Deny you access to your lawyer once you have been detained",
          "Use a statement obtained without notifying you of your right to a lawyer as evidence",
          "Threaten or discourage you from requesting legal representation",
        ],
        pcm: [
          "Question you about crime without telling you say you get right to lawyer",
          "Collect your statement after you don ask for lawyer but before lawyer come",
          "Block you from seeing your lawyer once dem don detain you",
          "Use statement dem collect without telling you about your right to lawyer as evidence",
          "Threaten you or discourage you from asking for lawyer",
        ],
        yo: [
          "Beere lọwọ rẹ nipa ọrọ ọdaràn laisi sọ ẹtọ rẹ si agbẹjọro",
          "Gba alaye lọwọ rẹ lẹhin ti o ba ti beere fun agbẹjọro ṣugbọn ṣaaju ki agbẹjọro to de",
          "Kọ ọ ni aye lati ba agbẹjọro rẹ pade lẹhin ti a ti fi ọ pamọ́",
          "Lo alaye ti a gba laisi sọ ẹtọ rẹ si agbẹjọro gẹgẹbi ẹri",
          "Halẹ mọ tabi dẹtẹ ọ lati beere iranlọwọ ofin",
        ],
        ha: [
          "Tambayar ka game da laifin ba tare da sanar da kai haƙƙinka na lauya ba",
          "Ɗaukan sanarwarka bayan ka nemi lauya amma kafin ya iso",
          "Hana ka shiga lauyana da zarar an tsare ka",
          "Amfani da sanarwa da aka ɗauka ba tare da sanar da kai haƙƙinka ba a matsayin shaida",
          "Yi maka barazana ko hana ka neman wakilcin doka",
        ],
        ig: [
          "Jụọ gị ajụjụ banyere ihe ọjọọ na-agwachị gị banyere ikike gị nke ọka iwu",
          "Nweta nkwupụta gị ka ị rịọọla ọka iwu mana tupu ya abịa",
          "Igbochi gị ịhụ ọka iwu gị ozugbo ka e nọdee gị n'ogige",
          "Ojiji nkwupụta e nweere na-agwachị gị banyere ikike gị dị ka ihe akaebe",
          "Iyi gị egwu ma ọ bụ igbochi gị ịrịọ nnọchiteanya n'iwu",
        ],
      },
      whatToDo: {
        en: [
          "As soon as you are detained or questioned, clearly state: 'I want to speak with a lawyer before answering any questions.'",
          "If you cannot afford a lawyer, say: 'I cannot afford a lawyer and request that one be provided for me.'",
          "Do not answer any substantive questions until your lawyer arrives",
          "Ask for your lawyer's contact to be noted and for them to be called immediately",
          "If a statement is recorded without you being informed of your rights, tell your lawyer — it may be inadmissible",
        ],
        pcm: [
          "As dem detain or question you, talk clear: 'I want to talk to lawyer before I answer any question.'",
          "If you no get money for lawyer, say: 'I no fit afford lawyer, I dey request make dem provide one for me.'",
          "No answer any serious question until your lawyer come",
          "Ask make dem write your lawyer contact and call am immediately",
          "If dem collect your statement without telling you your rights, tell your lawyer — dem fit use am against dem in court",
        ],
        yo: [
          "Ni kete ti a ba fi ọ pamọ́ tabi bẹrẹ ibeere, sọ gbangba: 'Mo fẹ ba agbẹjọro sọrọ ṣaaju ki mo to dahun eyikeyi ibeere.'",
          "Ti o ko ba le san agbẹjọro, sọ: 'Mi o le san agbẹjọro, mo n beere fun ọkan lati pese fun mi.'",
          "Má dahun awọn ibeere pataki titi di igba ti agbẹjọro rẹ yoo de",
          "Beere ki a ṣe akiyesi alaanu agbẹjọro rẹ ki a pe wọn lẹsẹkẹsẹ",
          "Ti a ba gba alaye laisi sọ ẹtọ rẹ, sọ fun agbẹjọro rẹ — o le jẹ pe a ko gba gbà",
        ],
        ha: [
          "Da zarar an tsare ka ko an fara tambayarka, ce a sarari: 'Ina so in yi magana da lauya kafin in amsa wata tambaya.'",
          "Idan ba ka iya biyan kuɗin lauya ba, ce: 'Ba zan iya biyan kuɗin lauya ba, ina neman a samar da ɗaya a gare ni.'",
          "Kada ka amsa wata mahimiyar tambaya har sai lauyanka ya zo",
          "Nemi a rubuta lambar hulɗar lauyanka kuma a kira shi nan da nan",
          "Idan aka ɗauki sanarwa ba tare da sanar da kai haƙƙoƙinka ba, gaya wa lauyanka — ƙila ba za a yarda da ita ba",
        ],
        ig: [
          "Ozugbo ka e nọdee gị n'ogige ma ọ bụ jụọ gị ajụjụ, kwuo nke ọma: 'Achọrọ m ikwu okwu na ọka iwu tupu m aza ajụjụ ọ bụla.'",
          "Ọ bụrụ na ị enweghị ego maka ọka iwu, kwuo: 'Enweghị m ego ọka iwu, na m arịọ ka a nye m otu.'",
          "Azaghị ajụjụ dị mkpa ọ bụla ruo mgbe ọka iwu gị abịa",
          "Rịọ ka a deechie ụdị kọntaktị nke ọka iwu gị ma kpọọ ya ozugbo",
          "Ọ bụrụ na e dekọọ nkwupụta na-agwachị gị banyere ikike gị, gwa ọka iwu gị — ọ nwere ike ọ gaghị abara n'ụlọ ikpe",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not answer questions about a crime before speaking with a lawyer",
          "Do not sign any statement or document without your lawyer reviewing it",
          "Do not assume a lawyer will be provided automatically — request one explicitly",
          "Do not give up your right to a lawyer due to police pressure or persuasion",
        ],
        pcm: [
          "No answer question about crime before you talk to lawyer",
          "No sign any statement or document without your lawyer checking am",
          "No assume dem go automatically give you lawyer — ask for am directly",
          "No give up your right to lawyer because police dey pressure or beg you",
        ],
        yo: [
          "Má dahun awọn ibeere nipa ẹṣẹ ṣaaju ki o to ba agbẹjọro sọrọ",
          "Má fowo si alaye tabi iwe eyikeyi laisi agbẹjọro rẹ ṣàyẹwò rẹ",
          "Má ro pe agbẹjọro yoo wa ni aitọ — beere ni gbangba",
          "Má kọ ẹtọ rẹ si agbẹjọro nitori titẹ ọlọpaa",
        ],
        ha: [
          "Kada ka amsa tambayoyi game da laifi kafin ka yi magana da lauya",
          "Kada ka sanya hannu kan wata sanarwa ko takarda ba tare da lauyanka ya duba shi ba",
          "Kada ka ɗauka za a samar da lauya kai tsaye — neme shi a fili",
          "Kada ka yi watsi da haƙƙinka na lauya saboda matsin 'yan sanda ko shawo kansu",
        ],
        ig: [
          "Azaghị ajụjụ banyere mmehie tupu ị kwurita okwu na ọka iwu",
          "Akwadobiahala nkwupụta ma ọ bụ akwụkwọ ọ bụla na-enweghị ọka iwu gị lele ya",
          "Echeghị na a ga-enye gị ọka iwu n'ozuzu — rịọ ya nke ọma",
          "Ahapụla ikike gị nke ọka iwu n'ihi nrụgide ma ọ bụ mkwenye nke ndị uwe ojii",
        ],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 36(6)(c)",
          plainEnglish: {
            en: "Every person charged with a criminal offence shall be entitled to defend himself in person or by legal practitioners of his own choice.",
            pcm: "Every person wey dem charge with crime get right to defend himself or use lawyer of their own choice.",
            yo: "Gbogbo eniyan ti a fi ẹsun ọdaràn kan ni ẹtọ lati daabobo ara rẹ funrarẹ tabi nipasẹ agbẹjọro ti yiyan rẹ.",
            ha: "Duk wanda ake tuhumar da laifin yana da haƙƙin kare kansa ko ta hanyar lauyansa na zaɓi.",
            ig: "Onye ọ bụla a buọrọ mmehie nwere ikike ịchebe onwe ya n'onwe ya ma ọ bụ site n'aka ọka iwu ya nhọrọ.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 6(1)(b)",
          plainEnglish: {
            en: "A suspect shall be informed of his right to retain and instruct a legal practitioner of his choice and to remain silent or avoid answering any question until after consultation with a legal practitioner.",
            pcm: "Every suspect must be told say dem get right to choose their own lawyer and to keep quiet until dem don talk to lawyer.",
            yo: "Gbogbo afurasi gbọdọ gba alaye pe wọn ni ẹtọ lati yan agbẹjọro ti wọn fẹ ati lati dakẹ titi di igba ti wọn ba ti ba agbẹjọro sọrọ.",
            ha: "Dole a sanar da duk wanda ake zargi cewa yana da haƙƙin yin amfani da lauyan zaɓinsa kuma yana iya yin shiru har sai ya yi magana da lauya.",
            ig: "A ga-agwa onye ọ bụla a na-achọ ikpe banyere ikike ya ịhọrọ ọka iwu ya na ịnọ nè ruo mgbe ha kwurita okwu na ọka iwu.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "You are taken to a police station and officers begin questioning you about an alleged robbery before you have spoken to a lawyer.",
            pcm: "Dem carry you go police station and dem start to question you about robbery before you don talk to any lawyer.",
            yo: "Wọn mu ọ lọ si ibudo ọlọpaa, awọn ọfẹ si bẹrẹ beere lọwọ rẹ nipa ole ṣaaju ki o to ba agbẹjọro sọrọ.",
            ha: "An kai ka tashar 'yan sanda kuma jandaman sun fara tambayarka game da wani fashi kafin ka yi magana da lauya.",
            ig: "Ha kpọ gị ụlọ ọrụ uwe ojii ma ndị ọrụ jikwa ịjụ gị ajụjụ banyere ịzụ n'ụzọ ọjọọ tupu ị kwurita okwu na ọka iwu.",
          },
          steps: {
            en: [
              "Remain calm. Do not answer any questions about the alleged offence.",
              "State clearly: 'I am exercising my right to remain silent. I want to speak with a lawyer before answering any questions.'",
              "If you cannot afford a lawyer, say: 'I cannot afford a lawyer. I am requesting that one be provided for me under Section 36(6)(c) of the Constitution.'",
              "Do not sign any document or statement until your lawyer is present.",
              "Your lawyer can later challenge any statement obtained in violation of this right.",
            ],
            pcm: [
              "Stay calm. No answer any question about the offence.",
              "Tell dem clear: 'I dey use my right to remain silent. I want to talk to lawyer before I answer any question.'",
              "If you no get money for lawyer, say: 'I no fit afford lawyer. I dey request make dem give me one under Section 36(6)(c) of Constitution.'",
              "No sign any document or statement until your lawyer dey there.",
              "Your lawyer fit challenge any statement dem collect when dem violate your right.",
            ],
            yo: [
              "Jẹ ki o balẹ. Má dahun awọn ibeere nipa ẹṣẹ ti a fura si.",
              "Sọ gbangba: 'Mo n lo ẹtọ mi lati dakẹ. Mo fẹ ba agbẹjọro sọrọ ṣaaju ki mo to dahun eyikeyi ibeere.'",
              "Ti o ko ba le san agbẹjọro, sọ: 'Mi o le san agbẹjọro. Mo n beere pe ki a pese ọkan fun mi labẹ Abala 36(6)(c) ti Ofin.'",
              "Má fowo si iwe tabi alaye eyikeyi titi di igba ti agbẹjọro rẹ yoo wa.",
              "Agbẹjọro rẹ le lẹhinna tako alaye eyikeyi ti a gba ni ilodi si ẹtọ yii.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka amsa wata tambaya game da zargin laifin.",
              "Ce a sarari: 'Ina amfani da haƙƙina na yin shiru. Ina so in yi magana da lauya kafin in amsa wata tambaya.'",
              "Idan ba ka iya biyan kuɗin lauya ba, ce: 'Ba zan iya biyan kuɗin lauya ba. Ina neman a samar da ɗaya a gare ni a ƙarƙashin Sashe na 36(6)(c) na Kundin Tsarin Mulki.'",
              "Kada ka sanya hannu kan takarda ko sanarwa har sai lauyanka ya zo.",
              "Lauyanka zai iya daga baya kalubalanci duk wata sanarwa da aka ɗauka ta hanyar keta wannan haƙƙin.",
            ],
            ig: [
              "Nọrọ n'udo. Azaghị ajụjụ ọ bụla banyere mmehie a na-ebo.",
              "Kwuo nke ọma: 'Ana m iji ikike m ịnọ nè. Achọrọ m ikwu okwu na ọka iwu tupu m aza ajụjụ ọ bụla.'",
              "Ọ bụrụ na ị enweghị ego maka ọka iwu, kwuo: 'Enweghị m ego ọka iwu. Ana m arịọ ka a nye m otu n'okpuru Ngalaba 36(6)(c) nke Ihe Ọmụma.'",
              "Akwadobiahala akwụkwọ ma ọ bụ nkwupụta ọ bụla ruo mgbe ọka iwu gị dị ebe ahụ.",
              "Ọka iwu gị nwere ike ijikwa iwu megide nkwupụta ọ bụla e nweere n'ịgagharị ikike a.",
            ],
          },
        },
      ],
    },
    {
      slug: "freedom-from-torture",
      title: {
        en: "Freedom from Torture and Degrading Treatment",
        pcm: "Right Against Torture and Wickedness",
        yo: "Ẹtọ Lodi si Ìjìyà àti Ìtọ́jú Alàánú",
        ha: "Haƙƙi Daga Azabtarwa da Wulakanci",
        ig: "Nwere Onwe Site n'Ịta Ahụhụ na Ọdachi",
      },
      summary: {
        en: "Section 34 of the Constitution guarantees every person's right to dignity. Torture, inhuman or degrading treatment is absolutely prohibited. Any confession obtained through torture is inadmissible. The Anti-Torture Act 2017 criminalises torture by public officials, and you have the right to be examined by a medical officer if you have been assaulted in custody.",
        pcm: "Section 34 of the Constitution give every person right to dignity. Torture, cruelty or wicked treatment na totally forbidden. Any confession dem take by force or torture no fit be used for court. Anti-Torture Act 2017 make torture by government official a crime, and you get right to see doctor if dem beat you for custody.",
        yo: "Abala 34 ti Ofin ṣe idaniloju ẹtọ gbogbo eniyan si ọlá. Ìjìyà, ìtọ́jú aibikita tabi ti o lẹbi jẹ eewọ patapata. Ijẹwọ eyikeyi ti a gba nipasẹ ìjìyà ko le gba gbà. Ofin Atako Ìjìyà 2017 ṣe ìjìyà nipasẹ awọn oṣiṣẹ ijọba gẹgẹbi ẹṣẹ, ati pe o ni ẹtọ lati jẹ ki oniwosan ṣàyẹwò rẹ ti o ba ti kọlu ọ ninu àtìmọ́lé.",
        ha: "Sashe na 34 na Kundin Tsarin Mulki yana ba da tabbacin haƙƙin kowa na mutunci. Azabtarwa, wulakanci ko hana mutunci an hana su gaba ɗaya. Duk wata ikirari da aka samu ta hanyar azabtarwa ba za a yarda da ita ba. Dokar Anti-Torture ta 2017 ta sa azabtarwa da jami'an gwamnati ke yi a matsayin laifi, kuma kana da haƙƙin a bincika ka daga wani jami'in lafiya idan an doke ka a tsarewa.",
        ig: "Ngalaba 34 nke Ihe Ọmụma na-echekwa ikike onye ọ bụla nke nsọpụrụ. A machibidoro ịta ahụhụ, omume ọjọọ ma ọ bụ ihe iwu n'ụzọ zuru oke. Nkwupụta ngụzọ ọ bụla e nweere site n'ịta ahụhụ adịghị mma n'ụlọ ikpe. Iwu Anti-Torture nke 2017 na-eme ịta ahụhụ site n'aka ndị ọrụ ọchịchị dị ka mmehie, na ị nwere ikike ka onye ọrụ ahụ lelee gị ọ bụrụ na a kụọ gị n'ọgige.",
      },
      readMinutes: 5,
      canDo: {
        en: [
          "Use minimum, proportionate force during a lawful arrest if you resist",
          "Restrain you physically if you are violent and pose a risk to yourself or others",
          "Place you in a holding cell pending charge or bail",
          "Conduct a medical examination of you if required for investigation purposes",
        ],
        pcm: [
          "Use small, reasonable force during legal arrest if you dey resist",
          "Restrain you physically if you dey violent and dey risk yourself or others",
          "Put you for cell while dem dey process charge or bail",
          "Do medical check on you if it dey related to their investigation",
        ],
        yo: [
          "Lo agbara ti o kere julọ, ti o yẹ lakoko imudani ti o tọ ti o ba dojuko",
          "Di ọ duro ni ara ti o ba jẹ ipalara ati pe o ṣe irokeke si ararẹ tabi awọn miiran",
          "Fi ọ sinu ẹwọn ti n duro de ẹsun tabi ìdásílẹ̀",
          "Ṣe ayẹwo iṣoogun ti o ba jẹ dandan fun awọn idi iwadii",
        ],
        ha: [
          "Yi amfani da ƙarfi mafi ƙanƙanta, mai ma'ana a lokacin kama bisa doka idan ka tsayas",
          "Kame ka jiki idan kana da tashin hankali kuma kana haifar da haɗari ga kanka ko wasu",
          "Saka ka cikin dakin tsare jiran tuhuma ko beli",
          "Yi binciken likita a kanka idan ya zama wajibi don dalilan bincike",
        ],
        ig: [
          "Ojiji ike pere mpe, kwesịrị n'oge njide iwu ọ bụrụ na ị melite",
          "Jide gị n'ahụ ọ bụrụ na ị na-emegbu ma bụrụ ihe egwu nye onwe gị ma ọ bụ ndị ọzọ",
          "Tinye gị n'ụlọ mkpọrọ n'ime nọọ ibulie gị ma ọ bụ nweta bọọlụ",
          "Mee nyocha ọgwụgwọ gị ọ bụrụ na ọ dị mkpa maka ebumnuche nyocha",
        ],
      },
      cannotDo: {
        en: [
          "Beat, slap, kick or use any form of physical violence against you while in custody",
          "Subject you to electric shock, stress positions, sleep deprivation, or starvation",
          "Threaten you or your family members to extract a confession",
          "Use a confession obtained through torture or threats as evidence",
          "Deny you medical attention after you have been injured in custody",
          "Punish you before you have been convicted by a court",
        ],
        pcm: [
          "Beat, slap, kick or do any kind of physical violence on you while dem hold you",
          "Give you electric shock, make you stand in stress position, deprive you of sleep, or starve you",
          "Threaten you or your family to force you confess",
          "Use confession wey dem take by force or threat as evidence",
          "Deny you medical treatment after dem don injure you in custody",
          "Punish you before court don find you guilty",
        ],
        yo: [
          "Na, ta, tabi lo eyikeyi fọọmu ti ìwa ipá lori rẹ ninu àtìmọ́lé",
          "Ṣe adanwo mọnamọna, pa ọ mọ ninu irora, fi ọ lẹ oorun, tabi pa ọ mọ ounjẹ",
          "Halẹ mọ tabi fi ẹbi rẹ lẹru lati fa ijẹwọ",
          "Lo ijẹwọ ti a fa nipasẹ ìjìyà tabi ewu bi ẹri",
          "Kọ ọ ni itọju iṣoogun lẹhin ti o ba ti farapa ninu àtìmọ́lé",
          "Jẹ ki ọ jiya ṣaaju ki ile-ẹjọ to da ọ lẹjọ",
        ],
        ha: [
          "Doke, mari, ko yi wani nau'i na tashin jiki a kanka yayin tsarewa",
          "Azabtar da kai da wutar lantarki, matsawa a matsanancin yanayi, hana kai barci, ko azumi tilas",
          "Yi maka barazana ko dangin ka don tilasta ikirari",
          "Amfani da ikirarin da aka samu ta hanyar azabtarwa ko barazana a matsayin shaida",
          "Hana kai magani bayan an ji maka rauni a tsarewa",
          "Hukunta ka kafin kotu ta same ka da laifi",
        ],
        ig: [
          "Tie, taa, ma ọ bụ ojiji ụdị ike ọ bụla megide gị n'ọgige",
          "Nyụọ gị ọkụ eletrik, tinye gị n'ọnọdụ mgbu, gbochie gị ụra, ma ọ bụ gbochie gị nri",
          "Iyi gị egwu ma ọ bụ ndị ikwu gị iji nweta nkwupụta ngụzọ",
          "Ojiji nkwupụta ngụzọ e nweere site n'ịta ahụhụ ma ọ bụ iyi egwu dị ka ihe akaebe",
          "Igbochi gị ọgwụgwọ ka e merụọ gị ahụ n'ọgige",
          "Taa gị ahụhụ tupu ụlọ ikpe achị gị ikpe",
        ],
      },
      whatToDo: {
        en: [
          "If assaulted in custody, immediately request to see a medical officer and state that you have been assaulted",
          "Tell your lawyer everything that happened — including names of officers involved",
          "Ask that any injuries be documented by a doctor as soon as possible",
          "Report the incident to the National Human Rights Commission or a civil liberties organisation",
          "Know that any confession you made under duress can be challenged and excluded in court",
        ],
        pcm: [
          "If dem beat you in custody, immediately ask to see doctor and tell dem say dem don beat you",
          "Tell your lawyer everything wey happen — including names of officers wey do am",
          "Ask make doctor document your injuries as soon as possible",
          "Report the matter to the National Human Rights Commission or any human rights group",
          "Know say any confession you give under force fit be challenged and removed from court evidence",
        ],
        yo: [
          "Ti a ba kọlu ọ ninu àtìmọ́lé, beere lẹsẹkẹsẹ lati ri dokita ki o sọ pe a ti kọlu ọ",
          "Sọ fun agbẹjọro rẹ ohun gbogbo ti o ṣẹlẹ — pẹlu awọn orukọ awọn ọfẹ ti o wa ninu rẹ",
          "Beere pe ki dokita ṣe igbasilẹ awọn ọgbẹ rẹ ni kete bi o ti ṣeeṣe",
          "Ròyìn ìṣẹlẹ naa si National Human Rights Commission tabi ẹgbẹ ominira ara ilu",
          "Mọ pe ijẹwọ eyikeyi ti o ṣe labẹ ìpéníjà le tako ati yọ kuro ni ile-ẹjọ",
        ],
        ha: [
          "Idan an doke ka a tsarewa, nan da nan nemi ganin likita kuma faɗa an doke ka",
          "Gaya wa lauyanka komai da ya faru — ciki har da sunayen jandaman da ke tattare da shi",
          "Nemi likita ya rubuta raunanka da wuri-wuri",
          "Kai rahoton abin da ya faru ga National Human Rights Commission ko wata ƙungiyar kare haƙƙin ɗan adam",
          "Sani cewa duk wata ikirari da ka bayar ƙarƙashin tilastawa ana iya kalubalantar ta kuma a cire ta daga shaida a kotu",
        ],
        ig: [
          "Ọ bụrụ na e kụọ gị n'ọgige, ozugbo rịọ ka i hụ onye ọrụ ahụ ma kwuo na e kụọ gị",
          "Gwa ọka iwu gị ihe niile mere — gụnyere aha ndị ọrụ ndị gụnyere n'ya",
          "Rịọ ka onye ọgwụgwọ deechie ọnya gị n'oge ọ soonest",
          "Kọọ ihe ahụ mere n'National Human Rights Commission ma ọ bụ otu ikike mmadụ",
          "Mara na nkwupụta ngụzọ ọ bụla ị nyere n'okpuru mmanye nwere ike ijikwa iwu ya wee ewepụ ya n'ihe akaebe n'ụlọ ikpe",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not assume that because you were tortured nothing can be done — it is a criminal offence",
          "Do not delay seeking medical attention — early documentation is critical",
          "Do not sign any statement made under duress, and tell the court if you did",
          "Do not retaliate physically — report through legal channels",
        ],
        pcm: [
          "No think say nothing fit be done because dem torture you — na criminal offence",
          "No delay to go see doctor — early documentation dey very important",
          "No sign any statement wey dem force you make, and tell court if you already sign am",
          "No try revenge dem physically — report am through legal channels",
        ],
        yo: [
          "Má ro pe nitori a ṣe ìjìyà ọ pe ko si ohun ti a le ṣe — o jẹ ẹṣẹ ọdaràn",
          "Má fa fifẹ lati wa itọju iṣoogun — igbasilẹ ni kutukutu jẹ pataki",
          "Má fowo si alaye eyikeyi ti a ṣe labẹ ìpéníjà, ki o si sọ fun ile-ẹjọ ti o ba ti fowo si",
          "Má gbẹsan ni ara — ròyìn nipasẹ awọn ọna ofin",
        ],
        ha: [
          "Kada ka ɗauka cewa komai ba za a iya yi ba saboda an azabtar da kai — laifin aikata laifi ne",
          "Kada ka jinkirta neman kulawar likita — yin rajista da wuri yana da matuƙar mahimmanci",
          "Kada ka sanya hannu kan duk wata sanarwa da aka yi ƙarƙashin tilastawa, kuma faɗa wa kotu idan ka sanya hannu",
          "Kada ka rama musu jiki — kai rahoto ta hanyoyin doka",
        ],
        ig: [
          "Echeghị na n'ihi na e taara gị ahụhụ na ọ dịghị ihe e nwere ike ime — ọ bụ mmehie n'iwu",
          "Echekwala ịchọ ọgwụgwọ — ndeekọ ya n'oge bụ ihe dị mkpa",
          "Akwadobiahala nkwupụta ọ bụla emere n'okpuru mmanye, ma gwa ụlọ ikpe ọ bụrụ na ị mere ya",
          "Azaghachi ha n'ahụ — kọọ ya site n'ụzọ iwu",
        ],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 34",
          plainEnglish: {
            en: "Every individual is entitled to respect for the dignity of his person. No person shall be subjected to torture or to inhuman or degrading treatment.",
            pcm: "Every person get right to be treated with dignity. Nobody fit torture you or treat you in wicked and degrading way.",
            yo: "Gbogbo eniyan ni ẹtọ si ọwọ fun ọlá eniyan rẹ. Ẹnikẹni ko gbọdọ jẹ ki o wa labẹ ìjìyà tabi ìtọ́jú aibikita tabi ti o lẹbi.",
            ha: "Kowane mutum yana da haƙƙin a mutunta shi. Ba za a iya azabtar da kowa ba ko a yi masa wulakanci ko hana mutunci.",
            ig: "Onye ọ bụla nwere ikike nsọpụrụ nke onwe ya. Onye ọ bụla anaghị-enweghị ike ịta ya ahụhụ ma ọ bụ omume ọjọọ ma ọ bụ ihe iwu.",
          },
        },
        {
          name: "Anti-Torture Act 2017",
          section: "Section 2",
          plainEnglish: {
            en: "Any public officer who commits torture is guilty of an offence and is liable to imprisonment for a term of 25 years.",
            pcm: "Any government worker wey torture somebody na criminal and dem fit sentence am to 25 years for prison.",
            yo: "Eyikeyi oṣiṣẹ ijọba ti o ṣe ìjìyà jẹ ẹlẹṣẹ ati pe o le jẹ ẹwọn fun ọdun 25.",
            ha: "Duk wani jami'in gwamnati da ya yi azabtarwa laifin aikata laifi ya aikata kuma yana da alhakin daurin kurkuku na shekaru 25.",
            ig: "Onye ọrụ ọchịchị ọ bụla na-ata onye ọzọ ahụhụ nwere mmehie ma nwere ike ikpọrọ ya n'ụlọ mkpọrọ ọrụ afọ 25.",
          },
        },
        {
          name: "Anti-Torture Act 2017",
          section: "Section 8",
          plainEnglish: {
            en: "Any confession or statement obtained from a person through torture shall be inadmissible as evidence in any legal proceedings.",
            pcm: "Any confession or statement wey dem take by torture no fit be used as evidence for any court case.",
            yo: "Ijẹwọ tabi alaye eyikeyi ti a gba lọwọ eniyan nipasẹ ìjìyà ko le gba gbà gẹgẹbi ẹri ninu eyikeyi ilana ofin.",
            ha: "Duk wata ikirari ko sanarwa da aka ɗauka daga mutumin ta hanyar azabtarwa ba za a yarda da ita a matsayin shaida a kowane shari'a ba.",
            ig: "Nkwupụta ngụzọ ma ọ bụ nkwupụta ọ bụla e nweere n'aka onye site n'ịta ahụhụ adịghị mma dị ka ihe akaebe n'ikpe ọ bụla n'iwu.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 8",
          plainEnglish: {
            en: "A suspect who has been arrested shall be treated humanely and shall not be subjected to any form of torture, cruel, inhuman or degrading treatment.",
            pcm: "Any suspect wey dem don arrest must be treated well and must not be tortured or treated in any cruel or degrading way.",
            yo: "Afurasi ti a mu gbọdọ jẹ ki a ṣe pẹlu rẹ ni ọna ẹda ati pe a ko gbọdọ ṣe ìjìyà rẹ tabi ṣe pẹlu rẹ ni ọna iwa ipá.",
            ha: "Dole a bi da duk wanda aka kama yadda ya dace kuma ba za a azabtar da shi ba ko a yi masa wulakanci a kowane irin hali.",
            ig: "A ga-agwọ onye ọ bụla a jidere n'ụzọ mmadụ na-atọ ụtọ ma anaghị-enweghị ike ịta ya ahụhụ ma ọ bụ omume ọjọọ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "You are held overnight at a police station. Officers slap you and threaten your family to make you confess to a crime you did not commit.",
            pcm: "Dem hold you overnight for police station. Officers slap you and threaten your family to force you confess to crime wey you no do.",
            yo: "A fi ọ pamọ́ ni alẹ ni ibudo ọlọpaa. Awọn ọfẹ ta ọ ati fi ẹbi rẹ lẹru lati mu ọ jẹwọ si ẹṣẹ ti o ko ṣe.",
            ha: "An tsare ka dare a tashar 'yan sanda. Jandaman sun mari ka kuma suka yi wa dangin ka barazana don sa ka ikirari laifin da ba ka aikata ba.",
            ig: "E nọdee gị n'abalị n'ụlọ ọrụ uwe ojii. Ndị ọrụ tụọ gị ihe ma iyi ndị ikwu gị egwu iji manye gị ịnkwupụta mmehie ị emeghị.",
          },
          steps: {
            en: [
              "Do not confess to anything under pressure — any statement made under torture is inadmissible.",
              "As soon as you see a lawyer or family member, tell them exactly what happened and identify the officers involved.",
              "Request to be examined by a medical officer immediately to document your injuries.",
              "Your lawyer can file a complaint and apply to have any coerced statement excluded from evidence.",
              "The officers involved can be prosecuted under the Anti-Torture Act 2017 — sentences of up to 25 years apply.",
            ],
            pcm: [
              "No confess to anything under pressure — any statement wey dem force you give no fit be used in court.",
              "As soon as you see lawyer or family, tell dem exactly wetin happen and mention the officers.",
              "Ask to see doctor immediately so dem can record your injuries.",
              "Your lawyer fit file complaint and ask court to remove the forced statement from evidence.",
              "The officers fit be prosecuted under Anti-Torture Act 2017 — dem fit get up to 25 years for prison.",
            ],
            yo: [
              "Má jẹwọ si ohunkohun labẹ ìpéníjà — alaye eyikeyi ti a ṣe labẹ ìjìyà ko le gba gbà.",
              "Ni kete ti o ba ri agbẹjọro tabi ẹbi, sọ fun wọn ni pato ohun ti o ṣẹlẹ ki o ṣe idanimọ awọn ọfẹ ti o wa ninu rẹ.",
              "Beere lati jẹ ki dokita ṣàyẹwò rẹ lẹsẹkẹsẹ lati ṣe igbasilẹ awọn ọgbẹ rẹ.",
              "Agbẹjọro rẹ le fi ẹjọ ati beere lọwọ ile-ẹjọ lati yọ alaye ti a fi agbara mu rẹ kuro ninu ẹri.",
              "Awọn ọfẹ ti o wa ninu rẹ le jẹ ki a fi ẹsun kan wọn labẹ Ofin Atako Ìjìyà 2017 — ẹwọn titi di ọdun 25 ni owo.",
            ],
            ha: [
              "Kada ka yi ikirari game da kome ƙarƙashin tilastawa — duk wata sanarwa da aka yi ƙarƙashin azabtarwa ba za a yarda da ita ba.",
              "Da zarar ka ga lauya ko ɗan uwa, gaya musu daidai abin da ya faru kuma gano jandaman da ke tattare da shi.",
              "Nemi a bincika ka daga likita nan da nan don rubuta raunanka.",
              "Lauyanka zai iya shigar da kara kuma nemi kotu ta cire sanarwar da aka tilasta daga shaida.",
              "Za a iya gurfanar da jandaman da ke tattare da shi ƙarƙashin Dokar Anti-Torture ta 2017 — daurin kurkuku har shekaru 25 ya shafi wannan.",
            ],
            ig: [
              "Nkwupụtaghị ihe ọ bụla n'okpuru nrụgide — nkwupụta ọ bụla emere n'okpuru ịta ahụhụ adịghị mma n'ụlọ ikpe.",
              "Ozugbo ị hụ ọka iwu ma ọ bụ onye ikwu, gwa ha ihe niile mere n'ụzọ ziri ezi ma kọwaa ndị ọrụ ndị gụnyere n'ya.",
              "Rịọ ka onye ọrụ ahụ lelee gị ozugbo iji deechie ọnya gị.",
              "Ọka iwu gị nwere ike ibuo mkpe ma rịọ ụlọ ikpe ka ewepụ nkwupụta mmanye ahụ n'ihe akaebe.",
              "A nwere ike ịkpe ndị ọrụ ndị gụnyere n'ya n'okpuru Iwu Anti-Torture nke 2017 — ọrụ afọ ruo 25 na-emetụta ihe a.",
            ],
          },
        },
      ],
    },
  ],
};
