import type { Section } from "./types";

export const generalPublic: Section = {
  slug: "general-public",
  title: {
    en: "General Public",
    pcm: "Every Nigerian",
    yo: "Gbogbo Eniyan",
    ha: "Jama'a Gabaɗaya",
    ig: "Ọha na Eze",
  },
  description: {
    en: "Your fundamental rights during police encounters, arrests, detention, and searches — backed by the Nigerian Constitution.",
    pcm: "Your basic rights when police stop you, arrest you, or search your things — according to Nigerian Constitution.",
    yo: "Awọn ẹtọ rẹ nigba ti ọlọpaa ba da ọ duro, mu ọ, tabi ṣàyẹwò ohun ini rẹ.",
    ha: "Haƙƙoƙinka na asali a lokacin da 'yan sanda suka tsai da kai, kama ka, ko bincika kayanki.",
    ig: "Ikike gị bụ nke ndị ọha ya mgbe ndị uwe ojii kwụsịa gị, jidee gị, ma ọ bụ nyochaa ihe nke gị.",
  },
  icon: "Shield",
  color: "bg-primary-50 text-primary-700",
  topics: [
    {
      slug: "right-to-silence",
      title: {
        en: "Right to Remain Silent",
        pcm: "Right to Keep Quiet",
        yo: "Ẹtọ Lati Dakẹ",
        ha: "Haƙƙin Yin Shiru",
        ig: "Ikike Ị Nọ Nè",
      },
      summary: {
        en: "You are not legally required to answer questions that may incriminate you. This right is guaranteed by Section 35 of the 1999 Constitution.",
        pcm: "You no need to answer any question wey fit land you for trouble. Section 35 of Nigeria Constitution cover you.",
        yo: "Ofin ko fi ọ lọwọ lati dahun awọn ibeere ti o le jẹ ki wọn fi ẹsun kan ọ.",
        ha: "Dokar ba ta tilasta ka amsa tambayoyi da zai iya sa ka zama mai laifi.",
        ig: "Iwu anaghị amanye gị ịza ajụjụ ndị nwere ike ibupụta ihe ojọ megide gị.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Ask you questions voluntarily",
          "Inform you that you are being questioned",
          "Record your statement if you choose to give one voluntarily",
        ],
        pcm: [
          "Dem fit ask you question if you agree",
          "Dem fit tell you say dem dey question you",
          "Dem fit write your statement if you want give am",
        ],
        yo: ["Beere lọwọ rẹ awọn ibeere lairotẹlẹ", "Sọ fun ọ pe wọn n beere lọwọ rẹ", "Gbasilẹ alaye rẹ ti o ba fẹ fun un"],
        ha: ["Su maka tambayoyi bisa son rai", "Sanar da kai cewa ana tambaya maka", "Rubuta magana naka idan ka zabi bayarwa"],
        ig: ["Jụọ gị ajụjụ ọ bụrụ na ị kwere", "Gwa gị na ha na-ajụ gị ajụjụ", "Dekọọ nkwupụta gị ọ bụrụ na ị họrọ inye ya"],
      },
      cannotDo: {
        en: [
          "Force you to make a statement",
          "Beat or torture you to extract a confession",
          "Use your silence as proof of guilt",
          "Refuse to let you contact a lawyer before questioning",
        ],
        pcm: [
          "Dem no fit force you give statement",
          "Dem no fit beat you to make you talk",
          "Dem no fit use your silence to say you guilty",
          "Dem no fit stop you from calling lawyer before dem question you",
        ],
        yo: ["Fi agbara mu ọ sọ ohun", "Na ọ tabi fọ ọ lara lati fa ijẹwọ", "Lo idakẹjẹ rẹ gẹgẹbi ẹri ẹbi", "Kọ lati jẹ ki o pe agbẹjọro"],
        ha: ["Tilastar ka bayar da sanarwa", "Duka ko azabtar da kai don ciro ikirari", "Amfani da shiru naka a matsayin hujja", "Hana ka tuntubi lauya"],
        ig: ["Manye gị ịwụpụta nkwupụta", "Tie gị ma ọ bụ ịta gị ahụhụ iji nweta nkwupụta ngụzọ", "Ojiji nnọọ gị dị ka ihe akaebe nke mmehie", "Igbochi gị ịkpọtụrụ ọka iwu"],
      },
      whatToDo: {
        en: [
          "Calmly state: 'I am exercising my right to remain silent.'",
          "Ask clearly: 'Am I free to go? Am I under arrest?'",
          "Request a lawyer before answering any questions",
          "Note the officer's badge number and name if possible",
        ],
        pcm: [
          "Tell dem calmly: 'I dey use my right to keep quiet.'",
          "Ask am: 'I free to go? You don arrest me?'",
          "Ask for lawyer before you answer any question",
          "Try remember the officer badge number and name",
        ],
        yo: ["Sọ ni idakẹjẹ: 'Mo n lo ẹtọ mi lati dakẹ.'", "Beere: 'Ṣe mo le lọ? Ṣe o mu mi?'", "Beere lati ri agbẹjọro", "Ṣe akiyesi nọmba aami ọfẹ rẹ"],
        ha: ["Fada cikin nutsuwa: 'Ina amfani da haƙƙina na yin shiru.'", "Yi tambaya: 'Ina iya tafiya? An kama ni?'", "Nemi lauya kafin amsa tambayoyi", "Lura da lambar ƙaramin badge"],
        ig: ["Kwuo n'ịdị jụụ: 'Ana m iji ikike m ịnọ nè.'", "Jụọ: 'Enwere m ike ịga? A jidere m?'", "Rịọ ọka iwu tupu ị za ajụjụ ọ bụla", "Cheta nọmba badge nke onye ọrụ ahụ"],
      },
      whatNotToDo: {
        en: [
          "Do not argue aggressively or raise your voice",
          "Do not volunteer information beyond what is necessary",
          "Do not sign any statement without reading it and consulting a lawyer",
          "Do not physically resist — comply, then challenge it legally later",
        ],
        pcm: [
          "No fight dem or shout — e go make things worse",
          "No give dem extra information wey dem no ask for",
          "No sign any paper without reading am and talking to lawyer",
          "No try fight dem physically — obey first, fight am for court later",
        ],
        yo: ["Má ja pẹlu wọn ni agbara", "Má fi ẹsun ara rẹ silẹ larọwọto", "Má fowo si iwe eyikeyi laisi kika ati agbẹjọro", "Má dojuko wọn ni ara — tẹle, lẹhinna ja ni ile-ẹjọ"],
        ha: ["Kada ka yi jayayya ko ɗagawa muryarka", "Kada ka ba da bayani fiye da yadda ya kamata", "Kada ka sanya hannu kan duk wata sanarwa ba tare da karantawa ba", "Kada ka tsayas da su jiki — yi biyayya, sannan ka kalubalance daga baya"],
        ig: ["Emekwala esemokwu ma ọ bụ ọtụtụ olu", "Ekwuwanla ihe ndị ọzọ karịa ihe dị mkpa", "Akwadobiahala nkwupụta ọ bụla na-agụghị ya na ọka iwu", "Emegidekwala ha n'ahụ — soro ha, wee luso ha ọgụ n'ụlọ ikpe"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 35(2)",
          plainEnglish: {
            en: "Any person who is arrested or detained shall be informed of the reasons for the arrest or detention within 24 hours.",
            pcm: "Any person wey dem arrest or detain must hear why dem do am within 24 hours.",
            yo: "Ẹnikẹni ti a mu tabi ti a fi pa duro gbọdọ gba alaye fun idi naa laarin wakati 24.",
            ha: "Duk wanda aka kama ko tsare dole a sanar da shi dalilin kama ko tsare a cikin awanni 24.",
            ig: "Onye ọ bụla a jidere ma ọ bụ nọdere n'ogige ga-anọwa ozi maka ihe kpatara ya n'ime awa 24.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 6",
          plainEnglish: {
            en: "A suspect has the right to remain silent and cannot be compelled to give any statement.",
            pcm: "Any suspect get right to keep quiet and nobody fit force am to talk.",
            yo: "Afurasi ni ẹtọ lati dakẹ, ẹnikẹni ko le fi agbara mu u sọ ohun.",
            ha: "Mai zargi yana da haƙƙin yin shiru kuma ba za a iya tilastar da shi ya bayyana ba.",
            ig: "Onye a na-achọ ikpe nwere ikike ịnọ nè, a nweghị onye nwere ike ịmanye ya ikwu ihe.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A police officer stops you on the street and begins asking where you are coming from and what you do for a living.",
            pcm: "One police stop you for road and e dey ask you where you dey come from and wetin you do for work.",
            yo: "Ọlọpaa kan da ọ duro lori ita ati bẹrẹ lati beere ibiti o ti nbo ati ohun ti o ṣe fun igbesi aye.",
            ha: "Jandarm ya tsai da kai a kan hanya ya fara tambayar inda kake zuwa da abin da kake yi.",
            ig: "Onye uwe ojii kwụsịa gị n'ụzọ ma jikwa ịjụ gị ebe i si bia na ihe ị na-arụ ọrụ.",
          },
          steps: {
            en: [
              "Stay calm. Do not panic or run.",
              "Politely ask: 'Good day officer, am I being detained or am I free to go?'",
              "If they say you are free — leave politely.",
              "If detained, say: 'I understand. I would like to exercise my right to remain silent and speak with a lawyer.'",
              "Do not answer questions about your personal life, phone content, or finances.",
              "Note the officer's name, badge number, and location.",
            ],
            pcm: [
              "No panic, no run.",
              "Ask am politely: 'Good day officer, you don detain me or I free to go?'",
              "If dem say you free — leave with respect.",
              "If dem detain you, say: 'I hear. I want to use my right to keep quiet and talk to lawyer.'",
              "No answer question about your personal life, phone, or money.",
              "Try remember officer name, badge number, and where e happen.",
            ],
            yo: [
              "Jẹ ki o balẹ. Má ṣe ẹru tabi sá.",
              "Beere pẹlu ọwọ: 'Ẹkáàárọ̀ ọgagun, ṣe o n fi mi pamọ́ tabi mo le lọ?'",
              "Ti wọn ba sọ pe o le lọ — lọ pẹlu ọwọ.",
              "Ti o ba fi ọ pamọ́, sọ: 'Mo gbọ. Mo fẹ lo ẹtọ mi lati dakẹ ati ba agbẹjọro sọrọ.'",
              "Má dahun awọn ibeere nipa igbesi aye ara ẹni rẹ, foonu, tabi owo.",
              "Ṣe akiyesi orukọ ọfẹ, nọmba aami, ati ipo naa.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka firgita ko gudu.",
              "Yi tambaya da ladabi: 'Rana mai kyau jandarm, ana tsare ni ne ko ina da 'yanci in tafi?'",
              "Idan sun ce ka da 'yanci — ka tafi da ladabi.",
              "Idan an tsare ka, ce: 'Na fahimta. Ina son yin amfani da haƙƙina na yin shiru da magana da lauya.'",
              "Kada ka amsa tambayoyi game da rayuwarka, waya, ko kudi.",
              "Lura da sunan jandarm, lambar badge, da wurin da hakan ya faru.",
            ],
            ig: [
              "Nọrọ n'udo. Atụla egwu ma ọ bụ gbaa ọsọ.",
              "Jụọ ya n'ụzọ ọcha: 'Ehihie ọma oga, a na-enye m mkpọrọ ka o kwesịrị ma ọ bụ enwere m ike ịgaghachi?'",
              "Ọ bụrụ na ha kwuo na ị nwere ike ịga — hapụ ya nke ọma.",
              "Ọ bụrụ na e nọdere gị n'ogige, kwuo: 'Anọwa m. Achọrọ m iji ikike m ịnọ nè wee kwuo n'ọka iwu.'",
              "Azaghị ajụjụ banyere ndụ onwe gị, ekwenti, ma ọ bụ ego.",
              "Cheta aha onye ọrụ ahụ, nọmba badge, na ebe ọ mere.",
            ],
          },
        },
      ],
    },
    {
      slug: "unlawful-arrest",
      title: {
        en: "Right Against Unlawful Arrest",
        pcm: "Right Against Illegal Arrest",
        yo: "Ẹtọ Lodi si Imudani Aifowosi",
        ha: "Haƙƙi Kan Kama Kai Ba Bisa Doka Ba",
        ig: "Ikike Megide Njide Na-ezughị Oke",
      },
      summary: {
        en: "Police cannot arrest you without a warrant or reasonable cause. Section 35 of the Constitution protects you from arbitrary detention.",
        pcm: "Police no fit arrest you without warrant or good reason. Section 35 of Constitution protect you from illegal detention.",
        yo: "Ọlọpaa ko le mu ọ laisi iwe aṣẹ tabi idi ti o tọ. Abala 35 daabo bo ọ.",
        ha: "Yan sanda ba za su iya kama ka ba tare da doka ko dalili mai kyau ba.",
        ig: "Ndị uwe ojii enweghị ike ijide gị na-enweghị iwu ma ọ bụ ezi ihe kpatara.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Arrest you if they witness you committing a crime",
          "Arrest you with a valid warrant signed by a judge",
          "Detain you for questioning for up to 24 hours before charging or releasing you",
          "Use reasonable force if you resist a lawful arrest",
        ],
        pcm: [
          "Dem fit arrest you if dem see you do crime",
          "Dem fit arrest you with valid court warrant",
          "Dem fit hold you for 24 hours before charge or release",
          "Dem fit use force if you resist legal arrest",
        ],
        yo: ["Mu ọ ti wọn ba ri ọ ṣe ẹṣẹ", "Mu ọ pẹlu iwe aṣẹ ti idajọ ti fowo si", "Fi ọ pamọ́ fun wakati 24 ṣaaju idiyele", "Lo agbara ti o ba dojuko imudani ti o tọ"],
        ha: ["Kama ka idan sun gan ka yin laifi", "Kama ka tare da takardar kama daga alkali", "Tsare ka har zuwa awanni 24 kafin tuhumar ko sakin ka", "Yi amfani da ƙarfi mai ma'ana idan ka tsayas da kama bisa doka"],
        ig: ["Jide gị ọ bụrụ na ha hụ gị na-eme ihe ọjọọ", "Jide gị na iwu edeere n'aka ikpe", "Nọdee gị n'ogige ruo awa 24 tupu ha ebulizie gị ma ọ bụ hapụ gị", "Ojiji ike kwesịrị ọ bụrụ na ị melite njide iwu"],
      },
      cannotDo: {
        en: [
          "Arrest you based on your appearance, tattoos, dreadlocks, or style of dress",
          "Arrest you without telling you why",
          "Hold you for more than 24 hours without charging you or taking you to court",
          "Arrest you as a way to extort money",
          "Detain you at night in an unofficial location",
        ],
        pcm: [
          "Dem no fit arrest you because of how you look, tattoo, dreadlocks, or clothes",
          "Dem no fit arrest you without telling you why",
          "Dem no fit hold you more than 24 hours without charging you or taking you court",
          "Dem no fit arrest you just to collect money from you",
          "Dem no fit keep you for night for unofficial place",
        ],
        yo: ["Mu ọ nitori irisi rẹ, tatuu, dreads, tabi aṣọ", "Mu ọ laisi sọ idi fun ọ", "Fi ọ pamọ́ fun ju wakati 24 lọ laisi ẹsun", "Mu ọ lati gba owo rẹ", "Fi ọ pamọ́ ni alẹ ni ibi aiṣẹ"],
        ha: ["Kama ka saboda bayyanarka, zane jiki, dreads, ko tufafi", "Kama ka ba tare da sanar da kai dalilin ba", "Tsare ka fiye da awanni 24 ba tare da tuhuma ba", "Kama ka don neman cin hanci", "Tsare ka daren dare a wuri marasa izini"],
        ig: ["Jide gị n'ihi ọdịdị gị, tatuu, dreads, ma ọ bụ uwe", "Jide gị na-agwa gị ihe kpatara", "Nọdee gị n'ogige ihe karịa awa 24 na-ebulizie gị", "Jide gị iji nnwere ego gị", "Nọdee gị n'abalị n'ebe na-adịghị n'ọrụ"],
      },
      whatToDo: {
        en: [
          "Ask clearly: 'What am I being arrested for?'",
          "Ask to see the arrest warrant if they claim to have one",
          "Do not physically resist — it can be used against you",
          "Contact a lawyer or relative as soon as possible",
          "If held beyond 24 hours without charge, your lawyer can file for habeas corpus",
        ],
        pcm: [
          "Ask am: 'Why una dey arrest me?'",
          "Ask to see the warrant if dem say dem get am",
          "No fight dem — e fit be used against you later",
          "Call lawyer or family member as soon as you can",
          "If dem hold you pass 24 hours without charge, your lawyer fit file habeas corpus",
        ],
        yo: ["Beere gbangba: 'Kí ni mo ṣe tí ẹ fi n mu mí?'", "Beere lati ri iwe aṣẹ", "Má dojuko wọn ni ara", "Kan si agbẹjọro tabi ẹbi lẹsẹkẹsẹ", "Ti o ba fi ọ pamọ́ ju wakati 24 lọ, agbẹjọro le fi ẹjọ habeas corpus"],
        ha: ["Yi tambaya a sarari: 'Me zan kamawa?'", "Nemi ganin takardar kama", "Kada ka tsayas da su jiki", "Tuntubi lauya ko ɗan uwa da wuri", "Idan aka tsare ka fiye da awanni 24, lauyanka zai iya shigar da kara habeas corpus"],
        ig: ["Jụọ nke ọma: 'Gịnị ka e ji ejide m?'", "Rịọ ka i hụ iwu njide", "Emegidekwala ha n'ahụ", "Kpọtụrụ ọka iwu ma ọ bụ onye ikwu n'oge ọ soonest", "Ọ bụrụ na e nọdee gị n'ogige ihe karịa awa 24, ọka iwu gị nwere ike ibuo habeas corpus"],
      },
      whatNotToDo: {
        en: [
          "Do not run — it can be used as evidence of guilt",
          "Do not bribe officers — it is a crime and weakens your case",
          "Do not sign any document you have not read",
          "Do not insult or threaten officers",
        ],
        pcm: [
          "No run — dem fit use am against you say you guilty",
          "No give officer bribe — na crime and e go weaken your case",
          "No sign any paper you no read",
          "No curse or threaten officer",
        ],
        yo: ["Má sá — wọn le lo o gẹgẹbi ẹri ẹbi", "Má gbọn ọfẹ — ọ jẹ ẹṣẹ ati ó mú ẹjọ rẹ lagbara lagbara", "Má fowo si iwe eyikeyi ti o ko ti ka", "Má bú tabi pa ọfẹ lẹru"],
        ha: ["Kada ka gudu — ana iya amfani da shi a matsayin hujja", "Kada ka yi cin hanci — laifi ne kuma yana raunana karar ka", "Kada ka sanya hannu kan takarda da ba ka karanta ba", "Kada ka zagi ko yi wa jandarm barazana"],
        ig: ["Agbakwala ọsọ — a nwere ike iji ya dị ka ihe akaebe nke mmehie", "Atụkwasịla ego n'aka ndị ọrụ — ọ bụ mmehie ma ọ dị ka ntụgharị nke ikpe gị", "Akwadobiahala akwụkwọ ọ bụla ọ bụrụ na ọ naghị agụ ya", "Atụkwasịla iyi ma ọ bụ iyi egwu ndị ọrụ"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 35(1)",
          plainEnglish: {
            en: "Every person shall be entitled to his personal liberty and no person shall be deprived of such liberty except in cases prescribed by law.",
            pcm: "Every person get right to their freedom and nobody fit take that freedom except the law say so.",
            yo: "Gbogbo eniyan ni ẹtọ si ominira ti ara ẹni ati pe ẹnikẹni ko gbọdọ gba ominira na kuro ayafi ti ofin ba gba laaye.",
            ha: "Kowane mutum yana da haƙƙin yana da 'yancin kai kuma babu wanda za a hana 'yancin sa sai dai yadda doka ta tanada.",
            ig: "Onye ọ bụla nwere ikike na onwe ya, onye ọ bụla enweghị ike ibochie ya n'ike ahụ ma ọ dịghị n'ụzọ iwu kwetara.",
          },
        },
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 9",
          plainEnglish: {
            en: "A police officer may arrest a person without a warrant if the person commits a felony in his presence, or if he reasonably suspects the person of having committed a felony.",
            pcm: "Police fit arrest person without warrant if dem see the person do serious crime, or if dem get good reason to believe the person do am.",
            yo: "Ọlọpaa le mu eniyan laisi iwe aṣẹ ti eniyan na ba ẹṣẹ nla ṣe ni iwaju rẹ, tabi ti o ba ni idi to dara lati fura si.",
            ha: "Jandarm na iya kama mutum ba tare da takardar kama ba idan mutumin ya aikata babban laifi a gabansa, ko idan yana da dalili mai kyau na zargi.",
            ig: "Onye uwe ojii nwere ike ijide onye na-enweghị iwu ọ bụrụ na onye ahụ na-emegbu iwu n'ihu ya, ma ọ bụ ọ nwere ezi ihe kpatara ijidere ya.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Police stop you near your house and say you 'look suspicious.' They want to take you to the station.",
            pcm: "Police stop you near your house say you 'look suspicious.' Dem wan carry you go station.",
            yo: "Ọlọpaa da ọ duro nitosi ile rẹ wí pé o 'dabi ẹni ifura.' Wọn fẹ mu ọ lọ si ibudo.",
            ha: "Yan sanda sun tsai da kai kusa da gidanka cewa kana 'kamar mai zargi.' Suna son kai ka tashar.",
            ig: "Ndị uwe ojii kwụsịa gị n'akụkụ ụlọ gị wee kwuo na ị 'dị ka onye a na-eche anya ya.' Ha chọọ ịkpọ gị ụlọ ọrụ.",
          },
          steps: {
            en: [
              "Stay calm. Do not run or raise your voice.",
              "Ask politely: 'Officer, what crime am I suspected of committing?'",
              "'Looking suspicious' is not a crime. You cannot be arrested for it.",
              "If they insist, say: 'I am being arrested for looking suspicious? Please give me the warrant or inform me of the specific crime.'",
              "If taken to the station, immediately ask to call a lawyer or family member.",
              "Document everything: time, location, officer's name and badge number.",
            ],
            pcm: [
              "No panic, no run, no shout.",
              "Ask am: 'Officer, which crime you say I commit?'",
              "'Looking suspicious' na nothing — e no be crime.",
              "If dem insist, tell dem: 'You dey arrest me because I look suspicious? Show me warrant or tell me the crime.'",
              "If dem carry you go station, ask immediately to call lawyer or family.",
              "Write everything down: time, place, officer name and badge number.",
            ],
            yo: ["Jẹ ki o balẹ. Má sá tabi ṣe ariwo.", "Beere pẹlu ọwọ: 'Ọgagun, ẹṣẹ wo ni mo ṣe?'", "'Dabi ẹni ifura' kii ṣe ẹṣẹ. Won ko le mu ọ fun idi yii.", "Ti wọn ba tẹnumọ, sọ: 'Mo n mu mi duro nitori mo dabi ẹni ifura? Jọwọ fihan mi iwe aṣẹ.'", "Ti wọn ba mu ọ lọ, beere lẹsẹkẹsẹ lati pe agbẹjọro tabi ẹbi.", "Ṣe akiyesi ohun gbogbo: akoko, ipo, orukọ ọfẹ ati nọmba."],
            ha: ["Kasance a nutsuwa. Kada ka gudu ko ɗaga muryarka.", "Yi tambaya da ladabi: 'Jandarm, wane laifi ake zargin nan?'", "'Kamar mai zargi' ba laifi bane. Ba za a iya kama ka saboda haka ba.", "Idan sun dage, ce: 'Ana kamana saboda ina kamar mai zargi? Don Allah nuna min takardar kama ko fada min laifin.'", "Idan aka kai ka tashar, nan da nan nemi kiran lauya ko ɗan uwa.", "Rubuta komai: lokaci, wuri, sunan jandarm da lambar badge."],
            ig: ["Nọrọ n'udo. Agbakwala ọsọ ma ọ bụ ọtụtụ olu.", "Jụọ ya n'ụzọ ọcha: 'Oga, ihe ọjọọ gịnị ka a na-eche na m mere?'", "'Dị ka onye a na-eche anya ya' abụghị ihe ọjọọ. A nweghị ike ijide gị n'ihi ya.", "Ọ bụrụ na ha arọba, kwuo: 'A na-ejide m n'ihi na m dị ka onye a na-eche anya ya? Biko nye m iwu ma ọ bụ gwa m ihe ọjọọ ọ bụ.'", "Ọ bụrụ na ha kpọ gị ụlọ ọrụ, ozugbo rịọ ka i kpọọ ọka iwu ma ọ bụ onye ikwu.", "Deechie ihe niile: oge, ebe, aha onye ọrụ na nọmba badge."],
          },
        },
      ],
    },
    {
      slug: "right-to-bail",
      title: {
        en: "Right to Bail",
        pcm: "Right to Get Bail",
        yo: "Ẹtọ si Ìdásílẹ̀",
        ha: "Haƙƙin Beli",
        ig: "Ikike Nweta Bọọlụ",
      },
      summary: {
        en: "For most offences, you have a right to bail. Police cannot hold you indefinitely without charge. Bail is not for sale — paying for bail is illegal.",
        pcm: "For most offences, you get right to bail. Police no fit hold you forever without charge. Bail no be for sale — paying for bail na crime.",
        yo: "Fun ọpọlọpọ awọn ẹṣẹ, o ni ẹtọ si ìdásílẹ̀. Ọlọpaa ko le fi ọ pamọ́ lailai laisi ẹsun. Ìdásílẹ̀ kii ta — sisanwo fun ìdásílẹ̀ jẹ ẹṣẹ.",
        ha: "Don yawancin laifuka, kana da haƙƙin beli. Yan sanda ba za su iya tsare ka har abada ba tare da tuhuma ba. Beli ba ya sayarwa.",
        ig: "Maka ọtụtụ mmehie, ị nwere ikike nweta bọọlụ. Ndị uwe ojii enweghị ike ijidegide gị na-ebulizie gị. Bọọlụ abụghị ihe ere — ịkwụ ụgwọ maka bọọlụ bụ mmehie.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Refuse bail for capital offences (murder, treason, armed robbery)",
          "Set bail conditions and amounts",
          "Require a surety (guarantor) for bail",
          "Revoke bail if conditions are violated",
        ],
        pcm: ["Refuse bail for serious offence like murder or armed robbery", "Set bail amount and conditions", "Ask for surety (guarantor) before giving bail", "Cancel bail if you violate the conditions"],
        yo: ["Kọ ìdásílẹ̀ fun awọn ẹṣẹ pataki (ipaniyan, ọlọ́ọ̀tà)", "Ṣeto awọn ipo ati iye ìdásílẹ̀", "Beere fun ẹni iṣeduro", "Fagile ìdásílẹ̀ ti awọn ipo ba fọ"],
        ha: ["Ƙi beli ga laifuka masu nauyi (kisa, cin amanar kasa, fashi da makami)", "Tsara yanayin da adadin beli", "Buƙatar mai ba da tabbaci", "Soke beli idan an karya yanayin"],
        ig: ["Jụ bọọlụ maka nnukwu mmehie (igbu mmadụ, armed robbery)", "Tọọ ọnụahịa na ọnọdụ bọọlụ", "Chọọ onye nkwado", "Kagbuo bọọlụ ọ bụrụ na ọnọdụ ahụ e mebiiri"],
      },
      cannotDo: {
        en: [
          "Demand money in exchange for bail at a police station",
          "Hold you beyond 24 hours without charging you or granting bail",
          "Refuse bail for bailable offences",
          "Demand personal gifts or bribes as conditions for release",
        ],
        pcm: ["Collect money from you to give you bail for station", "Hold you pass 24 hours without charge or bail", "Refuse bail for offences wey deserve bail", "Ask for gifts or bribe before dem release you"],
        yo: ["Beere owo fun ìdásílẹ̀ ni ibudo ọlọpaa", "Fi ọ pamọ́ ju wakati 24 lọ laisi ẹsun tabi ìdásílẹ̀", "Kọ ìdásílẹ̀ fun awọn ẹṣẹ ti o yẹ fun ìdásílẹ̀", "Beere awọn ẹbun tabi ẹbọ bi ipo ìdásílẹ̀"],
        ha: ["Nemi kuɗi don beli a tashar 'yan sanda", "Tsare ka fiye da awanni 24 ba tare da tuhuma ko beli ba", "Ƙi beli ga laifuka masu cancanta", "Nemi kyaututtuka ko cin hanci don sake ka"],
        ig: ["Rịọ ego maka bọọlụ n'ụlọ ọrụ uwe ojii", "Nọdee gị n'ogige ihe karịa awa 24 na-ebulizie gị ma ọ bụ enye gị bọọlụ", "Jụ bọọlụ maka mmehie ndị kwesịrị bọọlụ", "Rịọ onyinye ma ọ bụ ego iji tọhapụ gị"],
      },
      whatToDo: {
        en: [
          "Clearly request bail: 'I am requesting bail as is my legal right.'",
          "Ask for the bail amount in writing",
          "Have a family member or lawyer come to the station",
          "If bail is denied improperly, your lawyer can apply to court for bail",
          "If asked to pay for bail informally, refuse and report it",
        ],
        pcm: ["Ask for bail clearly: 'I dey request bail, na my legal right.'", "Ask make dem write the bail amount for paper", "Make family or lawyer come to station", "If dem deny bail without good reason, your lawyer fit go court for bail", "If dem ask you to pay for bail under the table, refuse and report am"],
        yo: ["Beere ìdásílẹ̀ gbangba: 'Mo n beere ìdásílẹ̀ gẹgẹbi ẹtọ mi ti ofin.'", "Beere lati gba iye ìdásílẹ̀ ni kikọ", "Jẹ ki ẹbi tabi agbẹjọro wa si ibudo", "Ti a ba kọ ìdásílẹ̀ laisi idi to dara, agbẹjọro le lo si ile-ẹjọ", "Ti wọn ba beere owo ni aṣiri, kọ ati ròyìn rẹ"],
        ha: ["Nemi beli a sarari: 'Ina neman beli kamar yadda haƙƙina na doka yake.'", "Nemi adadin beli a rubuce", "Sa ɗan uwa ko lauya ya zo tashar", "Idan aka ki beli ba bisa ƙa'ida ba, lauyanka zai iya neman beli a kotu", "Idan aka nemi ka biya beli a boyaye, ƙi kuma kai ƙara"],
        ig: ["Rịọ bọọlụ nke ọma: 'Ana m arịọ bọọlụ dị ka ikike m n'iwu.'", "Rịọ ka e dee ọnụahịa bọọlụ n'akwụkwọ", "Mee ka onye ikwu ma ọ bụ ọka iwu bia ụlọ ọrụ", "Ọ bụrụ na e jụ bọọlụ n'ụzọ na-ezighị ezi, ọka iwu gị nwere ike ịga n'ụlọ ikpe maka bọọlụ", "Ọ bụrụ na ha rịọ ka ị kwụọ ụgwọ maka bọọlụ n'ụzọ nzuzo, jụ ma ọ bụ kọọ ya"],
      },
      whatNotToDo: {
        en: [
          "Do not pay unofficial bail fees — it is bribery and a crime",
          "Do not leave without written documentation of your release",
          "Do not fail to report for court dates after bail",
          "Do not skip bail — a warrant will be issued for your arrest",
        ],
        pcm: ["No pay unofficial bail money — na bribery and crime", "No leave station without paper wey show your release", "No miss your court date after bail", "No skip bail — dem go issue warrant for your arrest"],
        yo: ["Má san owo ìdásílẹ̀ ti kii ṣe alaye — o jẹ ẹṣẹ", "Má lọ laisi iwe ikede ti ìdásílẹ̀ rẹ", "Má padanu ọjọ ile-ẹjọ lẹhin ìdásílẹ̀", "Má salọ ìdásílẹ̀ — wọn yoo gba iwe aṣẹ imudani fun ọ"],
        ha: ["Kada ka biya kuɗin beli marasa izini — cin hanci ne kuma laifi ne", "Kada ka tafi ba tare da takardar sakin ka ba", "Kada ka rasa kwanan kotu bayan beli", "Kada ka gudu daga beli — za a ba da takardar kama ka"],
        ig: ["Akwụkwala ụgwọ bọọlụ n'ụzọ ziri ezi — ọ bụ ọtụtụ achịcha na mmehie", "Agakwala na-enweghị akwụkwọ nke ntọhapụ gị", "Egosighị ụbọchị ụlọ ikpe ka bọọlụ gasie", "Agbakwala ọsọ bọọlụ — a ga-ede iwu maka njide gị"],
      },
      laws: [
        {
          name: "Administration of Criminal Justice Act (ACJA) 2015",
          section: "Section 17",
          plainEnglish: {
            en: "A suspect shall be entitled to bail if held for more than 24 hours without being charged to court.",
            pcm: "Any suspect wey dem hold for more than 24 hours without charge get right to bail.",
            yo: "Afurasi ni ẹtọ si ìdásílẹ̀ ti o ba fi pamọ́ ju wakati 24 lọ laisi ẹsun si ile-ẹjọ.",
            ha: "Mai zargi na da haƙƙin beli idan aka tsare shi fiye da awanni 24 ba tare da kai shi kotu ba.",
            ig: "Onye a na-achọ ikpe nwere ikike nweta bọọlụ ọ bụrụ na e nọdee ya n'ogige ihe karịa awa 24 na-akpọghị ya n'ụlọ ikpe.",
          },
        },
      ],
      scenarios: [],
    },
  ],
};
