import type { Section } from "./types";

export const tenants: Section = {
  slug: "tenants",
  title: {
    en: "Tenants & Landlords",
    pcm: "Tenants & Landlords",
    yo: "Awọn Agbatọ & Awọn Onile",
    ha: "Masu Haya & Ma'abocin Gida",
    ig: "Ndị Dị N'ụlọ Mgbazinye & Ndị Nwe Ụlọ",
  },
  description: {
    en: "Your rights as a tenant against illegal eviction, improper quit notices, and unlawful entry — and what landlords can and cannot legally do.",
    pcm: "Your rights as tenant against illegal eviction, improper quit notice, and unlawful entry — and wetin landlord fit and no fit do by law.",
    yo: "Awọn ẹtọ rẹ gẹgẹbi agbatọ lodi si ilepadanu aitọ, akiyesi ifi silẹ aibojumu, ati wọle aitọ — ati ohun ti onile le ati ko le ṣe ni ofin.",
    ha: "Haƙƙoƙinka a matsayin mai haya kan kora ba bisa ƙa'ida ba, sanarwar ƙaura ba daidai ba, da shiga ba bisa doka ba — da abin da mai gida zai iya da ba zai iya yi ba a bisa doka.",
    ig: "Ikike gị dị ka onye dị n'ụlọ mgbazinye megide ịchụpụ n'ụzọ na-ezighị ezi, ọkwa ịpụ na-ezighị ezi, na ọbanye na-ezighị ezi — na ihe onye nwe ụlọ nwere ike na enweghị ike ime n'iwu.",
  },
  icon: "Home",
  color: "bg-teal-50 text-teal-700",
  topics: [
    {
      slug: "illegal-eviction",
      title: {
        en: "Illegal Eviction — Know Your Rights",
        pcm: "Illegal Eviction — Know Your Rights",
        yo: "Ilepadanu Aitọ — Mọ Awọn Ẹtọ Rẹ",
        ha: "Korar Ba Bisa Ƙa'ida — Sani Haƙƙoƙinka",
        ig: "Ịchụpụ N'ụzọ Na-ezighị Ezi — Mara Ikike Gị",
      },
      summary: {
        en: "A landlord cannot evict you without a valid court order, regardless of rent disputes. Self-help evictions — changing locks, removing your belongings, cutting utilities — are illegal.",
        pcm: "Landlord no fit evict you without valid court order, no matter the rent dispute. Changing locks, removing your things, cutting light or water — na illegal.",
        yo: "Onile ko le le ọ kuro laisi aṣẹ ile-ẹjọ to wulo, laibikita awọn ariyanjiyan iyasilẹ. Iyipada awọn titiipa, yiyọ awọn ohun ini rẹ, gige awọn iṣẹ — jẹ aitọ.",
        ha: "Mai gida ba zai iya kore ka ba tare da ingantaccen umurnin kotu ba, ko da rigimar haya. Canza kulle-kulle, cire kayanka, yanke ruwa ko wuta — ba doka ba ne.",
        ig: "Onye nwe ụlọ enweghị ike ịchụpụ gị na-enweghị iwu ụlọ ikpe dị mma, n'agbanyeghị esemokwu mgbazinye. Ịgbanwe mkpọchi, iwepụ ihe nke gị, ịkpọcha ọrụ — ọ bụghị iwu.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Issue a valid quit notice as required by law",
          "Apply to court for a possession order after the notice period",
          "Enter the property with your consent for repairs or inspection",
          "Increase rent with proper notice as allowed by state law",
        ],
        pcm: ["Issue valid quit notice as law requires", "Apply to court for possession order after notice period", "Enter the property with your consent for repairs or inspection", "Increase rent with proper notice as state law allows"],
        yo: ["Fun akiyesi ifi silẹ to wulo bi ofin ti nilo", "Beere si ile-ẹjọ fun aṣẹ ohun ini lẹhin akoko akiyesi", "Wọ ile pẹlu igbanilaaye rẹ fun atunṣe tabi ayẹwo", "Gbe iyasilẹ pẹlu akiyesi to dara bi ofin ipinle ti gba laaye"],
        ha: ["Ba da ingantacciyar sanarwar ƙaura kamar yadda doka ta bukata", "Nemi umurnin mallaka a kotu bayan lokacin sanarwar", "Shiga gidan tare da izininka don gyara ko bincike", "Ƙara haya tare da sanarwa mai kyau kamar yadda dokar jiha ta yarda"],
        ig: ["Nye ọkwa ịpụ dị mma dị ka iwu chọrọ", "Rịọ n'ụlọ ikpe maka iwu ihe onwe onwe ka oge ọkwa gasie", "Banye n'ụlọ na ikike gị maka mgbazi ma ọ bụ nyochaa", "Bụlite mgbazinye na ọkwa kwesịrị dị ka iwu steeti kwere"],
      },
      cannotDo: {
        en: [
          "Evict you without a court order",
          "Change locks while you are still a tenant",
          "Remove your belongings from the property",
          "Cut off water, electricity, or other utilities to force you out",
          "Enter your home without prior notice or your consent",
          "Harass or intimidate you to force you to leave",
        ],
        pcm: ["Evict you without court order", "Change locks while you still dey there as tenant", "Remove your belongings from the property", "Cut off water, light, or other utilities to force you out", "Enter your house without prior notice or your consent", "Harass or intimidate you to force you leave"],
        yo: ["Le ọ kuro laisi aṣẹ ile-ẹjọ", "Yipada awọn titiipa lakoko ti o ṣi jẹ agbatọ", "Yọ ohun ini rẹ kuro ni ile", "Ge omi, ina, tabi awọn iṣẹ miiran lati fi ọ ni ipa", "Wọ ile rẹ laisi akiyesi iṣaju tabi igbanilaaye rẹ", "Wọ tabi ṣe ìdọjútì mọ ọ lati fi ọ ni ipa lati lọ"],
        ha: ["Kore ka ba tare da umurnin kotu ba", "Canza kulle-kulle a lokacin da kake kan haya", "Cire kayanka daga gidan", "Yanke ruwa, wuta, ko sauran ayyuka don tilasta ka fita", "Shiga gidanka ba tare da sanarwa ko izinka ba", "Yi wa kai damunawa ko tsoratarwa don tilasta ka tafi"],
        ig: ["Chụpụ gị na-enweghị iwu ụlọ ikpe", "Gbanwee mkpọchi ị ka dị n'ụlọ dị ka onye mgbazinye", "Wepu ihe nke gị n'ụlọ", "Kpọcha mmiri, ọkụ, ma ọ bụ ọrụ ndị ọzọ iji manye gị pụọ", "Banye n'ụlọ gị na-enyekwala ọkwa ma ọ bụ ikike gị", "Iyi egwu ma ọ bụ atụọ gị egwu iji manye gị ịpụ"],
      },
      whatToDo: {
        en: [
          "If served a quit notice, do not immediately vacate — verify it is lawfully issued",
          "A monthly tenant typically requires one month's notice; an annual tenant requires six months",
          "If you refuse to leave after a valid notice, the landlord must go to court",
          "If locks are changed or utilities cut, contact a lawyer immediately",
          "Document everything — photos, messages, the notice itself",
          "Apply to court for an injunction if eviction is imminent and unlawful",
        ],
        pcm: ["If dem serve you quit notice, no rush to leave — verify am first", "Monthly tenant need one month notice; annual tenant need six months", "If you refuse to leave after valid notice, landlord must go court", "If dem change locks or cut utilities, call lawyer immediately", "Document everything — photos, messages, the notice", "Apply to court for injunction if illegal eviction is coming"],
        yo: ["Ti a ba fi akiyesi ifi silẹ fun ọ, má yara lọ — ṣe idaniloju pe o wulo", "Agbatọ oṣu mọkankan nilo akiyesi oṣu kan; agbatọ ọdọọdun nilo oṣu mẹfa", "Ti o ba kọ lati lọ lẹhin akiyesi to wulo, onile gbọdọ lọ si ile-ẹjọ", "Ti a ba yipada awọn titiipa tabi ge awọn iṣẹ, kan si agbẹjọro lẹsẹkẹsẹ", "Gba akọsilẹ ohun gbogbo — awọn aworan, awọn ifiranṣẹ, akiyesi naa", "Beere si ile-ẹjọ fun ilana ti ilepadanu aitọ ba sunmọ"],
        ha: ["Idan aka ba ka sanarwar ƙaura, kada ka yi gaggawa ka tafi — tabbatar da daidaituwarta", "Mai hayan wata guda yana buƙatar sanarwa ta wata guda; mai hayan shekara yana buƙatar watanni shida", "Idan ka ƙi tafiya bayan ingantacciyar sanarwa, mai gida dole ya je kotu", "Idan aka canza kulle-kulle ko yanke ayyuka, tuntubi lauya nan da nan", "Rubuta komai — hotuna, saƙonni, sanarwar kanta", "Nemi kotun ta ba da hani idan kora ba bisa ƙa'ida ba ta kusanto"],
        ig: ["Ọ bụrụ na e nyere gị ọkwa ịpụ, ghakwala n'oge — nwaa ma ọ dị mma n'iwu", "Onye mgbazinye ọnwa chọọ ọkwa ọnwa otu; onye mgbazinye afọ chọọ ọnwa isii", "Ọ bụrụ na ị jụ ịpụ ka ọkwa dị mma gasie, onye nwe ụlọ kwesịrị ịga n'ụlọ ikpe", "Ọ bụrụ na ha gbanwee mkpọchi ma ọ bụ kpọcha ọrụ, kpọtụrụ ọka iwu n'ozuzu", "Deechie ihe niile — foto, ozi, ọkwa ahụ", "Rịọ n'ụlọ ikpe maka ihe igbochi ọ bụrụ na ịchụpụ na-ezighị ezi dị nso"],
      },
      whatNotToDo: {
        en: [
          "Do not ignore a valid quit notice — respond in writing and seek legal advice",
          "Do not destroy or damage the property",
          "Do not withhold rent as leverage — this weakens your legal position",
          "Do not allow a landlord to intimidate you into leaving without a court order",
        ],
        pcm: ["No ignore valid quit notice — respond in writing and get legal advice", "No destroy or damage the property", "No withhold rent as leverage — e go weaken your legal position", "No allow landlord to intimidate you into leaving without court order"],
        yo: ["Má fojufori akiyesi ifi silẹ to wulo — dahun ni kikọ ati wa imọran ofin", "Má run tabi ba ile jẹ", "Má dẹ iyasilẹ bi ohun ti a le lo — yoo jẹ ki ipo ofin rẹ lagbara lagbara", "Má jẹ ki onile ṣe ìdọjútì mọ ọ lati lọ laisi aṣẹ ile-ẹjọ"],
        ha: ["Kada ka yi watsi da ingantacciyar sanarwar ƙaura — amsa a rubuce kuma nemi shawara ta doka", "Kada ka halaka ko lalata gidan", "Kada ka riƙe haya a matsayin matsin lamba — yana raunana matsayinka na doka", "Kada ka bar mai gida ya tsorata ka ya kore ka ba tare da umurnin kotu ba"],
        ig: ["Anakwụkwala ọkwa ịpụ dị mma — zaghachi n'ihe ede ede ma chọọ ndụmọdụ iwu", "Emebiakwala ụlọ ahụ", "Echekwakwala mgbazinye dị ka ihe mmebe — ọ ga-adịghị mma ọnọdụ iwu gị", "Ikwekwala onye nwe ụlọ ịtụọ gị egwu ka ị pụọ na-enweghị iwu ụlọ ikpe"],
      },
      laws: [
        {
          name: "Recovery of Premises Act (and State Tenancy Laws)",
          section: "Section 2 & 7",
          plainEnglish: {
            en: "A landlord must serve a valid notice to quit before applying to court for possession. For monthly tenants, the notice is one month; for yearly tenants, it is six months.",
            pcm: "Landlord must give valid quit notice before going court for possession. Monthly tenant: one month notice. Yearly tenant: six months notice.",
            yo: "Onile gbọdọ fun akiyesi ifi silẹ to wulo ṣaaju ki o to beere si ile-ẹjọ fun ohun ini. Fun awọn agbatọ oṣu kan: oṣu kan; fun awọn agbatọ ọdọọdun: oṣu mẹfa.",
            ha: "Mai gida dole ya ba da ingantacciyar sanarwar ƙaura kafin ya nemi kotu don mallaka. Ga mai hayan wata guda: wata guda; ga mai hayan shekara: watanni shida.",
            ig: "Onye nwe ụlọ kwesịrị inye ọkwa ịpụ dị mma tupu ịrịọ n'ụlọ ikpe maka ihe onwe onwe. Onye mgbazinye ọnwa: ọnwa otu; onye mgbazinye afọ: ọnwa isii.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "quit-notice",
      title: {
        en: "Quit Notice — Requirements and Your Rights",
        pcm: "Quit Notice — Requirements and Your Rights",
        yo: "Akiyesi Ifi Silẹ — Awọn Ibeere ati Awọn Ẹtọ Rẹ",
        ha: "Sanarwar Ƙaura — Buƙatoci da Haƙƙoƙinka",
        ig: "Ọkwa Ịpụ — Ihe A Chọrọ na Ikike Gị",
      },
      summary: {
        en: "The law requires different notice periods depending on your tenancy type: weekly tenants get 1 week, monthly tenants get 1 month, and yearly tenants get 6 months. A quit notice must be in writing, state the reason, and be properly served. Even after a notice expires, a landlord cannot forcibly remove you — they must obtain a court order.",
        pcm: "Law dey require different notice period depending on your type of tenancy: weekly tenant get 1 week, monthly tenant get 1 month, yearly tenant get 6 months. Quit notice must dey in writing, state reason, and dem must serve am properly. Even if notice don expire, landlord no fit forcibly remove you — dem must get court order.",
        yo: "Ofin nilo awọn akoko akiyesi oriṣiriṣi ti o da lori iru agbatọ rẹ: agbatọ ọsẹ gba ọsẹ kan, agbatọ oṣu gba oṣu kan, agbatọ ọdọọdun gba oṣu mẹfa. Akiyesi ifi silẹ gbọdọ wa ni kikọ, sọ idi naa, a si gbọdọ firanṣẹ rẹ ni ọna to tọ. Paapaa lẹhin ti akiyesi ba pari, onile ko le yọ ọ ni ipa — o gbọdọ gba aṣẹ ile-ẹjọ.",
        ha: "Doka tana buƙatar lokutan sanarwa daban-daban dangane da nau'in hayarka: mai hayan mako yana samun mako 1, mai hayan wata yana samun wata 1, mai hayan shekara yana samun watanni 6. Sanarwar ƙaura dole ta kasance a rubuce, ta bayyana dalilin, kuma a ba da ita yadda ya kamata. Ko bayan sanarwar ta ƙare, mai gida ba zai iya cire ka da ƙarfi ba — dole ya sami umurnin kotu.",
        ig: "Iwu chọọ oge ọkwa dị iche iche dabere na ụdị mgbazinye gị: onye mgbazinye izu nwere izu 1, onye mgbazinye ọnwa nwere ọnwa 1, onye mgbazinye afọ nwere ọnwa 6. Ọkwa ịpụ kwesịrị ịdị n'ihe ede ede, kwuo ihe kpatara ya, ma e nyekwara ya n'ụzọ kwesịrị. Ọbụna mgbe ọkwa ahụ gasie, onye nwe ụlọ enweghị ike ịpụpụta gị n'ike — ha kwesịrị nweta iwu ụlọ ikpe.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Serve a written quit notice stating a clear reason for requiring you to leave",
          "Give 1 week's notice to a weekly tenant, 1 month's notice to a monthly tenant, or 6 months' notice to a yearly tenant",
          "Apply to court for a possession order once the notice period has expired and you have not vacated",
          "Negotiate an earlier vacation date with you if both parties agree",
        ],
        pcm: [
          "Serve written quit notice wey clearly state reason why dem want you leave",
          "Give 1 week notice to weekly tenant, 1 month notice to monthly tenant, or 6 months notice to yearly tenant",
          "Apply to court for possession order once notice period don expire and you never leave",
          "Negotiate earlier vacation date with you if both of una agree",
        ],
        yo: [
          "Fi akiyesi ifi silẹ kikọ ti o sọ idi to han fun beere ki o lọ",
          "Fun akiyesi ọsẹ kan fun agbatọ ọsẹ, oṣu kan fun agbatọ oṣu, tabi oṣu mẹfa fun agbatọ ọdọọdun",
          "Beere si ile-ẹjọ fun aṣẹ ohun ini ni kete ti akoko akiyesi ti pari ti o ko ba ti kuro",
          "Gba adehun ọjọ ifisilẹ tete pẹlu rẹ ti awọn ẹgbẹ mejeeji ba gba",
        ],
        ha: [
          "Ba da sanarwar ƙaura ta rubuce wacce ke bayyana dalilin da ya sa ake son ka tafi",
          "Ba da sanarwa ta mako guda ga mai hayan mako, wata guda ga mai hayan wata, ko watanni 6 ga mai hayan shekara",
          "Nemi kotu don umurnin mallaka da zarar lokacin sanarwa ya ƙare kuma ba ka bar ba",
          "Tattauna ranar ficewa da wuri tare da kai idan bangarorin biyu sun yarda",
        ],
        ig: [
          "Nye ọkwa ịpụ edere n'ihe ede ede na-ekwu ihe kpatara ịchọ ka ị pụọ",
          "Nye onye mgbazinye izu ọkwa izu otu, onye mgbazinye ọnwa ọkwa ọnwa otu, ma ọ bụ onye mgbazinye afọ ọkwa ọnwa isii",
          "Rịọ n'ụlọ ikpe maka iwu ihe onwe onwe ozugbo oge ọkwa ahụ gasie ma ị hapụbeghị",
          "Kwenye na oge ịpụ ya n'oge n'oge ọ bụrụ na ụzọ abụọ kwere",
        ],
      },
      cannotDo: {
        en: [
          "Serve an oral (verbal) quit notice — it must always be in writing",
          "Give less than the legally required notice period for your tenancy type",
          "Forcibly remove you or your belongings once the notice expires — only a court can order that",
          "Serve a quit notice as retaliation for you exercising your legal rights (e.g., reporting disrepair)",
          "Use an agent or third party to harass you after serving a notice",
        ],
        pcm: [
          "Serve quit notice by mouth — e must always dey in writing",
          "Give less than the required notice period for your type of tenancy",
          "Forcibly remove you or your things once notice don expire — only court fit order that",
          "Serve quit notice because you report bad condition of house or exercise your rights",
          "Use agent or third party to harass you after serving notice",
        ],
        yo: [
          "Fi akiyesi ifi silẹ ẹnu (ọrọ) — gbọdọ wa ni kikọ nigbagbogbo",
          "Fun akoko akiyesi ti o kere ju ti ofin nilo fun iru agbatọ rẹ",
          "Yọ ọ tabi ohun ini rẹ ni ipa nigbati akiyesi ba pari — ile-ẹjọ nikan le paṣẹ bẹ",
          "Fi akiyesi ifi silẹ gẹgẹbi igbẹsan fun lilo awọn ẹtọ ofin rẹ",
          "Lo aṣoju tabi ẹni kẹta lati ṣe ipọnju mọ ọ lẹhin fifi akiyesi",
        ],
        ha: [
          "Ba da sanarwar ƙaura ta baki — dole ta kasance a rubuce koyaushe",
          "Ba da ƙarancin lokacin sanarwa da doka ta bukata ga nau'in hayarka",
          "Cire ka ko kayanka da ƙarfi da zarar sanarwa ta ƙare — kotu ce kaɗai za ta iya ba da umurnin haka",
          "Ba da sanarwar ƙaura a matsayin ramuwar gayya saboda ka yi amfani da haƙƙoƙinka na doka",
          "Yi amfani da wakilai ko wani mutum na uku don damunawa da kai bayan ba da sanarwa",
        ],
        ig: [
          "Nye ọkwa ịpụ n'ọnụ — ọ kwesịrị ịdị n'ihe ede ede mgbe niile",
          "Nye oge ọkwa pere mpe karịa nke iwu chọrọ maka ụdị mgbazinye gị",
          "Pụpụta gị ma ọ bụ ihe nke gị n'ike ozugbo ọkwa ahụ gasie — ụlọ ikpe naanị nwere ike iwu nke ahụ",
          "Nye ọkwa ịpụ dị ka mgbachi maka iji ikike iwu gị (dị ka ikpesa ọnọdụ ụlọ ọjọọ)",
          "Iji onye nnọchiteanya ma ọ bụ onye ọzọ itọrọ gị isi mgbe ọkwa ewepụtara",
        ],
      },
      whatToDo: {
        en: [
          "When you receive a quit notice, check that it is in writing and states the reason clearly",
          "Verify that the notice period matches your tenancy type — weekly, monthly, or yearly",
          "Respond to the notice in writing, acknowledging receipt and noting any defects in the notice",
          "Seek legal advice promptly if you believe the notice is defective or served in bad faith",
          "If you choose to leave, get written confirmation that all rent obligations have been settled",
        ],
        pcm: [
          "When you receive quit notice, check say e dey in writing and e clearly state reason",
          "Verify say the notice period match your tenancy type — weekly, monthly, or yearly",
          "Reply the notice in writing, acknowledge say you receive am and note any problem with it",
          "Quickly get legal advice if you think the notice get defect or dem serve am in bad faith",
          "If you decide to leave, get written confirmation say all rent matter don settle",
        ],
        yo: [
          "Nigbati o ba gba akiyesi ifi silẹ, ṣayẹwo pe o wa ni kikọ ati sọ idi naa ni kedere",
          "Ṣe idaniloju pe akoko akiyesi ba iru agbatọ rẹ mu — ọsẹ, oṣu, tabi ọdọọdun",
          "Dahun akiyesi naa ni kikọ, jẹrisi gbigba ati ṣe akiyesi eyikeyi aipe ninu akiyesi naa",
          "Wa imọran ofin ni kiakia ti o ba gbagbọ pe akiyesi naa ni aipe tabi a fi ni ẹtan",
          "Ti o ba pinnu lati lọ, gba ijẹrisi kikọ pe a ti gba gbogbo awọn adehun iyasilẹ",
        ],
        ha: [
          "Da zarar ka karɓi sanarwar ƙaura, duba cewa tana a rubuce kuma tana fayyace dalilin a sarari",
          "Tabbatar cewa lokacin sanarwa ya dace da nau'in hayarka — na mako, na wata, ko na shekara",
          "Amsa sanarwar a rubuce, tabbatar karɓuwarta kuma lura da duk wani aibi a cikinta",
          "Nemi shawara ta doka da sauri idan ka yi imanin sanarwar tana da aibi ko an ba da ita da niyyar mugu",
          "Idan ka yanke shawarar tafiya, sami tabbacin rubuce cewa an daidaita duk wajibai na haya",
        ],
        ig: [
          "Mgbe ị natara ọkwa ịpụ, lelee ma ọ dị n'ihe ede ede ma kwuo ihe kpatara ya n'ụzọ doro anya",
          "Nyochaa ma oge ọkwa ahụ dabara na ụdị mgbazinye gị — izu, ọnwa, ma ọ bụ afọ",
          "Zaghachi ọkwa ahụ n'ihe ede ede, kwenye nnatara ya ma deechie ihe ọ bụla na-adịghị mma na ya",
          "Chọọ ndụmọdụ iwu n'oge ọ bụrụ na ị chere na ọkwa ahụ enweghị ike ma ọ bụ e nyere ya n'obi ojoo",
          "Ọ bụrụ na ị họrọ ịpụ, nweta nkwenye edere na ihe niile banyere mgbazinye edoziri",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not vacate immediately upon receiving a quit notice without verifying it is legally valid",
          "Do not ignore a quit notice entirely — this could weaken your position if the matter goes to court",
          "Do not accept a verbal quit notice as sufficient — always insist on written documentation",
          "Do not stop paying rent simply because you received a quit notice — you owe rent until you legally vacate",
        ],
        pcm: [
          "No rush to leave immediately you receive quit notice without checking if e valid by law",
          "No ignore quit notice completely — e fit weaken your position if matter reach court",
          "No accept verbal quit notice as enough — always insist on written document",
          "No stop paying rent just because you receive quit notice — you owe rent until you legally vacate",
        ],
        yo: [
          "Má kuro lẹsẹkẹsẹ lori gbigba akiyesi ifi silẹ laisi ṣiṣayẹwo pe o wulo ni ofin",
          "Má fojufori akiyesi ifi silẹ patapata — eyi le ṣe irẹwẹsi ipo rẹ ti ọrọ ba lọ si ile-ẹjọ",
          "Má gba akiyesi ifi silẹ ẹnu gẹgẹbi to — ma ṣe ibeere akọsilẹ kikọ nigbagbogbo",
          "Má dẹ iyasilẹ nitori o gba akiyesi ifi silẹ — o jẹ iyasilẹ titi ti o fi kuro ni ofin",
        ],
        ha: [
          "Kada ka bar nan da nan bayan karɓar sanarwar ƙaura ba tare da tabbatar cewa tana da inganci a bisa doka ba",
          "Kada ka yi watsi da sanarwar ƙaura gaba ɗaya — hakan na iya raunana matsayinka idan al'amarin ya je kotu",
          "Kada ka karɓi sanarwar ƙaura ta baki a matsayin isasshe — koyaushe ka nace kan takaddun rubuce",
          "Kada ka daina biyan haya kawai saboda ka karɓi sanarwar ƙaura — kana da bashin haya har sai ka fice bisa doka",
        ],
        ig: [
          "Hapụkwala n'oge n'oge ị natara ọkwa ịpụ na-enyochaghị ma ọ dị mma n'iwu",
          "Echefukwala ọkwa ịpụ n'ụzọ niile — nke a nwere ike ịdịghị mma ọnọdụ gị ọ bụrụ na ihe ahụ ga n'ụlọ ikpe",
          "Anabatakwala ọkwa ịpụ n'ọnụ dị ka nke zuru oke — chọọ ihe ede ede mgbe niile",
          "Akwụkwala mgbazinye n'ihi naanị na ị natara ọkwa ịpụ — ị ji mgbazinye rue mgbe ị pụọ n'iwu",
        ],
      },
      laws: [
        {
          name: "Rent Control and Recovery of Residential Premises Law (Lagos State)",
          section: "Sections 4 & 5",
          plainEnglish: {
            en: "A valid quit notice must be in writing, state the grounds for recovery of premises, and observe the correct notice period: 1 week for weekly tenants, 1 month for monthly tenants, and 6 months for yearly tenants. An expired notice does not authorise self-help eviction.",
            pcm: "Valid quit notice must dey in writing, state reason dem want possession, and follow correct notice period: 1 week for weekly tenant, 1 month for monthly tenant, 6 months for yearly tenant. Expired notice no give landlord right to forcibly remove you.",
            yo: "Akiyesi ifi silẹ to wulo gbọdọ wa ni kikọ, sọ idi fun gbigba ohun ini, ati tẹle akoko akiyesi to tọ: ọsẹ kan fun agbatọ ọsẹ, oṣu kan fun agbatọ oṣu, oṣu mẹfa fun agbatọ ọdọọdun. Akiyesi ti o pari ko fun laaye ilepadanu ara-ẹni.",
            ha: "Ingantacciyar sanarwar ƙaura dole ta kasance a rubuce, ta bayyana dalilan dawowar gidan, kuma ta bi lokacin sanarwa mai dacewa: mako 1 ga mai hayan mako, wata 1 ga mai hayan wata, watanni 6 ga mai hayan shekara. Sanarwa da ta ƙare ba ta ba da izini kora da ƙarfi ba.",
            ig: "Ọkwa ịpụ dị mma kwesịrị ịdị n'ihe ede ede, kwuo ihe kpatara ịchọ ihe onwe onwe, ma soro oge ọkwa kwesịrị: izu 1 maka onye mgbazinye izu, ọnwa 1 maka onye mgbazinye ọnwa, ọnwa 6 maka onye mgbazinye afọ. Ọkwa gara aga abịaghị onye nwe ụlọ ikike ịchụpụ n'ike.",
          },
        },
        {
          name: "Recovery of Premises Act (Federal)",
          section: "Section 2",
          plainEnglish: {
            en: "Proceedings for recovery of premises can only commence after a valid notice to quit has been served and the period has expired. The court alone has authority to order a tenant to leave.",
            pcm: "Court proceedings for eviction can only start after valid quit notice don expire. Only court fit order tenant to leave.",
            yo: "Awọn ilana fun gbigba ohun ini le bẹrẹ lẹhin ti akiyesi ifi silẹ to wulo ti a firanṣẹ ati akoko ti pari. Ile-ẹjọ nikan ni agbara lati paṣẹ fun agbatọ lati lọ.",
            ha: "Shari'ar maido da gidan na iya farawa ne kawai bayan an ba da ingantacciyar sanarwar ƙaura kuma lokacin ya ƙare. Kotu ce kaɗai ke da ikon umurtar mai haya ya fita.",
            ig: "Njikwa maka nwetaghachi ihe onwe onwe nwere ike ịmalite naanị mgbe ọkwa ịpụ dị mma nyesịrị gasie. Naanị ụlọ ikpe nwere ike ịnye onye mgbazinye iwu ka ọ pụọ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Your landlord sends a WhatsApp message telling you to leave within two weeks. You are a monthly tenant and have paid rent up to date.",
            pcm: "Your landlord send WhatsApp message tell you say make you comot within two weeks. You be monthly tenant and you don pay rent current.",
            yo: "Onile rẹ fi ifiranṣẹ WhatsApp ranṣẹ fun ọ pe ki o kuro laarin ọsẹ meji. O jẹ agbatọ oṣu ati pe o ti san iyasilẹ titi di oni.",
            ha: "Maigidanka ya aiko maka saƙon WhatsApp yana gaya maka ka fita a cikin makonni biyu. Kai mai hayan wata ne kuma ka biya haya har zuwa yau.",
            ig: "Onye nwe ụlọ gị zipu ozi WhatsApp na-agwa gị ka ị pụọ n'ime izu abụọ. Ị bụ onye mgbazinye ọnwa ma ikwụtara mgbazinye ruo taa.",
          },
          steps: {
            en: [
              "A WhatsApp message is not a valid quit notice — a written, formally served notice is required by law",
              "As a monthly tenant you are entitled to at least one full month's written notice",
              "Reply in writing (even via WhatsApp) stating that the message does not constitute a valid quit notice",
              "Do not vacate — continue paying rent on time while you seek legal advice",
              "If the landlord escalates or threatens to change your locks, contact a lawyer immediately",
            ],
            pcm: [
              "WhatsApp message no be valid quit notice — written, formally served notice na wetin law require",
              "As monthly tenant you get right to at least one full month written notice",
              "Reply in writing (even via WhatsApp) say the message no be valid quit notice",
              "No comot — keep paying rent on time while you dey seek legal advice",
              "If landlord escalate or threaten to change your locks, call lawyer immediately",
            ],
            yo: [
              "Ifiranṣẹ WhatsApp kii ṣe akiyesi ifi silẹ to wulo — ofin nilo akiyesi kikọ, ti a firanṣẹ ni deede",
              "Gẹgẹbi agbatọ oṣu o ni ẹtọ si o kere ju oṣu kan akiyesi kikọ ni kikun",
              "Dahun ni kikọ (paapaa nipasẹ WhatsApp) ni sisọ pe ifiranṣẹ naa ko jẹ akiyesi ifi silẹ to wulo",
              "Má kuro — tẹsiwaju san iyasilẹ ni akoko bi o ti wa imọran ofin",
              "Ti onile ba gbega tabi halẹ lati yipada titiipa rẹ, kan si agbẹjọro lẹsẹkẹsẹ",
            ],
            ha: [
              "Saƙon WhatsApp ba ingantacciyar sanarwar ƙaura ba ce — doka tana buƙatar sanarwa ta rubuce, wadda aka ba da ita a hukumance",
              "A matsayin mai hayan wata kana da haƙƙin aƙalla wata guda cikakken sanarwar rubuce",
              "Amsa a rubuce (ko ta WhatsApp) yana bayyana cewa saƙon ba ingantacciyar sanarwar ƙaura ba ne",
              "Kada ka fita — ci gaba da biyan haya a lokaci yayin da kake neman shawara ta doka",
              "Idan mai gida ya ƙara ko ya yi barazanar canza kulleka, tuntubi lauya nan da nan",
            ],
            ig: [
              "Ozi WhatsApp abụghị ọkwa ịpụ dị mma — iwu chọọ ọkwa edere n'ihe ede ede, nyesịrị n'ụzọ kwesịrị",
              "Dị ka onye mgbazinye ọnwa ị nwere ikike na ọkwa edere nke ọnwa otu zuru oke",
              "Zaghachi n'ihe ede ede (ọbụna site na WhatsApp) na-ekwu na ozi ahụ abụghị ọkwa ịpụ dị mma",
              "Hapụkwala — na-akwụ mgbazinye n'oge ka ị na-achọ ndụmọdụ iwu",
              "Ọ bụrụ na onye nwe ụlọ gbaa ume ma ọ bụ soro mkpọchi gị ọ bụ iyi egwu, kpọtụrụ ọka iwu n'ozuzu",
            ],
          },
        },
      ],
    },
    {
      slug: "rent-receipts-and-deposit",
      title: {
        en: "Rent Receipts & Security Deposits — Know Your Rights",
        pcm: "Rent Receipts & Security Deposits — Know Your Rights",
        yo: "Awọn Iwe-eri Iyasilẹ & Awọn Idogo Aabo — Mọ Awọn Ẹtọ Rẹ",
        ha: "Rasitoci Haya & Ajiyar Tsaro — Sani Haƙƙoƙinka",
        ig: "Ọkwa Nnata Mgbazinye & Ego Ntinye Nchedo — Mara Ikike Gị",
      },
      summary: {
        en: "A landlord must issue a written receipt for every payment you make. Demanding more than one or two years' rent in advance is illegal in many states including Lagos. Security deposits must be fully refunded at the end of tenancy unless there is documented damage. No landlord can pocket your deposit without proper accounting.",
        pcm: "Landlord must give you written receipt for every payment you make. Demanding more than 1 or 2 years rent in advance na illegal in many states including Lagos. Security deposit must be fully refunded at end of tenancy except if there be documented damage. No landlord fit pocket your deposit without proper accounting.",
        yo: "Onile gbọdọ fun iwe-eri kikọ fun gbogbo isanwo ti o ṣe. Beere fun diẹ sii ju ọdun kan tabi meji iyasilẹ ni iwaju jẹ aitọ ni ọpọlọpọ awọn ipinle pẹlu Lagos. A gbọdọ da awọn idogo aabo pada ni kikun ni opin agbatọ ayafi ti o ba jẹ ipalara ti o ni akọsilẹ. Ko si onile ti o le gbe idogo rẹ laisi ṣiṣe iroyin to tọ.",
        ha: "Mai gida dole ya ba da rasiti na rubuce don kowace biyan da ka yi. Neman fiye da shekara ɗaya ko biyu na haya a gaba ba doka ba ne a jihohi da yawa ciki har da Lagos. Ajiyar tsaro dole a mayar da ita cikakke a ƙarshen hayar sai idan akwai lalacewar da aka rubuta. Babu wani mai gida da zai iya ɓoye ajiyarka ba tare da yin lissafi mai kyau ba.",
        ig: "Onye nwe ụlọ kwesịrị inye ọkwa nnata edere n'ihe ede ede maka ịkwụ ọkwa ọ bụla ị mere. Ịchọ ihe karịa afọ otu ma ọ bụ abụọ mgbazinye tupu oge ya bụ iwu na steeti dị iche iche gụnyere Lagos. E kwesịrị ịzaghachi ego ntinye nchedo n'ụzọ zuru ezu na njedebe mgbazinye ma ọ dịghị ihe mmebi edere. Onye nwe ụlọ ọ bụla enweghị ike itinye ego gị n'akpa na-edebeghị ya n'ụzọ kwesịrị.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Collect rent and request advance payment up to the legal maximum allowed in your state",
          "Take a reasonable security deposit to cover potential damage to the property",
          "Deduct the cost of documented damage caused by the tenant from the security deposit",
          "Issue rent receipts in any format — printed, handwritten, or electronic",
        ],
        pcm: [
          "Collect rent and request advance payment up to the legal maximum wey your state allow",
          "Take reasonable security deposit to cover potential damage to the property",
          "Deduct cost of documented damage wey tenant cause from the security deposit",
          "Issue rent receipts in any format — printed, handwritten, or electronic",
        ],
        yo: [
          "Gba iyasilẹ ati beere isanwo iwaju titi di opin ofin ti o gba laaye ni ipinle rẹ",
          "Gba idogo aabo ti o tọ lati bo ipalara ti o ṣeeṣe si ile",
          "Ge idiyele ipalara ti o ni akọsilẹ ti agbatọ fa lati idogo aabo",
          "Fun awọn iwe-eri iyasilẹ ni eyikeyi ọna — titẹ sita, iwe ọwọ, tabi itanna",
        ],
        ha: [
          "Karɓi haya kuma nemi biyan gaba har zuwa iyakar doka da jihar ka ta yarda da ita",
          "Ɗauki ajiyar tsaro mai ma'ana don rufe lalacewar da mai yiwuwa ga gidan",
          "Cire farashi na lalacewar da aka rubuta wanda mai haya ya haifar daga ajiyar tsaro",
          "Ba da rasitoci haya a kowace hanya — bugagge, rubutun hannu, ko na lantarki",
        ],
        ig: [
          "Nata mgbazinye ma rịọ ịkwụ ego tupu oge ya rue oke iwu kwere na steeti gị",
          "Were ego ntinye nchedo kwesịrị iji kpuchie mmebi nwere ike ime n'ụlọ ahụ",
          "Wepu ọnụ ahịa mmebi edere nke onye mgbazinye mere site na ego ntinye nchedo",
          "Nye ọkwa nnata mgbazinye n'ụdị ọ bụla — ebipụtara, edere n'aka, ma ọ bụ nke eletrọnik",
        ],
      },
      cannotDo: {
        en: [
          "Refuse to issue a receipt for rent or any other payment made by the tenant",
          "Demand more than the legally allowed advance rent — in Lagos, this is capped at 1 year for new tenancies (2 years in some states)",
          "Retain the security deposit at the end of tenancy without providing a written account of deductions",
          "Deduct from the deposit for normal wear and tear — only actual damage counts",
          "Threaten or pressure a tenant to forgo their deposit",
        ],
        pcm: [
          "Refuse to give receipt for rent or any other payment wey tenant make",
          "Demand more than the legally allowed advance rent — for Lagos e dey capped at 1 year for new tenancy (2 years for some states)",
          "Keep security deposit at end of tenancy without giving written account of deductions",
          "Deduct from deposit for normal wear and tear — only actual damage count",
          "Threaten or pressure tenant to give up their deposit",
        ],
        yo: [
          "Kọ lati fun iwe-eri fun iyasilẹ tabi isanwo eyikeyi miiran ti agbatọ ṣe",
          "Beere iyasilẹ iwaju ti o pọ ju ti ofin gba laaye — ni Lagos, eyi jẹ opin ọdun kan fun awọn agbatọ tuntun (ọdun meji ni diẹ ninu awọn ipinle)",
          "Da idogo aabo pada ni opin agbatọ laisi pese akọsilẹ kikọ ti awọn idinku",
          "Ge lati idogo fun wiwọ ati yiya deede — ibajẹ gidi nikan ni o ka",
          "Halẹ tabi tẹ agbatọ lati dawọ idogo wọn silẹ",
        ],
        ha: [
          "Ƙi ba da rasiti don haya ko wani biyan da mai haya ya yi",
          "Neman fiye da hayan gaba da aka yarda da shi a bisa doka — a Lagos, an ƙakkaɓe shi a shekara 1 ga sabon hayar (shekaru 2 a wasu jihohi)",
          "Riƙe ajiyar tsaro a ƙarshen haya ba tare da ba da lissafin rubuce na cirewa ba",
          "Cire daga ajiyar saboda tsufa da taɓarɓarewa na al'ada — lalacewar gaske ne kawai ke da muhimmanci",
          "Yi barazana ko matsin lamba ga mai haya don ya yi watsi da ajiyarsa",
        ],
        ig: [
          "Jụ inye ọkwa nnata maka mgbazinye ma ọ bụ ịkwụ ọ bụla ọzọ onye mgbazinye mere",
          "Chọọ ego mgbazinye tupu oge ya karịa nke iwu kwere — na Lagos, e kpọchie ya n'afọ 1 maka mgbazinye ọhụrụ (afọ 2 na steeti ụfọdụ)",
          "Nọdụ na ego ntinye nchedo na njedebe mgbazinye na-enye ọkwa edere nke mkpochapụ",
          "Wepu site na ego ntinye maka oge na agbaji nke ọbụna — naanị mmebi n'ezie a tọọ ya",
          "Iyi onye mgbazinye egwu ma ọ bụ tụọ ya ọnụ ka ọ hapụ ego ntinye ya",
        ],
      },
      whatToDo: {
        en: [
          "Always request and keep receipts for every payment — rent, deposit, agency fees, and any other charges",
          "Before paying a deposit, ask the landlord for a written statement of the deposit amount and conditions for refund",
          "At the end of tenancy, do a joint inspection of the property and obtain a written record of its condition",
          "If the landlord refuses to refund your deposit, send a formal demand letter and follow up in writing",
          "If the refund is still withheld, report to the Rent Tribunal or file in the Magistrate's Court",
        ],
        pcm: [
          "Always request and keep receipts for every payment — rent, deposit, agency fees, and any other charge",
          "Before you pay deposit, ask landlord for written statement of deposit amount and conditions for refund",
          "At end of tenancy, do joint inspection of the property and get written record of its condition",
          "If landlord refuse to refund your deposit, send formal demand letter and follow up in writing",
          "If dem still no refund, report to Rent Tribunal or file in Magistrate Court",
        ],
        yo: [
          "Nigbagbogbo beere ati pa awọn iwe-eri fun gbogbo isanwo — iyasilẹ, idogo, awọn owo ile-iṣẹ, ati awọn ẹ̀dùn ọrọ miiran",
          "Ṣaaju ki o to san idogo, beere lọwọ onile fun alaye kikọ ti iye idogo ati awọn ipo fun ipadada",
          "Ni opin agbatọ, ṣe ayẹwo apapọ ti ile ati gba igbasilẹ kikọ ti ipo rẹ",
          "Ti onile ba kọ lati da idogo rẹ pada, fi lẹta ibeere ti o ṣe deede ranṣẹ ati tẹle ni kikọ",
          "Ti a ba tun dẹ idapadà, jabo si Ile-ẹjọ Iyasilẹ tabi fi ẹsun ni Ile-ẹjọ Magistrate",
        ],
        ha: [
          "Koyaushe ka nemi ka adana rasitoci don kowace biyan — haya, ajiya, kuɗin hukuma, da sauran cajin",
          "Kafin ka biya ajiya, ka nemi mai gida ya ba da bayanin rubuce na adadin ajiyar da sharuɗɗan mayarwa",
          "A ƙarshen haya, yi bincike tare na gidan kuma sami rikodin rubuce na yanayin sa",
          "Idan mai gida ya ƙi mayar da ajiyarka, aika wasiƙar neman hukuma kuma bi ta a rubuce",
          "Idan har yanzu ana riƙe mayarwa, ba da rahoto ga Kotun Haya ko gabatar da kara a Kotun Magistrate",
        ],
        ig: [
          "Chọọ ma debe ọkwa nnata maka ịkwụ ọkwa ọ bụla — mgbazinye, ego ntinye, ụgwọ ụlọ ọrụ, na ụgwọ ọzọ",
          "Tupu ikwụ ego ntinye, rịọ onye nwe ụlọ ka o nye nkwuputa edere nke oke ego ntinye na ụkpụrụ azaghachi",
          "Na njedebe mgbazinye, mee nyocha ọnụ ọgụgụ nke ụlọ ahụ ma nweta ndekọ edere nke ọnọdụ ya",
          "Ọ bụrụ na onye nwe ụlọ jụ ịzaghachi ego ntinye gị, zipu akwụkwọ ịchọ n'ụzọ ọchụchọ ma soro ya n'ihe ede ede",
          "Ọ bụrụ na a ka na-echebe azaghachi, kpesa na Ụlọ Ikpe Mgbazinye ma ọ bụ detuo ihe na Ụlọ Ikpe Magistrate",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not make any rent payment without collecting a receipt — verbal acknowledgement is not sufficient",
          "Do not agree to pay more than the legally allowed advance rent — report any such demand to the appropriate authority",
          "Do not leave the property without doing a joint inspection — this protects you from false damage claims",
          "Do not accept the loss of your deposit without demanding a written account of what was deducted and why",
        ],
        pcm: [
          "No make any rent payment without collecting receipt — verbal acknowledgement no dey enough",
          "No agree to pay more than the legally allowed advance rent — report any such demand to appropriate authority",
          "No leave the property without doing joint inspection — e go protect you from false damage claims",
          "No accept losing your deposit without demanding written account of wetin dem deduct and why",
        ],
        yo: [
          "Má ṣe isanwo iyasilẹ eyikeyi laisi gbigba iwe-eri — jijẹrisi ẹnu ko to",
          "Má gba lati san iyasilẹ iwaju ti o ju ti ofin gba laaye — jabo eyikeyi iru ibeere bẹẹ si aṣẹ ti o yẹ",
          "Má kuro ile laisi ṣiṣe ayẹwo apapọ — eyi n'daabobo ọ lọwọ awọn ẹtọ ibajẹ iro",
          "Má gba ipadanu idogo rẹ laisi beere akọsilẹ kikọ ti ohun ti a ge ati idi",
        ],
        ha: [
          "Kada ka yi wani biyan haya ba tare da karɓar rasiti ba — tabbatar da baki bai isa ba",
          "Kada ka yarda ka biya fiye da hayan gaba da aka yarda da shi a bisa doka — ba da rahoto game da irin wannan buƙata ga hukuma mai dacewa",
          "Kada ka bar gidan ba tare da yin bincike tare ba — wannan yana kare ka daga ƙarya da'awar lalacewa",
          "Kada ka yarda da asarar ajiyarka ba tare da neman lissafin rubuce na abin da aka cire da dalilin ba",
        ],
        ig: [
          "Emekwala ịkwụ mgbazinye ọ bụla na-anata ọkwa nnata — nkwenye n'ọnụ ezughị oke",
          "Ekwekwala ịkwụ ego mgbazinye tupu oge ya karịa nke iwu kwere — kpesa ịchọ ọ bụla dị otú ahụ na ọchịchọ kwesịrị",
          "Hapụkwala ụlọ ahụ na-emekwala nyocha ọnụ ọgụgụ — nke a na-echebe gị site na ụdị ụdị mmebi nke ezighi ezi",
          "Anabatakwala ifu ego ntinye gị na-achọghị ọkwa edere nke ihe ewepụtara na ihe kpatara ya",
        ],
      },
      laws: [
        {
          name: "Tenancy Law of Lagos State 2011",
          section: "Section 4 (Advance Rent) & Section 13 (Receipts)",
          plainEnglish: {
            en: "A landlord in Lagos cannot demand more than one year's rent in advance from a new tenant. Receipts must be issued for all rent payments. Security deposits must be refunded unless the landlord can demonstrate documented damage caused by the tenant.",
            pcm: "Landlord for Lagos no fit demand more than one year rent in advance from new tenant. Receipt must be issued for all rent payments. Security deposit must be refunded unless landlord fit show documented damage wey tenant cause.",
            yo: "Onile ni Lagos ko le beere fun diẹ sii ju ọdun kan iyasilẹ iwaju lọwọ agbatọ tuntun. A gbọdọ fun awọn iwe-eri fun gbogbo awọn isanwo iyasilẹ. A gbọdọ da awọn idogo aabo pada ayafi ti onile ba le fihan ipalara ti o ni akọsilẹ ti agbatọ fa.",
            ha: "Mai gida a Lagos ba zai iya neman fiye da shekara ɗaya na haya a gaba daga sabon mai haya ba. Dole a ba da rasitoci don duk biyan haya. Dole a mayar da ajiyar tsaro sai idan mai gida zai iya nuna lalacewar da aka rubuta wanda mai haya ya haifar.",
            ig: "Onye nwe ụlọ na Lagos enweghị ike ịchọ ihe karịa afọ otu mgbazinye tupu oge ya site n'aka onye mgbazinye ọhụrụ. E kwesịrị inye ọkwa nnata maka ịkwụ mgbazinye niile. E kwesịrị ịzaghachi ego ntinye nchedo ma ọ bụghị na onye nwe ụlọ nwere ike igosi mmebi edere nke onye mgbazinye kpatara.",
          },
        },
        {
          name: "Recovery of Premises Act (Federal)",
          section: "Section 9",
          plainEnglish: {
            en: "Any landlord who refuses to issue a receipt for rent received commits an offence and may be liable to a fine. This provision underscores the tenant's right to documented proof of payment.",
            pcm: "Any landlord wey refuse to issue receipt for rent wey dem receive don commit offence and fit face fine. This provision show that tenant get right to documented proof of payment.",
            yo: "Eyikeyi onile ti o kọ lati fun iwe-eri fun iyasilẹ ti a gba jẹ aṣiṣe ati pe o le jẹ idajọ si itanran. Ipese yii ṣe afihan ẹtọ agbatọ si ẹri kikọ ti isanwo.",
            ha: "Duk wani mai gida da ya ƙi ba da rasiti don haya da aka karɓa ya aikata laifi kuma ana iya hukunta shi tare da tara. Wannan tanadi yana jaddada haƙƙin mai haya na tabbataccen shaida ta biyan.",
            ig: "Onye nwe ụlọ ọ bụla jụrụ inye ọkwa nnata maka mgbazinye natara rụọ arụ omume ma nwee ike ịkwụ mkpagbu. Nchoputa a gosipụtara ikike onye mgbazinye na ihe akaebe edere nke ịkwụ ụgwọ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "You are vacating a property after two years. Your landlord says he is keeping your deposit because 'the house needs repainting' but refuses to show you any receipts or written breakdown of costs.",
            pcm: "You dey pack out after two years. Your landlord say he dey keep your deposit because 'house need repainting' but he dey refuse to show you any receipt or written breakdown of cost.",
            yo: "O n-lọ kuro ni ile lẹhin ọdun meji. Onile rẹ sọ pe o n-pa idogo rẹ mọ nitori 'ile nilo kun awọ tuntun' ṣugbọn o kọ lati fihan awọn iwe-eri eyikeyi tabi alaye kikọ ti awọn idiyele.",
            ha: "Kana ficewa daga gidan bayan shekaru biyu. Maigidanka ya ce yana riƙe ajiyarka saboda 'gida yana buƙatar fentin' amma ya ƙi nuna maka kowane rasiti ko rubuce-rubucen farashi.",
            ig: "Ị na-apụ n'ụlọ mgbe afọ abụọ gasịrị. Onye nwe ụlọ gị na-ekwu na o na-ekepe ego ntinye gị n'ihi na 'ụlọ ahụ chọrọ ịtụ ọcha ọhụrụ' mana ọ jụ igosi gị ọkwa nnata ọ bụla ma ọ bụ ndekọ ụgwọ edere.",
          },
          steps: {
            en: [
              "Normal repainting after two years of tenancy is considered fair wear and tear — the landlord cannot lawfully charge you for this",
              "Request a written, itemised account of all deductions from your deposit within 7 days",
              "Send a formal demand letter by registered post or WhatsApp (screenshot for evidence) requesting your deposit be returned",
              "If no response within 14 days, file a complaint at the Rent Tribunal or Magistrate's Court in the state where the property is located",
              "Keep all payment receipts, your tenancy agreement, and any correspondence as evidence",
            ],
            pcm: [
              "Normal repainting after two years of tenancy na fair wear and tear — landlord no fit lawfully charge you for that",
              "Request written itemised account of all deductions from your deposit within 7 days",
              "Send formal demand letter by registered post or WhatsApp (take screenshot as evidence) requesting your deposit back",
              "If no response within 14 days, file complaint at Rent Tribunal or Magistrate Court for the state where the property dey",
              "Keep all payment receipts, your tenancy agreement, and any correspondence as evidence",
            ],
            yo: [
              "Kikun awọ deede lẹhin ọdun meji ti agbatọ ni a ka si wiwọ ati yiya deede — onile ko le gba ọ ni owo fun eyi ni ofin",
              "Beere akọsilẹ ọkọọkan kikọ ti gbogbo awọn idinku lati idogo rẹ laarin ọjọ 7",
              "Fi lẹta ibeere ti o ṣe deede ranṣẹ nipasẹ ifiweranṣẹ ti a forukọsilẹ tabi WhatsApp (ya aworan fun ẹri) ti o beere idogo rẹ pada",
              "Ti ko ba si idahun laarin ọjọ 14, fi ẹsun ni Ile-ẹjọ Iyasilẹ tabi Magistrate ni ipinle ti ile wa",
              "Pa gbogbo awọn iwe-eri isanwo, adehun agbatọ rẹ, ati eyikeyi ibasọrọ bi ẹri",
            ],
            ha: [
              "Fentin na al'ada bayan shekaru biyu na haya ana ɗauka a matsayin tsufa da taɓarɓarewa na al'ada — mai gida ba zai iya ƙidimaka bisa doka don wannan ba",
              "Nemi lissafin rubuce mai bayanin dukkan cirewa daga ajiyarka a cikin kwanaki 7",
              "Aika wasiƙar neman hukuma ta wasiƙar rijista ko WhatsApp (ɗauki screenshot a matsayin shaida) tana neman ajiyarka a mayar",
              "Idan babu amsa a cikin kwanaki 14, gabatar da ƙara a Kotun Haya ko Kotun Magistrate a jihar da gidan yake",
              "Adana duk rasitocin biyan, yarjejeniyar hayarka, da duk wata wasila a matsayin shaida",
            ],
            ig: [
              "Itụ ọcha ọbụna mgbe afọ abụọ mgbazinye bụ oge na agbaji kwesịrị — onye nwe ụlọ enweghị ike ịtọ gị ụgwọ nke ahụ n'iwu",
              "Rịọ ọkwa edere nke njikọ mkpochapụ niile site na ego ntinye gị n'ime ụbọchị 7",
              "Zipu akwụkwọ ịchọ n'ụzọ ọchụchọ site na ozi edere ndebanye aha ma ọ bụ WhatsApp (wepụta screenshot dị ka ihe akaebe) na-arịọ ka a laghachi na ego ntinye gị",
              "Ọ bụrụ na ọ dịghị nzaghachi n'ime ụbọchị 14, detuo ihe na Ụlọ Ikpe Mgbazinye ma ọ bụ Magistrate na steeti ebe ụlọ dị",
              "Debe ọkwa nnata ịkwụ niile, nkwekọrịta mgbazinye gị, na nkwurịta okwu ọ bụla dị ka ihe akaebe",
            ],
          },
        },
      ],
    },
    {
      slug: "landlord-entry-and-privacy",
      title: {
        en: "Landlord Entry & Your Right to Privacy",
        pcm: "Landlord Entry & Your Right to Privacy",
        yo: "Wiwọle Onile & Ẹtọ Rẹ si Asiri",
        ha: "Shigan Mai Gida & Haƙƙinka na Sirri",
        ig: "Ọbanye Onye Nwe Ụlọ & Ikike Gị na Nzuzo",
      },
      summary: {
        en: "As a tenant, you have the right to peaceful enjoyment of your home. A landlord cannot enter without at least 24 hours' written notice, except in a genuine emergency. Sending agents to harass tenants, or installing surveillance equipment in your private space without consent, is illegal. The right to quiet enjoyment is an implied term in every tenancy agreement.",
        pcm: "As tenant, you get right to peaceful enjoyment of your home. Landlord no fit enter without at least 24 hours written notice, except for genuine emergency. Sending agents to harass tenants, or installing camera for your private space without consent, na illegal. Right to quiet enjoyment na implied term for every tenancy agreement.",
        yo: "Gẹgẹbi agbatọ, o ni ẹtọ si igbadun alaafia ile rẹ. Onile ko le wọ laisi o kere ju akiyesi kikọ ti wakati 24, ayafi ni pajawiri gidi. Fifiranṣẹ awọn aṣoju lati wọ awọn agbatọ, tabi fifi ohun elo wiwo ni aaye ikọkọ rẹ laisi igbanilaaye, jẹ aitọ. Ẹtọ si igbadun idakẹjẹ jẹ ọrọ ti a tọka si ninu gbogbo adehun agbatọ.",
        ha: "A matsayin mai haya, kana da haƙƙin jin daɗin zaman lafiya a gidanka. Mai gida ba zai iya shiga ba tare da aƙalla sanarwar rubuce ta awanni 24 ba, sai dai a gaggawar gaske. Aika wakili don damunawa da masu haya, ko sanya kayan sa ido a sarinka na sirri ba tare da izini ba, ba doka ba ne. Haƙƙin jin daɗin zaman lafiya sharaɗi ne da aka bayyana a kowace yarjejeniyar haya.",
        ig: "Dị ka onye mgbazinye, ị nwere ikike nweta ụlọ gị n'udo. Onye nwe ụlọ enweghị ike ịbanye na-enweghị ọkwa edere nke awa 24 ma ọ dịghị ihe mberede n'ezie. Izo onye nnọchiteanya ka o tọrọ onye mgbazinye isi, ma ọ bụ itinye ngwa nlele na ebe nzuzo gị na-enyekwala ikike, bụ iwu. Ikike nweta udo bụ usoro edere n'ihe nọ n'ibe ụlọ nke nkwekọrịta mgbazinye ọ bụla.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Enter the property with at least 24 hours' prior written notice for repairs, inspection, or showing to prospective tenants",
          "Enter immediately and without notice in a genuine emergency such as a fire, gas leak, or flood",
          "Install security cameras in common areas such as corridors, gates, or car parks with notice to tenants",
          "Conduct a routine inspection at reasonable intervals after giving proper advance notice",
        ],
        pcm: [
          "Enter the property with at least 24 hours prior written notice for repairs, inspection, or showing to prospective tenants",
          "Enter immediately without notice in genuine emergency like fire, gas leak, or flood",
          "Install security cameras in common areas like corridors, gates, or car parks with notice to tenants",
          "Do routine inspection at reasonable intervals after giving proper advance notice",
        ],
        yo: [
          "Wọ ile pẹlu o kere ju akiyesi kikọ iṣaju ti wakati 24 fun atunṣe, ayẹwo, tabi fihan si awọn agbatọ ifojusọna",
          "Wọ lẹsẹkẹsẹ laisi akiyesi ni pajawiri gidi gẹgẹbi ina, jijo gaasi, tabi iṣan omi",
          "Fi awọn kamẹra aabo ni awọn agbegbe ti o wọpọ gẹgẹbi awọn ọna inu, ẹnubode, tabi awọn papa ọkọ pẹlu akiyesi si awọn agbatọ",
          "Ṣe ayẹwo deede ni awọn aaye akoko ti o tọ lẹhin fifi akiyesi iwaju to dara",
        ],
        ha: [
          "Shiga gidan tare da aƙalla sanarwar rubuce ta awanni 24 don gyara, bincike, ko nuna wa masu haya masu yuwuwa",
          "Shiga nan da nan ba tare da sanarwa ba a gaggawar gaske kamar wuta, zubewar gas, ko ambaliya",
          "Sanya kyamarori na tsaro a wuraren da aka saba amfani dasu kamar hanyoyin ciki, ƙofofin, ko wuraren ajiye mota tare da sanarwa ga masu haya",
          "Yi bincike na yau da kullum a lokuta masu ma'ana bayan ba da ingantacciyar sanarwa ta gaba",
        ],
        ig: [
          "Banye n'ụlọ na ọkwa edere tupu oge ya nke awa 24 maka mgbazi, nyocha, ma ọ bụ igosi ndị na-achọ mgbazinye",
          "Banye n'oge n'oge na-enyekwala ọkwa na ihe mberede n'ezie dị ka ọkụ, mmiri gas gbapụ, ma ọ bụ ọkpu mmiri",
          "Tinyee mkpụrụ nlele nchedo n'ebe a na-ejikọ dị ka ụzọ, ọnụ ụzọ, ma ọ bụ ebe ikwe ụgbọ ala na ọkwa nye ndị mgbazinye",
          "Mee nyocha oge na oge n'oge kwesịrị mgbe enyere ọkwa n'oge kwesịrị",
        ],
      },
      cannotDo: {
        en: [
          "Enter your home without prior notice except in a genuine emergency",
          "Send agents, family members, or any third party to enter or inspect the property without your knowledge",
          "Install cameras, recording devices, or any surveillance equipment inside your private living space without your explicit consent",
          "Use repeated, unannounced visits to harass or intimidate you",
          "Interfere with your quiet enjoyment of the property in any way — including loud disturbances, threats, or persistent uninvited presence",
        ],
        pcm: [
          "Enter your house without prior notice except for genuine emergency",
          "Send agents, family members, or any third party to enter or inspect the property without your knowledge",
          "Install cameras, recording devices, or any surveillance equipment inside your private living space without your explicit consent",
          "Use repeated unannounced visits to harass or intimidate you",
          "Interfere with your quiet enjoyment of the property in any way — including loud disturbances, threats, or persistent uninvited presence",
        ],
        yo: [
          "Wọ ile rẹ laisi akiyesi iṣaju ayafi ni pajawiri gidi",
          "Fi awọn aṣoju, awọn ọmọ ẹbí, tabi ẹni kẹta eyikeyi ranṣẹ lati wọ tabi ṣayẹwo ile laisi imọ rẹ",
          "Fi awọn kamẹra, awọn ẹrọ gbigbasilẹ, tabi ohun elo wiwo eyikeyi sori inu aaye igbesi aye ikọkọ rẹ laisi igbanilaaye rẹ ti o han gbangba",
          "Lo awọn abẹwo leralera ti a ko kede lati wọ tabi ṣe ìdọjútì mọ ọ",
          "Dabaru igbadun idakẹjẹ rẹ ti ile ni ọna eyikeyi — pẹlu idarudapọ ariwo, awọn ihalẹ, tabi wiwa ti a ko pe ti o tẹsiwaju",
        ],
        ha: [
          "Shiga gidanka ba tare da sanarwa ta gaba ba sai dai a gaggawar gaske",
          "Aika wakili, 'yan uwa, ko wani mutum na uku don shiga ko bincika gidan ba tare da saninki ba",
          "Sanya kyamarori, na'urorin yin rikodin, ko kowane kayan sa ido a cikin sarinka na sirri ba tare da yardanka bayyananniya ba",
          "Yi amfani da ziyarori masu yawa da ba a sanar da su don damunawa ko tsoratarwa",
          "Tsoma baki cikin jin daɗin zaman lafiyarka na gidan ta kowace hanya — ciki har da tashin hankali mai ƙara, barazana, ko kasancewar da ba a gayyata ba mai ci gaba",
        ],
        ig: [
          "Banye n'ụlọ gị na-enyekwala ọkwa tupu oge ya ma ọ bụghị ihe mberede n'ezie",
          "Izo onye nnọchiteanya, ndị ezi na ụlọ, ma ọ bụ onye ọzọ ọ bụla banye ma ọ bụ nyochaa ụlọ ahụ na-ama gị",
          "Tinye mkpụrụ nlele, ngwa ndekọ, ma ọ bụ ngwa nlele ọ bụla n'ime ebe obibi nzuzo gị na-enweghị ikike gị doro anya",
          "Iji ọbịa anaghị ama na-emegharị emegharị ịtọrọ gị isi ma ọ bụ atụọ gị egwu",
          "Gbochie ịnweta udo n'ụlọ gị n'ụzọ ọ bụla — gụnyere ọkụ ọkụ, iyi egwu, ma ọ bụ ọnọdụ na-arịọghị ya na-aga n'ihu",
        ],
      },
      whatToDo: {
        en: [
          "If a landlord or agent enters without notice, document it in writing — date, time, and what happened — and inform the landlord formally",
          "If harassment continues, send a formal written warning that further interference will result in legal action",
          "Report repeated unlawful entry to the police or apply to court for an injunction to restrain the landlord",
          "If surveillance equipment is found in your private space, report to the police immediately as it may constitute a criminal offence",
        ],
        pcm: [
          "If landlord or agent enter without notice, document am in writing — date, time, and wetin happen — and formally inform the landlord",
          "If harassment continue, send formal written warning that further interference go result in legal action",
          "Report repeated unlawful entry to police or apply to court for injunction to restrain the landlord",
          "If you find surveillance equipment for your private space, report to police immediately because e fit be criminal offence",
        ],
        yo: [
          "Ti onile tabi aṣoju ba wọle laisi akiyesi, gba akọsilẹ ni kikọ — ọjọ, akoko, ati ohun ti o ṣẹlẹ — ki o si sọ fun onile ni kikọ ni ọna deede",
          "Ti ipọnju ba tẹsiwaju, fi ikilọ kikọ deede ranṣẹ pe idasi siwaju yoo yorisi igbese ofin",
          "Jabo wiwọle aitọ leralera si ọlọpaa tabi beere si ile-ẹjọ fun ilana lati dẹkun onile",
          "Ti a ba ri ohun elo wiwo ni aaye ikọkọ rẹ, jabo si ọlọpaa lẹsẹkẹsẹ nitori o le jẹ ẹṣẹ ọdaràn",
        ],
        ha: [
          "Idan mai gida ko wakili ya shiga ba tare da sanarwa ba, rubuta shi a rubuce — ranar, lokacin, da abin da ya faru — kuma sanar da mai gida a hukumance",
          "Idan damunawa ta ci gaba, aika gargadi na hukuma mai rubuce cewa tsoma baki na ƙarin zai haifar da matakan doka",
          "Ba da rahoto ga 'yan sanda game da shigowa ba bisa ƙa'ida ba da maimaitawa ko nemi kotu don hana mai gida",
          "Idan an sami kayan sa ido a sarinka na sirri, ba da rahoto ga 'yan sanda nan da nan saboda yana iya zama laifin aikata laifi",
        ],
        ig: [
          "Ọ bụrụ na onye nwe ụlọ ma ọ bụ onye nnọchiteanya banye na-enyekwala ọkwa, deechie ya n'ihe ede ede — ụbọchị, oge, na ihe mere — ma gwa onye nwe ụlọ n'ụzọ ọchụchọ",
          "Ọ bụrụ na ịtọrọ isi na-aga n'ihu, zipu ọdọ edere n'ụzọ ọchụchọ na ntụgharị ọzọ ga-ebute ọrụ iwu",
          "Kpesa ọbanye na-ezighị ezi na-emegharị emegharị na ọha ndụ ma ọ bụ rịọ n'ụlọ ikpe maka ihe igbochi iji gbochie onye nwe ụlọ",
          "Ọ bụrụ na achọta ngwa nlele n'ime ebe nzuzo gị, kpesa na ọha ndụ n'ozuzu n'ihi na ọ nwere ike ịbụ arụ omume iwu",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not physically block or use force against a landlord or agent seeking to enter — use the law instead",
          "Do not ignore repeated unlawful entries hoping they will stop — document and escalate formally",
          "Do not consent to surveillance equipment being installed in your private space — consent, once given, is hard to withdraw",
          "Do not abandon the property because of harassment — this could be construed as voluntary vacation and harm your legal position",
        ],
        pcm: [
          "No physically block or use force against landlord or agent wey wan enter — use the law instead",
          "No ignore repeated unlawful entries dey hope say dem go stop — document and formally escalate",
          "No consent to surveillance equipment being installed for your private space — consent wey you give dey hard to take back",
          "No abandon the property because of harassment — dem fit say you voluntarily vacated and e go damage your legal position",
        ],
        yo: [
          "Má dẹkun ni ti ara tabi lo agbara lodi si onile tabi aṣoju ti o fẹ wọle — lo ofin dipo",
          "Má fojufori awọn wiwọle aitọ leralera pẹlu ireti pe wọn yoo dẹkun — gba akọsilẹ ati gbega ni ọna deede",
          "Má gba laaye fifi ohun elo wiwo sori aaye ikọkọ rẹ — igbanilaaye, ni kete ti a ba fun, nira lati yọ kuro",
          "Má fi ile silẹ nitori ipọnju — eyi le ṣe itumọ bi ifisilẹ atinuwa ati ṣe ipalara si ipo ofin rẹ",
        ],
        ha: [
          "Kada ka toshe da jiki ko yi amfani da ƙarfi akan mai gida ko wakili da ke son shiga — yi amfani da doka maimakon haka",
          "Kada ka yi watsi da shigowa ba bisa ƙa'ida ba masu maimaitawa yana fata cewa za su daina — rubuta kuma ƙara a hukumance",
          "Kada ka yarda da sanya kayan sa ido a sarinka na sirri — yarda, da zarar an ba da ita, yana da wahala a janye",
          "Kada ka watsar da gidan saboda damunawa — ana iya fassara wannan a matsayin ficewa da son rai kuma yana cutar da matsayinka na doka",
        ],
        ig: [
          "Ekebekwala ahụ ma ọ bụ jiri ike megide onye nwe ụlọ ma ọ bụ onye nnọchiteanya na-achọ ịbanye — jiri iwu kama ya",
          "Echefukwala ọbanye na-ezighị ezi na-emegharị emegharị na-atụ anya na ha ga-akwụsị — deechie ma gbaa ume n'ụzọ ọchụchọ",
          "Ekwekwala ka a tinye ngwa nlele n'ebe nzuzo gị — ikike, ozugbo enyere ya, sie ike ibweghachi",
          "Hapụkwala ụlọ ahụ n'ihi ịtọrọ isi — nke a nwere ike ikọwa dị ka ịpụ n'obi onwe onwe ma mee ka ọnọdụ iwu gị daa njọ",
        ],
      },
      laws: [
        {
          name: "Common Law — Covenant of Quiet Enjoyment",
          section: "Implied Term in Every Tenancy",
          plainEnglish: {
            en: "Every tenancy agreement — whether written or oral — contains an implied covenant that the tenant will have quiet and peaceful enjoyment of the property without interference from the landlord. Breach of this covenant entitles the tenant to damages.",
            pcm: "Every tenancy agreement — whether written or by mouth — get implied covenant say tenant go enjoy the property peacefully without interference from landlord. If landlord breach this covenant, tenant fit claim damages.",
            yo: "Gbogbo adehun agbatọ — boya kikọ tabi ẹnu — ni adehun ti a tọka si pe agbatọ yoo ni igbadun idakẹjẹ ati alaafia ti ile laisi idasi lati ọdọ onile. Irufin adehun yii fun agbatọ ẹtọ si isanpada.",
            ha: "Kowace yarjejeniyar haya — ko rubuce ko ta baki — tana ɗauke da alkawari da aka bayyana cewa mai haya zai ji daɗin gidan cikin kwanciyar hankali da lumana ba tare da tsoma baki na mai gida ba. Karya wannan alkawari yana ba mai haya haƙƙin diyya.",
            ig: "Nkwekọrịta mgbazinye ọ bụla — ma edere ma n'ọnụ — nwere nkwa edere n'ihe nọ n'ibe na onye mgbazinye ga-anweta ụlọ ahụ n'udo na ụgwọ na-enweghị ntinye aka onye nwe ụlọ. Imebi nkwa a na-enye onye mgbazinye ikike na ihe ntụghị.",
          },
        },
        {
          name: "Tenancy Law of Lagos State 2011",
          section: "Section 21 (Harassment)",
          plainEnglish: {
            en: "It is a criminal offence for a landlord or any person acting on their behalf to harass a tenant with the intent to cause the tenant to give up occupation of the premises or to refrain from exercising any right. The penalty includes a fine and/or imprisonment.",
            pcm: "Na criminal offence for landlord or any person wey dey act on their behalf to harass tenant with the aim of making tenant vacate or stop exercising their rights. Penalty include fine and/or imprisonment.",
            yo: "Jẹ ẹṣẹ ọdaràn fun onile tabi ẹnikẹni ti o n-ṣiṣẹ fun wọn lati wọ agbatọ pẹlu ero lati fa ki agbatọ kọ iṣẹ ile tabi dawọ mimu eyikeyi ẹtọ duro. Ijiya pẹlu itanran ati/tabi ẹwọn.",
            ha: "Laifin aikata laifi ne ga mai gida ko kowane mutum da ke aiki a madadinsa ya damuni mai haya da niyyar sa mai haya ya yi watsi da amfani da gidan ko ya daina amfani da kowace haƙƙi. Hukunci ya haɗa da tara da/ko ɗaurin kurkuku.",
            ig: "Ọ bụ arụ omume iwu maka onye nwe ụlọ ma ọ bụ onye ọ bụla na-arụ ọrụ n'aha ha ịtọrọ onye mgbazinye isi na ebumnuche iji mee ka onye mgbazinye hapụ ọrụ ụlọ ma ọ bụ nwụfe iji ikike ọ bụla. Ahazị gụnyere mkpagbu na/ma ọ bụ mkpọ n'ọnọ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Your landlord has been sending his son to knock on your door every Saturday morning demanding that you vacate before your lease ends. He also had a padlock installed on your gate while you were away.",
            pcm: "Your landlord dey send him son to dey knock your door every Saturday morning dey tell you to comot before your lease end. He also put padlock on your gate while you comot go somewhere.",
            yo: "Onile rẹ ti n-fi ọmọkunrin rẹ ranṣẹ lati kọlu ẹnubode rẹ ni gbogbo owurọ Satidee ti n-beere pe ki o kuro ṣaaju ki adehun iyasilẹ rẹ to pari. O tun fi titiipa sori ẹnubode rẹ nigba ti o lọ jade.",
            ha: "Maigidanka yana aika ɗansa don kwankwasa ƙofar ka kowace asabar safiya yana neman ka fita kafin yarjejeniyarka ta ƙare. Ya kuma sanya makullin ƙofa a ƙofarka yayin da ka tafi waje.",
            ig: "Onye nwe ụlọ gị na-ezipu nwa ya nwoke ịkụ ọnụ ụzọ gị ụtụtụ Satọde ọ bụla na-arịọ ka ị pụọ tupu mgbazinye gị agwụ. O kwara mkpọchi na ọnụ ụzọ gị ka ị ga n'èzí.",
          },
          steps: {
            en: [
              "The landlord's behaviour constitutes harassment under the Tenancy Law — you do not have to tolerate it",
              "Document every incident: dates, times, what was said or done, and any witnesses",
              "Send a formal written notice to the landlord stating that these actions amount to harassment and must stop immediately",
              "Report the padlock installation to the police as unlawful interference with your possession — this may also constitute an illegal eviction attempt",
              "Apply to court for an injunction to restrain the landlord and his agents from interfering with your quiet enjoyment",
              "You may also seek compensation for the harassment suffered",
            ],
            pcm: [
              "Landlord behaviour na harassment under the Tenancy Law — you no need to tolerate am",
              "Document every incident: dates, times, wetin dem say or do, and any witnesses",
              "Send formal written notice to landlord say these actions na harassment and must stop immediately",
              "Report the padlock installation to police as unlawful interference with your possession — e fit also be illegal eviction attempt",
              "Apply to court for injunction to restrain landlord and him agents from interfering with your quiet enjoyment",
              "You fit also seek compensation for the harassment wey you suffer",
            ],
            yo: [
              "Ihuwasi onile jẹ ipọnju labẹ Ofin Agbatọ — o ko ni lati fi ara mu pẹlu rẹ",
              "Gba akọsilẹ gbogbo iṣẹlẹ: awọn ọjọ, awọn akoko, ohun ti a sọ tabi ṣe, ati awọn ẹlẹri eyikeyi",
              "Fi akiyesi kikọ deede ranṣẹ si onile ni sisọ pe awọn iṣe wọnyi jẹ ipọnju ati gbọdọ dẹkun lẹsẹkẹsẹ",
              "Jabo fifi titiipa sori si ọlọpaa gẹgẹbi idasi aitọ pẹlu ohun ini rẹ — eyi tun le jẹ igbiyanju ilepadanu aitọ",
              "Beere si ile-ẹjọ fun ilana lati dẹkun onile ati awọn aṣoju rẹ lati dabaru igbadun idakẹjẹ rẹ",
              "O tun le wa isanpada fun ipọnju ti o jiya",
            ],
            ha: [
              "Halin mai gida yana zama damunawa a ƙarƙashin Dokar Haya — ba dole ka jurewa ba",
              "Rubuta kowane lamari: kwanaki, lokuta, abin da aka faɗa ko aka yi, da kowane shaidu",
              "Aika sanarwar hukuma ta rubuce ga mai gida yana cewa waɗannan ayyuka na damunawa ne kuma dole su daina nan da nan",
              "Ba da rahoto ga 'yan sanda game da sanya makullin ƙofa a matsayin tsoma baki ba bisa ƙa'ida ba tare da mallakar ka — wannan na iya zama yunƙurin kora ba bisa ƙa'ida ba",
              "Nemi kotu don hani don hana mai gida da wakilansa daga tsoma baki cikin jin daɗin zaman lafiyanka",
              "Kana iya neman diyya ma don damunawa da ka sha",
            ],
            ig: [
              "Omume onye nwe ụlọ bụ ịtọrọ isi n'okpuru Iwu Mgbazinye — ị dịghị mkpa ịhara ya",
              "Deechie mmemme ọ bụla: ụbọchị, oge, ihe a kwuru ma ọ bụ mere, na ndị ọ bụla hụrụ",
              "Zipu ọkwa edere n'ụzọ ọchụchọ nye onye nwe ụlọ na-ekwu na omume ndị a bụ ịtọrọ isi ma kwesịrị ịkwụsị n'ozuzu",
              "Kpesa itinye mkpọchi na ọha ndụ dị ka ntinye aka na-ezighị ezi na ihe onwe onwe gị — nke a nwere ike ịbụ mgbalị ịchụpụ na-ezighị ezi",
              "Rịọ n'ụlọ ikpe maka ihe igbochi iji gbochie onye nwe ụlọ na ndị nnọchiteanya ya site na ntinye aka na ịnweta udo gị",
              "Ị nwekwara ike ịchọ ntụghị maka ịtọrọ isi ahụ ị taara",
            ],
          },
        },
      ],
    },
  ],
};
