import type { Section } from "./types";

export const traders: Section = {
  slug: "traders",
  title: {
    en: "Traders & Business Owners",
    pcm: "Traders & Business People",
    yo: "Awọn Oniṣowo & Awọn Oniwun Iṣowo",
    ha: "Masu Kasuwanci & Masu Kasuwanci",
    ig: "Ndị Ahịa & Ndị Nwe Azụmahịa",
  },
  description: {
    en: "Rights for market traders, shop owners, hawkers, and entrepreneurs facing task forces, NAFDAC, tax officials, or illegal shop sealing.",
    pcm: "Rights for market traders, shop owners, hawkers, and business people wey face task force, NAFDAC, tax officials, or illegal shop sealing.",
    yo: "Awọn ẹtọ fun awọn oniṣowo ọja, awọn oniwun ile itaja, awọn oniṣowo ita, ati awọn oniṣowo ti o dojuko pẹlu awọn ẹgbẹ iṣẹ, NAFDAC, awọn oṣiṣẹ owo-ori, tabi pipade ile itaja ti kii ṣe ofin.",
    ha: "Haƙƙoƙi ga masu kasuwancin kasuwa, masu shaguna, masu kaya a kan hanya, da masu kasuwanci da ke fuskantar ƙungiyar aiki, NAFDAC, jami'an haraji, ko rufin shago ba bisa ƙa'ida ba.",
    ig: "Ikike maka ndị ahịa ahịa, ndị nwe ụlọ ahịa, ndị ahịa ụzọ, na ndị ọrụ azụmahịa ndị na-emegbu ọrụ ọrụ, NAFDAC, ndị ọrụ ụtụ isi, ma ọ bụ mbozu ụlọ ahịa na-ezighị ezi.",
  },
  icon: "ShoppingBag",
  color: "bg-amber-50 text-amber-700",
  topics: [
    {
      slug: "market-task-force",
      title: {
        en: "Market Task Force Encounters",
        pcm: "Market Task Force",
        yo: "Awọn Ipade Ẹgbẹ Iṣẹ Ọja",
        ha: "Saurari Ƙungiyar Aikin Kasuwa",
        ig: "Ọgbọ Ọrụ Ahịa Ahịa",
      },
      summary: {
        en: "State and local government task forces operate in markets. They have specific limited powers — they cannot arbitrarily seize goods, demand cash, or assault traders.",
        pcm: "State and local government task force dey operate for market. Their power get limit — dem no fit just seize your goods, demand cash, or beat traders.",
        yo: "Awọn ẹgbẹ iṣẹ ijọba ipinle ati agbegbe n'ṣiṣẹ ni awọn ọja. Wọn ni agbara to ni opin — wọn ko le gba ẹru larọwọto, beere owo, tabi kọlu awọn oniṣowo.",
        ha: "Ƙungiyoyin aikin jiha da gwamnatin gari suna aiki a kasuwanni. Suna da ikon iyakantacce — ba za su iya kwace kaya ba tare da dalili ba, nemi kuɗi, ko duka masu kasuwanci ba.",
        ig: "Ọrụ ọrụ steeti na ọchịchọ ọbụbụ na-arụ ọrụ n'ahịa. Ha nwere ike obere — ha enweghị ike ịchekwa ngwongwo gị n'ụzọ ọ bụla, ịrịọ ego, ma ọ bụ ịkụ ndị ahịa.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Enforce market bylaws and regulations",
          "Issue notices for violations",
          "Seize goods that violate specific regulations (with documentation)",
          "Request valid business permits and licences",
        ],
        pcm: ["Enforce market bylaws and regulations", "Give notice for violations", "Seize goods wey violate specific rules (with paperwork)", "Ask for valid business permit and licence"],
        yo: ["Mu ẹjọ awọn ofin ọja ati awọn ilana", "Fun awọn akiyesi fun awọn ìka", "Gba ẹru ti o lodi si awọn ilana kan (pẹlu awọn iwe)", "Beere fun awọn iwe aṣẹ iṣowo to wulo"],
        ha: ["Tilasta bin dokokin kasuwa da ka'idoji", "Ba da sanarwa don keta doka", "Kwace kaya da ke keta ka'idoji na musamman (tare da takardu)", "Nemi ingantattun izinin kasuwanci da lasisi"],
        ig: ["Machibido iwu ahịa na usoro", "Nye ọkwa maka mmebi", "Chekwa ngwongwo ndị na-emebi usoro ụfọdụ (na akwụkwọ)", "Rịọ ikike azụmahịa na laịsensị dị mma"],
      },
      cannotDo: {
        en: [
          "Seize goods without issuing a formal receipt or documentation",
          "Demand cash payments that are not official levies",
          "Use violence or threats against traders",
          "Operate without displaying proper identification",
          "Seal a shop without a court order or formal notice",
        ],
        pcm: ["Seize goods without formal receipt or documentation", "Demand cash wey no be official levy", "Use violence or threat against traders", "Operate without showing proper ID", "Seal shop without court order or formal notice"],
        yo: ["Gba ẹru laisi fifun riri alaye tabi iwe", "Beere awọn sisanwo owo ti kii ṣe awọn adeta alaye", "Lo iwa-ipa tabi ìdọjútì si awọn oniṣowo", "Ṣiṣẹ laisi ifitonileti idanimọ to dara", "Pa ile itaja laisi aṣẹ ile-ẹjọ tabi akiyesi alaye"],
        ha: ["Kwace kaya ba tare da ba da kirtani ko takarda ba", "Nemi biyan kuɗi wanda ba haraji hukuma ba", "Yi amfani da tashin hankali ko barazana ga masu kasuwanci", "Aiki ba tare da nuna ingantaccen shaida ba", "Rufe shago ba tare da umurnin kotu ko sanarwa ta hukuma ba"],
        ig: ["Chekwa ngwongwo na-enweghị inyesite recept ma ọ bụ akwụkwọ", "Rịọ ụgwọ ego na-abụghị ụtụ ọrụ", "Ojiji ihe ike ma ọ bụ iyi egwu megide ndị ahịa", "Ọrụ na-egosighị njirimara dị mma", "Mechie ụlọ ahịa na-enweghị iwu ụlọ ikpe ma ọ bụ ọkwa ọrụ"],
      },
      whatToDo: {
        en: [
          "Ask for the officers' identification and the authority they represent",
          "Request a copy of any notice or seizure receipt",
          "Do not obstruct them physically, but assert your rights verbally",
          "Contact your market union or association immediately",
          "Document everything — photos if safe to do so",
          "Report to your Local Government Authority if rights are violated",
        ],
        pcm: ["Ask for their ID and which authority dem represent", "Request copy of any notice or seizure receipt", "No block them physically but use your voice to assert your rights", "Call your market union immediately", "Document everything — take photos if safe", "Report to Local Government if dem violate your rights"],
        yo: ["Beere fun idanimọ awọn ọfẹ ati aṣẹ ti wọn ṣojuuṣe", "Beere fun adakọ ti akiyesi tabi riri ijagba eyikeyi", "Má dẹ̀ wọn ni ara, ṣugbọn sọ awọn ẹtọ rẹ ni ohun", "Kan si ẹgbẹ ọja rẹ lẹsẹkẹsẹ", "Gba akọsilẹ ohun gbogbo — ya awọn aworan ti o ba jẹ ailewu", "Ròyìn si Aṣẹ Ijọba Agbegbe Rẹ ti a ba ru ẹtọ rẹ"],
        ha: ["Nemi shaida jami'an da ikon da suke wakilta", "Nemi kwafin kowane sanarwa ko kirtanin kwace", "Kada ka toshe su jiki, amma nemi haƙƙoƙinka ta murya", "Tuntubi ƙungiyar kasuwanku nan da nan", "Rubuta komai — dauki hotuna idan lafiya ta bada damar", "Kai ƙara ga Hukumar Gwamnatin Gari idan an keta haƙƙoƙinka"],
        ig: ["Rịọ njirimara ndị ọrụ ahụ na ọchịchọ ha na-anọchite anya ya", "Rịọ otu n'ime ọkwa ọ bụla ma ọ bụ recept nchekwa", "Emebikwala ha n'ahụ, mana kwuo ikike gị n'olu", "Kpọtụrụ ọgbakọ ahịa gị n'ozuzu", "Deechie ihe niile — were foto ọ bụrụ na ọ dị mma", "Kọọ na Ọchịchọ Gọọmenti Ebe ma ọ bụrụ na e mebiiri ikike gị"],
      },
      whatNotToDo: {
        en: [
          "Do not physically obstruct or assault task force officers",
          "Do not pay unofficial cash without documentation",
          "Do not abandon your goods at the scene without documentation",
          "Do not ignore notices — respond formally in writing",
        ],
        pcm: ["No physically block or attack task force officers", "No pay unofficial cash without documentation", "No abandon your goods without documentation", "No ignore notice — respond formally in writing"],
        yo: ["Má dẹ́ tabi kọlu awọn ọfẹ ẹgbẹ iṣẹ ni ara", "Má san owo aṣiri laisi iwe", "Má fi ẹru rẹ silẹ ni ibi laisi iwe", "Má fojufori awọn akiyesi — dahun ni alaye ni kikọ"],
        ha: ["Kada ka toshe ko kai wa jami'an ƙungiyar aikin hari jiki", "Kada ka biya kuɗin ɓoye ba tare da takardu ba", "Kada ka bar kayanka a wurin ba tare da takardu ba", "Kada ka yi watsi da sanarwa — amsa da hukuma a rubuce"],
        ig: ["Emebikwala ma ọ bụ kụọ ndị ọrụ ọrụ ọrụ n'ahụ", "Akwụkwala ego nzuzo na-enweghị akwụkwọ", "Hapụkwala ngwongwo gị n'ebe ahụ na-enweghị akwụkwọ", "Anakwụkwala ọkwa — zaghachi n'ụzọ ọrụ n'ihe ede ede"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 44",
          plainEnglish: {
            en: "No moveable property shall be compulsorily acquired unless fair compensation is paid. Seizure of goods without documentation or compensation may be unconstitutional.",
            pcm: "Nobody fit compulsorily take your property without fair compensation. Seizing goods without documentation or payment fit be unconstitutional.",
            yo: "Ko si ohun ini ti a le gba ni ipa laisi isanpada ododo. Imugba ẹru laisi iwe tabi isanpada le jẹ aiofin.",
            ha: "Ba za a kwace dukiya ta tilas ba sai an biya diyya mai adalci. Kwace kaya ba tare da takardu ko diyya ba na iya zama rashin tsarin mulki.",
            ig: "Enweghị ihe onwe onye ga-abụ nke a ga-anabata n'ike na-enweghị ụgwọ kwesịrị ekwesị. Ịchekwa ngwongwo na-enweghị akwụkwọ ma ọ bụ ụgwọ nwere ike ọ bụghị iwu.",
          },
        },
      ],
      scenarios: [],
    },

    {
      slug: "nafdac-raids",
      title: {
        en: "NAFDAC Inspections & Raids",
        pcm: "NAFDAC Inspection and Raid",
        yo: "Awọn Iṣayẹwo ati Awọn Igbogunti NAFDAC",
        ha: "Bincike da Farmakin NAFDAC",
        ig: "Nyocha na Mbuso NAFDAC",
      },
      summary: {
        en: "NAFDAC officials must carry valid identification and written authority before conducting any inspection or seizure. They can inspect regulated products but must follow due process — they cannot seize goods without proper documentation. Traders have the right to see NAFDAC's authority to act. The NAFDAC Act Cap N1 LFN 2004 governs their powers.",
        pcm: "NAFDAC officials must carry valid ID and written authority before dem do any inspection or seizure. Dem fit inspect regulated products but dem must follow due process — dem no fit seize your goods without proper documentation. You get right to see NAFDAC authority to act. NAFDAC Act Cap N1 LFN 2004 control their power.",
        yo: "Awọn oṣiṣẹ NAFDAC gbọdọ gbe idanimọ to wulo ati aṣẹ kikọ ṣaaju ki wọn ṣe eyikeyi ayẹwo tabi imugba. Wọn le ṣayẹwo awọn ọja ti a ṣakoso ṣugbọn gbọdọ tẹle ilana to dara — wọn ko le gba ẹru laisi iwe kikọ to dara. Awọn oniṣowo ni ẹtọ lati rii aṣẹ NAFDAC lati ṣiṣẹ. NAFDAC Act Cap N1 LFN 2004 n'ṣakoso awọn agbara wọn.",
        ha: "Jami'an NAFDAC dole su ɗauki ingantaccen shaida da izini a rubuce kafin su gudanar da kowane bincike ko kwace. Za su iya duba kayayyakin da ake kulawa da su amma dole su bi tsarin da ya dace — ba za su iya kwace kaya ba tare da takardu na hukuma ba. Masu kasuwanci na da haƙƙin ganin ikon NAFDAC na aiki. Dokar NAFDAC Cap N1 LFN 2004 ta tsara ikon su.",
        ig: "Ndị ọrụ NAFDAC ga-ebu njirimara dị mma na ikike edere n'akwụkwọ tupu ha eme nyocha ọ bụla ma ọ bụ nchekwa. Ha nwere ike ịnyocha ngwongwo ndị a na-ahụ maka ha mana ha ga-eso usoro kwesịrị ekwesị — ha enweghị ike ịchekwa ngwongwo gị na-enweghị akwụkwọ kwesịrị ekwesị. Ndị ahịa nwere ikike ịhụ ikike NAFDAC ịrụ ọrụ. NAFDAC Act Cap N1 LFN 2004 na-achịkwa ikike ha.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Inspect premises where regulated food, drugs, or cosmetics are sold",
          "Request product labels, batch numbers, and registration documents",
          "Collect samples for laboratory testing with proper documentation",
          "Seize counterfeit or unregistered products if they issue an official seizure receipt",
          "Prosecute traders selling products that violate NAFDAC regulations",
        ],
        pcm: [
          "Inspect place wey dem dey sell food, drugs, or cosmetics",
          "Ask for product labels, batch numbers, and registration documents",
          "Collect samples for lab testing with proper paperwork",
          "Seize fake or unregistered products if dem give official seizure receipt",
          "Prosecute traders wey dey sell products wey violate NAFDAC rules",
        ],
        yo: [
          "Ṣayẹwo awọn aaye ti a ta ounjẹ, oogun, tabi awọn ohun ikunra ti a ṣakoso",
          "Beere fun awọn aami ọja, awọn nọmba ìparọ, ati awọn iwe iforukọsilẹ",
          "Gba awọn ayẹwo fun idanwo yàrá pẹlu iwe to dara",
          "Gba awọn ọja iro tabi ti a ko forukọsilẹ ti wọn ba fun riri imugba alaye",
          "Fi ẹjọ si awọn oniṣowo ti o n'ta awọn ọja ti o lodi si awọn ilana NAFDAC",
        ],
        ha: [
          "Duba wuraren da ake sayar da abinci, magunguna, ko kayan kwalliya da ake kulawa da su",
          "Nemi alamun kaya, lambobin ɗari, da takardu na rajista",
          "Tattara samfura don gwajin dakin gwaje-gwaje tare da takardu na hukuma",
          "Kwace kayayyakin ƙarya ko marasa rajista idan sun ba da kirtanin kwace na hukuma",
          "Ƙara masu kasuwanci masu sayar da kayayyaki da ke keta ka'idojin NAFDAC",
        ],
        ig: [
          "Nyocha ebe a na-ere nri, ọgwụ, ma ọ bụ ihe ịchọ mma ndị a na-ahụ maka ha",
          "Rịọ akara ngwongwo, ọnụ ọgụgụ ụdị, na akwụkwọ ndebanye aha",
          "Nweta ihe nlele maka nnwale ụlọ nyocha na akwụkwọ kwesịrị ekwesị",
          "Chekwa ngwongwo ụgha ma ọ bụ ndị a debeghị aha ha ma ha wepụta recept nchekwa ọrụ",
          "Mee ikpe ndị ahịa ndị na-ere ngwongwo ndị na-emebi usoro NAFDAC",
        ],
      },
      cannotDo: {
        en: [
          "Conduct an inspection without showing a valid NAFDAC identity card and written warrant or authority",
          "Seize goods without issuing an official NAFDAC seizure receipt listing every item taken",
          "Demand cash payments or 'settlement' in lieu of prosecution",
          "Destroy goods on the spot without a court order authorising destruction",
          "Arrest or detain a trader without involving the Nigeria Police Force",
        ],
        pcm: [
          "Do inspection without showing valid NAFDAC ID card and written warrant or authority",
          "Seize goods without giving official NAFDAC seizure receipt wey list every item dem take",
          "Demand cash or 'settlement' instead of prosecution",
          "Destroy goods on the spot without court order",
          "Arrest or detain trader without involving Nigeria Police Force",
        ],
        yo: [
          "Ṣe ayẹwo laisi fifihan kaadi idanimọ NAFDAC to wulo ati aṣẹ kikọ",
          "Gba ẹru laisi fifun riri imugba NAFDAC alaye ti o n'darukọ ohun gbogbo ti a gba",
          "Beere fun owo ati 'ipinnu' dipo ẹjọ",
          "Pa ẹru run lori aaye laisi aṣẹ ile-ẹjọ ti o fun laṣẹ iparun",
          "Mu tabi di oniṣowo lẹwọn laisi fifiranṣẹ fun ọlọpa Nigeria",
        ],
        ha: [
          "Gudanar da bincike ba tare da nuna ingantaccen katin shaida na NAFDAC da izini a rubuce ba",
          "Kwace kaya ba tare da ba da kirtanin kwace na hukuma na NAFDAC da ke lissafin duk abin da aka kwace ba",
          "Nemi biyan kuɗi ko 'sulhu' maimakon ƙara",
          "Lalata kaya a kan wuri ba tare da umurnin kotu da ke ba da izinin lalata ba",
          "Kama ko tsare mai kasuwanci ba tare da shigar da 'yan sanda ta Najeriya ba",
        ],
        ig: [
          "Meere nyocha na-egosighị kaadị njirimara NAFDAC dị mma na ikike edere n'akwụkwọ",
          "Chekwa ngwongwo na-enweghị inyesite recept nchekwa NAFDAC ọrụ nke na-edepụta ihe niile a were",
          "Rịọ ụgwọ ego ma ọ bụ 'nkwụsị' n'ọnọdụ maka mkpe",
          "Nwepu ngwongwo n'ebe ahụ na-enweghị iwu ụlọ ikpe nke na-atọ nkwụsịtụ ikike",
          "Jide ma ọ bụ chekwaa onye ahịa na-esonweghị ndị uwe ojii Nigeria",
        ],
      },
      whatToDo: {
        en: [
          "Calmly ask to see the officer's NAFDAC identity card and the written authority or warrant for the inspection",
          "Request an itemised seizure receipt if any goods are taken — refuse to allow removal without one",
          "Write down the officer's name, badge number, and the time of the visit",
          "Contact your trade association or a lawyer as soon as possible",
          "If goods are seized, follow up at the nearest NAFDAC office with your receipt to understand next steps",
        ],
        pcm: [
          "Calmly ask to see officer NAFDAC ID card and written authority or warrant for the inspection",
          "Request itemised seizure receipt if dem take any goods — no allow dem remove anything without receipt",
          "Write down officer name, badge number, and time of the visit",
          "Contact your trade association or lawyer as soon as possible",
          "If dem seize goods, follow up at nearest NAFDAC office with your receipt to know next steps",
        ],
        yo: [
          "Beere ni alaafia lati rii kaadi idanimọ NAFDAC ti oṣiṣẹ ati aṣẹ kikọ tabi aṣẹ fun ayẹwo",
          "Beere fun riri imugba ti o ṣe alaye ti wọn ba gba eyikeyi ẹru — kọ lati gba yiyọ laisi ọkan",
          "Kọ orukọ oṣiṣẹ, nọmba ami-ẹri, ati akoko ibẹwo naa",
          "Kan si ẹgbẹ iṣowo rẹ tabi agbẹjọro ni kete bi o ti ṣee ṣe",
          "Ti wọn ba gba ẹru, tẹle soke ni ọfiisi NAFDAC ti o sunmọ julọ pẹlu riri rẹ lati ni oye awọn igbesẹ ti o tẹle",
        ],
        ha: [
          "Yi hankali ka nemi ganin katin shaida na NAFDAC na jami'in da izinin rubuce ko umurnin bincike",
          "Nemi kirtanin kwace mai cikakken bayani idan aka kwace kaya — ki ki ba da izinin cire kaya ba tare da shi ba",
          "Rubuta sunan jami'in, lambar alama, da lokacin ziyarar",
          "Tuntubi ƙungiyar kasuwancinka ko lauya da wuri-wuri",
          "Idan an kwace kaya, bi sahun a ofishin NAFDAC da ke kusa da kirtaninka don fahimtar matakan gaba",
        ],
        ig: [
          "Jụọ n'ụzọ dị jụjụ ka ị hụ kaadị njirimara NAFDAC nke onye ọrụ ahụ na ikike edere n'akwụkwọ ma ọ bụ ikike maka nyocha",
          "Rịọ recept nchekwa nke na-edepụta ihe niile ma ọ bụrụ na a were ngwongwo ọ bụla — jụ ka ha wepu ihe ọ bụla na-enweghị ya",
          "Dee aha onye ọrụ ahụ, ọnụ ọgụgụ akara ya, na oge nleta ahụ",
          "Kpọtụrụ ọgbakọ azụmahịa gị ma ọ bụ ọkàiwu ozugbo o kwere omume",
          "Ọ bụrụ na a chekwaa ngwongwo, soro n'ọfịs NAFDAC dị nso ọtụtụ na recept gị iji ghọta usoro ọzọ",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not pay cash to NAFDAC officials to 'settle' or avoid seizure — this is bribery and can be used against you",
          "Do not physically obstruct or threaten NAFDAC officers, even if you believe they are acting unlawfully",
          "Do not allow goods to be removed without an official, itemised seizure receipt",
          "Do not sign any statement or confession without first reading it and consulting a lawyer",
        ],
        pcm: [
          "No pay cash to NAFDAC officials to 'settle' or avoid seizure — na bribery and dem fit use am against you",
          "No physically block or threaten NAFDAC officers even if you think dem dey act unlawfully",
          "No allow dem remove goods without official, itemised seizure receipt",
          "No sign any statement or confession without reading am first and consulting lawyer",
        ],
        yo: [
          "Má san owo si awọn oṣiṣẹ NAFDAC lati 'yanju' tabi yago fun imugba — eyi jẹ ẹbọ ati pe a le lo lodi si ọ",
          "Má dẹ́ tabi halẹ awọn oṣiṣẹ NAFDAC ni ara, paapaa ti o ba gbagbọ pe wọn n'ṣiṣẹ ni aiofin",
          "Má gba ẹru lati yọ kuro laisi riri imugba alaye to wulo",
          "Má fọwọsi eyikeyi alaye tabi ijẹwọ laisi kika rẹ ni akọkọ ati imọran agbẹjọro",
        ],
        ha: [
          "Kada ka biya kuɗi ga jami'an NAFDAC don 'sulhu' ko gujewa kwace — wannan cin hanci ne kuma ana iya amfani da shi a kanka",
          "Kada ka toshe ko barazana jami'an NAFDAC jiki, ko da kana ganin suna aiki ba bisa ƙa'ida ba",
          "Kada ka yarda da cire kaya ba tare da kirtanin kwace na hukuma mai cikakken bayani ba",
          "Kada ka sanya hannu a kan wata sanarwa ko ikirari ba tare da karanta shi da farko da tuntubar lauya ba",
        ],
        ig: [
          "Akwụkwala ego ndị ọrụ NAFDAC iji 'kwụsị' ma ọ bụ zere nchekwa — ọ bụ nnata nnyefe ma a nwere ike iji ya megide gị",
          "Emebikwala ma ọ bụ iyi egwu ndị ọrụ NAFDAC n'ahụ, ọ bụ ezie na ị chere na ha na-arụ ọrụ n'ụzọ na-ezighị ezi",
          "Akwụkwala ka a wepu ngwongwo na-enweghị recept nchekwa ọrụ nke na-edepụta ihe niile",
          "Adebanyekwala aka n'akwụkwọ ọ bụla ma ọ bụ nkwupụta na-agụghị ya nke ọma ma ọ bụ n'ịhọchaghị ọkàiwu",
        ],
      },
      laws: [
        {
          name: "NAFDAC Act Cap N1 Laws of the Federation of Nigeria 2004",
          section: "Section 5 & 8",
          plainEnglish: {
            en: "Section 5 lists NAFDAC's functions including the power to analyse, inspect, and seize regulated products. Section 8 outlines inspection powers. All powers must be exercised by authorised officers carrying valid identity and written warrants.",
            pcm: "Section 5 list NAFDAC functions including power to analyse, inspect, and seize regulated products. Section 8 talk about inspection powers. All powers must be exercised by authorised officers wey carry valid ID and written warrant.",
            yo: "Abala 5 ṣe atokọ awọn iṣẹ NAFDAC pẹlu agbara lati ṣe atupale, ṣayẹwo, ati gba awọn ọja ti a ṣakoso. Abala 8 ṣe apejuwe awọn agbara ayẹwo. Gbogbo awọn agbara gbọdọ jẹ imuse nipasẹ awọn oṣiṣẹ ti a fun laṣẹ ti o gbe idanimọ to wulo ati awọn aṣẹ kikọ.",
            ha: "Sashi na 5 ya lissafin ayyukan NAFDAC ciki har da ikon yin nazari, bincike, da kwace kayayyakin da ake kulawa da su. Sashi na 8 ya bayyana ikon bincike. Dole ne ikon duka a yi amfani da su ta jami'an da aka ba izini waɗanda suke ɗauke da ingantaccen shaida da izini a rubuce.",
            ig: "Nkeji 5 na-edepụta ọrụ NAFDAC gụnyere ike ịtụle, ịnyocha, na ịchekwa ngwongwo ndị a na-ahụ maka ha. Nkeji 8 na-akọwa ike nyocha. A ga-esi na ndị ọrụ nwere ikike ndị na-ebu njirimara dị mma na ikike edere n'akwụkwọ rụọ ọrụ niile.",
          },
        },
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 44",
          plainEnglish: {
            en: "Your property cannot be compulsorily taken without fair compensation. Seizure of goods without proper documentation or follow-up process is potentially unconstitutional.",
            pcm: "Nobody fit take your property by force without fair compensation. Seizing goods without proper documentation or follow-up process fit be unconstitutional.",
            yo: "A ko le gba ohun-ini rẹ ni ipa laisi isanpada ododo. Imugba ẹru laisi iwe to dara tabi ilana atẹle le jẹ aiofin.",
            ha: "Ba za a iya ɗaukar dukiyarka ta tilas ba tare da isasshen diyya. Kwace kaya ba tare da takardu na hukuma ko tsarin bi-bayan aiki ba na iya zama rashin tsarin mulki.",
            ig: "A nweghị ike iwere ihe gị n'ike na-enweghị ụgwọ kwesịrị ekwesị. Ịchekwa ngwongwo na-enweghị akwụkwọ kwesịrị ekwesị ma ọ bụ usoro na-eso nwere ike ọ bụghị iwu.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "NAFDAC officials arrive at your provision store and begin removing goods from the shelves, saying the products are unregistered. They have not shown you any identification or written authority and are refusing to give you a receipt.",
            pcm: "NAFDAC officials come your provision store and start removing goods from shelf, saying the products no register. Dem no show you any ID or written authority and dem dey refuse to give you receipt.",
            yo: "Awọn oṣiṣẹ NAFDAC de si ile itaja ipese rẹ ti wọn bẹrẹ si yọ ẹru kuro lori awọn selifu, wipe awọn ọja ko ti forukọsilẹ. Wọn ko ti fihan ọ idanimọ tabi aṣẹ kikọ eyikeyi ati pe wọn n'kọ lati fun ọ ni riri.",
            ha: "Jami'an NAFDAC sun zo shagonka na kayan masarufi kuma sun fara cire kaya daga shelves, suna cewa kayayyakin ba su da rajista. Ba su nuna maka wata shaida ko izini a rubuce ba kuma suna ƙin ba ka kirtani.",
            ig: "Ndị ọrụ NAFDAC bịara n'ụlọ ahịa ihe gị wee malite iwepụ ngwongwo n'ime efere ahịa, na-ekwu na ngwongwo ndị ahụ abanyelaghị aha. Ha egosighaghị gị njirimara ọ bụla ma ọ bụ ikike edere n'akwụkwọ ma ha na-ajụ ịnye gị recept.",
          },
          steps: {
            en: [
              "Stay calm. Politely but firmly ask every person present to show their NAFDAC identity card and their written inspection warrant before anything is moved.",
              "If they cannot or will not show valid identification and written authority, state clearly: 'I am not authorising removal of any goods until you produce proper identification and a written warrant.'",
              "If they continue, do not physically resist but call out to witnesses — other traders or customers — and begin recording on your phone if it is safe to do so.",
              "Demand an itemised seizure receipt for every single item removed, listing product name, quantity, and batch number.",
              "After the incident, go to your nearest NAFDAC zonal office with your receipt and file a formal complaint if due process was not followed.",
            ],
            pcm: [
              "Calm down. Politely but firmly ask every person present to show their NAFDAC ID card and written inspection warrant before dem move anything.",
              "If dem no fit or no wan show valid ID and written authority, tell dem clearly: 'I no dey authorise removal of any goods until you produce proper ID and written warrant.'",
              "If dem continue, no physically resist but call witnesses — other traders or customers — and start recording on your phone if e safe.",
              "Demand itemised seizure receipt for every single item dem remove, listing product name, quantity, and batch number.",
              "After everything, go to nearest NAFDAC zonal office with your receipt and file formal complaint if dem no follow due process.",
            ],
            yo: [
              "Duro ni alaafia. Beere ni ọwọ-rere ṣugbọn ni ìmúrasín lọwọ gbogbo eniyan ti o wa nibẹ lati fihan kaadi idanimọ NAFDAC wọn ati aṣẹ ayẹwo kikọ wọn ṣaaju ki eyikeyi nkan to gbe.",
              "Ti wọn ko le tabi ko fẹ fihan idanimọ to wulo ati aṣẹ kikọ, sọ ni kedere: 'Emi ko fọwọsi yiyọ eyikeyi ẹru titi ti ẹ o fi mú idanimọ to dara ati aṣẹ kikọ wá.'",
              "Ti wọn ba tẹsiwaju, má dẹ́ wọn ni ara ṣugbọn pe awọn ẹlẹri — awọn oniṣowo miiran tabi awọn onibara — ti o bẹrẹ si gba fidio lori foonu rẹ ti o ba jẹ ailewu.",
              "Beere fun riri imugba ti o ṣe alaye fun gbogbo nkan ti a yọ kuro, ti o darukọ orukọ ọja, iye, ati nọmba ìparọ.",
              "Lẹhin iṣẹlẹ naa, lọ si ọfiisi agbegbe NAFDAC ti o sunmọ julọ pẹlu riri rẹ ki o gbe ẹdun alaye ti a ko ba tẹle ilana to dara.",
            ],
            ha: [
              "Kasance cikin natsuwa. Yi hankali amma da ƙarfi ka nemi kowane mutum da ke can nuna katin shaida na NAFDAC da izinin bincike a rubuce kafin a motsa komai.",
              "Idan ba za su iya ko ba sa son nuna ingantaccen shaida da izini a rubuce ba, fada a sarari: 'Ba na ba da izinin cire kaya har sai kun samar da ingantaccen shaida da izini a rubuce.'",
              "Idan sun ci gaba, kada ka yi turjiya jiki amma kira shaidu — sauran masu kasuwanci ko masu siye — ka fara yin rikodin a wayarka idan lafiya ta bada damar.",
              "Nemi kirtanin kwace mai cikakken bayani ga kowane abu da aka cire, yana lissafin sunan kaya, adadi, da lambar ɗari.",
              "Bayan lamarin, je ofishin yankin NAFDAC da ke kusa da kirtaninka ka shigar da ƙara ta hukuma idan ba a bi tsarin da ya dace ba.",
            ],
            ig: [
              "Nọ n'udo. Jụọ n'ụzọ dị mfe mana n'ụzọ siri ike onye ọ bụla dị ebe ahụ ka ha gosipụta kaadị njirimara NAFDAC ha na ikike nyocha edere n'akwụkwọ ha tupu a bufee ihe ọ bụla.",
              "Ọ bụrụ na ha enweghị ike ma ọ bụ ha achọghị igosi njirimara dị mma na ikike edere n'akwụkwọ, kwuo n'ụzọ doro anya: 'Anaghị m nye ikike wepu ngwongwo ọ bụla tupu ị wepụta njirimara kwesịrị ekwesị na ikike edere n'akwụkwọ.'",
              "Ọ bụrụ na ha na-aga n'ihu, ghara itogharị ha n'ahụ mana kpọọ ndị ọ bụ ha ga-akaebe — ndị ahịa ọzọ ma ọ bụ ndị ọrịa — wee malite idebanye ihe na ekwenti gị ọ bụrụ na ọ dị mma.",
              "Rịọ recept nchekwa nke na-edepụta ihe niile a were, na-ede aha ngwongwo, ọnụ ọgụgụ, na ọnụ ọgụgụ ụdị.",
              "Mgbe ihe ahụ gasịrị, gaa n'ọfịs mpaghara NAFDAC dị nso ọtụtụ na recept gị wee deba mkpesa ọrụ ma ọ bụrụ na a sọghị usoro kwesịrị ekwesị.",
            ],
          },
        },
      ],
    },

    {
      slug: "tax-levy-rights",
      title: {
        en: "Tax & Levy Rights for Traders",
        pcm: "Tax and Levy Rights for Traders",
        yo: "Awọn Ẹtọ Owo-ori ati Adeta fun Awọn Oniṣowo",
        ha: "Haƙƙoƙin Haraji da Ƙodon Masu Kasuwanci",
        ig: "Ikike Ụtụ Isi na Ụtụ maka Ndị Ahịa",
      },
      summary: {
        en: "Tax officials from FIRS, State Internal Revenue Service, and local government levy collectors have defined powers. Many unofficial collectors demand arbitrary 'levies.' Traders have the right to demand receipts for all official payments. No government official can demand cash without issuing an official receipt. Multiple taxation of the same business activity is illegal. The FIRS Act and relevant state tax laws govern what is permitted.",
        pcm: "Tax officials from FIRS, State Internal Revenue Service, and local government levy collectors get defined powers. Many unofficial collectors dey demand arbitrary 'levies.' Traders get right to demand receipt for all official payments. No government official fit demand cash without giving official receipt. Multiple taxation of same business activity na illegal. FIRS Act and relevant state tax laws govern wetin dem fit do.",
        yo: "Awọn oṣiṣẹ owo-ori lati FIRS, Iṣẹ Owo-ori Ipinle, ati awọn agbowọ adeta ijọba agbegbe ni awọn agbara ti a ṣalaye. Ọpọlọpọ awọn agbowọ ti ko ṣe alaye n'beere awọn 'adeta' aiṣedeede. Awọn oniṣowo ni ẹtọ lati beere awọn riri fun gbogbo awọn sisanwo alaye. Ko si oṣiṣẹ ijọba ti o le beere owo laisi fifun riri alaye. Owo-ori pupọ fun iṣẹ iṣowo kanna jẹ aiofin. Ofin FIRS ati awọn ofin owo-ori ipinle to wulo n'sakoso ohun ti a gba laaye.",
        ha: "Jami'an haraji daga FIRS, Sabis na Haraji na Cikin Gida na Jiha, da masu tattara kuɗin gari na gwamnatin gari suna da ikon da aka ayyana. Masu tattara ba hukuma da yawa suna neman 'kuɗaɗen gari' na yanke-yanke. Masu kasuwanci na da haƙƙin neman kirtani ga duk biyan kuɗi na hukuma. Babu jami'in gwamnati da zai iya neman kuɗi ba tare da ba da kirtani na hukuma ba. Haraji da yawa kan ayyukan kasuwanci ɗaya haramun ne. Dokar FIRS da dokokin haraji na jiha masu dacewa suna tsara abin da aka yarda da shi.",
        ig: "Ndị ọrụ ụtụ isi sitere na FIRS, Ọrụ Ego Ime Ala Steeti, na ndị na-anakọta ụtụ gọọmenti obodo nwere ikike a kọwara. Ọtụtụ ndị na-anakọta n'ụzọ na-abụghị ọrụ na-arịọ 'ụtụ' n'ụzọ ọ bụla. Ndị ahịa nwere ikike ịrịọ recept maka ụgwọ ọrụ niile. Ọ dịghị onye ọrụ gọọmenti nwere ike ịrịọ ego na-enweghị inyesite recept ọrụ. Ụtụ isi ọtụtụ maka ọrụ azụmahịa otu ahụ bụ ihe na-ezighị ezi. FIRS Act na iwu ụtụ isi steeti ndị kwesịrị ekwesị na-achịkwa ihe a kwere.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Assess and collect taxes or levies that are authorised by specific legislation",
          "Request to see a trader's business registration documents and tax identification number (TIN)",
          "Issue official demand notices for unpaid taxes with a specified payment period",
          "Enforce payment through formal legal process after issuing proper notices",
          "Conduct audits of business records with prior written notice",
        ],
        pcm: [
          "Assess and collect taxes or levies wey specific legislation authorise",
          "Ask to see trader business registration documents and tax identification number (TIN)",
          "Issue official demand notice for unpaid taxes with specified payment period",
          "Enforce payment through formal legal process after issuing proper notices",
          "Conduct audit of business records with prior written notice",
        ],
        yo: [
          "Ṣe iṣiro ati gba awọn owo-ori tabi awọn adeta ti ofin kan pato fọwọsi",
          "Beere lati rii awọn iwe iforukọsilẹ iṣowo oniṣowo ati nọmba idanimọ owo-ori (TIN)",
          "Fun awọn akiyesi ibeere alaye fun awọn owo-ori ti a ko san pẹlu akoko isanwo ti a ṣalaye",
          "Fi ipa mu isanwo nipasẹ ilana ofin alaye lẹhin fifun awọn akiyesi to dara",
          "Ṣe ayẹwo awọn igbasilẹ iṣowo pẹlu akiyesi kikọ iṣaaju",
        ],
        ha: [
          "Tantance da tattara haraji ko ƙodon da takamaiman doka ta ba da izini",
          "Nemi ganin takardu na rajistan kasuwanci na mai kasuwanci da lambar ganowa ta haraji (TIN)",
          "Ba da sanarwa ta hukuma don harajin da ba a biya ba tare da takamaiman lokacin biya",
          "Tilasta biya ta hanyar tsarin doka na hukuma bayan ba da sanarwa ta hukuma",
          "Gudanar da bincike na bayanan kasuwanci tare da sanarwa a rubuce kafin haka",
        ],
        ig: [
          "Nyocha na anakọta ụtụ isi ma ọ bụ ụtụ ndị iwu ụfọdụ kwere",
          "Rịọ ka ị hụ akwụkwọ ndebanye aha azụmahịa nke onye ahịa na ọnụ ọgụgụ njirimara ụtụ isi (TIN)",
          "Wepụta ọkwa arọ ọrụ maka ụtụ isi a na-akwụghị na oge ịkwụ ụgwọ a kapịchara",
          "Machibido ịkwụ ụgwọ site na usoro iwu ọrụ mgbe emechara ịwepụ ọkwa kwesịrị ekwesị",
          "Meere nyocha akwụkwọ azụmahịa na ọkwa edere n'akwụkwọ tupu oge",
        ],
      },
      cannotDo: {
        en: [
          "Demand cash payment without issuing an official government receipt at the same time",
          "Collect any levy or tax that is not backed by a specific law or by-law",
          "Subject the same business activity to multiple taxes from different government bodies (multiple taxation)",
          "Seize or lock up a business premises without a court order",
          "Physically threaten, intimidate, or assault a trader to force payment",
        ],
        pcm: [
          "Demand cash payment without giving official government receipt at same time",
          "Collect levy or tax wey no get specific law or by-law to back am",
          "Put same business activity under multiple taxes from different government bodies (multiple taxation)",
          "Seize or lock up business premises without court order",
          "Physically threaten, intimidate, or beat trader to force payment",
        ],
        yo: [
          "Beere owo owo laisi fifun riri ijọba alaye ni akoko kanna",
          "Gba adeta tabi owo-ori eyikeyi ti ofin tabi by-law kan pato ko ṣe atilẹyin",
          "Fi iṣẹ iṣowo kanna labẹ awọn owo-ori pupọ lati awọn ẹgbẹ ijọba oriṣiriṣi (owo-ori pupọ)",
          "Gba tabi tii awọn ọkọọkan ile-iṣẹ laisi aṣẹ ile-ẹjọ",
          "Halẹ, ṣe ìdọjútì, tabi kọlu oniṣowo ni ara lati fi ipa mu isanwo",
        ],
        ha: [
          "Nemi biyan kuɗi ba tare da ba da kirtanin gwamnati na hukuma a lokaci guda ba",
          "Tattara wani ƙodo ko haraji da ba takamaiman doka ko ƙa'ida ta goyi bayansa ba",
          "Sanya ayyukan kasuwanci ɗaya a ƙarƙashin haraji da yawa daga ƙungiyoyin gwamnati daban-daban (haraji mai yawa)",
          "Kwace ko kulle wurin kasuwanci ba tare da umurnin kotu ba",
          "Barazana ta jiki, tsoratar da shi, ko duka mai kasuwanci don tilasta biya",
        ],
        ig: [
          "Rịọ ịkwụ ụgwọ ego na-enweghị inyesite recept gọọmenti ọrụ n'oge ahụ ahụ",
          "Anakọta ụtụ ma ọ bụ ụtụ isi ọ bụla nke iwu ma ọ bụ usoro ụfọdụ adighi na-akwado ya",
          "Tinye ọrụ azụmahịa otu ahụ n'ime ụtụ isi ọtụtụ sitere n'ụlọ ọrụ gọọmenti dị iche iche (ụtụ isi ọtụtụ)",
          "Chekwa ma ọ bụ mechie ụlọ azụmahịa na-enweghị iwu ụlọ ikpe",
          "Iyi egwu n'ahụ, imegbu ma ọ bụ ịkụ onye ahịa n'ahụ iji machibido ịkwụ ụgwọ",
        ],
      },
      whatToDo: {
        en: [
          "Always ask for the collector's full name, the agency they represent, and their official identity card before any payment",
          "Demand and keep an official government receipt for every single payment — a handwritten note is not a valid receipt",
          "If you suspect a levy is unofficial or illegal, ask the collector to show you the law or by-law that authorises it",
          "Keep a record of all payments made: date, amount, receipt number, and collector's name",
          "If you face multiple taxation, report to the Joint Tax Board (JTB) or your State Internal Revenue Service",
        ],
        pcm: [
          "Always ask for collector full name, the agency dem represent, and their official ID card before any payment",
          "Demand and keep official government receipt for every single payment — handwritten note no be valid receipt",
          "If you suspect levy dey unofficial or illegal, ask collector to show you the law or by-law wey authorise am",
          "Keep record of all payments: date, amount, receipt number, and collector name",
          "If you face multiple taxation, report to Joint Tax Board (JTB) or your State Internal Revenue Service",
        ],
        yo: [
          "Beere nigbagbogbo fun orukọ kikun ti agbowọ, ile-iṣẹ ti wọn ṣojuuṣe, ati kaadi idanimọ alaye wọn ṣaaju isanwo eyikeyi",
          "Beere fun ati pa riri ijọba alaye fun gbogbo sisanwo — akọsilẹ ti a kọ pẹlu ọwọ kii ṣe riri to wulo",
          "Ti o ba fura pe adeta kii ṣe alaye tabi aiofin, beere agbowọ lati fihan ọ ofin tabi by-law ti o fọwọsi rẹ",
          "Pa igbasilẹ gbogbo awọn isanwo: ọjọ, iye, nọmba riri, ati orukọ agbowọ",
          "Ti o ba dojuko owo-ori pupọ, ròyìn si Igbimọ Owo-ori Apapọ (JTB) tabi Iṣẹ Owo-ori Ipinle rẹ",
        ],
        ha: [
          "Koyaushe nemi cikakken sunan mai tattara, hukumar da suke wakilta, da katin shaida na hukuma kafin kowane biya",
          "Nemi kuma riƙe kirtanin gwamnati na hukuma ga duk biyan kuɗi — rubutaccen bayanin da hannu ba kirtani mai inganci ba ne",
          "Idan kana zargin ƙodon ba hukuma ne ko haramun, nemi mai tattara ya nuna maka doka ko ƙa'idar da ke ba da izinin sa",
          "Kiyaye rikodin duk biyan kuɗi: kwanan wata, adadi, lambar kirtani, da sunan mai tattara",
          "Idan kana fuskantar haraji mai yawa, kai rahoto ga Hukumar Haraji ta Haɗin gwiwa (JTB) ko Sabis ɗin Haraji na Jiha",
        ],
        ig: [
          "Rịọ mgbe niile aha zuru oke nke onye na-anakọta ahụ, ụlọ ọrụ ha na-anọchite anya ya, na kaadị njirimara ọrụ ha tupu ịkwụ ụgwọ ọ bụla",
          "Rịọ ma chekwaa recept gọọmenti ọrụ maka ịkwụ ụgwọ niile — akwụkwọ edere n'aka abụghị recept dị mma",
          "Ọ bụrụ na ị na-echegbu onwe gị na ụtụ ahụ abụghị ọrụ ma ọ bụ na-ezighị ezi, rịọ onye na-anakọta ka ha gosipụta gị iwu ma ọ bụ usoro nke na-atọ ikike ya",
          "Debe ndekọ maka ịkwụ ụgwọ niile: ụbọchị, ọnụ ego, ọnụ ọgụgụ recept, na aha onye na-anakọta ahụ",
          "Ọ bụrụ na ị na-ezugbo ụtụ isi ọtụtụ, kọọ na Joint Tax Board (JTB) ma ọ bụ Ọrụ Ego Ime Ala Steeti gị",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not pay any levy or tax without receiving an official printed receipt — paying without a receipt means you have no proof",
          "Do not assume a levy is legitimate just because a person is wearing a uniform or carrying a clipboard",
          "Do not allow your goods or shop to be seized for tax default without first receiving a formal written demand notice",
          "Do not ignore official tax demand notices — respond in writing within the stated deadline or seek legal advice",
        ],
        pcm: [
          "No pay any levy or tax without receiving official printed receipt — payment without receipt means you get no proof",
          "No assume levy dey legitimate just because person dey wear uniform or carry clipboard",
          "No allow dem seize your goods or shop for tax default without first receiving formal written demand notice",
          "No ignore official tax demand notice — respond in writing within the stated deadline or seek legal advice",
        ],
        yo: [
          "Má san adeta tabi owo-ori eyikeyi laisi gbigba riri ti a tẹ alaye — isanwo laisi riri tumọ si pe o ko ni ẹri",
          "Má gba bi adeta jẹ to ti ẹnikan kan ba wọ aṣọ aṣọ-iṣẹ tabi gbe clipboard",
          "Má gba laaye fun ẹru rẹ tabi ile itaja lati jẹ imugba fun aisi-isanwo owo-ori laisi gbigba akiyesi ibeere kikọ alaye ni akọkọ",
          "Má fojufori awọn akiyesi ibeere owo-ori alaye — dahun ni kikọ laarin akoko ti a ṣalaye tabi wa imọran ofin",
        ],
        ha: [
          "Kada ka biya wani ƙodo ko haraji ba tare da samun kirtani na hukuma da aka buga ba — biya ba tare da kirtani ba yana nufin ba ka da hujja",
          "Kada ka ɗauki ƙodon a matsayin na doka kawai saboda mutum yana sanya rigar aiki ko ɗauke da allon rubutu",
          "Kada ka ba da izinin kwace kayanka ko shagonka don rashin biya haraji ba tare da samun sanarwar neman hukuma a rubuce da farko ba",
          "Kada ka yi watsi da sanarwar neman haraji ta hukuma — amsa a rubuce a cikin ƙa'idar da aka ayyana ko nemi shawara ta doka",
        ],
        ig: [
          "Akwụkwala ụtụ ma ọ bụ ụtụ isi ọ bụla na-anabataghị recept ebipụtara ọrụ — ịkwụ ụgwọ na-enweghị recept pụtara na ị nweghị ihe àmà",
          "Elekwekwala na ụtụ ahụ dị ezigbo nke ọma n'ihi na onye ahụ na-agba akwa ụlọ ọrụ ma ọ bụ na-ebu ihe ide ihe",
          "Akwụkwala ka a chekwa ngwongwo gị ma ọ bụ ụlọ ahịa maka enweghị ịkwụ ụgwọ ụtụ isi na-anabataghị ọkwa arọ edere n'akwụkwọ ọrụ nke mbụ",
          "Anakwụkwala ọkwa arọ ụtụ isi ọrụ — zaghachi n'ihe ede ede n'ime oge a kapịchara ma ọ bụ chọọ ndụmọdụ iwu",
        ],
      },
      laws: [
        {
          name: "Federal Inland Revenue Service (Establishment) Act 2007",
          section: "Section 8 & 25",
          plainEnglish: {
            en: "Section 8 empowers FIRS to assess, collect, and account for taxes. Section 25 requires that all revenue collected must be receipted. Any collection without an official receipt is unlawful.",
            pcm: "Section 8 give FIRS power to assess, collect, and account for taxes. Section 25 say all revenue collected must get receipt. Any collection without official receipt dey unlawful.",
            yo: "Abala 8 fun FIRS ni agbara lati ṣe iṣiro, gba, ati ṣe iṣiro fun awọn owo-ori. Abala 25 nilo pe gbogbo owo oya ti a gba gbọdọ ni riri. Gbigba eyikeyi laisi riri alaye jẹ aiofin.",
            ha: "Sashi na 8 ya ba FIRS ikon tantance, tattara, da yin hisabi na haraji. Sashi na 25 yana buƙatar duk kuɗin da aka tattara dole a ba da kirtani. Duk wata tattarawa ba tare da kirtani na hukuma ba bisa ƙa'ida ba ce.",
            ig: "Nkeji 8 na-enye FIRS ikike nyocha, ịnakọta, na ịgwa akọọnt maka ụtụ isi. Nkeji 25 na-achọ na a ga-enye recept maka ego niile a nakọtara. Ịnakọta ọ bụla na-enweghị recept ọrụ bụ ihe na-ezighị ezi.",
          },
        },
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 162 & 163",
          plainEnglish: {
            en: "These sections regulate how taxes are shared between the federal, state, and local governments. They confirm that any tax must have a clear constitutional or legislative basis — no government body can invent its own levies.",
            pcm: "These sections regulate how dem share taxes between federal, state, and local government. Dem confirm say any tax must have clear constitutional or legislative basis — no government body fit invent their own levies.",
            yo: "Awọn abala wọnyi ṣakoso bii a ṣe pin awọn owo-ori laarin awọn ijọba apapo, ipinle, ati agbegbe. Wọn jẹrisi pe owo-ori eyikeyi gbọdọ ni ipilẹ ofin tabi isofin to kedere — ko si ẹgbẹ ijọba ti o le ṣẹda awọn adeta tirẹ.",
            ha: "Waɗannan sassa suna tsara yadda ake raba haraji tsakanin gwamnatoci na tarayya, jiha, da gari. Sun tabbatar da cewa dole ne haraji ya sami tushen tsarin mulki ko na majalisar dokoki a sarari — babu ƙungiyar gwamnati da za ta iya ƙirƙirar ƙodonta.",
            ig: "Nkeji ndị a na-achịkwa otu a na-ekesa ụtụ isi n'etiti gọọmenti etiti, steeti, na obodo. Ha na-akwado na ụtụ isi ọ bụla ga-enweghị ntọala iwu ma ọ bụ ochiche iwu doro anya — ọ dịghị ụlọ ọrụ gọọmenti nwere ike ịmepụta ụtụ nke ya.",
          },
        },
        {
          name: "Taxes and Levies (Approved List for Collection) Act Cap T2 LFN 2004",
          section: "Schedule",
          plainEnglish: {
            en: "This Act provides the approved list of taxes each tier of government — federal, state, and local — is permitted to collect. Any levy not on this list is illegal. Traders can use this list to challenge unofficial levies.",
            pcm: "This Act provide approved list of taxes each tier of government — federal, state, and local — fit collect. Any levy wey no dey this list na illegal. Traders fit use this list to challenge unofficial levies.",
            yo: "Ofin yii pese atokọ ti a fọwọsi ti awọn owo-ori ti ipele kọọkan ti ijọba — apapo, ipinle, ati agbegbe — gba laaye lati gba. Adeta eyikeyi ti ko si ninu atokọ yii jẹ aiofin. Awọn oniṣowo le lo atokọ yii lati tako awọn adeta ti ko ṣe alaye.",
            ha: "Wannan Doka tana ba da ingantaccen jerin harajin da kowane mataki na gwamnati — tarayya, jiha, da gari — an yarda ya tattara. Duk wani ƙodo da ba ya cikin wannan jerin haramun ne. Masu kasuwanci za su iya amfani da wannan jerin don ƙalubalantar ƙodaɗen da ba na hukuma ba.",
            ig: "Iwu a na-enye ndepụta ụtụ isi akwadoro nke ọkwa ọ bụla nke gọọmenti — etiti, steeti, na obodo — nwere ikike ịnakọta. Ụtụ ọ bụla nke anaghị adị n'ndepụta a bụ ihe na-ezighị ezi. Ndị ahịa nwere ike iji ndepụta a ịga n'ụzọ megide ụtụ na-abụghị ọrụ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A man in a yellow local government vest arrives at your stall demanding ₦5,000 as a 'development levy.' He has no identity card and offers only a handwritten piece of paper as a receipt.",
            pcm: "One man wearing yellow local government vest come your stall dey demand ₦5,000 as 'development levy.' He no carry ID card and him only offer handwritten paper as receipt.",
            yo: "Ọkunrin kan ti o wọ aṣọ ipọn ijọba agbegbe de si stọl rẹ ti o n'beere ₦5,000 gẹgẹ bi 'adeta idagbasoke.' Ko ni kaadi idanimọ ati pe o pese nikan iwe ti a kọ pẹlu ọwọ gẹgẹ bi riri.",
            ha: "Wani mutum da ke sanya rigar gwamnatin gari ta rawaya ya zo a tabararku yana neman ₦5,000 a matsayin 'ƙodon ci gaba.' Ba shi da katin shaida kuma yana ba da rubutaccen takarda da hannu kawai a matsayin kirtani.",
            ig: "Otu nwoke na-eyi ịkwa gọọmenti obodo ọchịcha ọbara ọbara bịara n'ụlọ ọ dị gị na-arịọ ₦5,000 dị ka 'ụtụ mmepe.' O nweghị kaadị njirimara ma ọ naṣị akwụkwọ edere n'aka ka recept.",
          },
          steps: {
            en: [
              "Politely ask the man to show you his official identity card and the name of the specific law that authorises this 'development levy.'",
              "If he cannot show you a valid ID or name the authorising law, tell him clearly: 'I cannot pay a levy that has no legal basis. Please show me the law or come back with your supervisor and a proper receipt book.'",
              "Do not pay cash on the basis of a handwritten note — a handwritten note is not an official government receipt.",
              "If he becomes aggressive, do not escalate physically. Note his description and report to your local government secretariat with a written complaint.",
              "Check the Taxes and Levies (Approved List for Collection) Act schedule to confirm whether this levy is on the approved list.",
            ],
            pcm: [
              "Politely ask the man to show you his official ID card and the name of the specific law wey authorise this 'development levy.'",
              "If he no fit show you valid ID or name the law, tell him clearly: 'I cannot pay levy wey no get legal basis. Show me the law or come back with your supervisor and proper receipt book.'",
              "No pay cash because of handwritten note — handwritten note no be official government receipt.",
              "If he become aggressive, no escalate physically. Note his description and report to local government secretariat with written complaint.",
              "Check the Taxes and Levies (Approved List for Collection) Act schedule to confirm if this levy dey on the approved list.",
            ],
            yo: [
              "Beere ni ọwọ-rere fun ọkunrin naa lati fihan ọ kaadi idanimọ alaye rẹ ati orukọ ofin kan pato ti o fọwọsi 'adeta idagbasoke' yii.",
              "Ti o ko le fihan ọ ID to wulo tabi darukọ ofin ti o fọwọsi, sọ fun u ni kedere: 'Mi o le san adeta ti ko ni ipilẹ ofin. Jọwọ fihan mi ofin naa tabi pada pẹlu olori rẹ ati iwe riri to dara.'",
              "Má san owo ni ipilẹ akọsilẹ ti a kọ pẹlu ọwọ — akọsilẹ ti a kọ pẹlu ọwọ kii ṣe riri ijọba alaye.",
              "Ti o ba di ibinu, má gbe ni ara. Akiyesi apejuwe rẹ ki o ròyìn si ile-iṣẹ ijọba agbegbe rẹ pẹlu ẹdun alaye kikọ.",
              "Ṣayẹwo iṣeto ti Ofin Awọn owo-ori ati Awọn adeta (Atokọ Ti a Fọwọsi fun Gbigba) lati jẹrisi boya adeta yii wa lori atokọ ti a fọwọsi.",
            ],
            ha: [
              "Yi hankali ka nemi mutumin ya nuna maka katin shaida na hukuma da sunan takamaiman dokar da ke ba da izinin wannan 'ƙodon ci gaba.'",
              "Idan ba zai iya nuna maka ingantaccen shaida ko sanya suna dokar izini ba, fada masa a sarari: 'Ba zan iya biya ƙodo wanda ba shi da tushen doka ba. Da fatan za ka nuna mini doka ko dawo da babanka da ingantaccen littafin kirtani.'",
              "Kada ka biya kuɗi saboda rubutaccen bayanin da hannu — rubutaccen bayanin da hannu ba kirtanin gwamnati na hukuma ba ne.",
              "Idan ya zama mai tsanani, kada ka ƙara da jiki. Rubuta bayananshi ka kai rahoto ga sakatariyar gwamnatin gari tare da ƙarar rubuce.",
              "Duba jadawalin Dokar Haraji da Ƙodon (Ingantaccen Jerin don Tattarawa) don tabbatar ko wannan ƙodon yana cikin jerin da aka amince da shi.",
            ],
            ig: [
              "Jụọ nwoke ahụ n'ụzọ dị mfe ka ha gosipụta gị kaadị njirimara ọrụ ha na aha iwu ụfọdụ nke na-atọ 'ụtụ mmepe' a ikike.",
              "Ọ bụrụ na ha enweghị ike igosi gị ID dị mma ma ọ bụ ịkpọ aha iwu nke na-enye ikike, kwuo ya n'ụzọ doro anya: 'Enweghị m ike ịkwụ ụtụ nke enweghị ntọala iwu. Biko gosipụta m iwu ahụ ma ọ bụ laghachi na onyeisi gị na akwụkwọ recept kwesịrị ekwesị.'",
              "Akwụkwala ego n'ihe ndabere akwụkwọ edere n'aka — akwụkwọ edere n'aka abụghị recept gọọmenti ọrụ.",
              "Ọ bụrụ na ọ na-aghọ onye iwe, ghara ịbawanye ya n'ahụ. Dee nkọwa ya wee kọọ na secretariat gọọmenti obodo gị na mkpesa edere n'akwụkwọ.",
              "Lelee ndepụta Taxes and Levies (Approved List for Collection) Act iji kwado ma ọ bụrụ na ụtụ a dị n'ndepụta akwadoro.",
            ],
          },
        },
      ],
    },

    {
      slug: "consumer-goods-protection",
      title: {
        en: "Protection from False Accusations & Goods Seizure",
        pcm: "Protection from False Accusation and Goods Seizure",
        yo: "Aabo lati Awọn Ẹsun Eke ati Imugba Ẹru",
        ha: "Kariya daga Tuhumomi na Karya da Kwace Kaya",
        ig: "Nchedo Sitere na Ebubo Ụgha na Nchekwa Ngwongwo",
      },
      summary: {
        en: "Traders have the right to protection against false accusations of selling fake or substandard goods. The Standards Organisation of Nigeria (SON) and the Federal Competition and Consumer Protection Commission (FCCPC, formerly CPC) have enforcement powers but must follow due process. Any seizure of goods must be backed by proper legal authority. Traders have the right to request the legal basis for any seizure and to receive an itemised receipt.",
        pcm: "Traders get right to protection against false accusation of selling fake or substandard goods. Standards Organisation of Nigeria (SON) and Federal Competition and Consumer Protection Commission (FCCPC, formerly CPC) get enforcement powers but dem must follow due process. Any seizure of goods must have proper legal authority. Traders get right to request the legal basis for any seizure and to receive itemised receipt.",
        yo: "Awọn oniṣowo ni ẹtọ si aabo lodi si awọn ẹsun eke ti tita awọn ọja iro tabi ti ko ba ipele mu. Ajo Awọn Iṣedede ti Orile-ede Naijiria (SON) ati Igbimọ Aabo Idije ati Olumulo ti Apapo (FCCPC, tẹlẹ CPC) ni awọn agbara imuse ṣugbọn gbọdọ tẹle ilana to dara. Imugba ẹru eyikeyi gbọdọ jẹ atilẹyin nipasẹ aṣẹ ofin to dara. Awọn oniṣowo ni ẹtọ lati beere ipilẹ ofin fun imugba eyikeyi ati lati gba riri ti o ṣe alaye.",
        ha: "Masu kasuwanci na da haƙƙin kariya daga tuhumomi na karya na sayar da kayayyakin ƙarya ko marasa inganci. Hukumar Ƙa'idojin Najeriya (SON) da Hukumar Tarayya ta Gasa da Kare Mabukaci (FCCPC, tsohuwar CPC) suna da ikon tilastawa amma dole su bi tsarin da ya dace. Dole ne a goyi bayan kwace kaya da ikon doka mai dacewa. Masu kasuwanci na da haƙƙin neman tushen doka na kowane kwacewa da karɓar kirtani mai cikakken bayani.",
        ig: "Ndị ahịa nwere ikike nchedo megide ebubo ụgha nke ire ngwongwo ụgha ma ọ bụ ndị na-adịghị ọkpụkpụ. Standards Organisation of Nigeria (SON) na Federal Competition and Consumer Protection Commission (FCCPC, bụbu CPC) nwere ikike machibido mana ha ga-eso usoro kwesịrị ekwesị. Nchekwa ngwongwo ọ bụla ga-enweghị ikike iwu kwesịrị ekwesị na-akwado ya. Ndị ahịa nwere ikike ịrịọ ntọala iwu maka nchekwa ọ bụla ma ịnata recept nke na-edepụta ihe niile.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Inspect products at a trader's premises to check compliance with Nigerian standards (SON officers)",
          "Collect product samples for testing at an accredited laboratory with proper documentation",
          "Issue compliance notices requiring a trader to remedy a specific deficiency within a stated period",
          "Seize genuinely counterfeit, adulterated, or dangerous products by issuing an official itemised receipt",
          "Commence prosecution through proper legal channels for confirmed violations",
        ],
        pcm: [
          "Inspect products at trader premises to check compliance with Nigerian standards (SON officers)",
          "Collect product samples for testing at accredited lab with proper documentation",
          "Issue compliance notice requiring trader to fix specific deficiency within stated period",
          "Seize genuinely fake, adulterated, or dangerous products by issuing official itemised receipt",
          "Start prosecution through proper legal channels for confirmed violations",
        ],
        yo: [
          "Ṣayẹwo awọn ọja ni awọn ọkọọkan oniṣowo lati ṣayẹwo ibamu pẹlu awọn iṣedede Naijiria (awọn oṣiṣẹ SON)",
          "Gba awọn ayẹwo ọja fun idanwo ni yàrá ti a fọwọsi pẹlu iwe to dara",
          "Fun awọn akiyesi ibamu ti o nilo oniṣowo lati tun aisedede kan pato ṣe laarin akoko ti a sọ",
          "Gba awọn ọja iro to gidi, ti o dapọ, tabi ti o lewu nipa fifun riri imugba alaye to wulo",
          "Bẹrẹ ẹjọ nipasẹ awọn ikanni ofin to dara fun awọn ìka ti a jẹrisi",
        ],
        ha: [
          "Duba kayayyaki a wuraren masu kasuwanci don duba bin daidaiton Najeriya (jami'an SON)",
          "Tattara samfuran kaya don gwajin dakin gwaje-gwaje da aka amince da shi tare da takardu na hukuma",
          "Ba da sanarwar bin doka da ke buƙatar mai kasuwanci ya gyara wani rashi na musamman a cikin takamaiman lokaci",
          "Kwace kayayyakin ƙarya na gaske, waɗanda aka gurbata, ko masu haɗari ta hanyar ba da kirtani na hukuma mai cikakken bayani",
          "Fara ƙara ta hanyoyin doka na hukuma don tabbatattun take-take",
        ],
        ig: [
          "Nyocha ngwongwo n'ụlọ ọrụ onye ahịa iji lelee nkwado na ọkọlọtọ Nigeria (ndị ọrụ SON)",
          "Nweta ihe nlele ngwongwo maka nnwale n'ụlọ nyocha nwere ikike na akwụkwọ kwesịrị ekwesị",
          "Wepụta ọkwa nkwado na-achọ ka onye ahịa dozie mmefu ụfọdụ n'ime oge a kapịchara",
          "Chekwa ngwongwo ụgha n'ezie, ndị a tịkọrọ, ma ọ bụ ndị dị ize ndụ site n'ịwepụta recept nchekwa ọrụ nke na-edepụta ihe niile",
          "Bido mkpe site na ụzọ iwu kwesịrị ekwesị maka mmebi akwadoro",
        ],
      },
      cannotDo: {
        en: [
          "Seize goods based solely on suspicion without a proper inspection and written documentation",
          "Destroy or dispose of seized goods without a court order authorising destruction",
          "Demand money or 'settlement' to overlook alleged violations instead of following legal process",
          "Seize goods without issuing an itemised receipt listing every item taken and the reason for seizure",
          "Accuse a trader of selling fake goods and seize stock without first conducting or producing laboratory test results",
        ],
        pcm: [
          "Seize goods based only on suspicion without proper inspection and written documentation",
          "Destroy or dispose seized goods without court order authorising destruction",
          "Demand money or 'settlement' to overlook alleged violations instead of following legal process",
          "Seize goods without issuing itemised receipt listing every item and reason for seizure",
          "Accuse trader of selling fake goods and seize stock without first conducting or producing lab test results",
        ],
        yo: [
          "Gba ẹru ni ipilẹ ifura nikan laisi ayẹwo to dara ati iwe kikọ",
          "Pa tabi sọ awọn ẹru ti a gba nù laisi aṣẹ ile-ẹjọ ti o fun laṣẹ iparun",
          "Beere owo tabi 'ipinnu' lati fojufori awọn ìka ti a fi ẹsun dipo tẹle ilana ofin",
          "Gba ẹru laisi fifun riri ti o ṣe alaye ti o ṣe atokọ gbogbo nkan ti a gba ati idi fun imugba",
          "Fi ẹsun oniṣowo ti tita awọn ọja iro ati gba ẹru laisi ṣiṣe tabi ṣẹda awọn abajade idanwo yàrá ni akọkọ",
        ],
        ha: [
          "Kwace kaya bisa zato kawai ba tare da ingantaccen bincike da takardu a rubuce ba",
          "Lalata ko zubar da kayan da aka kwace ba tare da umurnin kotu da ke ba da izinin lalata ba",
          "Nemi kuɗi ko 'sulhu' don yin watsi da take-taken da ake zargi maimakon bin tsarin doka",
          "Kwace kaya ba tare da ba da kirtani mai cikakken bayani da ke lissafin kowane abu da aka kwace da dalilan kwacewa ba",
          "Tuhumi mai kasuwanci da sayar da kayayyakin ƙarya da kwace kaya ba tare da gudanar da ko samar da sakamakon gwajin dakin gwaje-gwaje da farko ba",
        ],
        ig: [
          "Chekwa ngwongwo dabere naanị echiche na-enweghị nyocha kwesịrị ekwesị na akwụkwọ edere n'akwụkwọ",
          "Nwepu ma ọ bụ wepụ ngwongwo a chekwara na-enweghị iwu ụlọ ikpe nke na-atọ nkwụsịtụ ikike",
          "Rịọ ego ma ọ bụ 'nkwụsị' iji lelee mmebi ndị a buuru n'ụzọ iwu n'ọnọdụ nke ịso usoro iwu",
          "Chekwa ngwongwo na-enweghị ịwepụta recept nke na-edepụta ihe niile nke na-edepụta ihe niile a were na ihe mere nchekwa",
          "Ebubo onye ahịa ire ngwongwo ụgha ma chekwa ngwongwo na-emechaghị ma ọ bụ wepụta nsonaazụ nnwale ụlọ nyocha nke mbụ",
        ],
      },
      whatToDo: {
        en: [
          "Ask the officer to identify themselves, state which agency they represent, and show their official identity card",
          "Ask for the legal basis for any inspection — specifically the law or regulation under which they are operating",
          "If goods are seized, insist on receiving a written, itemised seizure receipt before the officers leave",
          "Document the incident: take photos of the officers, any notices issued, and the goods being removed if it is safe to do so",
          "Contact the SON or FCCPC complaints desk, your trade association, or a lawyer to understand your rights to contest the seizure",
        ],
        pcm: [
          "Ask officer to identify themselves, state which agency dem represent, and show their official ID card",
          "Ask for legal basis for any inspection — specifically the law or regulation dem dey operate under",
          "If dem seize goods, insist on receiving written, itemised seizure receipt before officers leave",
          "Document the incident: take photos of officers, any notices issued, and goods being removed if safe",
          "Contact SON or FCCPC complaints desk, your trade association, or lawyer to understand your rights to contest the seizure",
        ],
        yo: [
          "Beere oṣiṣẹ lati ṣe idanimọ ara wọn, sọ ẹgbẹ wo ni wọn ṣojuuṣe, ati fihan kaadi idanimọ alaye wọn",
          "Beere fun ipilẹ ofin fun ayẹwo eyikeyi — ni pataki ofin tabi ilana ti wọn n'ṣiṣẹ labẹ rẹ",
          "Ti wọn ba gba ẹru, tẹnumọ lori gbigba riri imugba kikọ, ti o ṣe alaye ṣaaju ki awọn oṣiṣẹ to lọ",
          "Gba akọsilẹ iṣẹlẹ naa: ya awọn aworan ti awọn oṣiṣẹ, awọn akiyesi eyikeyi ti a fun, ati awọn ẹru ti a n'yọ kuro ti o ba jẹ ailewu",
          "Kan si tabili ẹdun SON tabi FCCPC, ẹgbẹ iṣowo rẹ, tabi agbẹjọro lati ni oye awọn ẹtọ rẹ lati tako imugba naa",
        ],
        ha: [
          "Nemi jami'in ya gane kansa, ya bayyana wace hukuma ce yake wakilta, ya nuna katin shaida na hukuma",
          "Nemi tushen doka don kowane bincike — musamman doka ko ka'ida da suke aiki a ƙarƙashinta",
          "Idan an kwace kaya, nace kan karɓar kirtanin kwace a rubuce mai cikakken bayani kafin jami'an su tafi",
          "Rubuta lamarin: dauki hotuna na jami'an, kowane sanarwa da aka ba da, da kayan da ake cire idan lafiya ta bada damar",
          "Tuntubi tebur ƙorau na SON ko FCCPC, ƙungiyar kasuwancinka, ko lauya don fahimtar haƙƙoƙinka na ƙalubalantar kwacen",
        ],
        ig: [
          "Rịọ onye ọrụ ahụ ka ha nọchie onwe ha, kwuo ụlọ ọrụ ha na-anọchite anya ya, ma gosipụta kaadị njirimara ọrụ ha",
          "Rịọ ntọala iwu maka nyocha ọ bụla — ọkachasị iwu ma ọ bụ usoro ndị ha na-arụ ọrụ n'okpuru ya",
          "Ọ bụrụ na a chekwaa ngwongwo, nọkwusị n'ịnata recept nchekwa edere n'akwụkwọ nke na-edepụta ihe niile tupu ndị ọrụ ahụ apụọ",
          "Deechie ihe mere: were foto nke ndị ọrụ ahụ, ọkwa ọ bụla a nyere, na ngwongwo a na-ewepụ ọ bụrụ na ọ dị mma",
          "Kpọtụrụ tebụl mkpesa SON ma ọ bụ FCCPC, ọgbakọ azụmahịa gị, ma ọ bụ ọkàiwu iji ghọta ikike gị ịja esemokwu na nchekwa ahụ",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not pay any money to officers to avoid seizure — this can constitute bribery and will not protect you legally",
          "Do not physically resist a seizure, even if you believe it is unlawful — resist through legal process, not physical force",
          "Do not allow goods to be removed without an itemised receipt; if officers refuse, state clearly that you object and note every item being taken",
          "Do not sign any admission of guilt or confessional statement without consulting a lawyer first",
        ],
        pcm: [
          "No pay any money to officers to avoid seizure — e fit be bribery and e no go protect you legally",
          "No physically resist seizure even if you believe am dey unlawful — resist through legal process, not physical force",
          "No allow goods to be removed without itemised receipt; if officers refuse, state clearly say you dey object and note every item being taken",
          "No sign any admission of guilt or confessional statement without consulting lawyer first",
        ],
        yo: [
          "Má san owo eyikeyi si awọn oṣiṣẹ lati yago fun imugba — eyi le jẹ ẹbọ ati pe kii yoo daabobo ọ ni ofin",
          "Má dẹ́ imugba ni ara, paapaa ti o ba gbagbọ pe aiofin ni — dojuko nipasẹ ilana ofin, kii ṣe agbara ara",
          "Má gba laaye fun ẹru lati yọ kuro laisi riri ti o ṣe alaye; ti awọn oṣiṣẹ ba kọ, sọ ni kedere pe o n'tako ati ṣe akọsilẹ ohun gbogbo ti a n'gba",
          "Má fọwọsi eyikeyi gbigba ẹsun tabi alaye ijẹwọ laisi imọran agbẹjọro ni akọkọ",
        ],
        ha: [
          "Kada ka biya wani kuɗi ga jami'an don gujewa kwace — wannan na iya kasancewa cin hanci kuma ba zai karɓeka daga batu na doka ba",
          "Kada ka yi turjiya ga kwace ta jiki, ko da kana ganin ba bisa ƙa'ida ba ne — yi turjiya ta hanyar tsarin doka, ba ta ƙarfin jiki ba",
          "Kada ka ba da izinin cire kaya ba tare da kirtani mai cikakken bayani ba; idan jami'an sun ƙi, bayyana a sarari cewa kana ƙin yarda ka rubuta kowane abu da ake ɗauka",
          "Kada ka sanya hannu a kan kowane ikirarin laifi ko sanarwar ƙirari ba tare da tuntubar lauya da farko ba",
        ],
        ig: [
          "Akwụkwala ego ọ bụla ndị ọrụ ahụ iji zere nchekwa — nke a nwere ike ịbụ nnata nnyefe ma ọ gaghị echebe gị n'ụzọ iwu",
          "Atogharịkwala nchekwa n'ahụ, ọ bụ ezie na ị chere na ọ ezighị ezi — tochie site na usoro iwu, ọ bụghị ike ahụ",
          "Akwụkwala ka a wepu ngwongwo na-enweghị recept nke na-edepụta ihe niile; ọ bụrụ na ndị ọrụ ahụ ajụ, kwuo n'ụzọ doro anya na ị na-atọ ya asọ ma dee ihe niile a na-ewere",
          "Adebanyekwala aka n'ihe ọ bụla nkwupụta ikpe ma ọ bụ nkwupụta nkwucha na-ahọchaghị ọkàiwu nke mbụ",
        ],
      },
      laws: [
        {
          name: "Standards Organisation of Nigeria Act Cap S9 LFN 2004",
          section: "Section 17 & 18",
          plainEnglish: {
            en: "Section 17 empowers SON officers to inspect premises and seize products that do not meet Nigerian standards. Section 18 requires that a certificate of analysis be obtained before products are condemned. Officers must identify themselves and follow procedure.",
            pcm: "Section 17 give SON officers power to inspect premises and seize products wey no meet Nigerian standards. Section 18 say dem must obtain certificate of analysis before dem condemn products. Officers must identify themselves and follow procedure.",
            yo: "Abala 17 fun awọn oṣiṣẹ SON ni agbara lati ṣayẹwo awọn ọkọọkan ati gba awọn ọja ti ko pade awọn iṣedede Naijiria. Abala 18 nilo pe wọn gbọdọ gba iwe-ẹri itupalẹ ṣaaju ki awọn ọja to jẹ idalẹbi. Awọn oṣiṣẹ gbọdọ ṣe idanimọ ara wọn ati tẹle ilana.",
            ha: "Sashi na 17 ya ba jami'an SON ikon duba wuraren da kwace kayayyakin da ba su cika ƙa'idojin Najeriya ba. Sashi na 18 yana buƙatar a sami takardar shaida ta nazari kafin a la'anci kayayyaki. Jami'an dole su gane kansu kuma su bi hanya.",
            ig: "Nkeji 17 na-enye ndị ọrụ SON ikike ịnyocha ụlọ ọrụ na ịchekwa ngwongwo ndị na-adịghị nkwado ọkọlọtọ Nigeria. Nkeji 18 na-achọ ka a nweta asambodo nyocha tupu a kpọọ ngwongwo mkpọsa. Ndị ọrụ ga-anọchie onwe ha ma soro usoro.",
          },
        },
        {
          name: "Federal Competition and Consumer Protection Act 2018",
          section: "Section 17, 26 & 127",
          plainEnglish: {
            en: "Section 17 establishes the FCCPC and its mandate to protect consumers. Section 26 gives officers inspection and seizure powers that must be exercised with proper documentation. Section 127 provides that traders have a right to be heard before enforcement action is taken against them.",
            pcm: "Section 17 establish FCCPC and their mandate to protect consumers. Section 26 give officers inspection and seizure powers wey dem must exercise with proper documentation. Section 127 say traders get right to be heard before enforcement action is taken against them.",
            yo: "Abala 17 ṣẹda FCCPC ati iṣẹ rẹ lati daabobo awọn olumulo. Abala 26 fun awọn oṣiṣẹ ni agbara ayẹwo ati imugba ti gbọdọ jẹ imuse pẹlu iwe to dara. Abala 127 pese pe awọn oniṣowo ni ẹtọ lati gbọ ṣaaju ki igbese imuse to gbe lodi si wọn.",
            ha: "Sashi na 17 ya kafa FCCPC da aikin sa na kare mabukaci. Sashi na 26 ya ba jami'an ikon bincike da kwace da dole a yi amfani da su tare da takardu na hukuma. Sashi na 127 ya bayyana cewa masu kasuwanci na da haƙƙin jin muryarsu kafin a ɗauki matakan tilastawa a kansu.",
            ig: "Nkeji 17 na-eme ka FCCPC dị na ọrụ ya nke nchedo ndị na-azụ ahịa. Nkeji 26 na-enye ndị ọrụ ikike nyocha na nchekwa ndị a ga-esi na akwụkwọ kwesịrị ekwesị rụọ ọrụ. Nkeji 127 na-enye ndị ahịa ikike ịnụ naanị ha tupu a were ọrụ machibido megide ha.",
          },
        },
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 36(1)",
          plainEnglish: {
            en: "Every person is entitled to a fair hearing. Before a trader's goods are permanently condemned or they face prosecution, they must be given a proper opportunity to be heard and to challenge the evidence against them.",
            pcm: "Every person get right to fair hearing. Before dem permanently condemn trader goods or dem face prosecution, dem must give trader proper opportunity to be heard and challenge evidence against them.",
            yo: "Gbogbo eniyan ni ẹtọ si igbọran idajọ. Ṣaaju ki ẹru oniṣowo to jẹ idalẹbi titi lai tabi wọn ba dojuko ẹjọ, wọn gbọdọ fun wọn ni anfaani to dara lati gbọ ati lati tako ẹri lodi si wọn.",
            ha: "Kowane mutum na da haƙƙin sauraro mai adalci. Kafin a la'anci kayan mai kasuwanci na dindindin ko su fuskanci ƙara, dole a ba su ingantaccen damar ji muryarsu da kuma ƙalubalantar shaida da ke kan su.",
            ig: "Onye ọ bụla nwere ikike ịnụ n'ụzọ ziri ezi. Tupu a kpọọ ngwongwo onye ahịa mkpọsa n'oge niile ma ọ bụ ha emegbu mkpe, a ga-enye ha ohere kwesịrị ekwesị ịnụ ma ịja esemokwu na ihe àmà ndị megide ha.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Two officers in SON uniforms arrive at your electronics shop. One immediately starts picking items off the shelf, claiming they are substandard, while the other demands you pay ₦20,000 to 'clear the matter quickly.' They have not shown identification.",
            pcm: "Two officers wearing SON uniform come your electronics shop. One immediately start picking items off shelf, claiming dem dey substandard, while the other demand you pay ₦20,000 to 'clear the matter quickly.' Dem no show you any ID.",
            yo: "Awọn oṣiṣẹ meji ti o wọ aṣọ SON de si ile itaja ẹrọ itanna rẹ. Ọkan bẹrẹ lẹsẹkẹsẹ si mu awọn nkan kuro lori selifu, ti o n'sọ pe wọn kii ba ipele mu, lakoko ti ekeji n'beere lọwọ rẹ lati san ₦20,000 lati 'yanju ọrọ naa ni kiakia.' Wọn ko ti fihan idanimọ.",
            ha: "Jami'ai biyu suna sanya rigar SON sun zo shagonka na kayan lantarki. Ɗaya nan da nan ya fara ɗaukar kayan daga shelf, yana iƙirarin su marasa inganci ne, yayin da ɗayan ke neman ka biya ₦20,000 don 'warware lamarin da sauri.' Ba su nuna maka shaida ba.",
            ig: "Ndị ọrụ abụọ na-eyi ịkwa SON bịara n'ụlọ ahịa ihe ọkụ eletrik gị. Otu n'ime ha malitere ozugbo ịkọwa ihe n'efere ahịa, na-ekwu na ha enweghị ọkọlọtọ, ebe nke ọzọ na-arịọ gị ịkwụ ₦20,000 iji 'mechaa ihe ngwa ngwa.' Ha egosighaghị njirimara.",
          },
          steps: {
            en: [
              "Do not pay the ₦20,000. Demanding payment to overlook an alleged violation is corrupt — paying makes you complicit in bribery.",
              "Firmly but calmly say: 'Please show me your official SON identity cards before anything else happens.' Legitimate SON officers will have them.",
              "If they show IDs, note down the names and badge numbers. If they refuse to show ID, state: 'I do not consent to any removal of goods until you identify yourselves properly and show me your written authority.'",
              "If they begin removing items anyway, do not physically restrain them but loudly object, list every item being taken, and take photos or video if it is safe.",
              "Demand a written, itemised seizure receipt before they leave. Refuse to sign any document you have not fully read.",
              "After the incident, call the SON consumer helpline (07057000001) or file a report at the nearest SON office and consult a trade association lawyer.",
            ],
            pcm: [
              "No pay the ₦20,000. Demanding payment to overlook alleged violation dey corrupt — paying make you part of bribery.",
              "Firmly but calmly say: 'Please show me your official SON identity cards before anything else happen.' Legitimate SON officers go get them.",
              "If dem show ID, write down their names and badge numbers. If dem refuse to show ID, say: 'I no consent to any removal of goods until you identify yourselves properly and show me your written authority.'",
              "If dem begin removing items anyway, no physically stop them but loudly object, list every item dem take, and take photos or video if safe.",
              "Demand written, itemised seizure receipt before dem leave. Refuse to sign any document wey you never fully read.",
              "After everything, call SON consumer helpline (07057000001) or file report at nearest SON office and consult trade association lawyer.",
            ],
            yo: [
              "Má san ₦20,000 naa. Beere isanwo lati fojufori ìka ti a fi ẹsun jẹ ibajẹ — isanwo jẹ ki o jẹ alabaṣiṣẹpọ ninu ẹbọ.",
              "Sọ ni ìmúrasín ṣugbọn ni alaafia: 'Jọwọ fihan mi awọn kaadi idanimọ SON alaye rẹ ṣaaju ki ohun miiran to ṣẹlẹ.' Awọn oṣiṣẹ SON to wulo yoo ni wọn.",
              "Ti wọn ba fihan awọn ID, kọ awọn orukọ ati awọn nọmba ami-ẹri wọn silẹ. Ti wọn ba kọ lati fihan ID, sọ: 'Emi ko gba si yiyọ ẹru eyikeyi titi ti ẹ o fi ṣe idanimọ ara yin ni to ati fi aṣẹ kikọ rẹ han mi.'",
              "Ti wọn ba bẹrẹ si yọ awọn nkan kuro lonakona, má dẹ́ wọn ni ara ṣugbọn tako pẹlu ohun to ga, ṣe atokọ gbogbo nkan ti a n'gba, ki o si ya awọn aworan tabi fidio ti o ba jẹ ailewu.",
              "Beere fun riri imugba kikọ, ti o ṣe alaye ṣaaju ki wọn to lọ. Kọ lati fọwọsi iwe eyikeyi ti o ko ti ka ni kikun.",
              "Lẹhin iṣẹlẹ naa, pe ẹrọ iranlọwọ olumulo SON (07057000001) tabi fi ẹdun alaye si ọfiisi SON ti o sunmọ julọ ki o si kan si agbẹjọro ẹgbẹ iṣowo.",
            ],
            ha: [
              "Kada ka biya ₦20,000. Neman biyan kuɗi don yin watsi da take-taken da ake zargi cin hanci ne — biya ya sa ka zama abokin tarayya a cin hanci.",
              "Yi da ƙarfi amma da natsuwa: 'Don Allah nuna mini ingantattun katan shaida na SON kafin wani abu ya faru.' Ingantattun jami'an SON za su samu su.",
              "Idan sun nuna ID, rubuta sunansu da lambobin alama. Idan sun ƙi nuna ID, ce: 'Ba na yarda da cire kaya ba tare da ku gane kanku yadda ya kamata kuma nuna mini izininkku a rubuce ba.'",
              "Idan sun fara cire abubuwa ta kowace hanya, kada ka hana su ta jiki amma ki ta murya, lissafta kowane abu da ake ɗauka, ka dauki hotuna ko bidiyo idan lafiya ta bada damar.",
              "Nace kan kirtanin kwace a rubuce mai cikakken bayani kafin su tafi. Ƙi sanya hannu a kan duk wani takarda da ba ka karanta shi gaba ɗaya ba.",
              "Bayan lamarin, kira layin taimakon mabukaci na SON (07057000001) ko shigar da rahoto a ofishin SON da ke kusa kuma tuntubo lauyan ƙungiyar kasuwanci.",
            ],
            ig: [
              "Akwụkwala ₦20,000 ahụ. Ịrịọ ịkwụ ụgwọ iji lelee mmebi ndị a buuru bụ ihe ọjọọ — ịkwụ ụgwọ mere gị onye mmekọ na nnata nnyefe.",
              "Kwuo n'ụzọ siri ike mana n'udo: 'Biko gosipụtam kaadị njirimara SON ọrụ gị tupu ihe ọzọ mere.' Ndị ọrụ SON kwesịrị ekwesị ga-enwe ha.",
              "Ọ bụrụ na ha gosipụta ID, dee aha ha na ọnụ ọgụgụ akara ha. Ọ bụrụ na ha jụ igosi ID, kwuo: 'Anaghị m kwetara na ịwepu ngwongwo ọ bụla tupu ị nọchie onwe gị n'ụzọ kwesịrị ekwesị ma gosipụtam ikike gị edere n'akwụkwọ.'",
              "Ọ bụrụ na ha malite iwepụ ihe n'ụzọ ọ bụla, ghara ịgbochi ha n'ahụ mana tochie n'olu dị elu, dee ihe niile a na-ewere, were foto ma ọ bụ vidiyo ọ bụrụ na ọ dị mma.",
              "Rịọ recept nchekwa edere n'akwụkwọ nke na-edepụta ihe niile tupu ha apụọ. Jụ ịdebanya aka n'akwụkwọ ọ bụla ị agụghị ya n'ụzọ zuru oke.",
              "Mgbe ihe ahụ gasịrị, kpọọ ọnụ ọrụ ndị ọrụ SON (07057000001) ma ọ bụ tinye mkpesa n'ọfịs SON dị nso ọtụtụ wee kpọtụrụ ọkàiwu ọgbakọ azụmahịa.",
            ],
          },
        },
      ],
    },
  ],
};
