import type { Section } from "./types";

export const women: Section = {
  slug: "women",
  title: {
    en: "Women & Vulnerable Persons",
    pcm: "Women & Vulnerable Persons",
    yo: "Awọn Obinrin & Awọn Eniyan Alailagbara",
    ha: "Mata & Mutanen da ke cikin Haɗari",
    ig: "Ụmụ Nwanyị & Ndị Na-adịghị Ike",
  },
  description: {
    en: "Legal protections for women, survivors of domestic violence, victims of sexual harassment, and vulnerable persons under the VAPP Act and Nigerian Constitution.",
    pcm: "Legal protection for women, domestic violence survivors, sexual harassment victims, and vulnerable persons under VAPP Act and Nigerian Constitution.",
    yo: "Awọn aabo ofin fun awọn obinrin, awọn aláàárọ̀ iwa ipa ni ile, awọn olufaragba ipalara ibalopo, ati awọn eniyan alailagbara labẹ Ofin VAPP ati Ofin Ipilẹ Nigeria.",
    ha: "Kariyar doka ga mata, wadanda suka tsira daga cin zarafin gida, wadanda suka fuskanci cin zarafin jima'i, da mutanen da ke cikin haɗari a ƙarƙashin Dokar VAPP da Kundin Tsarin Mulki na Najeriya.",
    ig: "Nchebe iwu maka ụmụ nwanyị, ndị gasịrị n'ime ihe ike n'ụlọ, ndị ihe ọjọọ mere n'ihe banyere mmekọahụ, na ndị na-adịghị ike n'okpuru VAPP Act na Iwu Nke Naịjirịa.",
  },
  icon: "Heart",
  color: "bg-rose-50 text-rose-700",
  topics: [
    {
      slug: "domestic-violence",
      title: {
        en: "Domestic Violence & the VAPP Act",
        pcm: "Domestic Violence & VAPP Act",
        yo: "Iwa Ipa Ìdílé & Ofin VAPP",
        ha: "Cin Zarafin Gida & Dokar VAPP",
        ig: "Ihe Ike N'ụlọ & VAPP Act",
      },
      summary: {
        en: "The Violence Against Persons Prohibition (VAPP) Act 2015 criminalises domestic violence, sexual assault, stalking, and emotional abuse. It applies at the federal level and in states that have adopted it.",
        pcm: "VAPP Act 2015 make domestic violence, sexual assault, stalking, and emotional abuse na crime. E apply for federal level and states wey don adopt am.",
        yo: "Ofin VAPP 2015 ṣe iwa ipa ìdílé, ikọlu ibalopo, takurọsẹ, ati ilokulo ẹdun jẹ ẹṣẹ. O kan ni ipele apapo ati ni awọn ipinle ti o ti gba a.",
        ha: "Dokar VAPP 2015 ta mai da cin zarafin gida, cin zarafin jima'i, kiyayya, da cin zarafin tunani su zama laifi. Tana aiki a matakin tarayya da jihohin da suka karbe ta.",
        ig: "VAPP Act 2015 mere ka ihe ike n'ụlọ, inyeaghara n'ihe mmekọahụ, ịgba ọsọ imi ọzọ, na mmegbu mwute bụ mmehie. Ọ na-arụ ọrụ n'ọkwa gọọmenti etiti na n'obodo ndị nabatara ya.",
      },
      readMinutes: 5,
      canDo: {
        en: [
          "Police must accept reports of domestic violence",
          "A court can issue a Protection Order against an abuser",
          "You can apply for an emergency protection order without the abuser's presence",
          "Shelters and support services must be made available to victims",
        ],
        pcm: ["Police must accept report of domestic violence", "Court fit issue Protection Order against abuser", "You fit apply for emergency protection order without abuser being there", "Shelters and support services must be available for victims"],
        yo: ["Ọlọpaa gbọdọ gba ijabọ iwa ipa ìdílé", "Ile-ẹjọ le fun Aṣẹ Aabo si ẹni ti o kọlu", "O le beere fun aṣẹ aabo pajawiri laisi wiwa ẹni ti o kọlu", "Awọn ile aabo ati awọn iṣẹ atilẹyin gbọdọ wa fun awọn olufaragba"],
        ha: ["Yan sanda dole su karɓi rahotannin cin zarafin gida", "Kotu na iya ba da Dokar Kariya kan mai cin zarafi", "Kuna iya neman umarni na gaggawa na kariya ba tare da halartar mai cin zarafi ba", "Dole a samar da matsugunan kuma da ayyukan tallafi ga waɗanda aka azabtar"],
        ig: ["Ndị uwe ojii kwesịrị anabata akụkọ banyere ihe ike n'ụlọ", "Ụlọ ikpe nwere ike enye Iwu Nchebe megide onye na-eme ihe ike", "Ị nwere ike arịọ iwu nchebe mberede na-enweghị ọnụ onye na-eme ihe ike", "A kwesịrị inye ndị ihe ike mere ụlọ nchedo na ọrụ nkwado"],
      },
      cannotDo: {
        en: [
          "Police cannot refuse to file a report of domestic violence",
          "An abuser cannot legally prevent you from leaving the home",
          "No officer can dismiss domestic violence as a 'family matter' and refuse to act",
          "A landlord cannot evict you for leaving an abusive partner",
        ],
        pcm: ["Police no fit refuse to accept domestic violence report", "Abuser no fit legally stop you from leaving house", "No officer fit say domestic violence na 'family matter' and refuse to act", "Landlord no fit evict you for leaving abusive partner"],
        yo: ["Ọlọpaa ko le kọ lati gba ijabọ iwa ipa ìdílé", "Ẹni ti o kọlu ko le ṣe idiwọ fun ọ lati lọ kuro ni ile", "Oṣiṣẹ kankan ko le kọ iwa ipa ìdílé silẹ bi 'ọrọ ìdílé'", "Onile ko le le ọ kuro nitori ti o ti lọ kuro lọwọ alabaṣiṣẹpọ ti o kọlu"],
        ha: ["Yan sanda ba za su iya ƙi karɓar rahoton cin zarafin gida ba", "Mai cin zarafi ba zai iya hana ka barin gida ta doka ba", "Babu jami'i da zai iya yafe cin zarafin gida a matsayin 'al'amarin iyali'", "Mai gida ba zai iya kore ka saboda ka bar abokin da ke cin zarafi ba"],
        ig: ["Ndị uwe ojii enweghị ike ịjụ ịnabata akụkọ banyere ihe ike n'ụlọ", "Onye na-eme ihe ike enweghị ike izọpụta gị na iwu n'ụlọ", "Onye ọrụ ọ bụla enweghị ike ikwu na ihe ike n'ụlọ bụ 'ihe ezinụlọ' wee jụ ime ihe", "Landlord enweghị ike ịchụpụ gị maka ihapụ onye ndụ gị na-eme ihe ike"],
      },
      whatToDo: {
        en: [
          "Go to the nearest police station and report the violence",
          "Request to see a female officer if you prefer",
          "Seek medical attention and ask the hospital to document your injuries",
          "Contact a legal aid organisation or the National Agency for the Prohibition of Trafficking in Persons (NAPTIP)",
          "Apply for a Protection Order at the Magistrates' Court",
          "Save all evidence: photos, messages, medical records",
        ],
        pcm: ["Go nearest police station and report the violence", "Ask to see female officer if you prefer", "Get medical treatment and ask hospital to document your injuries", "Contact legal aid or NAPTIP", "Apply for Protection Order at Magistrates' Court", "Save all evidence: photos, messages, medical records"],
        yo: ["Lọ si ibudo ọlọpaa ti o sunmọ julọ ati ròyìn iwa ipa naa", "Beere lati ri ọfẹ obinrin ti o ba fẹ", "Wa itọju iṣoogun ati beere ile-iwosan lati ṣe akọsilẹ awọn ọgbẹ rẹ", "Kan si ẹgbẹ iranlọwọ ofin tabi NAPTIP", "Beere fun Aṣẹ Aabo ni Ile-ẹjọ Magistrate", "Fipamọ gbogbo ẹri: awọn aworan, awọn ifiranṣẹ, awọn igbasilẹ iṣoogun"],
        ha: ["Tafi tashar 'yan sanda mafi kusa kuma kai rahoto", "Nemi ganin jandarmiyar mata idan kana so", "Nemi kulawa ta likita kuma nemi asibitin ya rubuta raunuka", "Tuntubi ƙungiyar taimakon shari'a ko NAPTIP", "Nemi Dokar Kariya a Kotun Mista", "Adana duk shaidu: hotuna, saƙonni, takardun likita"],
        ig: ["Gaa n'ụlọ ọrụ uwe ojii kacha nso ma kọọ ihe ike ahụ", "Rịọ ka i hụ onye uwe ojii nwanyị ọ bụrụ na ị chọọ ya", "Chọọ ọgwụgwọ ahụike ma rịọ ụlọ ọgwụ ikwupụta ihere gị", "Kpọtụrụ ọgbakọ enyemaka iwu ma ọ bụ NAPTIP", "Rịọ Iwu Nchebe na Ụlọ Ikpe Magistrate", "Chekwaa ihe akaebe niile: foto, ozi, ndekọ ahụike"],
      },
      whatNotToDo: {
        en: [
          "Do not stay in a dangerous situation waiting for things to improve",
          "Do not be pressured by family to 'manage' the situation",
          "Do not destroy evidence — keep records of everything",
          "Do not be discouraged if police initially resist — insist on your right to report",
        ],
        pcm: ["No stay for dangerous situation waiting for things to get better", "No let family pressure you to 'manage' the situation", "No destroy evidence — keep everything", "No give up if police try to discourage you — insist on your right to report"],
        yo: ["Má duro ni ipo eewu ti o nduro fun awọn nkan lati ni ilọsiwaju", "Má jẹ ki ẹbi tẹ ọ lati 'ṣakoso' ipo naa", "Má run ẹri — tọju awọn igbasilẹ ohun gbogbo", "Má kọ silẹ ti ọlọpaa ba kọ ni akọkọ — duro si ẹtọ rẹ lati ròyìn"],
        ha: ["Kada ka zauna a yanayi mai haɗari suna jiran abubuwa su inganta", "Kada ka bar dangi ya matsa maka ka 'sarrafa' yanayin", "Kada ka lalata shaidu — kiyaye duk bayanan", "Kada ka yanke ƙauna idan 'yan sanda sun ƙi da farko — nace kan haƙƙinka na kai rahoto"],
        ig: ["Anọkwala n'ọnọdụ ize ndụ na-echere ka ihe dịkwuo mma", "Ikwekwala ezinụlọ igbochi gị 'ijikwa' ọnọdụ ahụ", "Eweghachikwala ihe akaebe — zachie ndekọ ihe niile", "Anakwụkwala ma ndị uwe ojii chọpụtara igbochi gị na mbụ — nọdee n'ikike gị ịkọ"],
      },
      laws: [
        {
          name: "Violence Against Persons (Prohibition) Act 2015",
          section: "Sections 1–46",
          plainEnglish: {
            en: "The VAPP Act prohibits all forms of violence against persons including physical, sexual, psychological, and socio-economic abuse. Offenders can be jailed for up to 14 years.",
            pcm: "VAPP Act prohibit all form of violence — physical, sexual, psychological, and economic. Person wey do am fit go jail for up to 14 years.",
            yo: "Ofin VAPP ṣe idinaduro gbogbo awọn iru iwa ipa pẹlu ti ara, ibalopo, ati ti ẹdun. Awọn olufisẹ le lọ si tubu fun ọdun 14.",
            ha: "Dokar VAPP ta hana duk nau'ikan cin zarafi ciki har da na jiki, na jima'i, na tunani, da na tattalin arziki. Masu laifin za a iya daurin su har zuwa shekara 14.",
            ig: "VAPP Act machibido ọdịdị ihe ike niile megide ndị mmadụ gụnyere ihe ahụike, mmekọahụ, uche, na akụ. Ndị na-emegbu iwu nwere ike ịga n'mkpọrọ ruo afọ 14.",
          },
        },
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 34",
          plainEnglish: {
            en: "Every individual is entitled to respect for the dignity of his person, and no person shall be subjected to torture or inhuman or degrading treatment.",
            pcm: "Every person get right to respect and dignity. Nobody suppose torture you or treat you in inhuman or degrading way.",
            yo: "Gbogbo eniyan ni ẹtọ si ọwọ fun iyì ara ẹni, ati pe ẹnikẹni ko gbọdọ jẹ ohun ti ijiya tabi itọju alailẹsan.",
            ha: "Kowane mutum yana da hakkin mutunci na mutumtakarsa, kuma ba za a azabtar da kowa ba ko a yi masa ta'adi.",
            ig: "Onye ọ bụla nwere ikike maka ihe ọ bụ onye ya, onye ọ bụla agaghị ata ahụhụ ma ọ bụ a ga-etinye ya n'ọnọdụ ihe mmejọ.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "sexual-harassment",
      title: {
        en: "Sexual Harassment at Work & in Public",
        pcm: "Sexual Harassment for Work & Public Places",
        yo: "Ipọnju Ibalopo ni Iṣẹ & ni Awọn Aaye Gbogbogbo",
        ha: "Cin Zarafin Jima'i a Wurin Aiki & Wuraren Jama'a",
        ig: "Ihe Ọjọọ Mmekọahụ N'ọrụ & N'ọha",
      },
      summary: {
        en: "The VAPP Act 2015 and the Sexual Harassment in Tertiary Educational Institutions (Prohibition) Act 2016 protect against sexual harassment at work and in educational institutions. A woman cannot be fired for refusing sexual advances. Employers have a legal duty to protect employees, and police must take reports seriously.",
        pcm: "VAPP Act 2015 and Sexual Harassment (Prohibition) Act 2016 protect against sexual harassment for work and schools. No be crime to refuse sexual advance — dem no fit fire you for that. Employers get legal duty to protect their workers, and police must take reports seriously.",
        yo: "Ofin VAPP 2015 ati Ofin Idinwọ Ipọnju Ibalopo ni Awọn Ile-ẹkọ Giga 2016 ṣe aabo lodi si ipọnju ibalopo ni iṣẹ ati ni ile-ẹkọ. A ko le fagi le obinrin ti o kọ ifẹkufẹ ibalopo. Awọn agbanisiṣẹ ni ọranyan ofin lati daabo bo awọn oṣiṣẹ, ati pe ọlọpaa gbọdọ gba awọn ijabọ ni pataki.",
        ha: "Dokar VAPP 2015 da Dokar Hana Cin Zarafin Jima'i a Cibiyoyin Ilimi 2016 suna kare daga cin zarafin jima'i a wurin aiki da makarantu. Ba za a iya kora mace saboda kin yarda da ci gaban jima'i ba. Ma'aikata suna da wajibin doka na kare ma'aikatansu, kuma 'yan sanda dole su ɗauki rahotanni da muhimmanci.",
        ig: "VAPP Act 2015 na Sexual Harassment in Tertiary Educational Institutions (Prohibition) Act 2016 na-echebe megide ihe ọjọọ mmekọahụ n'ọrụ na n'ụlọ akwụkwọ. A enweghị ike ilefu ụmụ nwanyị maka ịjụ mmekọahụ. Ndị ọrụ nwere ọrụ iwu ikechebe ndị ọrụ ha, ndị uwe ojii na-ekwesị iwere akụkọ n'anya.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Police must accept and investigate reports of sexual harassment",
          "Employers can be held legally liable if they fail to protect employees from harassment",
          "A victim can seek a court injunction to stop the harasser",
          "Educational institutions can be held accountable for harassment by lecturers or staff",
        ],
        pcm: [
          "Police must accept and investigate sexual harassment reports",
          "Employer fit be held liable if dem fail to protect workers from harassment",
          "Victim fit go court to get injunction to stop the person wey dey harass dem",
          "Schools and universities fit be held responsible for harassment by their staff",
        ],
        yo: [
          "Ọlọpaa gbọdọ gba ati ṣe iwadii awọn ijabọ ipọnju ibalopo",
          "Awọn agbanisiṣẹ le jẹ ẹni ti a mu lẹjọ ti wọn ba kuna lati daabo bo awọn oṣiṣẹ",
          "Olufaragba le wa aṣẹ ile-ẹjọ lati da ẹni ti o nṣe ipọnju duro",
          "Awọn ile-ẹkọ le jẹ ojuṣe fun ipọnju ti awọn olukọ tabi oṣiṣẹ wọn ṣe",
        ],
        ha: [
          "Yan sanda dole su karɓi kuma su binciki rahotannin cin zarafin jima'i",
          "Ana iya ɗaukan masu aikin yi alhakin doka idan sun kasa kare ma'aikata daga cin zarafi",
          "Wanda aka yi wa cin zarafi na iya neman umarni na kotu don dakatar da mai cin zarafin",
          "Cibiyoyin ilimi ana iya ɗaukar su alhakin cin zarafin da malaman su ko ma'aikatansu suka yi",
        ],
        ig: [
          "Ndị uwe ojii kwesịrị ịnabata ma nyochaa akụkọ banyere ihe ọjọọ mmekọahụ",
          "A nwere ike ijide ndị nnọchite anya ụlọ ọrụ n'ikike iwu ọ bụrụ na ha eweputaghị ndị ọrụ ha n'ihe ọjọọ",
          "Onye ihe mere nwere ike ịchọ iwu ụlọ ikpe iji kwụsị onye na-eme ihe ọjọọ ya",
          "A nwere ike ijide ụlọ akwụkwọ dị elu n'ọrụ maka ihe ọjọọ ndị ozugbo ha ma ọ bụ ndị ọrụ ha mere",
        ],
      },
      cannotDo: {
        en: [
          "An employer cannot fire or demote a woman for refusing sexual advances",
          "A harasser cannot condition employment, promotion, or grades on sexual favours",
          "Police cannot dismiss a report of sexual harassment as a 'minor issue'",
          "An institution cannot force a victim to confront or settle privately with the harasser",
          "No authority can punish a victim for speaking out about harassment",
        ],
        pcm: [
          "Employer no fit sack or demote woman because she refuse sexual advance",
          "Person no fit use job, promotion, or grades as condition for sexual favour",
          "Police no fit dismiss sexual harassment report as 'small matter'",
          "School or company no fit force victim to confront or settle privately with harasser",
          "Nobody in authority fit punish victim for speaking out about harassment",
        ],
        yo: [
          "Agbanisiṣẹ ko le fagi le tabi sokale ipo obinrin fun kiko ifẹkufẹ ibalopo",
          "Ẹni ti o nṣe ipọnju ko le ṣe iṣẹ, igbega, tabi awọn ami giga jẹ ipo fun awọn ojurere ibalopo",
          "Ọlọpaa ko le kọ ijabọ ipọnju ibalopo bi 'ọrọ kekere'",
          "Ile-iṣẹ tabi ile-ẹkọ ko le fi agbara mu olufaragba lati dojukọ tabi pinnu ni aladani pẹlu ẹni ti o nṣe ipọnju",
          "Ẹnikẹni ninu aṣẹ ko le jẹ ki olufaragba jiya fun sisọ nipa ipọnju",
        ],
        ha: [
          "Mai aikin yi ba zai iya kora ko rage matsayi mace saboda kin yarda da ci gaban jima'i ba",
          "Mai cin zarafi ba zai iya mai da aiki, ci gaba, ko maki a matsayin sharaɗi don samun lada ta jima'i ba",
          "Yan sanda ba za su iya yafe rahoton cin zarafin jima'i a matsayin 'ƙaramin abu' ba",
          "Cibiya ba za ta iya tilasta wanda aka yi wa cin zarafi ya fuskanci ko ya daidaita a asirce da mai cin zarafin ba",
          "Babu mai iko da zai iya hukunta wanda aka yi wa cin zarafi saboda ya yi magana game da cin zarafi",
        ],
        ig: [
          "Onye nnọchite anya ụlọ ọrụ enweghị ike ilefu ma ọ bụ ịdọwasị ụmụ nwanyị maka ịjụ mmekọahụ",
          "Onye na-eme ihe ọjọọ enweghị ike ime ọrụ, ọganihu, ma ọ bụ akara ọmụmụ ka ọ bụrụ ọnọdụ iji nweta ọchịchọ mmekọahụ",
          "Ndị uwe ojii enweghị ike iwepụ akụkọ banyere ihe ọjọọ mmekọahụ dị ka 'ihe nta'",
          "Ụlọ ọrụ ma ọ bụ ụlọ akwụkwọ enweghị ike ịmanye onye ihe mere ka o zuo onye na-eme ihe ọjọọ ya n'ihu ma ọ bụ kpebisie n'nzuzo",
          "Onye ọ bụla n'ọchịchọ enweghị ike ịta onye ihe mere ahụhụ maka ikwu okwu banyere ihe ọjọọ",
        ],
      },
      whatToDo: {
        en: [
          "Document every incident — dates, times, locations, witnesses, and screenshots of messages",
          "Report the harassment to your employer's HR department or a supervisor not involved",
          "If the employer fails to act, report to the police and file a formal complaint",
          "Contact a legal aid clinic, women's rights NGO, or the National Human Rights Commission (NHRC)",
          "Preserve all evidence before it is deleted or lost",
        ],
        pcm: [
          "Write down every incident — date, time, place, witness, and screenshot of any messages",
          "Report the harassment to HR or supervisor wey no be part of the problem",
          "If employer no act, report to police and file formal complaint",
          "Contact legal aid, women's rights NGO, or National Human Rights Commission (NHRC)",
          "Keep all evidence before dem delete or lose am",
        ],
        yo: [
          "Ṣe akọsilẹ gbogbo iṣẹlẹ — awọn ọjọ, awọn akoko, awọn ipo, awọn ẹlẹri, ati awọn aworan iboju ti awọn ifiranṣẹ",
          "Ròyìn ipọnju si ẹka HR ile-iṣẹ rẹ tabi alabojuto ti ko si ninu rẹ",
          "Ti agbanisiṣẹ ba kuna lati ṣe, ròyìn si ọlọpaa ati fi ẹsun osise",
          "Kan si ile-iwosan iranlọwọ ofin, NGO ẹtọ obinrin, tabi Igbimọ Eto Eniyan ti Orilẹ-ede (NHRC)",
          "Pa gbogbo ẹri mọ ṣaaju ki a to paarẹ tabi padanu rẹ",
        ],
        ha: [
          "Rubuta kowane lamari — kwanakin, lokuttai, wurare, shaidu, da hotunan saƙonnin",
          "Kai rahoto cin zarafi zuwa sashen HR ko babban jami'i da bai shiga cikin al'amarin ba",
          "Idan mai aikin yi ya kasa ɗaukar matakin, kai rahoto ga 'yan sanda kuma ka shigar da korafi na hukuma",
          "Tuntubi kliniken taimakon shari'a, NGO ta haƙƙin mata, ko Hukumar Kare Haƙƙin Dan-Adam ta ƙasa (NHRC)",
          "Adana duk shaidu kafin a goge ko a rasa su",
        ],
        ig: [
          "Dee ihe niile gbasara oge ọ bụla — ụbọchị, oge, ọnọdụ, ndị ọka-asị, na foto ozi",
          "Kọọ ihe ọjọọ ahụ n'ngalaba HR ụlọ ọrụ gị ma ọ bụ onye isi na-abụghị akụkụ nke nsogbu ahụ",
          "Ọ bụrụ na onye nnọchite anya ụlọ ọrụ emelataghị ihe, kọọ ndị uwe ojii ma detuo mkpesa n'ụzọ iwu",
          "Kpọtụrụ ụlọ ọrụ enyemaka iwu, NGO ikike ụmụ nwanyị, ma ọ bụ National Human Rights Commission (NHRC)",
          "Chekwaa ihe akaebe niile tupu ọ ehichaara ma ọ bụ fụọ",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not stay silent out of fear of losing your job — the law protects you from retaliation",
          "Do not delete messages or evidence thinking they are embarrassing",
          "Do not settle privately under pressure without legal advice",
          "Do not blame yourself — sexual harassment is never the victim's fault",
        ],
        pcm: [
          "No keep quiet because you fear to lose your job — law protect you from retaliation",
          "No delete messages or evidence because you feel shame",
          "No settle privately under pressure without getting legal advice first",
          "No blame yourself — sexual harassment no be your fault",
        ],
        yo: [
          "Má dakẹ nitori iberu padanu iṣẹ rẹ — ofin ṣe aabo fun ọ lati igbẹsan",
          "Má paarẹ awọn ifiranṣẹ tabi ẹri ti o ro pe wọn jẹ itiju",
          "Má pinnu ni aladani labẹ ẹri-ọkan laisi imọran ofin",
          "Má jẹ ki ara rẹ jẹ ẹbi — ipọnju ibalopo kọ jẹ aṣiṣe olufaragba rara",
        ],
        ha: [
          "Kada ka yi shiru saboda tsoro ka rasa aikin ka — doka tana kare ka daga ramako",
          "Kada ka goge saƙonnin ko shaidu saboda ka ji kunya",
          "Kada ka daidaita a asirce ƙarƙashin matsi ba tare da neman shawara ta doka ba",
          "Kada ka yi wa kanka laifi — cin zarafin jima'i ba laifin wanda aka yi masa ba ne",
        ],
        ig: [
          "Adịkwụghị ụda n'ihi ịtụ egwu ifu ọrụ gị — iwu na-echebe gị n'aka nzaghachi ọjọọ",
          "Ehichakwụghị ozi ma ọ bụ ihe akaebe n'echiche na ha na-eme ihere",
          "Edozikwụghị n'nzuzo n'okpuru nrụgide na-enweghị ndụmọdụ iwu",
          "Echefukwụghị onwe gị — ihe ọjọọ mmekọahụ abụghị njehie onye ihe mere ya",
        ],
      },
      laws: [
        {
          name: "Violence Against Persons (Prohibition) Act 2015",
          section: "Sections 1, 6, 17",
          plainEnglish: {
            en: "Criminalises sexual harassment, unwanted sexual advances, and creates offences for employers and institutions who fail to protect persons in their care.",
            pcm: "The Act make sexual harassment and unwanted sexual advances na crime, and hold employers and institutions responsible if dem fail to protect their people.",
            yo: "Ofin naa ṣe ipọnju ibalopo ati awọn igbesẹ ibalopo ti a ko fẹ jẹ ẹṣẹ, o si ṣe agbanisiṣẹ ati awọn ile-ẹkọ ni ojuṣe ti wọn ba kuna lati daabo bo awọn eniyan ni itọju wọn.",
            ha: "Dokar ta mai da cin zarafin jima'i da ci gaban jima'i maras so su zama laifi, kuma ta ɗauki ma'aikata da cibiyoyi alhakin idan sun kasa kare mutanen da ke ƙarƙashin kullarsu.",
            ig: "Iwu ahụ mere ihe ọjọọ mmekọahụ na nnabata mmekọahụ na-achọghị bụrụ mmehie, ma jide ndị nnọchite anya ụlọ ọrụ na ụlọ akwụkwọ n'ọrụ ọ bụrụ na ha eweputaghị ndị ha na-elekọta ha.",
          },
        },
        {
          name: "Sexual Harassment in Tertiary Educational Institutions (Prohibition) Act 2016",
          section: "Sections 1–14",
          plainEnglish: {
            en: "Specifically prohibits sexual harassment in universities, polytechnics, and colleges of education. Lecturers or staff who demand sexual favours in exchange for grades or employment benefits commit a criminal offence punishable by up to 14 years imprisonment.",
            pcm: "This Act specifically ban sexual harassment for universities, polytechnics, and colleges of education. Lecturer or staff wey demand sex in exchange for grades or job benefit don commit crime — dem fit go jail up to 14 years.",
            yo: "Ofin naa ṣe idinwọ pataki si ipọnju ibalopo ni awọn ile-ẹkọ giga, awọn ile-ẹkọ imọ-ẹrọ, ati awọn kọlẹji ẹkọ. Awọn olukọ tabi oṣiṣẹ ti o beere awọn ojurere ibalopo fun awọn ami tabi anfaani iṣẹ ṣe ẹṣẹ ọdaràn ti o le jẹ ẹwọn ọdun 14.",
            ha: "Wannan dokar ta hana cin zarafin jima'i a jami'o'i, kwalejoji na fasaha, da kwalejoji na ilimin malamai. Malaman da ke neman lada ta jima'i don maki ko fa'idodin aiki sun aikata laifin da ake iya dauri su har zuwa shekara 14.",
            ig: "Iwu a machibido kpọmkwem ihe ọjọọ mmekọahụ n'mahadum, polytechnic, na kọleji nkuzi. Ndị nkuzi ma ọ bụ ndị ọrụ na-achọ ọchịchọ mmekọahụ n'gbanwe maka akara ma ọ bụ uru ọrụ emere mmehie iwu nke a nwere ike ha ikpọrọ n'mkpọrọ ruo afọ 14.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A female employee's supervisor repeatedly makes sexual comments and suggests her promotion depends on accompanying him to dinner. She refuses and is passed over for promotion.",
            pcm: "Female worker supervisor dey make sexual comments and hint say her promotion depend on if she follow am go dinner. She refuse and dem skip her for promotion.",
            yo: "Alabojuto oṣiṣẹ obinrin kan tẹsiwaju lati ṣe awọn asọye ibalopo o si daba pe igbega ipo rẹ da lori pẹlu rẹ lọ si ounjẹ alẹ. O kọ o si padanu igbega ipo.",
            ha: "Babban jami'in ma'aikaciyar ya ci gaba da yin maganganun jima'i kuma ya nuna cewa tashuwarta ta dogara ne da rakiyarsa zuwa cin abinci. Ta ƙi kuma aka wuce ta don tashuwas.",
            ig: "Onye isi ụlọ ọrụ nwanyị ọrụ na-agbanwe agbanwe na-ekwu okwu mmekọahụ ma gosipụta na ọganihu ya dabere na ya eso ya gaa oriri n'abalị. O jụọ ya, wee hapụ ya n'ọganihu.",
          },
          steps: {
            en: [
              "Write down every incident with dates, times, and exact words used",
              "Report formally to HR or a senior manager not involved in the situation",
              "If the company fails to act, file a report at the nearest police station under the VAPP Act",
              "Consult a lawyer or contact the NHRC or a women's rights organisation",
              "The employer can be sued for failing to provide a safe working environment",
            ],
            pcm: [
              "Write down every incident — date, time, and exact words wey dem use",
              "Report formally to HR or senior manager wey no dey involved",
              "If company no act, go police station and report under VAPP Act",
              "Talk to lawyer or contact NHRC or women's rights organisation",
              "You fit sue the employer for not providing safe work environment",
            ],
            yo: [
              "Ṣe akọsilẹ gbogbo iṣẹlẹ pẹlu awọn ọjọ, awọn akoko, ati awọn ọrọ gangan ti a lo",
              "Ròyìn ni osise si HR tabi oluṣakoso agba ti ko si ninu ipo naa",
              "Ti ile-iṣẹ ba kuna lati ṣe, fi ẹsun ni ibudo ọlọpaa ti o sunmọ julọ labẹ Ofin VAPP",
              "Wa agbẹjọro tabi kan si NHRC tabi ẹgbẹ ẹtọ obinrin",
              "Agbanisiṣẹ le jẹ ẹjọ fun kuna lati pese agbegbe iṣẹ ailewu",
            ],
            ha: [
              "Rubuta kowane lamari tare da kwanakin, lokuttai, da daidai kalmomi da aka yi amfani da su",
              "Kai rahoto a hukumance zuwa HR ko manajan babba wanda ba shi cikin yanayin",
              "Idan kamfanin ya kasa ɗaukar matakin, shigar da rahoto a tashar 'yan sanda mafi kusa ƙarƙashin Dokar VAPP",
              "Nemi lauya ko tuntubi NHRC ko ƙungiyar haƙƙin mata",
              "Ana iya ɗaukaka kara a kan mai aikin yi saboda rashin samar da yanayin aiki mai aminci",
            ],
            ig: [
              "Dee ihe niile gbasara oge ọ bụla, ụbọchị, oge, na okwu kpọmkwem okwuwe",
              "Kọọ n'ụzọ iwu n'ngalaba HR ma ọ bụ onye isi okenye na-abụghị akụkụ nke nsogbu ahụ",
              "Ọ bụrụ na ụlọ ọrụ emelataghị ihe, detuo akụkọ n'ụlọ ọrụ uwe ojii kacha nso n'okpuru VAPP Act",
              "Chọọ onye ọka iwu ma ọ bụ kpọtụrụ NHRC ma ọ bụ ọgbakọ ikike ụmụ nwanyị",
              "A nwere ike isi ụlọ ikpe onye nnọchite anya ụlọ ọrụ maka ọ dịghị inye ọnọdụ ọrụ dị mma",
            ],
          },
        },
      ],
    },
    {
      slug: "marital-rights",
      title: {
        en: "Rights Within Marriage",
        pcm: "Your Rights Inside Marriage",
        yo: "Awọn Ẹtọ Laarin Igbeyawo",
        ha: "Haƙƙoƙi a Cikin Aure",
        ig: "Ikike N'ime Alụmdi Na Nwunye",
      },
      summary: {
        en: "Marriage does not remove a woman's legal rights. Marital rape is a crime under the VAPP Act. Women have equal rights to property in marriage. A husband cannot deny his wife her income or freeze her assets. Both spouses have equal rights to apply for divorce under the Matrimonial Causes Act.",
        pcm: "Marriage no remove woman's legal rights. Marital rape na crime under VAPP Act. Women get equal right to property for marriage. Husband no fit deny wife her money or freeze her assets. Both husband and wife get equal right to apply for divorce under Matrimonial Causes Act.",
        yo: "Igbeyawo ko yọ awọn ẹtọ ofin obinrin kuro. Ifipabanilopo inu igbeyawo jẹ ẹṣẹ labẹ Ofin VAPP. Awọn obinrin ni ẹtọ dọgba si ohun-ini ninu igbeyawo. Ọkọ ko le kọ iyawo rẹ owo rẹ tabi di awọn ohun-ini rẹ. Awọn tọkọtaya mejeeji ni ẹtọ dọgba lati beere fun ikọsilẹ labẹ Ofin Awọn Idi Igbeyawo.",
        ha: "Aure ba ya kawar da haƙƙoƙin doka na mace ba. Fyaɗe a cikin aure laifi ne ƙarƙashin Dokar VAPP. Mata suna da daidai haƙƙi ga dukiya a cikin aure. Miji ba zai iya hana matarsa kuɗinta ko dasge dukiyarta ba. Mata da maza duk suna da daidai haƙƙi na neman saki ƙarƙashin Dokar Sanadin Aure.",
        ig: "Alụmdi na nwunye ezọpụtaghị ikike iwu nwanyị. Iwu VAPP kpọọ mmekọahụ n'ike n'ime alụmdi na nwunye bụ mmehie. Ụmụ nwanyị nwere ikike hàtara n'ihe onwunwe n'ime alụmdi na nwunye. Di enweghị ike izọpụta nwunye ya ego ya ma ọ bụ machibido akụ ya. Onye alụmdi na nwunye abụọ nwere ikike hàtara ịrịọ ịkewapụ n'okpuru Matrimonial Causes Act.",
      },
      readMinutes: 5,
      canDo: {
        en: [
          "Either spouse can legally apply for divorce at the High Court",
          "A wife can open and operate her own bank account independently",
          "Courts can order division of marital property on divorce",
          "A wife can obtain a Protection Order under the VAPP Act if subjected to violence by her husband",
        ],
        pcm: [
          "Either husband or wife fit legally apply for divorce for High Court",
          "Wife fit open and operate her own bank account independently",
          "Court fit order division of marital property when dem divorce",
          "Wife fit get Protection Order under VAPP Act if husband dey use her",
        ],
        yo: [
          "Ẹnikẹni ninu tọkọtaya le beere fun ikọsilẹ ni Ile-ẹjọ Giga ni ofin",
          "Iyawo le ṣii ati ṣiṣẹ akọọlẹ banki tirẹ ni ominira",
          "Ile-ẹjọ le paṣẹ pipin ohun-ini igbeyawo ni ikọsilẹ",
          "Iyawo le gba Aṣẹ Aabo labẹ Ofin VAPP ti ọkọ ba ṣe iwa ipa si i",
        ],
        ha: [
          "Ko wane daga ma'aurata na iya neman saki a kotun koli ta doka",
          "Matar na iya bude kuma ta yi amfani da asusun banki nata da kanta",
          "Kotu na iya umartar rarraba dukiyar aure a kan saki",
          "Matar na iya samun Dokar Kariya ƙarƙashin Dokar VAPP idan miji ya yi mata tashin hankali",
        ],
        ig: [
          "Onye ọ bụla n'ime onye alụmdi na nwunye nwere ike ịrịọ ịkewapụ n'ụlọ ikpe dị elu n'iwu",
          "Nwunye nwere ike meghee ma rụọ ọrụ akaụntụ ụlọ akụ ya onwe ya n'onwe ya",
          "Ụlọ ikpe nwere ike nyere iwu ịkọwa ihe onwunwe alụmdi na nwunye mgbe ịkewapụ",
          "Nwunye nwere ike nweta Iwu Nchebe n'okpuru VAPP Act ọ bụrụ na di ya na-emegbu ya",
        ],
      },
      cannotDo: {
        en: [
          "A husband cannot legally force his wife to have sexual intercourse — marital rape is a crime under Section 1 of the VAPP Act",
          "A husband cannot seize, freeze, or control his wife's personal income or assets",
          "Neither spouse can unilaterally prevent the other from seeking a divorce",
          "A husband cannot legally stop his wife from leaving the matrimonial home to seek safety",
          "No family member or in-law can legally strip a wife of her property or children after a husband's death",
        ],
        pcm: [
          "Husband no fit legally force wife to have sex — marital rape na crime under VAPP Act Section 1",
          "Husband no fit seize, freeze, or control wife's personal money or assets",
          "Neither husband nor wife fit unilaterally block the other from seeking divorce",
          "Husband no fit legally stop wife from leaving home to find safety",
          "No family member or in-law fit legally take wife's property or children after husband die",
        ],
        yo: [
          "Ọkọ ko le fi ofin mu iyawo rẹ lati ni ibalopọ — ifipabanilopo inu igbeyawo jẹ ẹṣẹ labẹ Abala 1 ti Ofin VAPP",
          "Ọkọ ko le gba, di, tabi ṣakoso owo tabi ohun-ini ti iyawo rẹ ni funrararẹ",
          "Ẹnikẹni ninu tọkọtaya ko le ni ẹyọkan dènà ekeji lati wa ikọsilẹ",
          "Ọkọ ko le ni ofin da iyawo rẹ duro kuro ni ile igbeyawo lati wa aabo",
          "Ẹbí tabi araalu kankan ko le gba ohun-ini tabi awọn ọmọ iyawo ni ofin lẹhin ikú ọkọ",
        ],
        ha: [
          "Miji ba zai iya tilasta matarsa yin jima'i da doka ba — fyaɗen aure laifi ne ƙarƙashin Sashe 1 na Dokar VAPP",
          "Miji ba zai iya kwace, dasge, ko sarrafa kuɗin ko dukiyar matarsa ta kai tsaye ba",
          "Ko wane daga ma'aurata ba zai iya hana ɗayan neman saki ba shi kaɗai",
          "Miji ba zai iya hana matarsa ta bar gidan aure ta nemo aminci da doka ba",
          "Babu memba na iyali ko surukai da zai iya kwace dukiyar matar ko 'ya'yanta bisa doka bayan mutuwar miji",
        ],
        ig: [
          "Di enweghị ike iwu site n'iwu ịmanye nwunye ya mmekọahụ — mmekọahụ n'ike n'ime alụmdi na nwunye bụ mmehie n'okpuru Nkeji 1 nke VAPP Act",
          "Di enweghị ike ịchịkọ, ịmachibido, ma ọ bụ ichikwa ego ma ọ bụ akụ nwunye ya nke ya n'onwe ya",
          "Onye ọ bụla n'ime onye alụmdi na nwunye enweghị ike izọpụta onye ọzọ n'ụzọ ya n'onwe ya site n'ịchọ ịkewapụ",
          "Di enweghị ike n'iwu izọpụta nwunye ya site n'ịhapụ ụlọ alụmdi na nwunye iji chọọ nchedo",
          "Onye ezinụlọ ma ọ bụ onye di-n'ụlọ enweghị ike n'iwu iwepụ ihe onwunwe nwunye ma ọ bụ ụmụ ya mgbe di ya nwụọ",
        ],
      },
      whatToDo: {
        en: [
          "If subjected to marital rape, report to the police immediately — it is a criminal offence under the VAPP Act",
          "If your husband seizes your income or assets, seek legal advice from a lawyer or legal aid centre",
          "To apply for divorce, file a petition at the High Court — you do not need your husband's consent",
          "If facing violence, apply for a Protection Order at the Magistrates' Court or Family Court",
          "Seek help from women's rights organisations such as FIDA Nigeria or WARDC",
        ],
        pcm: [
          "If your husband rape you, report to police immediately — na criminal offence under VAPP Act",
          "If your husband seize your money or assets, seek legal advice from lawyer or legal aid centre",
          "To divorce, file petition at High Court — you no need your husband's consent",
          "If you face violence, apply for Protection Order at Magistrates' Court or Family Court",
          "Seek help from women's rights organisations like FIDA Nigeria or WARDC",
        ],
        yo: [
          "Ti o ba jẹ koko ti ifipabanilopo inu igbeyawo, ròyìn si ọlọpaa lẹsẹkẹsẹ — o jẹ ẹṣẹ ọdaràn labẹ Ofin VAPP",
          "Ti ọkọ rẹ ba gba owo tabi ohun-ini rẹ, wa imọran ofin lọwọ agbẹjọro tabi ile-iwosan iranlọwọ ofin",
          "Lati beere ikọsilẹ, fi ẹbẹ silẹ ni Ile-ẹjọ Giga — o ko nilo ifọwọsi ọkọ rẹ",
          "Ti o ba dojukọ iwa ipa, beere fun Aṣẹ Aabo ni Ile-ẹjọ Magistrate tabi Ile-ẹjọ Idile",
          "Wa iranlọwọ lọwọ awọn ẹgbẹ ẹtọ obinrin bi FIDA Nigeria tabi WARDC",
        ],
        ha: [
          "Idan an yi miki fyaɗen aure, kai rahoto ga 'yan sanda nan da nan — laifi ne na laifin ƙarƙashin Dokar VAPP",
          "Idan mijinki ya kwace kuɗinki ko dukiyarki, nemi shawara ta doka daga lauya ko cibiyar taimakon shari'a",
          "Don neman saki, shigar da kara a kotun koli — ba kwa buƙatar yardar mijinki",
          "Idan kana fuskantar tashin hankali, nemi Dokar Kariya a Kotun Mista ko Kotun Iyali",
          "Nemi taimako daga ƙungiyoyin haƙƙin mata kamar FIDA Nigeria ko WARDC",
        ],
        ig: [
          "Ọ bụrụ na di gị mekwara gị mmekọahụ n'ike, kọọ ndị uwe ojii ozugbo — ọ bụ mmehie iwu n'okpuru VAPP Act",
          "Ọ bụrụ na di gị achịkọo ego gị ma ọ bụ akụ gị, chọọ ndụmọdụ iwu n'aka onye ọka iwu ma ọ bụ ụlọ enyemaka iwu",
          "Iji rịọ ịkewapụ, detuo arịọ n'ụlọ ikpe dị elu — ọ dịghị mkpa ịnwe nkwenye di gị",
          "Ọ bụrụ na i na-ezugbu ihe ike, rịọ Iwu Nchebe na Ụlọ Ikpe Magistrate ma ọ bụ Ụlọ Ikpe Ezinụlọ",
          "Chọọ enyemaka n'ọgbakọ ikike ụmụ nwanyị dịka FIDA Nigeria ma ọ bụ WARDC",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not stay in a marriage that involves physical or sexual violence out of social pressure",
          "Do not allow anyone to convince you that your husband has an automatic right to all marital property",
          "Do not sign any documents under duress — consult a lawyer first",
          "Do not believe that you cannot divorce without your husband's consent — the law gives you that right",
        ],
        pcm: [
          "No stay for marriage wey get physical or sexual violence because of social pressure",
          "No let anybody convince you say husband automatically own all marital property",
          "No sign any document under pressure — talk to lawyer first",
          "No believe say you need husband's consent to divorce — the law give you that right",
        ],
        yo: [
          "Má duro ni igbeyawo ti o ni iwa ipa ti ara tabi ibalopo nitori titẹ awujọ",
          "Má jẹ ki ẹnikẹni parọ fun ọ pe ọkọ rẹ ni ẹtọ adaṣe si gbogbo ohun-ini igbeyawo",
          "Má fọwọsi eyikeyi iwe labẹ ipanilẹru — ba agbẹjọro sọrọ ni akọkọ",
          "Má gbagbọ pe o ko le kọsilẹ laisi ifọwọsi ọkọ rẹ — ofin fun ọ ni ẹtọ yẹn",
        ],
        ha: [
          "Kada ki zauna a aure wanda ke da tashin hankali na jiki ko na jima'i saboda matsin jama'a",
          "Kada ki bar kowa ya shawo kanki cewa mijinki yana da haƙƙin kai tsaye ga duk dukiyar aure",
          "Kada ki sanya hannu kan wani takarda ƙarƙashin tilastawa — nemi shawara daga lauya da farko",
          "Kada ki yi imani cewa ba za ki iya neman saki ba tare da yardar mijinki ba — doka ta ba ki wannan haƙƙin",
        ],
        ig: [
          "Anọkwụghị n'alụmdi na nwunye nwere ihe ike ahụike ma ọ bụ mmekọahụ n'ihi nrụgide mmekọahụ",
          "Ikwekwụghị onye ọ bụla ka ọ na-agwa gị na di gị nwere ikike ihe onwunwe alụmdi na nwunye niile n'ozuzu ya",
          "Adebienyekwụghị akwụkwọ ọ bụla n'okpuru ihe ike — jụọ onye ọka iwu ọzọ tupu",
          "Ekwebekwụghị na ị nweghị ike ịkewapụ na-enweghị nkwenye di gị — iwu nyere gị ikike ahụ",
        ],
      },
      laws: [
        {
          name: "Violence Against Persons (Prohibition) Act 2015",
          section: "Section 1",
          plainEnglish: {
            en: "Marital rape is expressly criminalised. A husband who forces sexual intercourse on his wife commits an offence punishable by imprisonment.",
            pcm: "The VAPP Act expressly make marital rape a crime. Husband wey force wife to have sex go face jail.",
            yo: "Ifipabanilopo inu igbeyawo jẹ ẹṣẹ ti a ti kede ni gbangba. Ọkọ ti o fi agbara mu iyawo rẹ lati ni ibalopọ ṣe ẹṣẹ ti o jẹ ẹwọn.",
            ha: "Fyaɗen aure an yi la'anta shi a sarari. Miji da ya tilasta matarsa yin jima'i ya aikata laifi da ake iya dauri shi.",
            ig: "A kpọọ mmekọahụ n'ike n'ime alụmdi na nwunye bụ mmehie n'ụzọ doro anya. Di nke ji ike mee nwunye ya mmekọahụ nwere mmehie nke a nwere ike ikpọrọ ya n'mkpọrọ.",
          },
        },
        {
          name: "Matrimonial Causes Act",
          section: "Sections 15–18",
          plainEnglish: {
            en: "Either spouse may petition the High Court for dissolution of marriage. Grounds include adultery, unreasonable behaviour, desertion, and irretrievable breakdown. No spouse can block the other from petitioning.",
            pcm: "Any husband or wife fit go High Court to end the marriage. Grounds include adultery, bad behaviour, desertion, and when the marriage don break down. Nobody fit block the other person from filing.",
            yo: "Ẹnikẹni ninu tọkọtaya le beere fun Ile-ẹjọ Giga lati tu igbeyawo. Awọn idi pẹlu agbere, ihuwasi ti ko tọ, isilọ, ati idasile ti ko le tún ṣe. Ko si tọkọtaya kankan ti o le da ekeji duro lati beere.",
            ha: "Ko wane daga ma'aurata na iya karar Kotun Koli don rusa aure. Dalilan sun haɗa da zina, hali maras kyau, watsi, da rusa da ba za a iya gyarawa ba. Babu wani ma'auraci da zai iya hana ɗayan daga shigar da kara.",
            ig: "Onye ọ bụla n'ime onye alụmdi na nwunye nwere ike rịọ n'ụlọ ikpe dị elu ka emegbuo alụmdi na nwunye. Ihe kpatara ya gụnyere ime mpako, omume ọjọọ, ịhapụ ya, na ọdịghị ike ịdọzikwa ya. Onye ọ bụla n'ime ndị alụmdi na nwunye enweghị ike izọpụta onye ọzọ site n'ịdetuo arịọ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "A woman's husband confiscates her salary each month and refuses to let her have her own bank account. He threatens to throw her out if she complains.",
            pcm: "Woman husband dey collect her salary every month and no allow her to have her own bank account. He dey threaten to throw her out if she complain.",
            yo: "Ọkọ obinrin kan n'igba gbogbo gba owo osu rẹ o si kọ lati jẹ ki o ni akọọlẹ banki tirẹ. O halẹ lati lé e kuro ti o ba kerora.",
            ha: "Mijin mace yana ɗaukar albashin ta kowane wata kuma yana ƙin ba ta damar samun asusun banki nata. Yana yi mata barazana cewa zai kore ta idan ta yi ƙara.",
            ig: "Di nwanyị na-aṅụ ugwo ọrụ ya kwa ọnwa ma jụ ya inwe akaụntụ ụlọ akụ ya n'onwe ya. Ọ na-egwu ya na ọ ga-apụchie ya ma ọ bụrụ na o soo ube.",
          },
          steps: {
            en: [
              "Know that you have a legal right to your own income — a husband cannot legally confiscate your earnings",
              "Open your own bank account and arrange for your salary to be paid directly into it",
              "If he retaliates with violence, apply for a Protection Order at the Magistrates' Court",
              "Contact FIDA Nigeria, WARDC, or a legal aid centre for free legal assistance",
              "Keep records of all financial interference in case you need to pursue legal action",
            ],
            pcm: [
              "Know say you get legal right to your own money — husband no fit legally collect your earnings",
              "Open your own bank account and arrange for salary to pay direct into am",
              "If he retaliate with violence, apply for Protection Order at Magistrates' Court",
              "Contact FIDA Nigeria, WARDC, or legal aid centre for free legal help",
              "Keep record of all financial interference in case you need to go to court",
            ],
            yo: [
              "Mọ pe o ni ẹtọ ofin si owo oya rẹ — ọkọ ko le gba owo oya rẹ ni ofin",
              "Ṣii akọọlẹ banki tirẹ ati ṣeto fun owo osu rẹ lati san wọle si rẹ taara",
              "Ti o ba gbẹsan pẹlu iwa ipa, beere fun Aṣẹ Aabo ni Ile-ẹjọ Magistrate",
              "Kan si FIDA Nigeria, WARDC, tabi ile-iwosan iranlọwọ ofin fun iranlọwọ ofin ọfẹ",
              "Pa awọn igbasilẹ gbogbo idọwọ owo mọ ni ọran ti o ba nilo lati lepa igbese ofin",
            ],
            ha: [
              "Sani cewa kana da haƙƙin doka ga kuɗin naki — miji ba zai iya kwace albashinki da doka ba",
              "Bude asusun banki naki kuma ka shirya a biya albashinki kai tsaye a ciki",
              "Idan ya rama da tashin hankali, nemi Dokar Kariya a Kotun Mista",
              "Tuntubi FIDA Nigeria, WARDC, ko cibiyar taimakon shari'a don taimakon shari'a kyauta",
              "Kiyaye bayanan duk tsangwama na kuɗi idan kana buƙatar ɗaukar mataki na doka",
            ],
            ig: [
              "Mara na i nwere ikike iwu n'ego gị n'onwe gị — di enweghị ike n'iwu ịchịkọ ugwo ọrụ gị",
              "Meghee akaụntụ ụlọ akụ gị n'onwe gị ma hazie ka a kwụọ ugwo ọrụ gị ozugbo ya n'ime ya",
              "Ọ bụrụ na o laghachi ihe ike, rịọ Iwu Nchebe na Ụlọ Ikpe Magistrate",
              "Kpọtụrụ FIDA Nigeria, WARDC, ma ọ bụ ụlọ enyemaka iwu maka enyemaka iwu n'efu",
              "Chekwaa ndekọ ịntụféé ọ bụla n'akụ n'ihe ọ bụrụ na ị chọọ ịgbaso ihe n'ụzọ iwu",
            ],
          },
        },
      ],
    },
    {
      slug: "child-custody",
      title: {
        en: "Child Custody Rights",
        pcm: "Child Custody Rights",
        yo: "Awọn Ẹtọ Itọjú Ọmọ",
        ha: "Haƙƙoƙin Riƙon Yara",
        ig: "Ikike Nlekọta Ụmụ",
      },
      summary: {
        en: "Courts apply the 'best interests of the child' principle when deciding custody. Mothers are not automatically denied custody. A father cannot forcibly take children from a mother without a court order. Child abduction by a parent is a criminal offence under the Child Rights Act 2003. Both parents retain rights unless a court rules otherwise.",
        pcm: "Court dey use 'best interests of the child' principle to decide custody. Court no automatically deny mother custody. Father no fit forcibly take children from mother without court order. Parent wey abduct pikin na criminal offence under Child Rights Act 2003. Both parents keep their rights unless court say otherwise.",
        yo: "Awọn ile-ẹjọ lo ilana 'anfaani ti o dara julọ ti ọmọ' nigbati wọn ba pinnu lori itọjú. Awọn iya ko ṣe ijẹun laifofo si itọjú. Baba ko le gba awọn ọmọ kuro lọwọ iya ni agbara laisi aṣẹ ile-ẹjọ. Ijapa ọmọ nipasẹ obi jẹ ẹṣẹ ọdaràn labẹ Ofin Awọn Ẹtọ Ọmọ 2003. Awọn obi mejeeji ni awọn ẹtọ ayafi ti ile-ẹjọ ba ṣe idajọ bibẹẹkọ.",
        ha: "Kotuna suna amfani da ka'idar 'mafi kyawun sha'anin yaro' wajen yanke hukunci a kan riƙo. Ba a ƙin wa uwaye riƙon yara ta atomatik. Uba ba zai iya ɗaukar yara da ƙarfi daga uwa ba tare da umarnin kotu ba. Satar yaro ta iyaye laifi ne ƙarƙashin Dokar Haƙƙin Yara 2003. Iyayen biyu suna riƙe haƙƙoƙinsu sai dai kotun ta yanke hukunci.",
        ig: "Ụlọ ikpe na-eji ụzọ 'ihe kacha mma maka nwa' eme ihe mgbe ha na-ekpebi nlekọta. A anaghị anọ n'ihu izọpụta ndị ọmọ n'aka ndị nne. Nna enweghị ike ji ike were ụmụ n'aka nne ha na-enweghị iwu ụlọ ikpe. Izipu nwa n'aka onye mụrụ ya bụ mmehie iwu n'okpuru Child Rights Act 2003. Onye mụrụ ya abụọ nọdebere n'ikike ha ma ọ bụrụ na ụlọ ikpe ekpebighị ọzọ.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Either parent can apply to a Family Court or High Court for custody",
          "A mother can apply for an emergency court order if a father unlawfully removes a child",
          "Courts can award sole custody to one parent if the other poses a risk to the child",
          "Both parents have the right to apply for access or visitation rights even if custody is denied",
        ],
        pcm: [
          "Any parent fit apply to Family Court or High Court for custody",
          "Mother fit apply for emergency court order if father unlawfully remove pikin",
          "Court fit give sole custody to one parent if the other one na risk to the pikin",
          "Both parents get right to apply for access or visitation even if dem no get custody",
        ],
        yo: [
          "Obi eyikeyi le beere ni Ile-ẹjọ Idile tabi Ile-ẹjọ Giga fun itọjú",
          "Iya le beere fun aṣẹ ile-ẹjọ pajawiri ti baba ba gbe ọmọ kuro ni alaiwọ",
          "Awọn ile-ẹjọ le fun itọjú kanṣoṣo si obi kan ti ekeji ba ṣe ewu si ọmọ",
          "Awọn obi mejeeji ni ẹtọ lati beere fun iwọle tabi ẹtọ ibẹwo paapaa ti a ba kọ itọjú",
        ],
        ha: [
          "Iyaye kowane nau'i na iya nema a Kotun Iyali ko Kotun Koli don riƙo",
          "Uwa na iya neman umarnin kotu na gaggawa idan uba ya ɗauki yaron ba da izini ba",
          "Kotuna na iya ba iyaye ɗaya riƙon kai tsaye idan ɗayan ya haifar da haɗari ga yaron",
          "Iyayen biyu suna da haƙƙin nema damar shiga ko haƙƙin ziyara ko da an ƙi riƙon",
        ],
        ig: [
          "Onye mụrụ ya ọ bụla nwere ike ịrịọ n'Ụlọ Ikpe Ezinụlọ ma ọ bụ Ụlọ Ikpe dị elu maka nlekọta",
          "Nne nwere ike ịrịọ iwu ụlọ ikpe mberede ọ bụrụ na nna ewepụtara nwa n'ụzọ na-adịghị mma n'iwu",
          "Ụlọ ikpe nwere ike inye onye nna ma ọ bụ nne nlekọta n'onwe ya ọ bụrụ na onye ọzọ na-apụta ihe egwu maka nwa",
          "Onye mụrụ ya abụọ nwere ikike ịrịọ ohere ma ọ bụ ikike ịga nleta ọbụlagodi ma e jụọ ha nlekọta",
        ],
      },
      cannotDo: {
        en: [
          "A father cannot forcibly remove children from their mother without a court order",
          "A court will not automatically award custody to the father simply because he earns more money",
          "Neither parent can relocate a child to another state or country without court approval or the other parent's consent",
          "A parent cannot deny the other parent court-ordered visitation rights",
          "No family member or in-law can claim custody of children without going through the proper court process",
        ],
        pcm: [
          "Father no fit forcibly take children from mother without court order",
          "Court no go automatically give custody to father just because he earn more money",
          "Neither parent fit relocate pikin to another state or country without court approval or other parent's consent",
          "Parent no fit deny other parent their court-ordered visitation rights",
          "No family member or in-law fit claim custody without going through proper court process",
        ],
        yo: [
          "Baba ko le gba awọn ọmọ kuro lọwọ iya ni agbara laisi aṣẹ ile-ẹjọ",
          "Ile-ẹjọ kii yoo fun itọjú baba laifofo nitori pe o jẹ owo diẹ sii",
          "Obi kankan ko le gbe ọmọ si ipinle tabi orilẹ-ede miiran laisi ifọwọsi ile-ẹjọ tabi ìfarabalẹ obi ekeji",
          "Obi ko le kọ ẹtọ ibẹwo ti ile-ẹjọ paṣẹ si obi ekeji",
          "Ẹbí tabi araalu kankan ko le beere fun itọjú ọmọ laisi lilọ nipasẹ ilana ile-ẹjọ to tọ",
        ],
        ha: [
          "Uba ba zai iya ɗaukar yara da ƙarfi daga uwa ba tare da umarnin kotu ba",
          "Kotu ba za ta ba uba riƙon ta atomatik kawai saboda yana samun kuɗi fiye ba",
          "Ko wane iyaye ba za su iya kawo yaro wani jiha ko ƙasa ba tare da amincewar kotu ko izinin ɗayan iyayen ba",
          "Iyaye ba za su iya hana ɗayan iyayen haƙƙin ziyarar da kotu ta umarta ba",
          "Babu memba na iyali ko surukaine da zai iya da'awar riƙo ba tare da bin hanyar kotu ta daidai ba",
        ],
        ig: [
          "Nna enweghị ike ji ike were ụmụ n'aka nne ha na-enweghị iwu ụlọ ikpe",
          "Ụlọ ikpe agaghị enye nna nlekọta n'ozuzu ya n'ihi na ọ na-enweta ego karịa",
          "Onye mụrụ ya ọ bụla enweghị ike ibugharị nwa gaa steeti ọzọ ma ọ bụ mba ọzọ na-enweghị nkwado ụlọ ikpe ma ọ bụ nkwenye onye ọzọ mụrụ ya",
          "Onye mụrụ ya enweghị ike izọpụta onye ọzọ mụrụ ya ikike ịga nleta ụlọ ikpe nyere iwu",
          "Onye ezinụlọ ma ọ bụ onye di-n'ụlọ enweghị ike ịrọ nlekọta nwa na-agafe n'usoro ụlọ ikpe kwesịrị ekwesị",
        ],
      },
      whatToDo: {
        en: [
          "If a father removes your children unlawfully, report immediately to the nearest police station — it is abduction under the Child Rights Act",
          "Apply to the Family Court or High Court for a custody order as soon as possible",
          "Gather evidence of your role as primary caregiver — school records, medical records, daily care documentation",
          "Contact a lawyer, FIDA Nigeria, or a legal aid centre to help you file for custody",
          "Keep communication with the other parent civil and document any threatening messages",
        ],
        pcm: [
          "If father take your children unlawfully, report immediately to nearest police station — na abduction under Child Rights Act",
          "Apply to Family Court or High Court for custody order as soon as possible",
          "Gather evidence of your role as main caregiver — school records, medical records, daily care documents",
          "Contact lawyer, FIDA Nigeria, or legal aid centre to help you file for custody",
          "Keep communication with other parent civil and document any threatening messages",
        ],
        yo: [
          "Ti baba ba gbe awọn ọmọ rẹ kuro ni alaiwọ, ròyìn lẹsẹkẹsẹ si ibudo ọlọpaa ti o sunmọ julọ — o jẹ ijapa labẹ Ofin Awọn Ẹtọ Ọmọ",
          "Beere fun Ile-ẹjọ Idile tabi Ile-ẹjọ Giga fun aṣẹ itọjú ni kete bi o ti ṣee ṣe",
          "Gba ẹri ti ipa rẹ gẹgẹ bi oluranlọwọ akọkọ — awọn igbasilẹ ile-iwe, awọn igbasilẹ iṣoogun, ati akọsilẹ itọju ojoojumọ",
          "Kan si agbẹjọro, FIDA Nigeria, tabi ile-iwosan iranlọwọ ofin lati ṣe iranlọwọ fun ọ lati fi ẹsun fun itọjú",
          "Pa ibaraẹnisọrọ pẹlu obi ekeji ni ọlaju ati ṣe akọsilẹ eyikeyi awọn ifiranṣẹ ihalẹmọni",
        ],
        ha: [
          "Idan uba ya ɗauki yaranki ba da izini ba, kai rahoto nan da nan ga tashar 'yan sanda mafi kusa — satar yaro ne ƙarƙashin Dokar Haƙƙin Yara",
          "Nema Kotun Iyali ko Kotun Koli don umarnin riƙo da wuri-wuri",
          "Tattara shaidu na rawarki a matsayin mai kulawa na farko — takardun makaranta, takardun likita, da takardar kulawa ta yau da kullun",
          "Tuntubi lauya, FIDA Nigeria, ko cibiyar taimakon shari'a don taimaka miki ka shigar da kara don riƙo",
          "Ci gaba da sadarwa da ɗayan iyayen cikin ladabi kuma ka rubuta duk wani saƙo mai barazana",
        ],
        ig: [
          "Ọ bụrụ na nna ewepụtara ụmụ gị n'ụzọ na-adịghị mma n'iwu, kọọ ozugbo n'ụlọ ọrụ uwe ojii kacha nso — ọ bụ ịzipu nwa n'okpuru Child Rights Act",
          "Rịọ n'Ụlọ Ikpe Ezinụlọ ma ọ bụ Ụlọ Ikpe dị elu maka iwu nlekọta ozugbo enwee ike",
          "Chịkọta ihe akaebe banyere ọrụ gị dị ka onye nlekọta bụisi — ndekọ akwụkwọ ọmụmụ, ndekọ ahụike, na ihe ndekọ nlekọta kwa ụbọchị",
          "Kpọtụrụ onye ọka iwu, FIDA Nigeria, ma ọ bụ ụlọ enyemaka iwu ka ha nyere gị aka ịdetuo maka nlekọta",
          "Jikwa nkwukọrịta gị na onye ọzọ mụrụ ya n'ụzọ dị mma ma dee ozi ọ bụla nke na-egwu egwu",
        ],
      },
      whatNotToDo: {
        en: [
          "Do not take or relocate children without a court order — this could constitute child abduction even if you are the mother",
          "Do not withhold the children from the other parent's court-ordered visitation to use as leverage",
          "Do not make negative statements about the other parent in front of the children — courts consider this harmful",
          "Do not assume courts will automatically favour mothers — prepare a strong case showing the child's best interests",
        ],
        pcm: [
          "No take or relocate children without court order — even if you be the mother, na abduction that one",
          "No use children as leverage by withholding court-ordered visitation from other parent",
          "No talk bad about other parent in front of children — court consider am harmful",
          "No assume court go automatically favour mothers — prepare strong case for best interests of child",
        ],
        yo: [
          "Má gbe tabi ṣe gbigbe awọn ọmọ laisi aṣẹ ile-ẹjọ — eyi le jẹ ijapa ọmọ paapaa ti o ba jẹ iya",
          "Má lo awọn ọmọ gẹgẹ bi agbara nipa kiko ẹtọ ibẹwo ti ile-ẹjọ paṣẹ lọwọ obi ekeji",
          "Má ṣe awọn alaye odi nipa obi ekeji ni iwaju awọn ọmọ — awọn ile-ẹjọ ro pe eyi ṣe ipalara",
          "Má ro pe awọn ile-ẹjọ yoo fẹ awọn iya laifofo — mura ẹsun ti o lagbara ti n fihan anfaani ti o dara julọ ti ọmọ",
        ],
        ha: [
          "Kada ki ɗauka ko tura yara ba tare da umarnin kotu ba — hatta ko ki ne uwar, wannan satar yaro ne",
          "Kada ki yi amfani da yara a matsayin matsa lamba ta hana ɗayan iyayen ziyartar da kotu ta umarta",
          "Kada ki yi maganganun mara kyau game da ɗayan iyayen a gaban yara — kotuna suna ɗaukan wannan a matsayin cutarwa",
          "Kada ki ɗauka kotuna za su fi son uwaye ta atomatik — shirya ƙarfin shari'a da ke nuna mafi kyawun sha'anin yaro",
        ],
        ig: [
          "Eweghakwụghị ma ọ bụ ibugharị ụmụ na-enweghị iwu ụlọ ikpe — nke a nwere ike bụrụ ịzipu nwa ọbụlagodi ma ị bụ nne",
          "Ejikwụghị ụmụ dị ka ihe mgbochi site n'izọpụta onye ọzọ mụrụ ya ikike ịga nleta ụlọ ikpe nyere iwu",
          "Emekwụghị okwu ọjọọ banyere onye ọzọ mụrụ ya n'ihu ụmụ — ụlọ ikpe na-ewere nke a dị ka ihe nke na-emetọ",
          "Echefukwụghị na ụlọ ikpe ga-adọkpụ ndị nne n'ozuzu ya — dị njikere ka ihe ịkọwa nke siri ike na-egosi ihe kacha mma maka nwa",
        ],
      },
      laws: [
        {
          name: "Child Rights Act 2003",
          section: "Sections 1, 71–74",
          plainEnglish: {
            en: "The best interests of the child are paramount in all decisions affecting the child. Section 71 criminalises child abduction. Both parents have duties and rights regarding the child unless a court orders otherwise.",
            pcm: "Best interests of the child na the most important thing in all decisions about the child. Section 71 make child abduction a crime. Both parents get duties and rights for the child unless court order otherwise.",
            yo: "Anfaani ti o dara julọ ti ọmọ jẹ akọkọ ni gbogbo awọn ipinnu ti o kan ọmọ. Abala 71 ṣe ijapa ọmọ jẹ ẹṣẹ. Awọn obi mejeeji ni awọn ojuṣe ati awọn ẹtọ nipa ọmọ ayafi ti ile-ẹjọ ba paṣẹ bibẹẹkọ.",
            ha: "Mafi kyawun sha'anin yaro shine mafi muhimmanci a duk yanke shawara da suka shafi yaron. Sashe 71 ya mai da satar yaro laifi. Iyayen biyu suna da ayyuka da haƙƙoƙi game da yaro sai dai kotun ta umarta.",
            ig: "Ihe kacha mma maka nwa bụ ihe kachasị mkpa n'mkpebi niile metụtara nwa ahụ. Nkeji 71 mere ịzipu nwa bụrụ mmehie. Onye mụrụ ya abụọ nwere ọrụ na ikike banyere nwa ma ọ bụrụhà na ụlọ ikpe nyere iwu ọzọ.",
          },
        },
        {
          name: "Matrimonial Causes Act",
          section: "Section 71",
          plainEnglish: {
            en: "Courts have power to make orders for the custody, guardianship, welfare, advancement, and education of children of a marriage. The welfare of the child is the first and paramount consideration.",
            pcm: "Court get power to make orders for custody, guardianship, welfare, and education of children. The welfare of the child na the first and most important consideration.",
            yo: "Awọn ile-ẹjọ ni agbara lati ṣe awọn aṣẹ fun itọjú, aṣojú, ire, ilọsiwaju, ati ẹkọ awọn ọmọ igbeyawo. Ire ọmọ jẹ akiyesi akọkọ ati pataki julọ.",
            ha: "Kotuna suna da ikon yanke hukunci game da riƙo, kulawa, jin daɗi, ci gaba, da ilimin yarankan aure. Jin daɗin yaro shi ne la'akari na farko da mafi muhimmanci.",
            ig: "Ụlọ ikpe nwere ike ime iwu maka nlekọta, ndọzi, ọdịmma, ọganihu, na agụmakwụkwọ ụmụ alụmdi na nwunye. Ọdịmma nwa bụ ihe a na-atụle nke mbụ kachasị mkpa.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "After separation, a woman's husband comes to the school and takes their children without her knowledge or consent, and refuses to return them or disclose where they are.",
            pcm: "After separation, woman husband go school take their children without her knowledge or consent and refuse to return them or tell her where dem dey.",
            yo: "Lẹhin ipinya, ọkọ obinrin kan lọ si ile-iwe o gba awọn ọmọ wọn laisi imọ tabi igbanilaaye rẹ, o si kọ lati pada wọn tabi sọ ibi ti wọn wà.",
            ha: "Bayan rabuwa, mijin mace ya tafi makaranta ya ɗauki yaransu ba tare da saninta ko izininta ba, kuma ya ƙi mayar da su ko bayyana inda suke.",
            ig: "Ka ha esebiewo, di nwanyị ahụ gara ụlọ akwụkwọ were ụmụ ha na-enweghị ihe ọ maara ma ọ bụ nkwenye ya, ma jụ ilaghachi ha ma ọ bụ ikwu ebe ha nọ.",
          },
          steps: {
            en: [
              "Report immediately to the nearest police station — this is child abduction under the Child Rights Act 2003",
              "Go to the Family Court or High Court the same day and apply for an emergency custody order",
              "Provide the court with any evidence you have — the children's birth certificates, school records, and proof of your care",
              "Contact FIDA Nigeria, WARDC, or a legal aid centre immediately for urgent legal assistance",
              "Once the court issues an order, police are legally obliged to enforce it and return the children",
            ],
            pcm: [
              "Report immediately to nearest police station — na child abduction under Child Rights Act 2003",
              "Go Family Court or High Court that same day and apply for emergency custody order",
              "Give court any evidence you have — birth certificates, school records, proof of your care",
              "Contact FIDA Nigeria, WARDC, or legal aid centre immediately for urgent legal help",
              "Once court issue order, police are legally obliged to enforce am and return the children",
            ],
            yo: [
              "Ròyìn lẹsẹkẹsẹ si ibudo ọlọpaa ti o sunmọ julọ — eyi jẹ ijapa ọmọ labẹ Ofin Awọn Ẹtọ Ọmọ 2003",
              "Lọ si Ile-ẹjọ Idile tabi Ile-ẹjọ Giga ni ọjọ kanna ati beere fun aṣẹ itọjú pajawiri",
              "Pese ile-ẹjọ pẹlu eyikeyi ẹri ti o ni — awọn iwe-ẹri ibi awọn ọmọ, awọn igbasilẹ ile-iwe, ati ẹri itọju rẹ",
              "Kan si FIDA Nigeria, WARDC, tabi ile-iwosan iranlọwọ ofin lẹsẹkẹsẹ fun iranlọwọ ofin ti o yara",
              "Ni kete ti ile-ẹjọ ba fun aṣẹ, awọn ọlọpaa ni ọranyan ofin lati mu aṣẹ naa ṣiṣẹ ati pada awọn ọmọ",
            ],
            ha: [
              "Kai rahoto nan da nan ga tashar 'yan sanda mafi kusa — satar yaro ne ƙarƙashin Dokar Haƙƙin Yara 2003",
              "Tafi Kotun Iyali ko Kotun Koli a wannan rana kuma ka nemi umarnin riƙo na gaggawa",
              "Ba da kotu duk shaidu da kuke da su — takardun haihuwar yaran, takardun makaranta, da hujjar kulawanki",
              "Tuntubi FIDA Nigeria, WARDC, ko cibiyar taimakon shari'a nan da nan don taimakon shari'a na gaggawa",
              "Da zarar kotun ta ba da umarnin, 'yan sanda sun fi ƙarfin doka su aiwatar da shi su kuma mayar da yaran",
            ],
            ig: [
              "Kọọ ozugbo n'ụlọ ọrụ uwe ojii kacha nso — ọ bụ ịzipu nwa n'okpuru Child Rights Act 2003",
              "Gaa n'Ụlọ Ikpe Ezinụlọ ma ọ bụ Ụlọ Ikpe dị elu n'ụbọchị ahụ ahụ ma rịọ iwu nlekọta mberede",
              "Nyere ụlọ ikpe ihe akaebe ọ bụla i nwere — akwụkwọ ọmụmụ ụmụ, ndekọ akwụkwọ ọmụmụ, na ihe akaebe nlekọta gị",
              "Kpọtụrụ FIDA Nigeria, WARDC, ma ọ bụ ụlọ enyemaka iwu ozugbo maka enyemaka iwu dị ọsọ",
              "Ozugbo ụlọ ikpe nyere iwu, ndị uwe ojii nwere ọrụ iwu iji mee ka iwu ahụ arụọ ọrụ ma laghachi ụmụ",
            ],
          },
        },
      ],
    },
  ],
};
