import type { Section } from "./types";

export const youth: Section = {
  slug: "youth",
  title: {
    en: "Youth & Students",
    pcm: "Youth & Students",
    yo: "Ọdọ & Awọn Akẹkọ",
    ha: "Matasa & Dalibai",
    ig: "Ọchịchọ & Ụmụ Akwụkwọ",
  },
  description: {
    en: "Know your rights during police stops targeting youth, campus security encounters, rights to protest, and your digital privacy rights.",
    pcm: "Know your rights when police target you because you're young, campus security encounters, right to protest, and digital privacy rights.",
    yo: "Mọ awọn ẹtọ rẹ nigba idaduro ọlọpaa ti o fojusi ọdọ, awọn ipade aabo ile-iwe, ẹtọ lati tako, ati awọn ẹtọ asiri oni-nọmba rẹ.",
    ha: "Sani haƙƙoƙinka lokacin da 'yan sanda suka tsai da matasa, haduwar tsaro na harabar makaranta, haƙƙin zanga-zanga, da haƙƙoƙin sirrin dijital.",
    ig: "Mara ikike gị n'oge nkwụsị uwe ojii na-elekwasị anya n'ọchịchọ, nnọkọ nchedo kmpus, ikike ịgagharị, na ikike nzuzo dijitalụ gị.",
  },
  icon: "GraduationCap",
  color: "bg-purple-50 text-purple-700",
  topics: [
    {
      slug: "profiling-stops",
      title: {
        en: "Profiling Stops — 'You Look Like a Fraudster'",
        pcm: "'You Look Like Yahoo Boy' Stops",
        yo: "Idaduro Profaili — 'O Dabi Ẹni Ti o Jẹ Jibiti'",
        ha: "Tsayawa Bisa Bayyana — 'Kana Kama Mai Zamba'",
        ig: "Nkwụsị Profaịlụ — 'I Dị Ka Onye Aghụghọ'",
      },
      summary: {
        en: "Police cannot stop, search, or arrest you based solely on your appearance — dreadlocks, tattoos, laptop, nice car, or phone. Profiling based on appearance is unconstitutional.",
        pcm: "Police no fit stop, search, or arrest you because of how you look — dreadlocks, tattoo, laptop, fine car, or phone. Profiling based on appearance against constitution.",
        yo: "Ọlọpaa ko le da ọ duro, ṣayẹwo, tabi mu ọ nikan nitori irisi rẹ — dreads, tatuu, laptop, ọkọ dara, tabi foonu. Profaili ti o da lori irisi jẹ aiofin.",
        ha: "Yan sanda ba za su iya tsai da kai, bincika ka, ko kama ka kawai saboda bayyanarka ba — dreads, zane jiki, kwamfuta, kyakkyawar mota, ko waya. Bayyana bisa zaton bai dace da kundin tsarin mulki ba.",
        ig: "Ndị uwe ojii enweghị ike ịkwụsị gị, ịnyocha gị, ma ọ bụ ijide gị naanị n'ihi ọdịdị gị — dreads, tatuu, laptọpụ, ụgbọ mara mma, ma ọ bụ ekwenti. Profaịlụ dabere n'ọdịdị bụ megide iwu.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Stop you if they have specific, articulable reasons to suspect you of a crime",
          "Ask for your ID",
          "Conduct a pat-down search if they reasonably suspect you carry a weapon",
        ],
        pcm: ["Stop you if dem get specific reason to suspect you of crime", "Ask for your ID", "Do pat-down search if dem reasonably suspect you carry weapon"],
        yo: ["Da ọ duro ti wọn ba ni awọn idi pato lati fura si ọ fun ẹṣẹ", "Beere fun idanimọ rẹ", "Ṣe ayẹwo ẹyẹ ti wọn ba ni idi to dara lati fura si pe o ni ohun ija"],
        ha: ["Tsai da ka idan suna da takamaiman dalilai don zargi ka da laifi", "Nemi ID naka", "Yi binciken harmala idan suna da dalili mai kyau na zargi cewa kana ɗauke da makami"],
        ig: ["Kwụsị gị ọ bụrụ na ha nwere ihe kpatara pụtara ìhè iji lechekwa gị n'mmehie", "Rịọ ID gị", "Mee nyocha pat-down ọ bụrụ na ha nwere ezi ihe kpatara ichefuo na ị na-eburu ngwa agha"],
      },
      cannotDo: {
        en: [
          "Stop you based on your hairstyle, clothing, tattoos, or race",
          "Demand to search your phone, laptop, or bags without a court order",
          "Detain you purely because you own expensive items",
          "Arrest you for 'looking like a fraudster' — that is not an offence under Nigerian law",
          "Seize your devices without a court order",
        ],
        pcm: ["Stop you because of your hair, clothes, tattoo, or race", "Search your phone, laptop, or bag without court order", "Detain you because you carry expensive things", "Arrest you for 'looking like yahoo boy' — that no be offence under Nigeria law", "Seize your devices without court order"],
        yo: ["Da ọ duro nitori irun, aṣọ, tatuu, tabi ẹya rẹ", "Ṣayẹwo foonu, laptop, tabi apo rẹ laisi aṣẹ ile-ẹjọ", "Fi ọ pamọ́ nikan nitori pe o ni awọn ohun elo gbowolori", "Mu ọ fun 'dabi ẹni jibiti' — iyẹn kii ṣe ẹṣẹ labẹ ofin Nigeria", "Gba awọn ẹrọ rẹ laisi aṣẹ ile-ẹjọ"],
        ha: ["Tsai da ka saboda gashinka, tufafi, zane jiki, ko kabila", "Bincika wayarka, kwamfutarka, ko jakunkuna ba tare da umurnin kotu ba", "Tsare ka kawai saboda kana da kayaye masu tsada", "Kama ka don 'kamar mai zamba' — ba laifi a ƙarƙashin dokar Najeriya ba ne", "Kwace na'urorin ka ba tare da umurnin kotu ba"],
        ig: ["Kwụsị gị n'ihi isi gị, uwe, tatuu, ma ọ bụ agbụrụ", "Nyochaa ekwenti, laptọpụ, ma ọ bụ akpa gị na-enweghị iwu ụlọ ikpe", "Nọdee gị naanị n'ihi ị nwe ihe ọbara ọbara", "Jide gị maka 'ịdị ka onye aghụghọ' — ọ bụghị mmehie n'okpuru iwu Naịjirịa", "Wepu ngwaọrụ gị na-enweghị iwu ụlọ ikpe"],
      },
      whatToDo: {
        en: [
          "Stay calm and do not run",
          "Ask: 'Officer, what specific crime am I suspected of?'",
          "If no specific crime is stated, say: 'I respectfully decline to be searched without a lawful basis.'",
          "If they insist on checking your phone, say: 'I do not consent to a search of my phone without a court order.'",
          "Comply physically to avoid escalation, then challenge it legally afterward",
          "Report to your school, a lawyer, or the Nigerian Bar Association",
        ],
        pcm: ["Calm down, no run", "Ask: 'Officer, which specific crime you suspect me of?'", "If dem no name specific crime, say: 'I respectfully refuse to be searched without lawful reason.'", "If dem want check your phone, say: 'I no consent to phone search without court order.'", "Comply physically to avoid trouble, then challenge legally after", "Report to your school, lawyer, or NBA"],
        yo: ["Jẹ ki o balẹ ati má sá", "Beere: 'Ọgagun, ẹṣẹ wo ni mo ṣe ti ẹ n fura si mí?'", "Ti ko ba si ẹṣẹ pato, sọ: 'Mo kọ pẹlu ọwọ lati jẹ ki a ṣayẹwo mi laisi ipilẹ ofin.'", "Ti wọn ba fẹ ṣayẹwo foonu rẹ, sọ: 'Mi o fohun si ṣiṣayẹwo foonu laisi aṣẹ ile-ẹjọ.'", "Tẹle ni ara lati yago fun ìga ipo, lẹhinna ja ni ofin lẹhinna", "Ròyìn si ile-iwe rẹ, agbẹjọro, tabi NBA"],
        ha: ["Kasance a nutsuwa kuma kada ka gudu", "Yi tambaya: 'Jandarm, wane takamaiman laifi ake zargin ni?'", "Idan ba a ambaci takamaiman laifi ba, ce: 'Ina ƙin da ladabi a bincika ni ba tare da dalili na doka ba.'", "Idan suna son bincika wayarka, ce: 'Ba na yarda da bincike wayata ba tare da umurnin kotu ba.'", "Yi biyayya jiki don gujewa tashin hankali, sannan ka kalubalance daga baya a doka", "Kai rahoto ga makarantarka, lauyanka, ko NBA"],
        ig: ["Nọrọ n'udo ma agbakwala ọsọ", "Jụọ: 'Oga, ihe ọjọọ pụtara ìhè gịnị ka a na-eche na m mere?'", "Ọ bụrụ na ha ekwughị mmehie a kapịrị ọnụ, kwuo: 'Ana m ajụ n'ọkịtọ ka a nyochaa m na-enweghị ezi ihe kpatara iwu.'", "Ọ bụrụ na ha chọọ inyocha ekwenti gị, kwuo: 'Anabatahị m inyocha ekwenti m na-enweghị iwu ụlọ ikpe.'", "Soro n'ahụ ikpochapụ esemokwu, wee luso ha ọgụ n'iwu mgbe e mesie ike", "Kọọ na ụlọ akwụkwọ gị, ọka iwu, ma ọ bụ NBA"],
      },
      whatNotToDo: {
        en: [
          "Do not verbally abuse or insult officers",
          "Do not give your phone PIN or password voluntarily",
          "Do not attempt to bribe — it makes your situation worse",
          "Do not sign any statement without reading and understanding it",
        ],
        pcm: ["No abuse or insult officers", "No give your phone PIN or password voluntarily", "No try bribe them — e go make your situation worse", "No sign any statement without reading and understanding am"],
        yo: ["Má bú tabi ṣe inira si awọn ọfẹ", "Má fun wọn ni PIN foonu rẹ tabi ọrọ aṣina ni ifẹ", "Má gbiyanju lati gbọn wọn — yoo ṣe ipo rẹ buru si", "Má fowo si eyikeyi alaye laisi kika ati oye"],
        ha: ["Kada ka zagi ko yi wa jandami baki", "Kada ka ba da PIN wayar ka ko kalmar wucewa cikin son rai", "Kada ka yi cin hanci — zai sa halin ka ya yi muni", "Kada ka sanya hannu kan duk wata sanarwa ba tare da karanta da fahimta ba"],
        ig: ["Atụkwasịla iyi ma ọ bụ ịsọ ndị ọrụ ọjọọ", "Ekenyekwala PIN ekwenti gị ma ọ bụ paswọọdụ ọcha ọcha", "Anọkwala na-agbalị ịtụ ego n'aka ha — ọ ga-eme ọnọdụ gị ka njọ", "Akwadobiahala nkwupụta ọ bụla na-agụghị ya na ịghọta ya"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 37",
          plainEnglish: {
            en: "The privacy of citizens, their homes, correspondence, telephone conversations, and telegraphic communications is guaranteed and protected. Accessing your phone without consent or court order is a violation.",
            pcm: "Nigeria Constitution guarantee privacy of citizens, their homes, letters, phone calls. Accessing your phone without your consent or court order na violation.",
            yo: "Ofin ipilẹ Nigeria ṣe iṣeduro ati daabo bo ikọkọ ti awọn ọmọ ilu, ile wọn, lẹta, ati awọn ipe foonu. Wiwọle si foonu rẹ laisi igbanilaaye tabi aṣẹ ile-ẹjọ jẹ ìka.",
            ha: "Kundin Tsarin Mulki na Najeriya ya tabbatar da kare sirrin 'yan kasa, gidajensu, wasiƙunsu, tattaunawar wayar tarho. Shiga wayarka ba tare da izini ko umurnin kotu ba cin zarafi ne.",
            ig: "Iwu Nke Naịjirịa na-ekwe nkwa ma na-echebe nzuzo nke ndị ọchịchọ, ụlọ ha, akwụkwọ ozi, mkparịta ụka ekwenti. Ọbanye n'ekwenti gị na-enweghị ikike ma ọ bụ iwu ụlọ ikpe bụ mmebi.",
          },
        },
        {
          name: "Cybercrimes (Prohibition, Prevention, Etc.) Act 2015",
          section: "Section 38",
          plainEnglish: {
            en: "Law enforcement agencies may apply to court for a warrant to access electronic records. They cannot simply demand access to your phone without a warrant.",
            pcm: "Law enforcement fit apply to court for warrant to access your electronic records. Dem no fit just demand your phone without warrant.",
            yo: "Awọn ile-iṣẹ ẹjọ le beere si ile-ẹjọ fun iwe aṣẹ lati wọle si awọn igbasilẹ itanna. Wọn ko le kan beere lọwọ rẹ lati wọle si foonu rẹ laisi iwe aṣẹ.",
            ha: "Hukumomin tsaro na iya neman izinin kotu don shiga bayanan lantarki. Ba za su iya kawai neman shiga wayarka ba tare da izini ba.",
            ig: "Ndị ọchịchọ iwu nwere ike ịrịọ n'ụlọ ikpe maka iwu ọbanye ndekọ eletrọnịk. Ha enweghị ike ọ bụ naanị ịrịọ ọbanye n'ekwenti gị na-enweghị iwu ahụ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Police stop you on the street. You have a laptop bag and dreadlocks. An officer says: 'You look like a yahoo boy. Open your laptop.'",
            pcm: "Police stop you for street. You carry laptop bag and you get dreadlocks. Officer say: 'You look like yahoo boy. Open your laptop.'",
            yo: "Ọlọpaa da ọ duro lori ita. O ni apo laptop ati dreads. Ọfẹ kan sọ: 'O dabi ẹni jibiti. Ṣii laptop rẹ.'",
            ha: "Yan sanda sun tsai da kai a kan hanya. Kana da jakar kwamfuta da dreads. Jandamin ya ce: 'Kana kama mai zamba. Bude kwamfutarka.'",
            ig: "Ndị uwe ojii kwụsịa gị n'ụzọ. I nwere akpa laptọpụ na dreads. Onye ọrụ kwuo: 'I dị ka onye yahoo. Meghee laptọpụ gị.'",
          },
          steps: {
            en: [
              "Stay calm. Do not open the laptop yet.",
              "Ask respectfully: 'Officer, what specific crime am I suspected of committing?'",
              "If the answer is 'you look like a fraudster' — that is not a crime. Say: 'Looking a certain way is not an offence under Nigerian law. I respectfully decline to consent to a search without a lawful basis.'",
              "If they insist and it becomes unsafe, you may comply physically but verbally state: 'I do not consent to this search.'",
              "Note everything: time, place, officer badge number and name.",
              "After the encounter, report to the Nigerian Bar Association or a lawyer, and consider filing a complaint.",
            ],
            pcm: [
              "Calm down. No open laptop yet.",
              "Ask respectfully: 'Officer, which specific crime you suspect me of?'",
              "If dem say 'you look like fraudster' — that no be crime. Tell dem: 'Looking certain way no be offence under Nigerian law. I respectfully refuse search without lawful reason.'",
              "If dem insist and e become unsafe, comply physically but say: 'I no consent to this search.'",
              "Note everything: time, place, officer badge number and name.",
              "After the encounter, report to NBA or lawyer.",
            ],
            yo: ["Jẹ ki o balẹ. Má ṣii laptop sibẹ.", "Beere pẹlu ọwọ: 'Ọgagun, ẹṣẹ wo ni mo ṣe ti o fura si mí?'", "Ti idahun naa ba jẹ 'o dabi ẹni jibiti' — iyẹn kii ṣe ẹṣẹ. Sọ: 'Wiwo ni ọna kan kii ṣe ẹṣẹ labẹ ofin Nigeria.'", "Ti wọn ba tẹnumọ ti o ba jẹ ailewu, o le tẹle ni ara ṣugbọn sọ: 'Mi o gba aṣẹ fun ayẹwo yii.'", "Ṣe akiyesi ohun gbogbo: akoko, ipo, nọmba aami ọfẹ.", "Lẹhin ipade naa, ròyìn si NBA tabi agbẹjọro."],
            ha: ["Kasance a nutsuwa. Kada ka bude kwamfuta tukuna.", "Yi tambaya da ladabi: 'Jandarm, wane takamaiman laifi ake zargin ni?'", "Idan amsar ta kasance 'kana kama mai zamba' — ba laifi bane. Ce: 'Bayyana wata hanya ba laifi bane a ƙarƙashin dokar Najeriya.'", "Idan sun dage kuma ya zama mara tsaro, kana iya biyayya jiki amma ce: 'Ba na yarda da wannan bincike.'", "Rubuta komai: lokaci, wuri, lambar badge da sunan jandamin.", "Bayan haduwar, kai rahoto ga NBA ko lauya."],
            ig: ["Nọrọ n'udo. Emegheela laptọpụ n'oge a.", "Jụọ n'ọkịtọ: 'Oga, ihe ọjọọ pụtara ìhè gịnị ka a na-eche na m mere?'", "Ọ bụrụ na ọzaghachi bụ 'i dị ka onye aghụghọ' — ọ bụghị mmehie. Kwuo: 'Ịdị n'ụzọ ụfọdụ abụghị mmehie n'okpuru iwu Naịjirịa.'", "Ọ bụrụ na ha arọba ma ọ ghara dị mma, ị nwere ike isoro n'ahụ mana kwuo: 'Anabatahị m nyochaa a.'", "Deechie ihe niile: oge, ebe, nọmba badge na aha onye ọrụ.", "Ka nnọkọ ahụ gasie, kọọ na NBA ma ọ bụ ọka iwu."],
          },
        },
      ],
    },
    {
      slug: "right-to-protest",
      title: {
        en: "Right to Peaceful Protest",
        pcm: "Right to Protest Peacefully",
        yo: "Ẹtọ Lati Ṣe Ehonu Alafia",
        ha: "Haƙƙin Zanga-Zanga Mai Lumana",
        ig: "Ikike Ịgagharị n'Udo",
      },
      summary: {
        en: "Every Nigerian has a constitutional right to peaceful assembly and protest. Police cannot disperse a peaceful protest with force, and you cannot be arrested simply for protesting.",
        pcm: "Every Nigerian get constitutional right to peaceful assembly and protest. Police no fit use force to disperse peaceful protest, and dem no fit arrest you just for protesting.",
        yo: "Gbogbo ọmọ Nigeria ni ẹtọ ofin ipilẹ si apejọ alafia ati ehonu. Ọlọpaa ko le lo agbara lati tuka ehonu alafia, ati pe wọn ko le mu ọ nikan nitori protesto.",
        ha: "Kowane ɗan Najeriya yana da haƙƙin tsarin mulki na taron lumana da zanga-zanga. Yan sanda ba za su iya amfani da ƙarfi don tarwatsa zanga-zangar lumana ba.",
        ig: "Onye Naịjirịa ọ bụla nwere ikike iwu maka njikọ n'udo na ịgagharị. Ndị uwe ojii enweghị ike ojiji ihe ike ịkpọ ọgbakọ ịgagharị n'udo, onye ọ bụla enweghị ike ijide gị naanị maka ịgagharị.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Request that protesters notify the police of a planned protest in advance",
          "Maintain order and protect protesters",
          "Arrest individuals who commit crimes during a protest (looting, assault)",
          "Disperse a protest if it becomes violent",
        ],
        pcm: ["Ask protesters to notify police before protest", "Maintain order and protect protesters", "Arrest people wey commit crime during protest", "Disperse protest if e become violent"],
        yo: ["Beere fun awọn oluyegbe lati fi ọlọpaa leti ti ehonu ti a gbero", "Ṣetọju aṣẹ ati daabo bo awọn oluyegbe", "Mu awọn ẹni ti o ṣe ẹṣẹ lakoko ehonu", "Tuka ehonu ti o ba di iwa-ipa"],
        ha: ["Nemi masu zanga-zanga su sanar da 'yan sanda kafin zanga-zangar", "Kiyaye tsari da kare masu zanga-zanga", "Kama mutanen da suka aikata laifi a lokacin zanga-zanga", "Tarwatsa zanga-zanga idan ta zama mai tashin hankali"],
        ig: ["Rịọ ndị ịgagharị ka ha mee ka ndị uwe ojii mara maka ịgagharị ahụ", "Nọdee n'usoro ma chebe ndị ịgagharị", "Jide ndị mere mmehie n'oge ịgagharị", "Kpọọ ndị ịgagharị ma ọ bụrụ na ha ghara ịdị n'udo"],
      },
      cannotDo: {
        en: [
          "Prohibit a peaceful protest",
          "Use tear gas, water cannons, or live ammunition against peaceful protesters",
          "Arrest protesters for peaceful expression",
          "Detain protesters beyond 24 hours without charge",
          "Demand protesters disperse without lawful cause",
        ],
        pcm: ["Prohibit peaceful protest", "Use tear gas, water cannon, or live ammo against peaceful protesters", "Arrest protesters for peaceful expression", "Hold protesters past 24 hours without charge", "Order protesters to disperse without lawful cause"],
        yo: ["Gbesele ehonu alafia", "Lo omi ẹkún, omi ẹrọ, tabi ohun ija atilẹhin lodi si awọn oluyegbe alafia", "Mu awọn oluyegbe fun ikosile alafia", "Fi awọn oluyegbe pamọ́ ju wakati 24 lọ laisi ẹsun", "Paṣẹ fun awọn oluyegbe lati tuka laisi idi ofin"],
        ha: ["Hana zanga-zangar lumana", "Yi amfani da hayakin hawaye, bindigar ruwa, ko harsashin raye akan masu zanga-zangar lumana", "Kama masu zanga-zanga don bayyana kur'ayana", "Tsare masu zanga-zanga fiye da awanni 24 ba tare da tuhuma ba", "Umurtar masu zanga-zanga da su wargaje ba tare da dalilin doka ba"],
        ig: ["Machibido ịgagharị n'udo", "Ojiji gas na-anya anya, cannon mmiri, ma ọ bụ ọgụ ndụ megide ndị ịgagharị n'udo", "Jide ndị ịgagharị maka ikwuputa n'udo", "Nọdee ndị ịgagharị n'ogige ihe karịa awa 24 na-ebulizie ha", "Nyee iwu ndị ịgagharị ka ha pụọ na-enweghị ezi ihe kpatara iwu"],
      },
      whatToDo: {
        en: [
          "Know the planned protest route and carry a copy of your rights",
          "Protest peacefully — do not engage in violence or destruction",
          "If arrested, exercise your right to remain silent and request a lawyer",
          "Document police misconduct — video record if safe",
          "If injured, seek medical attention and document injuries",
        ],
        pcm: ["Know the protest route and carry copy of your rights", "Protest peacefully — no do violence or destroy things", "If dem arrest you, use your right to silence and ask for lawyer", "Document police misconduct — video them if safe to do so", "If you get injured, get medical help and document"],
        yo: ["Mọ ipa-ọna ehonu ti a gbero ati gbe adakọ awọn ẹtọ rẹ", "Ṣe ehonu ni alafia — má ṣe iwa-ipa", "Ti a ba mu ọ, lo ẹtọ rẹ si idakẹjẹ ati beere agbẹjọro", "Ṣe akọsilẹ ihuwasi ọlọpaa — ya fídíò ti o ba jẹ ailewu", "Ti o ba farapa, wa itọju iṣoogun ati ṣe akọsilẹ"],
        ha: ["San hanyar zanga-zangar da aka tsara kuma ɗauki kwafin haƙƙoƙinka", "Yi zanga-zanga cikin lumana — kada ka yi tashin hankali ko halaka", "Idan aka kama ka, yi amfani da haƙƙinka na yin shiru kuma nemi lauya", "Rubuta miyagun halayyar 'yan sanda — yi bidiyo idan lafiya ta bada damar", "Idan ka ji rauni, nemi taimakon likita kuma rubuta"],
        ig: ["Mara ụzọ ịgagharị ahụ ma buru otu n'ime ikike gị", "Gagharị n'udo — emekwala ihe ike", "Ọ bụrụ na e jidee gị, jiri ikike gị ịnọ nè ma rịọ ọka iwu", "Deechie mmejọ uwe ojii — dee vidiyo ọ bụrụ na ọ dị mma", "Ọ bụrụ na imerụọ ahụ, chọọ ọgwụgwọ ahụike ma deechie imerụ ahụ"],
      },
      whatNotToDo: {
        en: [
          "Do not bring weapons to a protest",
          "Do not engage in looting or property destruction — it criminalises your protest",
          "Do not wear masks to conceal your identity (this can be unlawful)",
          "Do not provoke security forces physically",
        ],
        pcm: ["No bring weapon to protest", "No loot or destroy property — e go make your protest criminal", "No wear mask to hide face (fit be unlawful in some states)", "No physically provoke security forces"],
        yo: ["Má mu ohun ija lọ si ehonu", "Má ṣe jija tabi ìparun ohun ini — yoo ṣe ehonu rẹ di ọdaràn", "Má wọ iboju lati fi oju pamọ́ (o le jẹ aitọ)", "Má damu awọn ọmọ ogun ni ara"],
        ha: ["Kada ka kawo makami zanga-zanga", "Kada ka yi sata ko halaka dukiya — yana sanya zanga-zangar ka ta zama laifi", "Kada ka sa abin rufe fuska don ɓoye kai (na iya zama ba doka ba a wasu jihohi)", "Kada ka tayar da sojojin tsaro jiki"],
        ig: ["Ebugụkwala ngwa agha ịgagharị", "Emekwala ọ zụmahịa ma ọ bụ ịtọgbue ihe — ọ ga-eme ịgagharị gị bụrụ mmehie", "Ayịkwala ihe igbu anya iji zochie ihu gị (nwere ike ọ bụghị iwu)", "Egosikwala ọnụ n'ahụ ụmụ agha nchedo"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 40",
          plainEnglish: {
            en: "Every person shall be entitled to assemble freely and associate with other persons, and in particular, he may form or belong to any political party, trade union or any other association.",
            pcm: "Every person get right to gather freely and associate with others. You fit form or belong to any party, union, or association.",
            yo: "Gbogbo eniyan ni ẹtọ lati pejọ larọwọto ati lati papọ pẹlu awọn eniyan miiran, ati ni pataki, o le da tabi jẹ ti eyikeyi ẹgbẹ oṣelu, ẹgbẹ iṣẹ tabi eyikeyi ẹgbẹ miiran.",
            ha: "Kowane mutum na da haƙƙin taruwa 'yanci da yin hulɗa da sauran mutane, kuma musamman, zai iya kafa ko zama memba na duk wata jam'iyya ta siyasa, ƙungiyar kwadago ko duk wata ƙungiya.",
            ig: "Onye ọ bụla nwere ikike ịzọ n'ọchịchọ ọcha ma jikọọ na ndị ọzọ, na pụtara ìhè, ọ nwere ike ịhazi ma ọ bụ ịbụ onye otu ọ bụla n'ime ndị otu ndọrọ ndọrọ ọchịchọ, otu ndị ọrụ, ma ọ bụ ọgbakọ ọ bụla ọzọ.",
          },
        },
      ],
      scenarios: [],
    },
    {
      slug: "digital-privacy",
      title: {
        en: "Digital Privacy Rights — Your Phone Is Not Fair Game",
        pcm: "Digital Privacy — Dem No Get Right to Grab Your Phone",
        yo: "Ẹtọ Asiri Oni-Nọmba — Foonu Rẹ Kii Ṣe Ohun Gbogbo Eniyan",
        ha: "Haƙƙoƙin Sirrin Dijital — Wayarka Ba Ta Wa Ba Ce",
        ig: "Ikike Nzuzo Dijitalụ — Ekwenti Gị Abụghị Ihe Ha Ga-Anakwere",
      },
      summary: {
        en: "Police cannot search your phone or laptop without a court order. The Cybercrimes Act 2015 does not give police unlimited power to seize devices. Section 37 of the Constitution guarantees your privacy. EFCC officers need a court order or a properly issued warrant to seize electronics. You do not have to unlock your phone for police.",
        pcm: "Police no fit search your phone or laptop without court order. Cybercrimes Act 2015 no give police unlimited power to seize devices. Section 37 of Constitution guarantee your privacy. EFCC need court order or proper warrant to seize your electronics. You no need to unlock your phone for police.",
        yo: "Ọlọpaa ko le ṣayẹwo foonu tabi laptop rẹ laisi aṣẹ ile-ẹjọ. Ofin Cybercrimes 2015 ko fun ọlọpaa ni agbara ailopin lati gba awọn ẹrọ. Abala 37 ti Ofin Ipilẹ ṣe iṣeduro asiri rẹ. EFCC nilo aṣẹ ile-ẹjọ lati gba awọn ẹrọ itanna. O ko nilo lati ṣii foonu rẹ fun ọlọpaa.",
        ha: "Yan sanda ba za su iya bincika wayarka ko kwamfutarka ba tare da umurnin kotu ba. Dokar Cybercrimes ta 2015 ba ta ba 'yan sanda iko mara iyaka na kwace na'urori ba. Sashe na 37 na Kundin Tsarin Mulki ya tabbatar da sirrin ka. EFCC na buƙatar umurnin kotu don kwace na'urorin lantarki. Ba dole ka buɗe wayarka wa 'yan sanda ba.",
        ig: "Ndị uwe ojii enweghị ike ịnyocha ekwenti ma ọ bụ laptọpụ gị na-enweghị iwu ụlọ ikpe. Iwu Cybercrimes 2015 enyeghị ndị uwe ojii ọnụ na-enweghị oke iji wepụ ngwaọrụ. Ngalaba 37 nke Iwu Nke Naịjirịa na-ekwe nkwa nzuzo gị. Ndị EFCC chọọ iwu ụlọ ikpe iji wepụ ihe ọrụ eletrọnịk. Ọ dịghị mkpa ịmeghe ekwenti gị nye ndị uwe ojii.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Request to see your phone if they have a valid court order or warrant",
          "Seize your device if acting under a properly issued warrant",
          "Apply to court for an order to access your electronic records",
          "Arrest you if there is a lawful warrant for your arrest",
        ],
        pcm: ["Ask to see your phone if dem get valid court order or warrant", "Seize your device if dem get proper warrant", "Apply to court for order to access your electronic records", "Arrest you if dem get lawful warrant for your arrest"],
        yo: ["Beere lati ri foonu rẹ ti wọn ba ni aṣẹ ile-ẹjọ tabi iwe aṣẹ to wulo", "Gba ẹrọ rẹ ti wọn ba n ṣe labẹ iwe aṣẹ ti a ti fun ni deede", "Beere si ile-ẹjọ fun aṣẹ lati wọle si awọn igbasilẹ itanna rẹ", "Mu ọ ti aṣẹ ofin fun imuni rẹ ba si"],
        ha: ["Nemi ganin wayarka idan suna da ingantaccen umurnin kotu ko izini", "Kwace na'urarka idan suna aiki ƙarƙashin izini da aka ba da su yadda ya kamata", "Neman kotu don samun umurnin shiga bayanan lantarki naka", "Kama ka idan akwai ingantaccen umurnin kama ka"],
        ig: ["Rịọ ilele ekwenti gị ọ bụrụ ha nwere iwu ụlọ ikpe ma ọ bụ iwu ziri ezi", "Webata ngwaọrụ gị ọ bụrụ na ha na-arụ ọrụ n'okpuru iwu e nyere nke ọma", "Rịọ ụlọ ikpe maka iwu iji banye ndekọ eletrọnịk gị", "Jide gị ọ bụrụ na enwere iwu iwu ziri ezi maka iji jide gị"],
      },
      cannotDo: {
        en: [
          "Demand you unlock your phone without a court order",
          "Search your phone, laptop, or other devices without a valid warrant",
          "Seize your electronics based solely on suspicion or appearance",
          "Access your emails, chats, or stored data without a court order",
          "Use the Cybercrimes Act to justify unlimited seizure of devices — the Act requires a warrant",
        ],
        pcm: ["Force you to unlock your phone without court order", "Search your phone, laptop, or device without valid warrant", "Seize your electronics based on suspicion or how you look", "Access your emails, chats, or data without court order", "Use Cybercrimes Act to justify seizing devices anyhow — the Act requires warrant"],
        yo: ["Fi ọ pọn lati ṣii foonu rẹ laisi aṣẹ ile-ẹjọ", "Ṣayẹwo foonu, laptop, tabi awọn ẹrọ rẹ laisi iwe aṣẹ to wulo", "Gba awọn ẹrọ itanna rẹ nikan nitori ifura tabi irisi", "Wọle si imeeli, ibaraẹnisọrọ, tabi data ti o fipamọ laisi aṣẹ ile-ẹjọ", "Lo Ofin Cybercrimes lati da imudani awọn ẹrọ laisi iwe aṣẹ — Ofin naa nilo iwe aṣẹ"],
        ha: ["Tilasta ka buɗe wayarka ba tare da umurnin kotu ba", "Bincika wayarka, kwamfutarka, ko na'urorika ba tare da ingantaccen izini ba", "Kwace na'urorin lantarki naka kawai bisa zargi ko bayyana", "Shiga imel naka, tattaunawa, ko bayanan da aka adana ba tare da umurnin kotu ba", "Yi amfani da Dokar Cybercrimes don tabbatar da kwace na'urori cikin 'yanci — Dokar tana buƙatar izini"],
        ig: ["Ịmanye gị imeghe ekwenti gị na-enweghị iwu ụlọ ikpe", "Ịnyocha ekwenti, laptọpụ, ma ọ bụ ngwaọrụ gị na-enweghị iwu ziri ezi", "Ịwepụ ihe ọrụ eletrọnịk gị naanị n'ihi echiche ma ọ bụ ọdịdị", "Ọbanye n'ozi-e-mail gị, mkparịta ụka, ma ọ bụ data edekọ na-enweghị iwu ụlọ ikpe", "Iji Iwu Cybercrimes tọọ ụzọ ịwepụ ngwaọrụ na-enweghị iwu — Iwu ahụ chọọ iwu"],
      },
      whatToDo: {
        en: [
          "Calmly ask: 'Do you have a court order or warrant to search my device?'",
          "If no warrant is produced, say clearly: 'I do not consent to a search of my device without a court order.'",
          "If they insist, comply physically to avoid escalation but repeat your non-consent verbally",
          "Note the officer's name, badge number, the time, and location",
          "Contact a lawyer or the NBA as soon as possible after the encounter",
        ],
        pcm: ["Calmly ask: 'You get court order or warrant to search my device?'", "If dem no show warrant, say clearly: 'I no consent to search of my device without court order.'", "If dem insist, comply physically to avoid trouble but keep saying you no consent", "Note officer name, badge number, time, and location", "Contact lawyer or NBA as soon as possible after"],
        yo: ["Beere ni idakẹjẹ: 'Ṣe o ni aṣẹ ile-ẹjọ tabi iwe aṣẹ lati ṣayẹwo ẹrọ mi?'", "Ti ko ba si iwe aṣẹ, sọ ni gbangba: 'Mi o fohun si ṣiṣayẹwo ẹrọ mi laisi aṣẹ ile-ẹjọ.'", "Ti wọn ba tẹnumọ, tẹle ni ara lati yago fun ìga ipo ṣugbọn tun sọ pe o ko fohun", "Ṣe akiyesi oruko ọfẹ, nọmba ami, akoko, ati ipo", "Kan si agbẹjọro tabi NBA ni kete to ba tan"],
        ha: ["Yi tambaya cikin nutsuwa: 'Kuna da umurnin kotu ko izini don bincika na'urata?'", "Idan ba a nuna izinin ba, ce a sarari: 'Ba na yarda da binciken na'urata ba tare da umurnin kotu ba.'", "Idan sun dage, yi biyayya jiki don gujewa matsala amma sake faɗar rashin yardarku", "Rubuta sunan jandamin, lambar badge, lokaci, da wuri", "Tuntubi lauya ko NBA da zarar ya yiwu bayan haduwar"],
        ig: ["Jụọ n'udo: 'I nwere iwu ụlọ ikpe ma ọ bụ iwu iji nyocha ngwaọrụ m?'", "Ọ bụrụ na ha egosighị iwu, kwuo n'ụzọ doro ìhè: 'Anabatahị m inyocha ngwaọrụ m na-enweghị iwu ụlọ ikpe.'", "Ọ bụrụ na ha arọba, soro n'ahụ iji zere esemokwu mana gaa n'ihu na-ekwu na ị kwadoghị", "Deechie aha onye ọrụ, nọmba badge, oge, na ebe", "Kpọtụrụ ọka iwu ma ọ bụ NBA ozugbo emesia nnọkọ ahụ"],
      },
      whatNotToDo: {
        en: [
          "Do not voluntarily hand over your phone PIN, password, or fingerprint",
          "Do not delete files or data in front of officers — it can be seen as obstruction",
          "Do not sign any consent form for device search without legal advice",
          "Do not assume the Cybercrimes Act gives officers automatic rights to your devices",
        ],
        pcm: ["No voluntarily give your phone PIN, password, or fingerprint", "No delete files or data in front of officers — dem fit see am as obstruction", "No sign any consent form for device search without legal advice", "No assume Cybercrimes Act give officers automatic right to your devices"],
        yo: ["Má fun wọn ni PIN foonu, ọrọ aṣina, tabi ika ọwọ ni ifẹ", "Má pa awọn faili tabi data ni iwaju awọn ọfẹ — wọn le rii rẹ bi idena", "Má fowo si fọọmu igbanilaaye fun ṣiṣayẹwo ẹrọ laisi imọran ofin", "Má ro pe Ofin Cybercrimes fun awọn ọfẹ ni awọn ẹtọ aifọwọyi si awọn ẹrọ rẹ"],
        ha: ["Kada ka ba da PIN wayarka, kalmar wucewa, ko yatsan hannu cikin son rai", "Kada ka share fayiloli ko bayanan a gaban jandaman — na iya zama kamar hana aiki", "Kada ka sanya hannu kan kowane fom na yarda don binciken na'ura ba tare da shawarar doka ba", "Kada ka ɗauka cewa Dokar Cybercrimes ta ba jandaman haƙƙin kai tsaye ga na'urorinaka"],
        ig: ["Ekenyekwala PIN ekwenti gị, paswọọdụ, ma ọ bụ mkpisi aka gị ọcha ọcha", "Ehichapụkwala faịlụ ma ọ bụ data n'iru ndị ọrụ — ha nwere ike ilele ya dị ka igbochi", "Akwadobiahala fọọm ikwe maka inyocha ngwaọrụ na-enweghị ndụmọdụ iwu", "Echeghị na Iwu Cybercrimes nyere ndị ọrụ ikike ozugbo n'ime ngwaọrụ gị"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 37",
          plainEnglish: {
            en: "The privacy of citizens, their homes, correspondence, telephone conversations, and telegraphic communications is guaranteed and protected. This extends to digital communications and devices.",
            pcm: "Nigeria Constitution guarantee privacy of citizens, their homes, letters, phone calls — this include digital communications and devices too.",
            yo: "Ofin Ipilẹ Nigeria ṣe iṣeduro ati daabo bo asiri ti awọn ọmọ ilu, ile wọn, lẹta, ati awọn ipe foonu. Eyi tun pẹlu awọn ibaraẹnisọrọ oni-nọmba ati awọn ẹrọ.",
            ha: "Kundin Tsarin Mulki na Najeriya ya tabbatar da kare sirrin 'yan kasa, gidajensu, wasiƙunsu, da tattaunawar wayar tarho — wannan ya haɗa da sadarwar dijital da na'urori.",
            ig: "Iwu Nke Naịjirịa na-ekwe nkwa ma na-echebe nzuzo nke ndị ọchịchọ, ụlọ ha, akwụkwọ ozi, mkparịta ụka ekwenti — nke a gụnyere mkparịta ụka dijitalụ na ngwaọrụ.",
          },
        },
        {
          name: "Cybercrimes (Prohibition, Prevention, Etc.) Act 2015",
          section: "Section 38",
          plainEnglish: {
            en: "Law enforcement must obtain a court order before accessing or seizing electronic records. The Act does not grant open-ended power to search devices — a warrant is required.",
            pcm: "Law enforcement must get court order before dem access or seize your electronic records. The Act no give dem open power to search devices anyhow — dem need warrant.",
            yo: "Ẹjọ ofin gbọdọ gba aṣẹ ile-ẹjọ ṣaaju wiwọle si tabi gbigba awọn igbasilẹ itanna. Ofin naa ko fun wọn ni agbara ailopin lati ṣayẹwo awọn ẹrọ — iwe aṣẹ ni a nilo.",
            ha: "Hukumomin tsaro dole ne su sami umurnin kotu kafin su shiga ko kwace bayanan lantarki. Dokar ba ta ba su iko mara iyaka na bincika na'urori — ana buƙatar izini.",
            ig: "Ndị ọchịchọ iwu kwesịrị nweta iwu ụlọ ikpe tupu ha banye ma ọ bụ wepụ ndekọ eletrọnịk. Iwu ahụ enyeghị ha ọnụ na-enweghị oke iji nyocha ngwaọrụ — a chọọ iwu.",
          },
        },
        {
          name: "Economic and Financial Crimes Commission (Establishment) Act 2004",
          section: "Section 28",
          plainEnglish: {
            en: "The EFCC has powers of search and seizure but these must be exercised under a warrant or court order. EFCC officers cannot seize your laptop or phone on the street without proper legal authority.",
            pcm: "EFCC get power to search and seize but dem must use warrant or court order. EFCC officers no fit just seize your laptop or phone for street without proper legal authority.",
            yo: "EFCC ni awọn agbara ti ṣiṣayẹwo ati gbigba ṣugbọn awọn wọnyi gbọdọ ṣe labẹ iwe aṣẹ tabi aṣẹ ile-ẹjọ. Awọn ọfẹ EFCC ko le gba laptop tabi foonu rẹ lori ita laisi aṣẹ ofin to peye.",
            ha: "EFCC tana da iko na bincike da kwace amma dole ne a yi amfani da su ƙarƙashin izini ko umurnin kotu. Jandaman EFCC ba za su iya kwace kwamfutarka ko wayarka a kan hanya ba tare da ingantaccen ikon doka ba.",
            ig: "EFCC nwere ọnụ nyocha na ịwepụ mana a ga-eri ha n'okpuru iwu ma ọ bụ iwu ụlọ ikpe. Ndị ọrụ EFCC enweghị ike ịwepụ laptọpụ ma ọ bụ ekwenti gị n'ụzọ na-enweghị ezi ọnụ iwu.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "An EFCC officer stops you outside a mall and demands you hand over your phone and unlock it, saying they are investigating cybercrime and you 'look suspicious'.",
            pcm: "EFCC officer stop you outside mall and demand your phone and say you must unlock am. Dem say dem dey investigate cybercrime and you 'look suspicious'.",
            yo: "Ọfẹ EFCC da ọ duro ita ile-itaja ati beere ki o fun wọn ni foonu rẹ ki o si ṣii rẹ, wọn ni wọn n ṣe iwadii cybercrime ati pe o 'dabi ẹni ti o fura si'.",
            ha: "Jandamin EFCC ya tsai da ka waje da shago kuma ya nemi ka ba shi wayarka kuma ka buɗe ta, yana cewa suna binciken laifin yanar gizo kuma kana 'kama mai zargi'.",
            ig: "Onye ọrụ EFCC kwụsịa gị n'èzí ụlọ ahịa ma rịọ gị ka ị nyefee ha ekwenti gị ma meghe ya, na-ekwu na ha na-enyocha cybercrime ma gị 'dị ka onye a na-ata obi ụjọ'.",
          },
          steps: {
            en: [
              "Stay calm. Do not panic or run.",
              "Ask politely: 'Officer, do you have a court order or warrant authorising this search?'",
              "If no warrant is shown, say: 'I respect your authority, but I am unable to hand over my device or unlock it without seeing a valid court order. This is my right under Section 37 of the Constitution and Section 38 of the Cybercrimes Act.'",
              "If they insist and you fear for your safety, you may comply physically — but clearly state out loud: 'I do not consent to this search. I am complying under duress.'",
              "Note the officer's name, ID number, vehicle plate if any, time, and location.",
              "Contact a lawyer or call the NBA's emergency legal aid line as soon as possible.",
            ],
            pcm: [
              "Calm down. No panic or run.",
              "Ask politely: 'Officer, you get court order or warrant for this search?'",
              "If dem no show warrant, say: 'I respect your authority but I cannot hand over my device or unlock am without valid court order. Na my right under Section 37 of Constitution and Section 38 of Cybercrimes Act.'",
              "If dem insist and you fear for your safety, comply physically — but say out loud: 'I no consent to this search. I dey comply under duress.'",
              "Note officer name, ID number, vehicle plate if any, time, and location.",
              "Contact lawyer or call NBA emergency legal aid as soon as possible.",
            ],
            yo: [
              "Jẹ ki o balẹ. Má bẹru tabi sá.",
              "Beere pẹlu ọwọ: 'Ọgagun, ṣe o ni aṣẹ ile-ẹjọ tabi iwe aṣẹ fun ṣiṣayẹwo yii?'",
              "Ti ko ba si iwe aṣẹ, sọ: 'Mo bọwọ fun aṣẹ rẹ ṣugbọn mi o le fun ẹrọ mi tabi ṣii rẹ laisi aṣẹ ile-ẹjọ to wulo. Eyi ni ẹtọ mi labẹ Abala 37 ti Ofin Ipilẹ ati Abala 38 ti Ofin Cybercrimes.'",
              "Ti wọn ba tẹnumọ ti o ba bẹru fun aabo rẹ, o le tẹle ni ara — ṣugbọn sọ ni gbangba: 'Mi o fohun si ayẹwo yii. Mo n tẹle labẹ ipọnju.'",
              "Ṣe akiyesi oruko ọfẹ, nọmba ID, pẹpẹ ọkọ ti o ba si, akoko, ati ipo.",
              "Kan si agbẹjọro tabi pe laini iranlọwọ ofin pajawiri ti NBA ni kete to ba tan.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka firgita ko gudu.",
              "Yi tambaya da ladabi: 'Jandarm, kuna da umurnin kotu ko izini don wannan bincike?'",
              "Idan ba a nuna izinin ba, ce: 'Ina girmama ikonku amma ba zan iya ba da na'urata ko buɗe ta ba tare da ingantaccen umurnin kotu ba. Wannan haƙƙina ne ƙarƙashin Sashe na 37 na Kundin Tsarin Mulki da Sashe na 38 na Dokar Cybercrimes.'",
              "Idan sun dage kuma kana jin tsoro don lafiyarka, kana iya biyayya jiki — amma faɗa a sarari: 'Ba na yarda da wannan bincike. Ina biyayya ne da tilastawa.'",
              "Rubuta sunan jandamin, lambar ID, farantir mota idan akwai, lokaci, da wuri.",
              "Tuntubi lauya ko kira layin taimakon doka na gaggawa na NBA da zarar ya yiwu.",
            ],
            ig: [
              "Nọrọ n'udo. Atọ egwụ ma agbakwala ọsọ.",
              "Jụọ n'ọkịtọ: 'Oga, i nwere iwu ụlọ ikpe ma ọ bụ iwu maka nyocha a?'",
              "Ọ bụrụ na ha egosighị iwu, kwuo: 'Ana m asọpụrụ ọnụ gị mana enweghị m ike inye ngwaọrụ m ma ọ bụ imeghe ya na-enweghị iwu ụlọ ikpe ziri ezi. Nke a bụ ikike m n'okpuru Ngalaba 37 nke Iwu Nke Naịjirịa na Ngalaba 38 nke Iwu Cybercrimes.'",
              "Ọ bụrụ na ha arọba ma ị tụọ egwụ maka nchekwa gị, ị nwere ike isoro n'ahụ — mana kwuo n'ụzọ pụtara ìhè: 'Anabatahị m nyochaa a. Ana m asoro n'okpuru ịmanye.'",
              "Deechie aha onye ọrụ, nọmba ID, nọmba ụgbọ ala ọ bụrụ na ọ dị, oge, na ebe.",
              "Kpọtụrụ ọka iwu ma ọ bụ kpọọ ahịa enyemaka iwu mberede NBA ozugbo o kwere omume.",
            ],
          },
        },
      ],
    },
    {
      slug: "cybercrime-rights",
      title: {
        en: "Cybercrime Accusations — Know Your Rights",
        pcm: "Cybercrime Accusation — Know Your Rights",
        yo: "Ẹsun Cybercrime — Mọ Awọn Ẹtọ Rẹ",
        ha: "Zargin Laifin Yanar Gizo — San Haƙƙoƙinka",
        ig: "Ebubo Cybercrime — Mara Ikike Gị",
      },
      summary: {
        en: "The EFCC and police sometimes arrest young Nigerians based purely on lifestyle or social media posts. Being accused of cybercrime does not remove your constitutional rights — you still have the right to silence, bail, and legal representation. The Cybercrimes Act 2015 defines specific offences — owning a laptop or living well is NOT an offence.",
        pcm: "EFCC and police sometimes arrest young Nigerians just because of their lifestyle or social media posts. If dem accuse you of cybercrime, your constitutional rights remain intact — you still get right to silence, bail, and legal representation. Cybercrimes Act 2015 define specific offences — owning laptop or living well NO be offence.",
        yo: "EFCC ati ọlọpaa máa n mu awọn ọdọ Nigerians da nikan nitori igbe aye wọn tabi awọn ifiweranṣẹ media awujọ. Jijẹ ẹni ti a fi ẹsun cybercrime kan ko yọ awọn ẹtọ ofin ipilẹ rẹ — o tun ni ẹtọ si idakẹjẹ, beli, ati aṣoju ofin. Ofin Cybercrimes 2015 ṣalaye awọn ẹṣẹ pato — nini laptop tabi gbigbe daradara KO ṣe ẹṣẹ.",
        ha: "EFCC da 'yan sanda wani lokaci suna kama matasan Najeriya kawai saboda salon rayuwarsu ko abubuwan da suka rubuta a kafofin sada zumunta. Zargin laifin yanar gizo ba ya cire haƙƙoƙin tsarin mulki naka — har yanzu kana da haƙƙin yin shiru, beli, da wakilcin doka. Dokar Cybercrimes ta 2015 ta bayyana takamaiman laifuka — mallakan kwamfuta ko rayuwa lafiya BA laifi bane.",
        ig: "EFCC na ndị uwe ojii n'oge ụfọdụ na-ejide ọchịchọ ndị Naịjirịa dabere n'ụzọ ha na-ebi ma ọ bụ ihe ha na-edeede na mgbasa ozi mmekọ. Ọ bụrụ a na-ebube gị maka cybercrime anaghị ewepụ ikike iwu gị — ị ka nwere ikike ịnọ nè, beli, na nnọchiteanya iwu. Iwu Cybercrimes 2015 na-akọwapụta mmehie a kapịrị ọnụ — inwe laptọpụ ma ọ bụ ibi ndụ ọma ABỤGHỊ mmehie.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Arrest you if they have reasonable grounds and a lawful warrant",
          "Investigate specific offences defined under the Cybercrimes Act 2015",
          "Request electronic records from service providers through a court order",
          "Charge you to court within a reasonable time if evidence supports a charge",
        ],
        pcm: ["Arrest you if dem get reasonable grounds and lawful warrant", "Investigate specific offences defined under Cybercrimes Act 2015", "Request electronic records from service providers through court order", "Charge you to court within reasonable time if evidence supports it"],
        yo: ["Mu ọ ti wọn ba ni awọn idi to peye ati iwe aṣẹ ofin", "Ṣe iwadii awọn ẹṣẹ pato ti a ṣalaye labẹ Ofin Cybercrimes 2015", "Beere awọn igbasilẹ itanna lọwọ awọn olupese iṣẹ nipasẹ aṣẹ ile-ẹjọ", "Mu ọ lọ si ile-ẹjọ laarin akoko to peye ti ẹri ba ṣe atilẹyin ẹsun"],
        ha: ["Kama ka idan suna da dalili mai kyau da ingantaccen umurnin kama", "Bincika takamaiman laifuka da aka bayyana ƙarƙashin Dokar Cybercrimes ta 2015", "Neman bayanan lantarki daga masu ba da sabis ta hanyar umurnin kotu", "Kai ka gaban kotu a cikin lokaci mai kyau idan shaida ta goyi bayan zargi"],
        ig: ["Jide gị ọ bụrụ ha nwere ezi ihe kpatara na iwu ziri ezi", "Nyocha mmehie a kapịrị ọnụ edepụtara n'okpuru Iwu Cybercrimes 2015", "Rịọ ndekọ eletrọnịk sitere n'aka ndị na-enye ọrụ site na iwu ụlọ ikpe", "Bulie gị n'ụlọ ikpe n'ime oge kwesịrị ekwesị ọ bụrụ na ihe akaebe na-akwado ebubo"],
      },
      cannotDo: {
        en: [
          "Arrest you based solely on your lifestyle, appearance, or social media posts",
          "Detain you beyond 24–48 hours without charging you or taking you to court",
          "Deny you access to a lawyer of your choice",
          "Compel you to incriminate yourself — you have the right to remain silent",
          "Treat owning a laptop, driving a nice car, or posting luxury items online as evidence of cybercrime",
        ],
        pcm: ["Arrest you just because of your lifestyle, appearance, or social media posts", "Hold you beyond 24–48 hours without charging you or taking you to court", "Deny you access to your own lawyer", "Force you to incriminate yourself — you get right to remain silent", "Treat owning laptop, driving fine car, or posting luxury things online as evidence of cybercrime"],
        yo: ["Mu ọ nikan nitori igbe aye rẹ, irisi, tabi awọn ifiweranṣẹ media awujọ", "Fi ọ pamọ́ ju wakati 24–48 lọ laisi ẹsun tabi gbigba lọ si ile-ẹjọ", "Kọ fun ọ lati ri agbẹjọro ti o yan", "Fi ọ pọn lati fi ara rẹ lẹbi — o ni ẹtọ si idakẹjẹ", "Wo nini laptop, iwakọ ọkọ dara, tabi fifiweranṣẹ awọn ohun elo igbadun ori ayelujara bi ẹri cybercrime"],
        ha: ["Kama ka kawai saboda salon rayuwarka, bayyana, ko abubuwan da kake rubuta a kafofin sada zumunta", "Tsare ka fiye da awanni 24–48 ba tare da tuhuma ko kai ka gaban kotu ba", "Hana ka samun lauyan da ka zaɓa", "Tilasta ka yin shaida a kan kanka — kana da haƙƙin yin shiru", "Ɗaukar mallakan kwamfuta, tuƙin kyakkyawar mota, ko rubuta abubuwan alfarma a kan layi a matsayin shaida ta laifin yanar gizo"],
        ig: ["Jide gị naanị n'ihi ụzọ gị na-ebi, ọdịdị, ma ọ bụ ihe ị na-edeede na mgbasa ozi mmekọ", "Nọdee gị karịa awa 24–48 na-ebulizie gị ma ọ bụ iwetara gị n'ụlọ ikpe", "Izighị gị ohere ịhụ ọka iwu gị họọrọ", "Ịmanye gị iji nkwupụta megide onwe gị — i nwere ikike ịnọ nè", "Ịlele inwe laptọpụ, ịnya ụgbọ mara mma, ma ọ bụ ịdeede ihe ọbara ọbara n'ịntanetị dị ka ihe akaebe cybercrime"],
      },
      whatToDo: {
        en: [
          "Immediately ask: 'Am I under arrest? What is the specific charge?'",
          "Exercise your right to remain silent — say: 'I choose to remain silent until I speak with a lawyer.'",
          "Ask for bail — you have a constitutional right to bail for bailable offences",
          "Contact a lawyer or ask that a lawyer be contacted on your behalf as soon as possible",
          "Do not sign any statement, admission, or consent form without your lawyer present",
        ],
        pcm: ["Immediately ask: 'You don arrest me? What be the specific charge?'", "Use your right to remain silent — say: 'I go remain silent until I talk to lawyer.'", "Ask for bail — you get constitutional right to bail for bailable offences", "Contact lawyer or ask them to contact lawyer on your behalf as soon as possible", "No sign any statement, admission, or consent form without your lawyer present"],
        yo: ["Lẹsẹkẹsẹ beere: 'Ṣe a mu mi? Kini ẹsun pato naa?'", "Lo ẹtọ rẹ si idakẹjẹ — sọ: 'Mo yan lati dakẹ titi ti mo fi ba agbẹjọro sọrọ.'", "Beere fun beli — o ni ẹtọ ofin ipilẹ si beli fun awọn ẹṣẹ to ni beli", "Kan si agbẹjọro tabi beere pe ki a kan si agbẹjọro fun ọ ni kete to ba tan", "Má fowo si eyikeyi alaye, igbawọle, tabi fọọmu igbanilaaye laisi agbẹjọro rẹ"],
        ha: ["Nan take yi tambaya: 'An kama ni ne? Menene takamaiman zargin?'", "Yi amfani da haƙƙinka na yin shiru — ce: 'Zan zauna a shiru har sai na yi magana da lauya.'", "Nemi beli — kana da haƙƙin tsarin mulki na beli don laifukan da ake ba da beli", "Tuntubi lauya ko nemi a tuntubi lauya a madadinka da zarar ya yiwu", "Kada ka sanya hannu kan duk wata sanarwa, yarda, ko fom na yarda ba tare da lauyan ka ba"],
        ig: ["Ozugbo jụọ: 'A jidere m? Gịnị bụ ebubo a kapịrị ọnụ?'", "Jiri ikike gị ịnọ nè — kwuo: 'Ana m họrọ ịnọ nè ruo mgbe m ga-ekwu okwu na ọka iwu.'", "Rịọ beli — i nwere ikike iwu maka beli maka mmehie nwere beli", "Kpọtụrụ ọka iwu ma ọ bụ rịọ ha ka ha kpọtụrụ ọka iwu maka gị ozugbo o kwere omume", "Akwadobiahala nkwupụta ọ bụla, nkwenye, ma ọ bụ fọọm ikwe na-enweghị ọka iwu gị"],
      },
      whatNotToDo: {
        en: [
          "Do not make any verbal or written statements before speaking to a lawyer",
          "Do not consent to a search of your devices without a court order",
          "Do not attempt to bribe officers — it constitutes a fresh criminal offence",
          "Do not assume that because you are innocent, you do not need a lawyer",
        ],
        pcm: ["No make any statement — verbal or written — before you talk to lawyer", "No consent to device search without court order", "No try to bribe officers — na fresh criminal offence", "No assume that because you innocent, you no need lawyer"],
        yo: ["Má ṣe eyikeyi alaye — ẹnu tabi kikọ — ṣaaju ki o ba ba agbẹjọro sọrọ", "Má fohun si ṣiṣayẹwo ẹrọ rẹ laisi aṣẹ ile-ẹjọ", "Má gbiyanju lati gbọn awọn ọfẹ — o jẹ ẹṣẹ ọdaràn tuntun", "Má ro pe nitori pe o jẹ alaiṣẹ, o ko nilo agbẹjọro"],
        ha: ["Kada ka yi wata sanarwa — ta baki ko rubuce — kafin ka yi magana da lauya", "Kada ka yarda da binciken na'urorinaka ba tare da umurnin kotu ba", "Kada ka yi ƙoƙarin cin hancin jandaman — laifi sabon ne na aikata laifi", "Kada ka ɗauka cewa saboda kai ba mai laifi ba ne, ba ka buƙatar lauya ba"],
        ig: ["Emekwala nkwupụta ọ bụla — n'ọnụ ma ọ bụ ederede — tupu ị kwuo okwu na ọka iwu", "Ikwetahị nyocha ngwaọrụ gị na-enweghị iwu ụlọ ikpe", "Anọkwala na-agbalị ịtụ ego n'aka ndị ọrụ — ọ bụ mmehie ọhụrụ", "Echeghị na n'ihi na ị ziri ezi, ọ dịghị mkpa ọka iwu"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 35",
          plainEnglish: {
            en: "Every person is entitled to personal liberty. A person arrested must be informed of the reason for arrest, brought before a court within 24–48 hours, and is entitled to bail.",
            pcm: "Every person get right to personal liberty. If dem arrest you, dem must tell you why, bring you to court within 24–48 hours, and you get right to bail.",
            yo: "Gbogbo eniyan ni ẹtọ si ominira ti ara. Ẹni ti a mu gbọdọ jẹ alaye idi imuni rẹ, mu wọle si ile-ẹjọ laarin wakati 24–48, ati pe o ni ẹtọ si beli.",
            ha: "Kowane mutum na da haƙƙin 'yancin kai. Dole ne a sanar da mutumin da aka kama dalilin kamawa, a kawo shi gaban kotu a cikin awanni 24–48, kuma yana da haƙƙin beli.",
            ig: "Onye ọ bụla nwere ikike onwe ya. A ga-ekwuputara onye ejidere ya ihe kpatara ijide ya, a wetara ya n'ụlọ ikpe n'ime awa 24–48, ma ọ nwere ikike beli.",
          },
        },
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 36",
          plainEnglish: {
            en: "Every person charged with a criminal offence shall be presumed innocent until proven guilty. You have the right to be told the charge, the right to defend yourself, and the right to legal representation.",
            pcm: "Every person wey dem charge with criminal offence suppose be presumed innocent until proven guilty. You get right to know the charge, defend yourself, and get legal representation.",
            yo: "Gbogbo eniyan ti a fi ẹsun ọdaràn kan gbọdọ jẹ ẹni ti a ro pe o jẹ alaiṣẹ titi ti a fi fi ẹbi kan. O ni ẹtọ lati mọ ẹsun naa, lati daabobo ara rẹ, ati lati ni aṣoju ofin.",
            ha: "Dole ne a ɗauki kowane mutumin da ake tuhuma da laifin aikata laifi a matsayin marar laifi sai an tabbatar da laifi. Kana da haƙƙin sanin zargin, kare kanka, da samun wakilcin doka.",
            ig: "A ga-elele onye ọ bụla e buworo ebubo mmehie iwu dị ka onye na-enweghị mmehie ruo mgbe e gosipụtara ya n'ikpe. I nwere ikike ịmara ebubo ahụ, ichebe onwe gị, na inwe nnọchiteanya iwu.",
          },
        },
        {
          name: "Cybercrimes (Prohibition, Prevention, Etc.) Act 2015",
          section: "Sections 14–32",
          plainEnglish: {
            en: "The Act lists specific cyber offences such as hacking, online fraud, and identity theft. Simply owning a laptop, smartphone, or living a comfortable lifestyle is not listed as an offence under this Act.",
            pcm: "The Act list specific cyber offences like hacking, online fraud, and identity theft. Owning laptop, smartphone, or living comfortable life no dey listed as offence under this Act.",
            yo: "Ofin naa ṣe atokọ awọn ẹṣẹ cyber pato bii hacking, jibiti ori ayelujara, ati jija idanimọ. Nini laptop, foonu ọlọgbọn, tabi gbigbe ni irọrun kii ṣe ẹṣẹ labẹ Ofin yii.",
            ha: "Dokar ta jera takamaiman laifukan yanar gizo kamar hacking, zamba ta yanar gizo, da satar asali. Mallakan kwamfuta, wayar hannu, ko rayuwa cikin jin daɗi ba a lissafa su a matsayin laifi ƙarƙashin wannan Dokar ba.",
            ig: "Iwu ahụ na-edepụta mmehie cyber a kapịrị ọnụ dị ka hacking, aghụghọ n'ịntanetị, na ịzuwa njirimara. Naanị inwe laptọpụ, ekwenti ọgụgụ, ma ọ bụ ibi ndụ dị mma edepụtabeghị dị ka mmehie n'okpuru Iwu a.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "EFCC officers raid your apartment because a neighbour reported that you 'live big for a young person'. They demand you hand over all devices and confess to cybercrime.",
            pcm: "EFCC officers raid your apartment because your neighbour report you say you 'dey live big for young person'. Dem demand all your devices and want you to confess to cybercrime.",
            yo: "Awọn ọfẹ EFCC jagun iyẹwu rẹ nitori adugbo kan royin pe o 'ngbe dara fun ọdọ kan'. Wọn beere ki o fun wọn ni gbogbo awọn ẹrọ ati jẹwọ si cybercrime.",
            ha: "Jandaman EFCC sun kai hari gidanka saboda maƙwabci ya ba da rahoton cewa kana 'rayuwa babba don ƙaramin mutum'. Suna neman duk na'urorinaka kuma suna son ka furta laifin yanar gizo.",
            ig: "Ndị ọrụ EFCC wakporo ụlọ gị n'ihi na onye agbata obi kọọ na ị 'na-ebi nnukwu ndụ maka onye nọ n'ọchịchọ'. Ha rịọ ngwaọrụ niile gị ma chọọ ka ị nakọ mmehie cybercrime.",
          },
          steps: {
            en: [
              "Do not panic. Ask immediately: 'Do you have a warrant for this search?'",
              "If they produce a warrant, read it carefully — check your name, address, and what it authorises.",
              "If no warrant is produced, say clearly: 'I do not consent to this search. I will cooperate once a valid warrant is presented.'",
              "Do not hand over devices voluntarily without seeing a warrant.",
              "Do not make any verbal statements or confessions — say: 'I will not answer questions without a lawyer present.'",
              "Contact a lawyer immediately. Write down the names and ID numbers of all officers present.",
              "After the encounter, compile a detailed account — dates, times, what was taken, what was said.",
            ],
            pcm: [
              "No panic. Immediately ask: 'You get warrant for this search?'",
              "If dem bring warrant, read am carefully — check your name, address, and wetin e authorise.",
              "If dem no show warrant, say clearly: 'I no consent to this search. I go cooperate when dem show valid warrant.'",
              "No hand over devices without seeing warrant.",
              "No make any statement or confession — say: 'I no go answer questions without lawyer.'",
              "Contact lawyer immediately. Write down names and ID numbers of all officers.",
              "After everything, write detailed account — dates, times, wetin dem take, wetin dem say.",
            ],
            yo: [
              "Má bẹru. Beere lẹsẹkẹsẹ: 'Ṣe o ni iwe aṣẹ fun ṣiṣayẹwo yii?'",
              "Ti wọn ba mu iwe aṣẹ wá, ka a ni pẹkipẹki — ṣayẹwo oruko rẹ, adirẹsi, ati ohun ti o fun ni aṣẹ.",
              "Ti ko ba si iwe aṣẹ, sọ ni gbangba: 'Mi o fohun si ayẹwo yii. Emi yoo fọwọsowọpọ ni kete ti wọn ba ṣafihan iwe aṣẹ to wulo.'",
              "Má fun wọn ni awọn ẹrọ laisi ri iwe aṣẹ.",
              "Má ṣe eyikeyi alaye tabi igbawọle — sọ: 'Emi kii yoo dahun awọn ibeere laisi agbẹjọro.'",
              "Kan si agbẹjọro lẹsẹkẹsẹ. Kọ oruko ati nọmba ID ti gbogbo awọn ọfẹ ti o wa.",
              "Lẹhin ipade naa, pejọ iroyin alaye — awọn ọjọ, awọn wakati, ohun ti a gba, ohun ti a sọ.",
            ],
            ha: [
              "Kada ka firgita. Nan take yi tambaya: 'Kuna da izini don wannan bincike?'",
              "Idan sun kawo izinin, karanta shi da kyau — duba sunanka, adireshi, da abin da ya ba da izini.",
              "Idan ba a nuna izinin ba, ce a sarari: 'Ba na yarda da wannan bincike. Zan haɗa kai da zarar an nuna ingantaccen izini.'",
              "Kada ka ba da na'urori ba tare da ganin izinin ba.",
              "Kada ka yi wata sanarwa ko furci — ce: 'Ba zan amsa tambayoyi ba tare da lauya ba.'",
              "Tuntubi lauya nan take. Rubuta sunaye da lambobin ID na duk jandaman da suke nan.",
              "Bayan komai, tattara cikakken bayani — kwanaki, lokuta, abin da aka kwace, abin da aka faɗa.",
            ],
            ig: [
              "Atọ egwụ. Ozugbo jụọ: 'I nwere iwu maka nyocha a?'",
              "Ọ bụrụ ha wetara iwu, gụọ ya nke ọma — lelee aha gị, adreesị, na ihe ọ nyere ikike.",
              "Ọ bụrụ na ha egosighị iwu, kwuo n'ụzọ doro ìhè: 'Anabatahị m nyocha a. Aga m asọrọ ozugbo ha gosipụtara iwu ziri ezi.'",
              "Ekenyekwala ngwaọrụ na-enweghị ilele iwu.",
              "Emekwala nkwupụta ma ọ bụ nkwenye ọ bụla — kwuo: 'Agaghị m azaghachi ajụjụ na-enweghị ọka iwu.'",
              "Kpọtụrụ ọka iwu ozugbo. Deechie aha na nọmba ID nke ndị ọrụ niile dị ebe ahụ.",
              "Ka ihe niile gasie, chịkọta akụkọ zuru ezu — ụbọchị, oge, ihe e weputara, ihe e kwuru.",
            ],
          },
        },
      ],
    },
    {
      slug: "campus-rights",
      title: {
        en: "Campus Rights — Students Are Not Second-Class Citizens",
        pcm: "Campus Rights — Student No Be Second-Class Citizen",
        yo: "Awọn Ẹtọ Ogba Ile-Iwe — Awọn Akẹkọ Kii Ṣe Ọmọ Ilu Kilasi Keji",
        ha: "Haƙƙoƙin Harabar Makaranta — Ɗalibai Ba Ƴan Ƙasa na Matakin Biyu Ba Ne",
        ig: "Ikike Kmpus — Ụmụ Akwụkwọ Abụghị Ndị Ọchịchọ Ụzọ Abụọ",
      },
      summary: {
        en: "Campus security cannot arrest students and hand them to police without due process. University authorities cannot expel students without a fair hearing. Students have the right to form associations and hold peaceful protests on campus. The right to education is protected. University disciplinary panels must follow natural justice principles.",
        pcm: "Campus security no fit arrest students and hand dem to police without due process. University authorities no fit expel students without fair hearing. Students get right to form associations and do peaceful protest on campus. Right to education na protected right. University disciplinary panels must follow natural justice principles.",
        yo: "Aabo ogba ile-iwe ko le mu awọn akẹkọ ati fi wọn fun ọlọpaa laisi ilana to peye. Awọn alaṣẹ ile-ẹkọ giga ko le le awọn akẹkọ jade laisi igbọran to dara. Awọn akẹkọ ni ẹtọ lati ṣẹda awọn ẹgbẹ ati ṣe ehonu alafia lori ogba. Ẹtọ si ẹkọ jẹ aabo. Awọn igbimọ iwa ẹṣẹ ile-ẹkọ giga gbọdọ tẹle awọn ilana idajọ adayeba.",
        ha: "Tsaro na harabar makaranta ba zai iya kama ɗalibai ba da mika su wa 'yan sanda ba tare da tsarin da ya dace ba. Hukumomin jami'a ba za su iya kora ɗalibai ba tare da sauraro mai adalci ba. Ɗalibai na da haƙƙin kafa ƙungiyoyi da yin zanga-zanga cikin lumana a harabar. An kare haƙƙin ilimi. Kwamitin hukunta jami'a dole ne su bi ƙa'idojin adalcin dabi'a.",
        ig: "Nchedo kmpus enweghị ike ijide ụmụ akwụkwọ ma nyefee ha ndị uwe ojii na-enweghị usoro kwesịrị ekwesị. Ndị ọchịchọ mahadum enweghị ike ịchụpụ ụmụ akwụkwọ na-enweghị nkwanye ezi. Ụmụ akwụkwọ nwere ikike ịhazi ndị otu na ịme ịgagharị n'udo n'ime kmpus. A na-echebe ikike ọmụmụ ihe. Ndị kọmitii ntarachi mahadum ga-esoro ụkpụrụ ikpe ọchịchọ.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Detain a student on campus for questioning about a specific incident",
          "Request police assistance if a crime has been committed on campus",
          "Impose reasonable disciplinary measures following a fair hearing",
          "Set rules for protests on campus that are reasonable and non-discriminatory",
        ],
        pcm: ["Hold student on campus for questioning about specific incident", "Call police if actual crime happen on campus", "Give reasonable punishment after fair hearing", "Set reasonable rules for campus protests wey no discriminate"],
        yo: ["Da akẹkọ duro lori ogba fun ibeere nipa iṣẹlẹ pato", "Beere iranlọwọ ọlọpaa ti a ba ṣe ẹṣẹ lori ogba", "Paṣẹ awọn igbese iwa ẹṣẹ to peye lẹhin igbọran to dara", "Ṣeto awọn ofin fun awọn ehonu lori ogba ti o jẹ to peye ati alailẹgbẹ"],
        ha: ["Tsare ɗalibi a harabar don tambayoyi game da takamaiman abin da ya faru", "Nemi taimakon 'yan sanda idan an aikata laifi a harabar", "Sanya matakan hukunci mai ma'ana bayan sauraron adalci", "Saita ka'idoji don zanga-zanga a harabar da suka dace kuma marasa nuna bambanci"],
        ig: ["Nọdee otu ụmụ akwụkwọ n'ime kmpus maka ajụjụ gbasara ihe omume a kapịrị ọnụ", "Rịọ ndị uwe ojii enyemaka ọ bụrụ na e meere mmehie n'ime kmpus", "Tinye usoro ntarachi kwesịrị ekwesị na-esoso nkwanye ezi", "Tọọ iwu maka ịgagharị n'ime kmpus nke dị mma ma na-enweghị ịkpa ókè"],
      },
      cannotDo: {
        en: [
          "Expel or suspend a student without giving them notice and a fair hearing",
          "Hand a student to police without a lawful basis — campus security are not police",
          "Ban student unions or associations without lawful authority",
          "Prevent students from peacefully protesting or petitioning authorities",
          "Penalise a student for exercising legal rights such as making a complaint",
        ],
        pcm: ["Expel or suspend student without giving notice and fair hearing", "Hand student to police without lawful basis — campus security no be police", "Ban student unions or associations without lawful authority", "Stop students from peacefully protesting or petitioning", "Punish student for exercising legal rights like making complaint"],
        yo: ["Le tabi dẹkun akẹkọ laisi fifun wọn ni ifitonileti ati igbọran to dara", "Fi akẹkọ fun ọlọpaa laisi ipilẹ ofin — aabo ogba ile-iwe kii ṣe ọlọpaa", "Gbesele awọn ẹgbẹ tabi ẹgbẹ akẹkọ laisi alaṣẹ ofin", "Ṣe idiwọ fun awọn akẹkọ lati ṣe ehonu alafia tabi fi ẹbẹ ranṣẹ si awọn alaṣẹ", "Jẹ akẹkọ ni ìjìyà fun lilo awọn ẹtọ ofin bii ṣiṣe ẹsun"],
        ha: ["Kora ko dakatar da ɗalibi ba tare da ba su sanarwa da sauraron adalci ba", "Mika ɗalibi wa 'yan sanda ba tare da dalili na doka ba — tsaro na harabar ba 'yan sanda ba ne", "Hana ƙungiyoyin ɗalibai ko ƙungiyoyi ba tare da ikon doka ba", "Hana ɗalibai yin zanga-zanga cikin lumana ko gabatar da koke ga hukumomi", "Hukunta ɗalibi don yin amfani da haƙƙoƙin doka kamar gabatar da ƙara"],
        ig: ["Ichupụ ma ọ bụ ikwụsị ụmụ akwụkwọ na-enweghị ịnyefe ha ọkwa na nkwanye ezi", "Inye ụmụ akwụkwọ n'aka ndị uwe ojii na-enweghị ezi ihe kpatara iwu — nchedo kmpus abụghị ndị uwe ojii", "Machibido ndị otu ụmụ akwụkwọ ma ọ bụ ndị otu na-enweghị ọnụ iwu", "Izighị ụmụ akwụkwọ ịgagharị n'udo ma ọ bụ ịde arịrịọ nye ndị ọchịchọ", "Ịta ụmụ akwụkwọ ahụhụ maka ojiji ikike iwu dị ka ịme mkpesa"],
      },
      whatToDo: {
        en: [
          "If facing disciplinary action, request a written notice of the charges against you",
          "Attend the hearing and bring a written response or a representative if permitted",
          "If campus security attempts to hand you to police without a warrant, ask: 'On what legal authority are you doing this?'",
          "Document everything — take notes, photograph any notices, and keep copies of all correspondence",
          "Contact your student union, a lawyer, or the NBA if your rights are violated",
        ],
        pcm: ["If dem want discipline you, request written notice of charges against you", "Attend the hearing and bring written response or representative if allowed", "If campus security wan hand you to police without warrant, ask: 'Under which law you dey do this?'", "Document everything — take notes, photograph notices, keep copies of all correspondence", "Contact your student union, lawyer, or NBA if dem violate your rights"],
        yo: ["Ti o ba dojukọ igbese iwa ẹṣẹ, beere fun ifitonileti kikọ ti awọn ẹsun si ọ", "Lọ si igbọran ati mu idahun kikọ tabi aṣoju ti o ba gba laaye", "Ti aabo ogba ile-iwe ba fẹ fi ọ fun ọlọpaa laisi iwe aṣẹ, beere: 'Nipa alaṣẹ ofin wo ni ẹ n ṣe eyi?'", "Ṣe akọsilẹ ohun gbogbo — ṣe akọsilẹ, ya aworan eyikeyi ifitonileti, ati pa awọn adakọ ti gbogbo ibasọrọ", "Kan si ẹgbẹ akẹkọ rẹ, agbẹjọro, tabi NBA ti a ba ru awọn ẹtọ rẹ"],
        ha: ["Idan kana fuskantar matakan hukunci, nemi takardar sanarwa ta zargin da ake yi maka ka", "Halarci sauraron kuma kawo amsa rubuce ko wakilin idan an yarda", "Idan tsaron harabar ya yi ƙoƙarin miƙa ka wa 'yan sanda ba tare da izini ba, tambaya: 'Ƙarƙashin wane ikon doka kuke yin wannan?'", "Rubuta komai — rubuta bayanai, ɗauki hoton sanarwa duk, ajiye kwafi na duk wasiƙa", "Tuntubi ƙungiyar ɗalibai naka, lauya, ko NBA idan an take haƙƙoƙinka"],
        ig: ["Ọ bụrụ na i na-enwe ihe ntarachi, rịọ ọkwa edere nke ebubo ndị ha na-ebu megide gị", "Pụta n'oge nkwanye ma wetara nzaghachi ederede ma ọ bụ onye nnọchiteanya ọ bụrụ e kwere ya", "Ọ bụrụ na nchedo kmpus na-agbalị inye gị n'aka ndị uwe ojii na-enweghị iwu, jụọ: 'N'okpuru ọnụ iwu gịnị ka ị na-arụ nke a?'", "Deechie ihe niile — dee ndekọ, wụpụ foto ọkwa ọ bụla, jide ọdịnaya nke mkparịta ụka niile", "Kpọtụrụ ndị otu ụmụ akwụkwọ gị, ọka iwu, ma ọ bụ NBA ọ bụrụ na a mebiri ikike gị"],
      },
      whatNotToDo: {
        en: [
          "Do not ignore a disciplinary summons — attend and state your case",
          "Do not sign any admission of wrongdoing without understanding what you are signing",
          "Do not resist campus security physically — challenge it through the proper channels",
          "Do not assume university rules override your constitutional rights",
        ],
        pcm: ["No ignore disciplinary summons — attend and state your case", "No sign any admission of wrongdoing without understanding wetin you dey sign", "No physically resist campus security — challenge through proper channels", "No assume university rules override your constitutional rights"],
        yo: ["Má fojufori ipe ile-ẹjọ iwa ẹṣẹ — lọ ati sọ ọran rẹ", "Má fowo si eyikeyi igbawọle ti iṣe aitọ laisi oye ohun ti o n fowo si", "Má tako aabo ogba ile-iwe ni ara — ja nipa awọn ọna to peye", "Má ro pe awọn ofin ile-ẹkọ giga bori awọn ẹtọ ofin ipilẹ rẹ"],
        ha: ["Kada ka yi watsi da kiran hukunci — halarce kuma bayyana kayanaka", "Kada ka sanya hannu kan duk wata yarda da laifi ba tare da fahimtar abin da kake sanya hannu ba", "Kada ka jurewa tsaro na harabar jiki — kalubalanci ta hanyoyin da suka dace", "Kada ka ɗauka cewa dokokin jami'a sun fi haƙƙoƙin tsarin mulki naka"],
        ig: ["Anarịkwala ihe ọkpụkpọ ntarachi — pụta n'oge ma kwuo okwu gị", "Akwadobiahala nkwenye mmehie ọ bụla na-aghọta ihe ị na-akwado", "Anabatahị ịgbaso nchedo kmpus n'ahụ — luso ya ọgụ site na ụzọ kwesịrị ekwesị", "Echeghị na iwu mahadum na-agafe ikike iwu gị"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 36",
          plainEnglish: {
            en: "Every person is entitled to a fair hearing. University disciplinary proceedings must give the student notice of the case against them, an opportunity to be heard, and must be conducted by an impartial panel.",
            pcm: "Every person get right to fair hearing. University disciplinary proceedings must give student notice of case against them, chance to be heard, and must be done by impartial panel.",
            yo: "Gbogbo eniyan ni ẹtọ si igbọran to dara. Awọn ilana iwa ẹṣẹ ile-ẹkọ giga gbọdọ fun akẹkọ ni ifitonileti ti ọran si wọn, anfani lati gbọ, ati pe o gbọdọ ṣe nipasẹ igbimọ ainidẹju.",
            ha: "Kowane mutum na da haƙƙin sauraro mai adalci. Hukuncin jami'a dole ne ya ba ɗalibi sanarwar karar da ake yi masa, damar a ji shi, kuma dole ne a gudanar da ita ta hanyar kwamiti mai adalci.",
            ig: "Onye ọ bụla nwere ikike nkwanye ezi. Usoro ntarachi mahadum kwesịrị ịnyefe ụmụ akwụkwọ ọkwa ikpe ndị ha na-ebu megide ha, ohere ka e nụọ ha okwu, ma a ga-eme ya site n'aka kọmitii na-enweghị isi abụọ.",
          },
        },
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 40",
          plainEnglish: {
            en: "Students have the right to form and belong to student unions, associations, and societies. University authorities cannot arbitrarily ban student associations without lawful justification.",
            pcm: "Students get right to form and belong to student unions and associations. University no fit ban student associations without lawful reason.",
            yo: "Awọn akẹkọ ni ẹtọ lati ṣẹda ati jẹ ti awọn ẹgbẹ akẹkọ, awọn ẹgbẹ, ati awọn awujọ. Awọn alaṣẹ ile-ẹkọ giga ko le gbesele awọn ẹgbẹ akẹkọ laisi idi ofin.",
            ha: "Ɗalibai na da haƙƙin kafa da zama memba na ƙungiyoyin ɗalibai da ƙungiyoyi. Hukumomin jami'a ba za su iya hana ƙungiyoyin ɗalibai ba tare da dalili na doka ba.",
            ig: "Ụmụ akwụkwọ nwere ikike ịhazi ma ịbụ otu ndị otu ụmụ akwụkwọ, ndị otu, na ndị otu mmekọ. Ndị ọchịchọ mahadum enweghị ike ịmachibido ndị otu ụmụ akwụkwọ na-enweghị ihe kpatara iwu.",
          },
        },
        {
          name: "Universities (Miscellaneous Provisions) Act 1993 (as amended)",
          section: "General",
          plainEnglish: {
            en: "Federal universities are governed by statutes that include provisions for student discipline. These statutes require fair procedures — students must receive proper notice and be given the opportunity to respond before any serious sanction.",
            pcm: "Federal universities governed by statutes wey include student discipline provisions. These statutes require fair procedures — students must receive proper notice and chance to respond before any serious punishment.",
            yo: "Awọn ile-ẹkọ giga ijọba ijọba n ṣakoso nipasẹ awọn ofin ti o pẹlu awọn ipese fun iwa ẹṣẹ akẹkọ. Awọn ofin wọnyi nilo awọn ilana to dara — awọn akẹkọ gbọdọ gba ifitonileti to peye ati ni anfani lati dahun ṣaaju eyikeyi ijẹniniya to le.",
            ha: "Ana gudanar da jami'o'in tarayya ta ƙa'idoji waɗanda suka haɗa da tanadi don hukuncin ɗalibai. Waɗannan ƙa'idoji suna buƙatar tsarin adalci — ɗalibai dole ne su sami sanarwa mai kyau da damar mayar da martani kafin a yi wata hukunci mai tsanani.",
            ig: "A na-achịkwa mahadum ndị ọchịchọ obodo site n'ime iwu nke gụnyere mkpọchi maka ntarachi ụmụ akwụkwọ. Iwu ndị a chọọ usoro ziri ezi — ụmụ akwụkwọ kwesịrị nnata ọkwa kwesịrị ekwesị ma nwee ohere izaghachi tupu ntarachi siri ike ọ bụla.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Campus security detains you after a peaceful student protest and tells you they are handing you over to the police. No crime was committed — you were simply marching and chanting.",
            pcm: "Campus security detain you after peaceful student protest and say dem wan hand you over to police. You no commit any crime — you just dey march and chant.",
            yo: "Aabo ogba ile-iwe da ọ duro lẹhin ehonu akẹkọ alafia ati sọ fun ọ pe wọn n fi ọ fun ọlọpaa. Ko si ẹṣẹ ti a ṣe — o n rìn ati korin nikan.",
            ha: "Tsaron harabar ya tsare ka bayan zanga-zangar ɗalibai ta lumana kuma ya faɗa maka cewa zai mika ka wa 'yan sanda. Ba a aikata wani laifi ba — kawai kana tattaki da rera waƙa.",
            ig: "Nchedo kmpus nọdee gị mgbe ịgagharị ụmụ akwụkwọ n'udo wee kwuo na ha ga-inye gị n'aka ndị uwe ojii. Emereghị mmehie ọ bụla — naanị i na-aga n'ukwu na ịkọ uri.",
          },
          steps: {
            en: [
              "Stay calm. Do not resist physically.",
              "Ask clearly: 'Am I under arrest? If so, what is the charge?'",
              "If campus security cannot state a lawful charge, say: 'Campus security does not have the authority to hand me to police without a lawful basis. I have committed no offence.'",
              "Ask to speak with your student union representative or a lawyer immediately.",
              "If transferred to police despite your objection, clearly state to the police: 'I do not consent to this detention. I was engaged in a peaceful protest — a constitutionally protected activity.'",
              "Exercise your right to silence. Do not sign anything without a lawyer.",
              "Note all names, badge numbers, times, and what was said. File a complaint with the university ombudsman and the NBA if necessary.",
            ],
            pcm: [
              "Calm down. No resist physically.",
              "Ask clearly: 'You don arrest me? If yes, what be the charge?'",
              "If campus security no fit state lawful charge, say: 'Campus security no get authority to hand me to police without lawful basis. I no commit any offence.'",
              "Ask to speak with student union rep or lawyer immediately.",
              "If dem transfer you to police despite your objection, tell police clearly: 'I no consent to this detention. I was doing peaceful protest — na constitutional right.'",
              "Use your right to silence. No sign anything without lawyer.",
              "Note all names, badge numbers, times, and what dem say. File complaint with university ombudsman and NBA if necessary.",
            ],
            yo: [
              "Jẹ ki o balẹ. Má tako ni ara.",
              "Beere ni gbangba: 'Ṣe a mu mi? Ti bẹẹ ba jẹ, kini ẹsun naa?'",
              "Ti aabo ogba ile-iwe ko ba le sọ ẹsun ofin, sọ: 'Aabo ogba ile-iwe ko ni alaṣẹ lati fi mi fun ọlọpaa laisi ipilẹ ofin. Mi o ṣe ẹṣẹ kankan.'",
              "Beere lati sọrọ pẹlu aṣoju ẹgbẹ akẹkọ rẹ tabi agbẹjọro lẹsẹkẹsẹ.",
              "Ti a ba gbe ọ lọ si ọlọpaa pelu aibikita si atako rẹ, sọ fun ọlọpaa ni gbangba: 'Mi o fohun si idaduro yii. Mo n ṣe ehonu alafia — iṣe ti a daabobo nipasẹ ofin ipilẹ.'",
              "Lo ẹtọ rẹ si idakẹjẹ. Má fowo si ohunkohun laisi agbẹjọro.",
              "Ṣe akiyesi gbogbo awọn oruko, nọmba ami, akoko, ati ohun ti a sọ. Fi ẹsun si ombudsman ile-ẹkọ giga ati NBA ti o ba jẹ dandan.",
            ],
            ha: [
              "Kasance a nutsuwa. Kada ka jurewa jiki.",
              "Yi tambaya a sarari: 'An kama ni ne? Idan haka ne, menene zargin?'",
              "Idan tsaron harabar ba zai iya bayyana zargi na doka ba, ce: 'Tsaron harabar ba shi da ikon miƙa ni wa 'yan sanda ba tare da dalili na doka ba. Ban aikata wani laifi ba.'",
              "Nemi yin magana da wakilin ƙungiyar ɗalibai naka ko lauya nan take.",
              "Idan aka kai ka 'yan sanda duk da adawarku, faɗa wa 'yan sanda a sarari: 'Ba na yarda da wannan tsarewa. Na kasance ina yin zanga-zanga cikin lumana — aiki da kundin tsarin mulki ya kare.'",
              "Yi amfani da haƙƙinka na yin shiru. Kada ka sanya hannu kan komai ba tare da lauya ba.",
              "Rubuta duk sunaye, lambobin badge, lokuta, da abin da aka faɗa. Gabatar da ƙara ga ombudsman na jami'a da NBA idan ya cancanta.",
            ],
            ig: [
              "Nọrọ n'udo. Anabatahị igbaso n'ahụ.",
              "Jụọ n'ụzọ doro ìhè: 'A jidere m? Ọ bụrụ ọ bụ eziokwu, gịnị bụ ebubo ahụ?'",
              "Ọ bụrụ na nchedo kmpus enweghị ike ikwuputa ebubo iwu, kwuo: 'Nchedo kmpus enweghị ọnụ ịnyefee m n'aka ndị uwe ojii na-enweghị ezi ihe kpatara iwu. Emeghị m mmehie ọ bụla.'",
              "Rịọ ka ị kwuo okwu na onye nnọchiteanya ndị otu ụmụ akwụkwọ gị ma ọ bụ ọka iwu ozugbo.",
              "Ọ bụrụ na e bufeere gị ndị uwe ojii n'agbanyeghị ihe ị kwuru megide ya, kwuo na ndị uwe ojii n'ụzọ doro ìhè: 'Anabatahị m nkwụsị a. Ana m ịgagharị n'udo — ọrụ nke iwu na-echebe.'",
              "Jiri ikike gị ịnọ nè. Akwadobiahala ihe ọ bụla na-enweghị ọka iwu.",
              "Deechie aha niile, nọmba badge, oge, na ihe e kwuru. Dee mkpesa nye ombudsman mahadum na NBA ọ bụrụ ọ dị mkpa.",
            ],
          },
        },
      ],
    },
  ],
};
