import type { Section } from "./types";

export const youth: Section = {
  slug: "youth",
  title: {
    en: "Youth & Students",
    pcm: "Youth & Students",
    yo: "Ọdọ & Awọn Akẹkọ",
    ha: "Matasa & Dalibai",
    ig: "Ọchịchọ & Ụmụ Akwụkwọ",
  },
  description: {
    en: "Know your rights during police stops targeting youth, campus security encounters, rights to protest, and your digital privacy rights.",
    pcm: "Know your rights when police target you because you're young, campus security encounters, right to protest, and digital privacy rights.",
    yo: "Mọ awọn ẹtọ rẹ nigba idaduro ọlọpaa ti o fojusi ọdọ, awọn ipade aabo ile-iwe, ẹtọ lati tako, ati awọn ẹtọ asiri oni-nọmba rẹ.",
    ha: "Sani haƙƙoƙinka lokacin da 'yan sanda suka tsai da matasa, haduwar tsaro na harabar makaranta, haƙƙin zanga-zanga, da haƙƙoƙin sirrin dijital.",
    ig: "Mara ikike gị n'oge nkwụsị uwe ojii na-elekwasị anya n'ọchịchọ, nnọkọ nchedo kmpus, ikike ịgagharị, na ikike nzuzo dijitalụ gị.",
  },
  icon: "GraduationCap",
  color: "bg-purple-50 text-purple-700",
  topics: [
    {
      slug: "profiling-stops",
      title: {
        en: "Profiling Stops — 'You Look Like a Fraudster'",
        pcm: "'You Look Like Yahoo Boy' Stops",
        yo: "Idaduro Profaili — 'O Dabi Ẹni Ti o Jẹ Jibiti'",
        ha: "Tsayawa Bisa Bayyana — 'Kana Kama Mai Zamba'",
        ig: "Nkwụsị Profaịlụ — 'I Dị Ka Onye Aghụghọ'",
      },
      summary: {
        en: "Police cannot stop, search, or arrest you based solely on your appearance — dreadlocks, tattoos, laptop, nice car, or phone. Profiling based on appearance is unconstitutional.",
        pcm: "Police no fit stop, search, or arrest you because of how you look — dreadlocks, tattoo, laptop, fine car, or phone. Profiling based on appearance against constitution.",
        yo: "Ọlọpaa ko le da ọ duro, ṣayẹwo, tabi mu ọ nikan nitori irisi rẹ — dreads, tatuu, laptop, ọkọ dara, tabi foonu. Profaili ti o da lori irisi jẹ aiofin.",
        ha: "Yan sanda ba za su iya tsai da kai, bincika ka, ko kama ka kawai saboda bayyanarka ba — dreads, zane jiki, kwamfuta, kyakkyawar mota, ko waya. Bayyana bisa zaton bai dace da kundin tsarin mulki ba.",
        ig: "Ndị uwe ojii enweghị ike ịkwụsị gị, ịnyocha gị, ma ọ bụ ijide gị naanị n'ihi ọdịdị gị — dreads, tatuu, laptọpụ, ụgbọ mara mma, ma ọ bụ ekwenti. Profaịlụ dabere n'ọdịdị bụ megide iwu.",
      },
      readMinutes: 4,
      canDo: {
        en: [
          "Stop you if they have specific, articulable reasons to suspect you of a crime",
          "Ask for your ID",
          "Conduct a pat-down search if they reasonably suspect you carry a weapon",
        ],
        pcm: ["Stop you if dem get specific reason to suspect you of crime", "Ask for your ID", "Do pat-down search if dem reasonably suspect you carry weapon"],
        yo: ["Da ọ duro ti wọn ba ni awọn idi pato lati fura si ọ fun ẹṣẹ", "Beere fun idanimọ rẹ", "Ṣe ayẹwo ẹyẹ ti wọn ba ni idi to dara lati fura si pe o ni ohun ija"],
        ha: ["Tsai da ka idan suna da takamaiman dalilai don zargi ka da laifi", "Nemi ID naka", "Yi binciken harmala idan suna da dalili mai kyau na zargi cewa kana ɗauke da makami"],
        ig: ["Kwụsị gị ọ bụrụ na ha nwere ihe kpatara pụtara ìhè iji lechekwa gị n'mmehie", "Rịọ ID gị", "Mee nyocha pat-down ọ bụrụ na ha nwere ezi ihe kpatara ichefuo na ị na-eburu ngwa agha"],
      },
      cannotDo: {
        en: [
          "Stop you based on your hairstyle, clothing, tattoos, or race",
          "Demand to search your phone, laptop, or bags without a court order",
          "Detain you purely because you own expensive items",
          "Arrest you for 'looking like a fraudster' — that is not an offence under Nigerian law",
          "Seize your devices without a court order",
        ],
        pcm: ["Stop you because of your hair, clothes, tattoo, or race", "Search your phone, laptop, or bag without court order", "Detain you because you carry expensive things", "Arrest you for 'looking like yahoo boy' — that no be offence under Nigeria law", "Seize your devices without court order"],
        yo: ["Da ọ duro nitori irun, aṣọ, tatuu, tabi ẹya rẹ", "Ṣayẹwo foonu, laptop, tabi apo rẹ laisi aṣẹ ile-ẹjọ", "Fi ọ pamọ́ nikan nitori pe o ni awọn ohun elo gbowolori", "Mu ọ fun 'dabi ẹni jibiti' — iyẹn kii ṣe ẹṣẹ labẹ ofin Nigeria", "Gba awọn ẹrọ rẹ laisi aṣẹ ile-ẹjọ"],
        ha: ["Tsai da ka saboda gashinka, tufafi, zane jiki, ko kabila", "Bincika wayarka, kwamfutarka, ko jakunkuna ba tare da umurnin kotu ba", "Tsare ka kawai saboda kana da kayaye masu tsada", "Kama ka don 'kamar mai zamba' — ba laifi a ƙarƙashin dokar Najeriya ba ne", "Kwace na'urorin ka ba tare da umurnin kotu ba"],
        ig: ["Kwụsị gị n'ihi isi gị, uwe, tatuu, ma ọ bụ agbụrụ", "Nyochaa ekwenti, laptọpụ, ma ọ bụ akpa gị na-enweghị iwu ụlọ ikpe", "Nọdee gị naanị n'ihi ị nwe ihe ọbara ọbara", "Jide gị maka 'ịdị ka onye aghụghọ' — ọ bụghị mmehie n'okpuru iwu Naịjirịa", "Wepu ngwaọrụ gị na-enweghị iwu ụlọ ikpe"],
      },
      whatToDo: {
        en: [
          "Stay calm and do not run",
          "Ask: 'Officer, what specific crime am I suspected of?'",
          "If no specific crime is stated, say: 'I respectfully decline to be searched without a lawful basis.'",
          "If they insist on checking your phone, say: 'I do not consent to a search of my phone without a court order.'",
          "Comply physically to avoid escalation, then challenge it legally afterward",
          "Report to your school, a lawyer, or the Nigerian Bar Association",
        ],
        pcm: ["Calm down, no run", "Ask: 'Officer, which specific crime you suspect me of?'", "If dem no name specific crime, say: 'I respectfully refuse to be searched without lawful reason.'", "If dem want check your phone, say: 'I no consent to phone search without court order.'", "Comply physically to avoid trouble, then challenge legally after", "Report to your school, lawyer, or NBA"],
        yo: ["Jẹ ki o balẹ ati má sá", "Beere: 'Ọgagun, ẹṣẹ wo ni mo ṣe ti ẹ n fura si mí?'", "Ti ko ba si ẹṣẹ pato, sọ: 'Mo kọ pẹlu ọwọ lati jẹ ki a ṣayẹwo mi laisi ipilẹ ofin.'", "Ti wọn ba fẹ ṣayẹwo foonu rẹ, sọ: 'Mi o fohun si ṣiṣayẹwo foonu laisi aṣẹ ile-ẹjọ.'", "Tẹle ni ara lati yago fun ìga ipo, lẹhinna ja ni ofin lẹhinna", "Ròyìn si ile-iwe rẹ, agbẹjọro, tabi NBA"],
        ha: ["Kasance a nutsuwa kuma kada ka gudu", "Yi tambaya: 'Jandarm, wane takamaiman laifi ake zargin ni?'", "Idan ba a ambaci takamaiman laifi ba, ce: 'Ina ƙin da ladabi a bincika ni ba tare da dalili na doka ba.'", "Idan suna son bincika wayarka, ce: 'Ba na yarda da bincike wayata ba tare da umurnin kotu ba.'", "Yi biyayya jiki don gujewa tashin hankali, sannan ka kalubalance daga baya a doka", "Kai rahoto ga makarantarka, lauyanka, ko NBA"],
        ig: ["Nọrọ n'udo ma agbakwala ọsọ", "Jụọ: 'Oga, ihe ọjọọ pụtara ìhè gịnị ka a na-eche na m mere?'", "Ọ bụrụ na ha ekwughị mmehie a kapịrị ọnụ, kwuo: 'Ana m ajụ n'ọkịtọ ka a nyochaa m na-enweghị ezi ihe kpatara iwu.'", "Ọ bụrụ na ha chọọ inyocha ekwenti gị, kwuo: 'Anabatahị m inyocha ekwenti m na-enweghị iwu ụlọ ikpe.'", "Soro n'ahụ ikpochapụ esemokwu, wee luso ha ọgụ n'iwu mgbe e mesie ike", "Kọọ na ụlọ akwụkwọ gị, ọka iwu, ma ọ bụ NBA"],
      },
      whatNotToDo: {
        en: [
          "Do not verbally abuse or insult officers",
          "Do not give your phone PIN or password voluntarily",
          "Do not attempt to bribe — it makes your situation worse",
          "Do not sign any statement without reading and understanding it",
        ],
        pcm: ["No abuse or insult officers", "No give your phone PIN or password voluntarily", "No try bribe them — e go make your situation worse", "No sign any statement without reading and understanding am"],
        yo: ["Má bú tabi ṣe inira si awọn ọfẹ", "Má fun wọn ni PIN foonu rẹ tabi ọrọ aṣina ni ifẹ", "Má gbiyanju lati gbọn wọn — yoo ṣe ipo rẹ buru si", "Má fowo si eyikeyi alaye laisi kika ati oye"],
        ha: ["Kada ka zagi ko yi wa jandami baki", "Kada ka ba da PIN wayar ka ko kalmar wucewa cikin son rai", "Kada ka yi cin hanci — zai sa halin ka ya yi muni", "Kada ka sanya hannu kan duk wata sanarwa ba tare da karanta da fahimta ba"],
        ig: ["Atụkwasịla iyi ma ọ bụ ịsọ ndị ọrụ ọjọọ", "Ekenyekwala PIN ekwenti gị ma ọ bụ paswọọdụ ọcha ọcha", "Anọkwala na-agbalị ịtụ ego n'aka ha — ọ ga-eme ọnọdụ gị ka njọ", "Akwadobiahala nkwupụta ọ bụla na-agụghị ya na ịghọta ya"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 37",
          plainEnglish: {
            en: "The privacy of citizens, their homes, correspondence, telephone conversations, and telegraphic communications is guaranteed and protected. Accessing your phone without consent or court order is a violation.",
            pcm: "Nigeria Constitution guarantee privacy of citizens, their homes, letters, phone calls. Accessing your phone without your consent or court order na violation.",
            yo: "Ofin ipilẹ Nigeria ṣe iṣeduro ati daabo bo ikọkọ ti awọn ọmọ ilu, ile wọn, lẹta, ati awọn ipe foonu. Wiwọle si foonu rẹ laisi igbanilaaye tabi aṣẹ ile-ẹjọ jẹ ìka.",
            ha: "Kundin Tsarin Mulki na Najeriya ya tabbatar da kare sirrin 'yan kasa, gidajensu, wasiƙunsu, tattaunawar wayar tarho. Shiga wayarka ba tare da izini ko umurnin kotu ba cin zarafi ne.",
            ig: "Iwu Nke Naịjirịa na-ekwe nkwa ma na-echebe nzuzo nke ndị ọchịchọ, ụlọ ha, akwụkwọ ozi, mkparịta ụka ekwenti. Ọbanye n'ekwenti gị na-enweghị ikike ma ọ bụ iwu ụlọ ikpe bụ mmebi.",
          },
        },
        {
          name: "Cybercrimes (Prohibition, Prevention, Etc.) Act 2015",
          section: "Section 38",
          plainEnglish: {
            en: "Law enforcement agencies may apply to court for a warrant to access electronic records. They cannot simply demand access to your phone without a warrant.",
            pcm: "Law enforcement fit apply to court for warrant to access your electronic records. Dem no fit just demand your phone without warrant.",
            yo: "Awọn ile-iṣẹ ẹjọ le beere si ile-ẹjọ fun iwe aṣẹ lati wọle si awọn igbasilẹ itanna. Wọn ko le kan beere lọwọ rẹ lati wọle si foonu rẹ laisi iwe aṣẹ.",
            ha: "Hukumomin tsaro na iya neman izinin kotu don shiga bayanan lantarki. Ba za su iya kawai neman shiga wayarka ba tare da izini ba.",
            ig: "Ndị ọchịchọ iwu nwere ike ịrịọ n'ụlọ ikpe maka iwu ọbanye ndekọ eletrọnịk. Ha enweghị ike ọ bụ naanị ịrịọ ọbanye n'ekwenti gị na-enweghị iwu ahụ.",
          },
        },
      ],
      scenarios: [
        {
          situation: {
            en: "Police stop you on the street. You have a laptop bag and dreadlocks. An officer says: 'You look like a yahoo boy. Open your laptop.'",
            pcm: "Police stop you for street. You carry laptop bag and you get dreadlocks. Officer say: 'You look like yahoo boy. Open your laptop.'",
            yo: "Ọlọpaa da ọ duro lori ita. O ni apo laptop ati dreads. Ọfẹ kan sọ: 'O dabi ẹni jibiti. Ṣii laptop rẹ.'",
            ha: "Yan sanda sun tsai da kai a kan hanya. Kana da jakar kwamfuta da dreads. Jandamin ya ce: 'Kana kama mai zamba. Bude kwamfutarka.'",
            ig: "Ndị uwe ojii kwụsịa gị n'ụzọ. I nwere akpa laptọpụ na dreads. Onye ọrụ kwuo: 'I dị ka onye yahoo. Meghee laptọpụ gị.'",
          },
          steps: {
            en: [
              "Stay calm. Do not open the laptop yet.",
              "Ask respectfully: 'Officer, what specific crime am I suspected of committing?'",
              "If the answer is 'you look like a fraudster' — that is not a crime. Say: 'Looking a certain way is not an offence under Nigerian law. I respectfully decline to consent to a search without a lawful basis.'",
              "If they insist and it becomes unsafe, you may comply physically but verbally state: 'I do not consent to this search.'",
              "Note everything: time, place, officer badge number and name.",
              "After the encounter, report to the Nigerian Bar Association or a lawyer, and consider filing a complaint.",
            ],
            pcm: [
              "Calm down. No open laptop yet.",
              "Ask respectfully: 'Officer, which specific crime you suspect me of?'",
              "If dem say 'you look like fraudster' — that no be crime. Tell dem: 'Looking certain way no be offence under Nigerian law. I respectfully refuse search without lawful reason.'",
              "If dem insist and e become unsafe, comply physically but say: 'I no consent to this search.'",
              "Note everything: time, place, officer badge number and name.",
              "After the encounter, report to NBA or lawyer.",
            ],
            yo: ["Jẹ ki o balẹ. Má ṣii laptop sibẹ.", "Beere pẹlu ọwọ: 'Ọgagun, ẹṣẹ wo ni mo ṣe ti o fura si mí?'", "Ti idahun naa ba jẹ 'o dabi ẹni jibiti' — iyẹn kii ṣe ẹṣẹ. Sọ: 'Wiwo ni ọna kan kii ṣe ẹṣẹ labẹ ofin Nigeria.'", "Ti wọn ba tẹnumọ ti o ba jẹ ailewu, o le tẹle ni ara ṣugbọn sọ: 'Mi o gba aṣẹ fun ayẹwo yii.'", "Ṣe akiyesi ohun gbogbo: akoko, ipo, nọmba aami ọfẹ.", "Lẹhin ipade naa, ròyìn si NBA tabi agbẹjọro."],
            ha: ["Kasance a nutsuwa. Kada ka bude kwamfuta tukuna.", "Yi tambaya da ladabi: 'Jandarm, wane takamaiman laifi ake zargin ni?'", "Idan amsar ta kasance 'kana kama mai zamba' — ba laifi bane. Ce: 'Bayyana wata hanya ba laifi bane a ƙarƙashin dokar Najeriya.'", "Idan sun dage kuma ya zama mara tsaro, kana iya biyayya jiki amma ce: 'Ba na yarda da wannan bincike.'", "Rubuta komai: lokaci, wuri, lambar badge da sunan jandamin.", "Bayan haduwar, kai rahoto ga NBA ko lauya."],
            ig: ["Nọrọ n'udo. Emegheela laptọpụ n'oge a.", "Jụọ n'ọkịtọ: 'Oga, ihe ọjọọ pụtara ìhè gịnị ka a na-eche na m mere?'", "Ọ bụrụ na ọzaghachi bụ 'i dị ka onye aghụghọ' — ọ bụghị mmehie. Kwuo: 'Ịdị n'ụzọ ụfọdụ abụghị mmehie n'okpuru iwu Naịjirịa.'", "Ọ bụrụ na ha arọba ma ọ ghara dị mma, ị nwere ike isoro n'ahụ mana kwuo: 'Anabatahị m nyochaa a.'", "Deechie ihe niile: oge, ebe, nọmba badge na aha onye ọrụ.", "Ka nnọkọ ahụ gasie, kọọ na NBA ma ọ bụ ọka iwu."],
          },
        },
      ],
    },
    {
      slug: "right-to-protest",
      title: {
        en: "Right to Peaceful Protest",
        pcm: "Right to Protest Peacefully",
        yo: "Ẹtọ Lati Ṣe Ehonu Alafia",
        ha: "Haƙƙin Zanga-Zanga Mai Lumana",
        ig: "Ikike Ịgagharị n'Udo",
      },
      summary: {
        en: "Every Nigerian has a constitutional right to peaceful assembly and protest. Police cannot disperse a peaceful protest with force, and you cannot be arrested simply for protesting.",
        pcm: "Every Nigerian get constitutional right to peaceful assembly and protest. Police no fit use force to disperse peaceful protest, and dem no fit arrest you just for protesting.",
        yo: "Gbogbo ọmọ Nigeria ni ẹtọ ofin ipilẹ si apejọ alafia ati ehonu. Ọlọpaa ko le lo agbara lati tuka ehonu alafia, ati pe wọn ko le mu ọ nikan nitori protesto.",
        ha: "Kowane ɗan Najeriya yana da haƙƙin tsarin mulki na taron lumana da zanga-zanga. Yan sanda ba za su iya amfani da ƙarfi don tarwatsa zanga-zangar lumana ba.",
        ig: "Onye Naịjirịa ọ bụla nwere ikike iwu maka njikọ n'udo na ịgagharị. Ndị uwe ojii enweghị ike ojiji ihe ike ịkpọ ọgbakọ ịgagharị n'udo, onye ọ bụla enweghị ike ijide gị naanị maka ịgagharị.",
      },
      readMinutes: 3,
      canDo: {
        en: [
          "Request that protesters notify the police of a planned protest in advance",
          "Maintain order and protect protesters",
          "Arrest individuals who commit crimes during a protest (looting, assault)",
          "Disperse a protest if it becomes violent",
        ],
        pcm: ["Ask protesters to notify police before protest", "Maintain order and protect protesters", "Arrest people wey commit crime during protest", "Disperse protest if e become violent"],
        yo: ["Beere fun awọn oluyegbe lati fi ọlọpaa leti ti ehonu ti a gbero", "Ṣetọju aṣẹ ati daabo bo awọn oluyegbe", "Mu awọn ẹni ti o ṣe ẹṣẹ lakoko ehonu", "Tuka ehonu ti o ba di iwa-ipa"],
        ha: ["Nemi masu zanga-zanga su sanar da 'yan sanda kafin zanga-zangar", "Kiyaye tsari da kare masu zanga-zanga", "Kama mutanen da suka aikata laifi a lokacin zanga-zanga", "Tarwatsa zanga-zanga idan ta zama mai tashin hankali"],
        ig: ["Rịọ ndị ịgagharị ka ha mee ka ndị uwe ojii mara maka ịgagharị ahụ", "Nọdee n'usoro ma chebe ndị ịgagharị", "Jide ndị mere mmehie n'oge ịgagharị", "Kpọọ ndị ịgagharị ma ọ bụrụ na ha ghara ịdị n'udo"],
      },
      cannotDo: {
        en: [
          "Prohibit a peaceful protest",
          "Use tear gas, water cannons, or live ammunition against peaceful protesters",
          "Arrest protesters for peaceful expression",
          "Detain protesters beyond 24 hours without charge",
          "Demand protesters disperse without lawful cause",
        ],
        pcm: ["Prohibit peaceful protest", "Use tear gas, water cannon, or live ammo against peaceful protesters", "Arrest protesters for peaceful expression", "Hold protesters past 24 hours without charge", "Order protesters to disperse without lawful cause"],
        yo: ["Gbesele ehonu alafia", "Lo omi ẹkún, omi ẹrọ, tabi ohun ija atilẹhin lodi si awọn oluyegbe alafia", "Mu awọn oluyegbe fun ikosile alafia", "Fi awọn oluyegbe pamọ́ ju wakati 24 lọ laisi ẹsun", "Paṣẹ fun awọn oluyegbe lati tuka laisi idi ofin"],
        ha: ["Hana zanga-zangar lumana", "Yi amfani da hayakin hawaye, bindigar ruwa, ko harsashin raye akan masu zanga-zangar lumana", "Kama masu zanga-zanga don bayyana kur'ayana", "Tsare masu zanga-zanga fiye da awanni 24 ba tare da tuhuma ba", "Umurtar masu zanga-zanga da su wargaje ba tare da dalilin doka ba"],
        ig: ["Machibido ịgagharị n'udo", "Ojiji gas na-anya anya, cannon mmiri, ma ọ bụ ọgụ ndụ megide ndị ịgagharị n'udo", "Jide ndị ịgagharị maka ikwuputa n'udo", "Nọdee ndị ịgagharị n'ogige ihe karịa awa 24 na-ebulizie ha", "Nyee iwu ndị ịgagharị ka ha pụọ na-enweghị ezi ihe kpatara iwu"],
      },
      whatToDo: {
        en: [
          "Know the planned protest route and carry a copy of your rights",
          "Protest peacefully — do not engage in violence or destruction",
          "If arrested, exercise your right to remain silent and request a lawyer",
          "Document police misconduct — video record if safe",
          "If injured, seek medical attention and document injuries",
        ],
        pcm: ["Know the protest route and carry copy of your rights", "Protest peacefully — no do violence or destroy things", "If dem arrest you, use your right to silence and ask for lawyer", "Document police misconduct — video them if safe to do so", "If you get injured, get medical help and document"],
        yo: ["Mọ ipa-ọna ehonu ti a gbero ati gbe adakọ awọn ẹtọ rẹ", "Ṣe ehonu ni alafia — má ṣe iwa-ipa", "Ti a ba mu ọ, lo ẹtọ rẹ si idakẹjẹ ati beere agbẹjọro", "Ṣe akọsilẹ ihuwasi ọlọpaa — ya fídíò ti o ba jẹ ailewu", "Ti o ba farapa, wa itọju iṣoogun ati ṣe akọsilẹ"],
        ha: ["San hanyar zanga-zangar da aka tsara kuma ɗauki kwafin haƙƙoƙinka", "Yi zanga-zanga cikin lumana — kada ka yi tashin hankali ko halaka", "Idan aka kama ka, yi amfani da haƙƙinka na yin shiru kuma nemi lauya", "Rubuta miyagun halayyar 'yan sanda — yi bidiyo idan lafiya ta bada damar", "Idan ka ji rauni, nemi taimakon likita kuma rubuta"],
        ig: ["Mara ụzọ ịgagharị ahụ ma buru otu n'ime ikike gị", "Gagharị n'udo — emekwala ihe ike", "Ọ bụrụ na e jidee gị, jiri ikike gị ịnọ nè ma rịọ ọka iwu", "Deechie mmejọ uwe ojii — dee vidiyo ọ bụrụ na ọ dị mma", "Ọ bụrụ na imerụọ ahụ, chọọ ọgwụgwọ ahụike ma deechie imerụ ahụ"],
      },
      whatNotToDo: {
        en: [
          "Do not bring weapons to a protest",
          "Do not engage in looting or property destruction — it criminalises your protest",
          "Do not wear masks to conceal your identity (this can be unlawful)",
          "Do not provoke security forces physically",
        ],
        pcm: ["No bring weapon to protest", "No loot or destroy property — e go make your protest criminal", "No wear mask to hide face (fit be unlawful in some states)", "No physically provoke security forces"],
        yo: ["Má mu ohun ija lọ si ehonu", "Má ṣe jija tabi ìparun ohun ini — yoo ṣe ehonu rẹ di ọdaràn", "Má wọ iboju lati fi oju pamọ́ (o le jẹ aitọ)", "Má damu awọn ọmọ ogun ni ara"],
        ha: ["Kada ka kawo makami zanga-zanga", "Kada ka yi sata ko halaka dukiya — yana sanya zanga-zangar ka ta zama laifi", "Kada ka sa abin rufe fuska don ɓoye kai (na iya zama ba doka ba a wasu jihohi)", "Kada ka tayar da sojojin tsaro jiki"],
        ig: ["Ebugụkwala ngwa agha ịgagharị", "Emekwala ọ zụmahịa ma ọ bụ ịtọgbue ihe — ọ ga-eme ịgagharị gị bụrụ mmehie", "Ayịkwala ihe igbu anya iji zochie ihu gị (nwere ike ọ bụghị iwu)", "Egosikwala ọnụ n'ahụ ụmụ agha nchedo"],
      },
      laws: [
        {
          name: "Constitution of the Federal Republic of Nigeria 1999",
          section: "Section 40",
          plainEnglish: {
            en: "Every person shall be entitled to assemble freely and associate with other persons, and in particular, he may form or belong to any political party, trade union or any other association.",
            pcm: "Every person get right to gather freely and associate with others. You fit form or belong to any party, union, or association.",
            yo: "Gbogbo eniyan ni ẹtọ lati pejọ larọwọto ati lati papọ pẹlu awọn eniyan miiran, ati ni pataki, o le da tabi jẹ ti eyikeyi ẹgbẹ oṣelu, ẹgbẹ iṣẹ tabi eyikeyi ẹgbẹ miiran.",
            ha: "Kowane mutum na da haƙƙin taruwa 'yanci da yin hulɗa da sauran mutane, kuma musamman, zai iya kafa ko zama memba na duk wata jam'iyya ta siyasa, ƙungiyar kwadago ko duk wata ƙungiya.",
            ig: "Onye ọ bụla nwere ikike ịzọ n'ọchịchọ ọcha ma jikọọ na ndị ọzọ, na pụtara ìhè, ọ nwere ike ịhazi ma ọ bụ ịbụ onye otu ọ bụla n'ime ndị otu ndọrọ ndọrọ ọchịchọ, otu ndị ọrụ, ma ọ bụ ọgbakọ ọ bụla ọzọ.",
          },
        },
      ],
      scenarios: [],
    },
  ],
};
